In [1]:
import pandas
import requests
from collections import Counter
from pathlib import Path

In [2]:
server = "http://localhost:8000"

In [3]:
def get_all_pages(url):
    results = []
    while url is not None:
        resp = requests.get(url, headers={"Accept": "application/json"})
        data = resp.json()
        url = data.get("next")
        results.extend(data.get("results", []))
        print("Retrieved {} of {}".format(len(files), data.get("count")))
        
    return results

In [4]:
def get_object(url, cache={}):
    if not isinstance(url, str):
        return url

    if url not in cache:
        resp = requests.get(url)
        if resp.status_code == 200:
            cache[url] = resp.json()
            
    return cache[url]

In [5]:
def get_files(server):
    url = "{server}/subpool-in-run-file".format(server=server)

    files = []
    while url is not None:
        resp = requests.get(url, headers={"Accept": "application/json"})
        data = resp.json()
        url = data.get("next")
        for f in data.get("results", []):
            f["sequencing_run"] = get_object(f["sequencing_run"])
            f["subpool_run"] = get_object(f["subpool_run"])
            f["subpool_run"]["subpool"] = get_object(f["subpool_run"]["subpool"])
            files.append(f)
        print("Retrieved {} of {}".format(len(files), data.get("count")))
        
    return files

In [6]:
files = get_files(server)
len(files)

Retrieved 100 of 3119
Retrieved 200 of 3119
Retrieved 300 of 3119
Retrieved 400 of 3119
Retrieved 500 of 3119
Retrieved 600 of 3119
Retrieved 700 of 3119
Retrieved 800 of 3119
Retrieved 900 of 3119
Retrieved 1000 of 3119
Retrieved 1100 of 3119
Retrieved 1200 of 3119
Retrieved 1300 of 3119
Retrieved 1400 of 3119
Retrieved 1500 of 3119
Retrieved 1600 of 3119
Retrieved 1700 of 3119
Retrieved 1800 of 3119
Retrieved 1900 of 3119
Retrieved 2000 of 3119
Retrieved 2100 of 3119
Retrieved 2200 of 3119
Retrieved 2300 of 3119
Retrieved 2400 of 3119
Retrieved 2500 of 3119
Retrieved 2600 of 3119
Retrieved 2700 of 3119
Retrieved 2800 of 3119
Retrieved 2900 of 3119
Retrieved 3000 of 3119
Retrieved 3100 of 3119
Retrieved 3119 of 3119

3119

In [7]:
files[0]

{'@id': 'http://localhost:8000/subpool-in-run-file/1/',
 'md5sum': '57e977fdfe32850db83ee5f7addb7165',
 'filename': 'igvf_003/nextseq2/003_13A_R1.fastq.gz',
 'flowcell_id': 'AAC3V7HHV',
 'lane': None,
 'read': 'R1',
 'sequencing_run': {'@id': 'http://localhost:8000/sequencing-run/1/',
  'name': 'igvf_003/nextseq2',
  'run_date': '2023-10-02',
  'stranded': 'R',
  'platform': {'@id': 'http://localhost:8000/platform/nextseq2000/',
   'igvf_id': '/platform-terms/EFO_0010963/',
   'display_name': 'Nextseq 2000',
   'family': 'illumina'},
  'plate': {'@id': 'http://localhost:8000/split-seq-plate/IGVF_003/',
   'name': 'IGVF_003',
   'size': '96',
   'pool_location': None,
   'date_performed': None,
   'barcoded_cell_counter': None,
   'volume_of_nuclei': None,
   'sequencing_runs': [{'@id': 'http://localhost:8000/sequencing-run/1/',
     'name': 'igvf_003/nextseq2',
     'run_date': '2023-10-02',
     'stranded': 'R',
     'platform': {'@id': 'http://localhost:8000/platform/nextseq2000/',
      'igvf_id': '/platform-terms/EFO_0010963/',
      'display_name': 'Nextseq 2000',
      'family': 'illumina'},
     'plate': 'http://localhost:8000/split-seq-plate/IGVF_003/'},
    {'@id': 'http://localhost:8000/sequencing-run/2/',
     'name': 'igvf_003/nextseq',
     'run_date': '2023-09-08',
     'stranded': 'R',
     'platform': {'@id': 'http://localhost:8000/platform/nextseq2000/',
      'igvf_id': '/platform-terms/EFO_0010963/',
      'display_name': 'Nextseq 2000',
      'family': 'illumina'},
     'plate': 'http://localhost:8000/split-seq-plate/IGVF_003/'},
    {'@id': 'http://localhost:8000/sequencing-run/3/',
     'name': 'igvf_003/nanopore',
     'run_date': '2022-12-13',
     'stranded': 'R',
     'platform': {'@id': 'http://localhost:8000/platform/minion/',
      'igvf_id': '/platform-terms/EFO_0008632/',
      'display_name': 'Oxford Nanopore MinION',
      'family': 'nanopore'},
     'plate': 'http://localhost:8000/split-seq-plate/IGVF_003/'},
    {'@id': 'http://localhost:8000/sequencing-run/4/',
     'name': 'igvf_003/nova1',
     'run_date': '2023-09-08',
     'stranded': 'R',
     'platform': {'@id': 'http://localhost:8000/platform/novaseq6000/',
      'igvf_id': '/platform-terms/EFO_0008637/',
      'display_name': 'Novaseq 6000',
      'family': 'illumina'},
     'plate': 'http://localhost:8000/split-seq-plate/IGVF_003/'},
    {'@id': 'http://localhost:8000/sequencing-run/5/',
     'name': 'igvf_003/nova2',
     'run_date': '2023-09-08',
     'stranded': 'R',
     'platform': {'@id': 'http://localhost:8000/platform/novaseq6000/',
      'igvf_id': '/platform-terms/EFO_0008637/',
      'display_name': 'Novaseq 6000',
      'family': 'illumina'},
     'plate': 'http://localhost:8000/split-seq-plate/IGVF_003/'}],
   'wells': [{'@id': 'http://localhost:8000/split-seq-well/1/', 'well': 'A1'},
    {'@id': 'http://localhost:8000/split-seq-well/2/', 'well': 'A2'},
    {'@id': 'http://localhost:8000/split-seq-well/3/', 'well': 'A3'},
    {'@id': 'http://localhost:8000/split-seq-well/4/', 'well': 'A4'},
    {'@id': 'http://localhost:8000/split-seq-well/5/', 'well': 'A5'},
    {'@id': 'http://localhost:8000/split-seq-well/6/', 'well': 'A6'},
    {'@id': 'http://localhost:8000/split-seq-well/7/', 'well': 'A7'},
    {'@id': 'http://localhost:8000/split-seq-well/8/', 'well': 'A8'},
    {'@id': 'http://localhost:8000/split-seq-well/9/', 'well': 'B1'},
    {'@id': 'http://localhost:8000/split-seq-well/10/', 'well': 'B2'},
    {'@id': 'http://localhost:8000/split-seq-well/11/', 'well': 'B3'},
    {'@id': 'http://localhost:8000/split-seq-well/12/', 'well': 'B4'},
    {'@id': 'http://localhost:8000/split-seq-well/13/', 'well': 'B5'},
    {'@id': 'http://localhost:8000/split-seq-well/14/', 'well': 'B6'},
    {'@id': 'http://localhost:8000/split-seq-well/15/', 'well': 'B7'},
    {'@id': 'http://localhost:8000/split-seq-well/16/', 'well': 'B8'},
    {'@id': 'http://localhost:8000/split-seq-well/17/', 'well': 'C1'},
    {'@id': 'http://localhost:8000/split-seq-well/18/', 'well': 'C2'},
    {'@id': 'http://localhost:8000/split-seq-well/19/', 'well': 'C3'},
    {'@id': 'http://localhost:8000/split-seq-well/20/', 'well': 'C4'},
    {'@id': 'http://localhost:8000/split-seq-well/21/', 'well': 'C5'},
    {'@id': 'http://localhost:8000/split-seq-well/22/', 'well': 'C6'},
    {'@id': 'http://localhost:8000/split-seq-well/23/', 'well': 'C7'},
    {'@id': 'http://localhost:8000/split-seq-well/24/', 'well': 'C8'},
    {'@id': 'http://localhost:8000/split-seq-well/25/', 'well': 'D1'},
    {'@id': 'http://localhost:8000/split-seq-well/26/', 'well': 'D2'},
    {'@id': 'http://localhost:8000/split-seq-well/27/', 'well': 'D3'},
    {'@id': 'http://localhost:8000/split-seq-well/28/', 'well': 'D4'},
    {'@id': 'http://localhost:8000/split-seq-well/29/', 'well': 'D5'},
    {'@id': 'http://localhost:8000/split-seq-well/30/', 'well': 'D6'},
    {'@id': 'http://localhost:8000/split-seq-well/31/', 'well': 'D7'},
    {'@id': 'http://localhost:8000/split-seq-well/32/', 'well': 'D8'},
    {'@id': 'http://localhost:8000/split-seq-well/33/', 'well': 'E1'},
    {'@id': 'http://localhost:8000/split-seq-well/34/', 'well': 'E2'},
    {'@id': 'http://localhost:8000/split-seq-well/35/', 'well': 'E3'},
    {'@id': 'http://localhost:8000/split-seq-well/36/', 'well': 'E4'},
    {'@id': 'http://localhost:8000/split-seq-well/37/', 'well': 'E5'},
    {'@id': 'http://localhost:8000/split-seq-well/38/', 'well': 'E6'},
    {'@id': 'http://localhost:8000/split-seq-well/39/', 'well': 'E7'},
    {'@id': 'http://localhost:8000/split-seq-well/40/', 'well': 'E8'},
    {'@id': 'http://localhost:8000/split-seq-well/41/', 'well': 'F1'},
    {'@id': 'http://localhost:8000/split-seq-well/42/', 'well': 'F2'},
    {'@id': 'http://localhost:8000/split-seq-well/43/', 'well': 'F3'},
    {'@id': 'http://localhost:8000/split-seq-well/44/', 'well': 'F4'},
    {'@id': 'http://localhost:8000/split-seq-well/45/', 'well': 'F5'},
    {'@id': 'http://localhost:8000/split-seq-well/46/', 'well': 'F6'},
    {'@id': 'http://localhost:8000/split-seq-well/47/', 'well': 'F7'},
    {'@id': 'http://localhost:8000/split-seq-well/48/', 'well': 'F8'},
    {'@id': 'http://localhost:8000/split-seq-well/49/', 'well': 'G1'},
    {'@id': 'http://localhost:8000/split-seq-well/50/', 'well': 'G2'},
    {'@id': 'http://localhost:8000/split-seq-well/51/', 'well': 'G3'},
    {'@id': 'http://localhost:8000/split-seq-well/52/', 'well': 'G4'},
    {'@id': 'http://localhost:8000/split-seq-well/53/', 'well': 'G5'},
    {'@id': 'http://localhost:8000/split-seq-well/54/', 'well': 'G6'},
    {'@id': 'http://localhost:8000/split-seq-well/55/', 'well': 'G7'},
    {'@id': 'http://localhost:8000/split-seq-well/56/', 'well': 'G8'},
    {'@id': 'http://localhost:8000/split-seq-well/57/', 'well': 'H1'},
    {'@id': 'http://localhost:8000/split-seq-well/58/', 'well': 'H2'},
    {'@id': 'http://localhost:8000/split-seq-well/59/', 'well': 'H3'},
    {'@id': 'http://localhost:8000/split-seq-well/60/', 'well': 'H4'},
    {'@id': 'http://localhost:8000/split-seq-well/61/', 'well': 'H5'},
    {'@id': 'http://localhost:8000/split-seq-well/62/', 'well': 'H6'},
    {'@id': 'http://localhost:8000/split-seq-well/63/', 'well': 'H7'},
    {'@id': 'http://localhost:8000/split-seq-well/64/', 'well': 'H8'},
    {'@id': 'http://localhost:8000/split-seq-well/65/', 'well': 'A9'},
    {'@id': 'http://localhost:8000/split-seq-well/66/', 'well': 'A10'},
    {'@id': 'http://localhost:8000/split-seq-well/67/', 'well': 'A11'},
    {'@id': 'http://localhost:8000/split-seq-well/68/', 'well': 'A12'},
    {'@id': 'http://localhost:8000/split-seq-well/69/', 'well': 'B9'},
    {'@id': 'http://localhost:8000/split-seq-well/70/', 'well': 'B10'},
    {'@id': 'http://localhost:8000/split-seq-well/71/', 'well': 'B11'},
    {'@id': 'http://localhost:8000/split-seq-well/72/', 'well': 'B12'},
    {'@id': 'http://localhost:8000/split-seq-well/73/', 'well': 'C9'},
    {'@id': 'http://localhost:8000/split-seq-well/74/', 'well': 'C10'},
    {'@id': 'http://localhost:8000/split-seq-well/75/', 'well': 'C11'},
    {'@id': 'http://localhost:8000/split-seq-well/76/', 'well': 'C12'},
    {'@id': 'http://localhost:8000/split-seq-well/77/', 'well': 'D9'},
    {'@id': 'http://localhost:8000/split-seq-well/78/', 'well': 'D10'},
    {'@id': 'http://localhost:8000/split-seq-well/79/', 'well': 'D11'},
    {'@id': 'http://localhost:8000/split-seq-well/80/', 'well': 'D12'},
    {'@id': 'http://localhost:8000/split-seq-well/81/', 'well': 'E9'},
    {'@id': 'http://localhost:8000/split-seq-well/82/', 'well': 'E10'},
    {'@id': 'http://localhost:8000/split-seq-well/83/', 'well': 'E11'},
    {'@id': 'http://localhost:8000/split-seq-well/84/', 'well': 'E12'},
    {'@id': 'http://localhost:8000/split-seq-well/85/', 'well': 'F9'},
    {'@id': 'http://localhost:8000/split-seq-well/86/', 'well': 'F10'},
    {'@id': 'http://localhost:8000/split-seq-well/87/', 'well': 'F11'},
    {'@id': 'http://localhost:8000/split-seq-well/88/', 'well': 'F12'},
    {'@id': 'http://localhost:8000/split-seq-well/89/', 'well': 'G9'},
    {'@id': 'http://localhost:8000/split-seq-well/90/', 'well': 'G10'},
    {'@id': 'http://localhost:8000/split-seq-well/91/', 'well': 'G11'},
    {'@id': 'http://localhost:8000/split-seq-well/92/', 'well': 'G12'},
    {'@id': 'http://localhost:8000/split-seq-well/93/', 'well': 'H9'},
    {'@id': 'http://localhost:8000/split-seq-well/94/', 'well': 'H10'},
    {'@id': 'http://localhost:8000/split-seq-well/95/', 'well': 'H11'},
    {'@id': 'http://localhost:8000/split-seq-well/96/', 'well': 'H12'}]}},
 'subpool_run': {'@id': 'http://localhost:8000/subpool-in-run/1/',
  'raw_reads': None,
  'status': 'P',
  'subpool': {'@id': 'http://localhost:8000/subpool/003_13A/',
   'name': '003_13A',
   'nuclei': 13000,
   'selection_type': 'EX',
   'cdna_ng_per_ul': 66.4,
   'cdna_volume': 25.0,
   'bioanalyzer_date': None,
   'cdna_average_bp_length': None,
   'index_pcr_number': 12,
   'index': '1',
   'library_ng_per_ul': 19.0,
   'library_average_bp_length': None,
   'plate': 'http://localhost:8000/split-seq-plate/IGVF_003/',
   'barcode': [{'@id': 'http://localhost:8000/library-barcode/193/',
     'name': '1',
     'code': '1',
     'i7_sequence': 'CAGATC',
     'i5_sequence': None,
     'barcode_type': None,
     'well_position': None,
     'reagent': 'http://localhost:8000/library-construction-reagent/wt-mega/'}]},
  'sequencing_run': 'http://localhost:8000/sequencing-run/1/',
  'measurement_set': 'http://localhost:8000/measurement-set/26/'},
 'accession': [{'@id': 'http://localhost:8000/accession/IGVFFI1667GRMZ/',
   'name': 'IGVFFI1667GRMZ',
   'see_also': 'https://api.data.igvf.org/sequence-files/IGVFFI1667GRMZ/'}]}

From https://docs.google.com/presentation/d/1W7lhTxsZH5tOY095HTo2353wUMfQLuoGHyD5V6CSMWY/edit#slide=id.g22b43c49617_0_9

```
${plate}_${subpool}_${protocol}_${platform}_$N{run}_R${read}


plate: igvf003, igvf004, etc.
subpool: 2 digit ID # for pool, i.e. 01, 02, 03….16. 
platform: next, nova, grid, prom
run: typically 1/2 for nova (1 for 008/008b), typically 1 for next (2 for bridge, 2 for exome capture subpools), many for grid, maybe 1 for prom
protocol: D or E (D = default, E = exome capture)
read: 1 for Nanopore (grid & prom) and 1/2 for Illumina (next & nova)
```

In [8]:
def format_barcode(value):
    assert value is not None
    if isinstance(value, int) or value.isdigit():
        return "B{:02}".format(int(value))
    else:
        return "B{}".format(value)

assert format_barcode(13) == "B13"
assert format_barcode("3") == "B03"
assert format_barcode("UDI03") == "BUDI03"

In [9]:
short_platform_names = {
    "/platform-terms/EFO_0010963/": "next",
    "/platform-terms/EFO_0008637/": "nova",
    "/platform-terms/EFO_0008632/": "mini",
    "/platform-terms/EFO_0008634/": "prom",

}

short_protocol_names = {
    "NO": "D",
    "EX": "E",
}

def decode_run_name(run_name):
    plate, run = run_name.split("/")
    
    return {
        "next": 1,
        "next1": 1,
        "next2": 2,
        "nextseq": 1,
        "nextseq1": 1,
        "nextseq2": 2,
        "nova1": 1,
        "nova2": 2,
    }[run]

records = []
for f in files:
    assert f["filename"].endswith(".fastq.gz")
    file_type = ".fastq.gz"
    
    if f["sequencing_run"]["platform"]["family"] == "nanopore":
        # Skip nanopore
        continue

    plate = f["sequencing_run"]["plate"]["name"].lower()
    subpool_index = format_barcode(f["subpool_run"]["subpool"]["index"])
    platform = short_platform_names[f["sequencing_run"]["platform"]["igvf_id"]]
    dirname = f["sequencing_run"]["name"]
    run = decode_run_name(f["sequencing_run"]["name"])
    protocol = short_protocol_names[f["subpool_run"]["subpool"]["selection_type"]]
    if f.get("lane") is not None:
        lane = "_L{:03}".format(f.get("lane"))
    else:
        lane = ""
    read = "_{}".format(f.get("read"))
    target_name = f"{dirname}/{plate}_{subpool_index}_{protocol}_{platform}_N{run}{lane}{read}{file_type}"
    accessions = [x["see_also"] for x in f["accession"] if x["name"].startswith("IGVF")]
    if len(accessions) == 0:
        accession = ""
    elif len(accessions) == 1:
        accession = accessions[0]
    else:
        raise RuntimeError(f"Itegrity error {f}")
    records.append({
        "source": f["filename"],
        "target": target_name,
        "md5sum": f["md5sum"],
        "accession": accession,
    })

records = pandas.DataFrame(records).sort_values("source")
records

,source,target,md5sum,accession
2,igvf_003/nextseq/003_67A_R1.fastq.gz,igvf_003/nextseq/igvf_003_B02_D_next_N1_R1.fas...,35350d53cf858267d294bce69e475c83,https://api.data.igvf.org/sequence-files/IGVFF...
3,igvf_003/nextseq/003_67A_R2.fastq.gz,igvf_003/nextseq/igvf_003_B02_D_next_N1_R2.fas...,00c68ff0f9e0217d422c57e8948d4bb4,https://api.data.igvf.org/sequence-files/IGVFF...
4,igvf_003/nextseq/003_67B_R1.fastq.gz,igvf_003/nextseq/igvf_003_B03_D_next_N1_R1.fas...,79db765143bb23e14c613c9e1339e9f7,https://api.data.igvf.org/sequence-files/IGVFF...
5,igvf_003/nextseq/003_67B_R2.fastq.gz,igvf_003/nextseq/igvf_003_B03_D_next_N1_R2.fas...,c4787058f6b8304b1ddae0a55b48fb13,https://api.data.igvf.org/sequence-files/IGVFF...
6,igvf_003/nextseq/003_8A_R1.fastq.gz,igvf_003/nextseq/igvf_003_B01_D_next_N1_R1.fas...,bb696e63b6a8710ec8435b60ef6c81f8,
...,...,...,...,...
3098,igvf_b01/next2/B01_13F_R2.fastq.gz,igvf_b01/next2/igvf_b01_B06_D_next_N2_R2.fastq.gz,5f49893f54aaf88d06ca5834268a4e55,https://api.data.igvf.org/sequence-files/IGVFF...
3100,igvf_b01/next2/B01_13G_R1.fastq.gz,igvf_b01/next2/igvf_b01_B07_E_next_N2_R1.fastq.gz,2d4a0beb2e31d5981ebc56748297395b,https://api.data.igvf.org/sequence-files/IGVFF...
3102,igvf_b01/next2/B01_13G_R2.fastq.gz,igvf_b01/next2/igvf_b01_B07_E_next_N2_R2.fastq.gz,b3f5e2b91fc926c070c85c40e654cb0d,https://api.data.igvf.org/sequence-files/IGVFF...
3104,igvf_b01/next2/B01_13H_R1.fastq.gz,igvf_b01/next2/igvf_b01_B08_D_next_N2_R1.fastq.gz,cef06002f2986f0c305da0031910c1f0,https://api.data.igvf.org/sequence-files/IGVFF...
3106,igvf_b01/next2/B01_13H_R2.fastq.gz,igvf_b01/next2/igvf_b01_B08_D_next_N2_R2.fastq.gz,2a5a07155767a2f541cfb20e7d0636e0,https://api.data.igvf.org/sequence-files/IGVFF...

As of Sept 5th, there's ~2931 fastq files.

In [10]:
with open("great-rename.txt", "wt") as outstream:
    full_collisions = Counter()
    name_collisions = Counter()
    for i, row in records.iterrows():
        full_collisions[row["target"]] += 1
        name_collisions[Path(row["target"]).name] += 1
        record = "mv -n\t{}\t{}\t\t#{}\t{}".format(row["source"], row["target"], row["md5sum"], row["accession"])
        print(record)
        outstream.write(record)
        outstream.write("\n")

mv -n	igvf_003/nextseq/003_67A_R1.fastq.gz	igvf_003/nextseq/igvf_003_B02_D_next_N1_R1.fastq.gz		#35350d53cf858267d294bce69e475c83	https://api.data.igvf.org/sequence-files/IGVFFI7878WYCE/
mv -n	igvf_003/nextseq/003_67A_R2.fastq.gz	igvf_003/nextseq/igvf_003_B02_D_next_N1_R2.fastq.gz		#00c68ff0f9e0217d422c57e8948d4bb4	https://api.data.igvf.org/sequence-files/IGVFFI6614EZDQ/
mv -n	igvf_003/nextseq/003_67B_R1.fastq.gz	igvf_003/nextseq/igvf_003_B03_D_next_N1_R1.fastq.gz		#79db765143bb23e14c613c9e1339e9f7	https://api.data.igvf.org/sequence-files/IGVFFI5879FSBN/
mv -n	igvf_003/nextseq/003_67B_R2.fastq.gz	igvf_003/nextseq/igvf_003_B03_D_next_N1_R2.fastq.gz		#c4787058f6b8304b1ddae0a55b48fb13	https://api.data.igvf.org/sequence-files/IGVFFI5078LLAB/
mv -n	igvf_003/nextseq/003_8A_R1.fastq.gz	igvf_003/nextseq/igvf_003_B01_D_next_N1_R1.fastq.gz		#bb696e63b6a8710ec8435b60ef6c81f8
mv -n	igvf_003/nextseq/003_8A_R2.fastq.gz	igvf_003/nextseq/igvf_003_B01_D_next_N1_R2.fastq.gz		#21967ba1a5a3218508961fac482a2952
mv -n	igvf_003/nextseq2/003_13A_R1.fastq.gz	igvf_003/nextseq2/igvf_003_B01_E_next_N2_R1.fastq.gz		#57e977fdfe32850db83ee5f7addb7165	https://api.data.igvf.org/sequence-files/IGVFFI1667GRMZ/
mv -n	igvf_003/nextseq2/003_13A_R2.fastq.gz	igvf_003/nextseq2/igvf_003_B01_E_next_N2_R2.fastq.gz		#148c181e7d81e4aa15611fb2086d5971	https://api.data.igvf.org/sequence-files/IGVFFI8315SDBA/
mv -n	igvf_003/nova1/Sublibrary_10_S9_L001_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B10_D_nova_N1_L001_I1.fastq.gz		#3b692ad25a4cb018645b76190913fc70
mv -n	igvf_003/nova1/Sublibrary_10_S9_L001_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B10_D_nova_N1_L001_R1.fastq.gz		#126fba5a50dbb4bf6deeb92e437bd2ef	https://api.data.igvf.org/sequence-files/IGVFFI1021FFPV/
mv -n	igvf_003/nova1/Sublibrary_10_S9_L001_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B10_D_nova_N1_L001_R2.fastq.gz		#1a3e05cc1ee44f91d386156653901ee3	https://api.data.igvf.org/sequence-files/IGVFFI4613WMMM/
mv -n	igvf_003/nova1/Sublibrary_10_S9_L002_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B10_D_nova_N1_L002_I1.fastq.gz		#a92935f73905a0065adab26927f75f5c
mv -n	igvf_003/nova1/Sublibrary_10_S9_L002_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B10_D_nova_N1_L002_R1.fastq.gz		#92714a3c303c97be0b2555479eba9ced	https://api.data.igvf.org/sequence-files/IGVFFI6370TDGH/
mv -n	igvf_003/nova1/Sublibrary_10_S9_L002_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B10_D_nova_N1_L002_R2.fastq.gz		#77a51c48fc46aae766ed7cb851c6cc55	https://api.data.igvf.org/sequence-files/IGVFFI0931LIXZ/
mv -n	igvf_003/nova1/Sublibrary_10_S9_L003_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B10_D_nova_N1_L003_I1.fastq.gz		#ae9ffc0ef015a0e4cebf20021bc89876
mv -n	igvf_003/nova1/Sublibrary_10_S9_L003_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B10_D_nova_N1_L003_R1.fastq.gz		#0db70d7928608d2db0ffdd51ae17609e	https://api.data.igvf.org/sequence-files/IGVFFI1523XZTN/
mv -n	igvf_003/nova1/Sublibrary_10_S9_L003_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B10_D_nova_N1_L003_R2.fastq.gz		#ce1896b779ad09c4e79102728c9e9285	https://api.data.igvf.org/sequence-files/IGVFFI2854QLLR/
mv -n	igvf_003/nova1/Sublibrary_10_S9_L004_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B10_D_nova_N1_L004_I1.fastq.gz		#ac869549ebcc924565d119dba8f5d392
mv -n	igvf_003/nova1/Sublibrary_10_S9_L004_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B10_D_nova_N1_L004_R1.fastq.gz		#515f81f14cc496a5a8e552e9136390e7	https://api.data.igvf.org/sequence-files/IGVFFI2705DCYL/
mv -n	igvf_003/nova1/Sublibrary_10_S9_L004_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B10_D_nova_N1_L004_R2.fastq.gz		#31306d49ef154a2ca3169fb843fd1196	https://api.data.igvf.org/sequence-files/IGVFFI2505EBOI/
mv -n	igvf_003/nova1/Sublibrary_11_S10_L001_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B11_D_nova_N1_L001_I1.fastq.gz		#e98a8a47507764ec7f681ab38336e670
mv -n	igvf_003/nova1/Sublibrary_11_S10_L001_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B11_D_nova_N1_L001_R1.fastq.gz		#6011447ff875eb8a53d0e80b683baf67	https://api.data.igvf.org/sequence-files/IGVFFI6799HLET/
mv -n	igvf_003/nova1/Sublibrary_11_S10_L001_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B11_D_nova_N1_L001_R2.fastq.gz		#46a52f63fa16b8890b96aa3afc6260cc	https://api.data.igvf.org/sequence-files/IGVFFI9794AVHH/
mv -n	igvf_003/nova1/Sublibrary_11_S10_L002_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B11_D_nova_N1_L002_I1.fastq.gz		#6676edbfbbdecb22cea8c7933c7dc137
mv -n	igvf_003/nova1/Sublibrary_11_S10_L002_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B11_D_nova_N1_L002_R1.fastq.gz		#80c425a329d5ced37d9fe6007792934c	https://api.data.igvf.org/sequence-files/IGVFFI5335WEFD/
mv -n	igvf_003/nova1/Sublibrary_11_S10_L002_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B11_D_nova_N1_L002_R2.fastq.gz		#b72e1f7fc33b6ff1d825d9d96aee3554	https://api.data.igvf.org/sequence-files/IGVFFI8391ZSZU/
mv -n	igvf_003/nova1/Sublibrary_11_S10_L003_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B11_D_nova_N1_L003_I1.fastq.gz		#1407dc83962f7130ec33c420aaa3eab7
mv -n	igvf_003/nova1/Sublibrary_11_S10_L003_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B11_D_nova_N1_L003_R1.fastq.gz		#7f844b9e04820c1bb42cf5d77189459c	https://api.data.igvf.org/sequence-files/IGVFFI5906AIED/
mv -n	igvf_003/nova1/Sublibrary_11_S10_L003_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B11_D_nova_N1_L003_R2.fastq.gz		#55252a4fe5e76b5ad433d23b5c7a8bab	https://api.data.igvf.org/sequence-files/IGVFFI9411OOCJ/
mv -n	igvf_003/nova1/Sublibrary_11_S10_L004_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B11_D_nova_N1_L004_I1.fastq.gz		#58b6017ff0fe0f5607325dbeba0c6364
mv -n	igvf_003/nova1/Sublibrary_11_S10_L004_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B11_D_nova_N1_L004_R1.fastq.gz		#ce2466e4f13032d161bb0511cb296fd8	https://api.data.igvf.org/sequence-files/IGVFFI7673NPFH/
mv -n	igvf_003/nova1/Sublibrary_11_S10_L004_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B11_D_nova_N1_L004_R2.fastq.gz		#ee7499922cd233c86fcdea21299c3d49	https://api.data.igvf.org/sequence-files/IGVFFI8058GHQR/
mv -n	igvf_003/nova1/Sublibrary_12_S11_L001_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B12_D_nova_N1_L001_I1.fastq.gz		#be07fe2188c2e601a446ca142ccd5f73
mv -n	igvf_003/nova1/Sublibrary_12_S11_L001_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B12_D_nova_N1_L001_R1.fastq.gz		#39f81a570022dd479fcbd19e8ad59ac1	https://api.data.igvf.org/sequence-files/IGVFFI7456NJLW/
mv -n	igvf_003/nova1/Sublibrary_12_S11_L001_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B12_D_nova_N1_L001_R2.fastq.gz		#75085d58cb484a7c6722fe9861a95027	https://api.data.igvf.org/sequence-files/IGVFFI0613RJGX/
mv -n	igvf_003/nova1/Sublibrary_12_S11_L002_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B12_D_nova_N1_L002_I1.fastq.gz		#17385e65b98870dcb42a130b00b4c9df
mv -n	igvf_003/nova1/Sublibrary_12_S11_L002_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B12_D_nova_N1_L002_R1.fastq.gz		#0f10cfcbc7cbcedc30f7e87c2ccddeec	https://api.data.igvf.org/sequence-files/IGVFFI9402PKUW/
mv -n	igvf_003/nova1/Sublibrary_12_S11_L002_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B12_D_nova_N1_L002_R2.fastq.gz		#8bbc6374ce04034acfbf5a57fb4cab5f	https://api.data.igvf.org/sequence-files/IGVFFI2056VAAC/
mv -n	igvf_003/nova1/Sublibrary_12_S11_L003_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B12_D_nova_N1_L003_I1.fastq.gz		#be5b89ead6c6e577749a55dccba518ce
mv -n	igvf_003/nova1/Sublibrary_12_S11_L003_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B12_D_nova_N1_L003_R1.fastq.gz		#4f5eda2d21e1b05e21c57d679c13beba	https://api.data.igvf.org/sequence-files/IGVFFI0449XCZP/
mv -n	igvf_003/nova1/Sublibrary_12_S11_L003_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B12_D_nova_N1_L003_R2.fastq.gz		#436909b9fb0e98039d3ae9d3915852be	https://api.data.igvf.org/sequence-files/IGVFFI4426MJSB/
mv -n	igvf_003/nova1/Sublibrary_12_S11_L004_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B12_D_nova_N1_L004_I1.fastq.gz		#4857f53164e7e51bbbafc20dbb444e25
mv -n	igvf_003/nova1/Sublibrary_12_S11_L004_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B12_D_nova_N1_L004_R1.fastq.gz		#92a83c54a0a4514fc6c1db4cf8c20fe3	https://api.data.igvf.org/sequence-files/IGVFFI5660FMKV/
mv -n	igvf_003/nova1/Sublibrary_12_S11_L004_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B12_D_nova_N1_L004_R2.fastq.gz		#799a09ca98f458e359d7ee731de20b67	https://api.data.igvf.org/sequence-files/IGVFFI4524EQYN/
mv -n	igvf_003/nova1/Sublibrary_13_S12_L001_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B13_D_nova_N1_L001_I1.fastq.gz		#b0d49f9245eaa9864988afc5bfe0a14f
mv -n	igvf_003/nova1/Sublibrary_13_S12_L001_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B13_D_nova_N1_L001_R1.fastq.gz		#54f71904aa48b1ccd7a3508e3e1c30f0	https://api.data.igvf.org/sequence-files/IGVFFI6783KFMS/
mv -n	igvf_003/nova1/Sublibrary_13_S12_L001_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B13_D_nova_N1_L001_R2.fastq.gz		#4fc7af2870a5c380b80f41a81383c6f0	https://api.data.igvf.org/sequence-files/IGVFFI2953TAHZ/
mv -n	igvf_003/nova1/Sublibrary_13_S12_L002_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B13_D_nova_N1_L002_I1.fastq.gz		#ccea17968af857e7432b86d8e2099bb9
mv -n	igvf_003/nova1/Sublibrary_13_S12_L002_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B13_D_nova_N1_L002_R1.fastq.gz		#af36e5e29fa12a85608316b6d87d657e	https://api.data.igvf.org/sequence-files/IGVFFI8373QRBG/
mv -n	igvf_003/nova1/Sublibrary_13_S12_L002_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B13_D_nova_N1_L002_R2.fastq.gz		#0d13275b72bf1f88e3ae91370e296cce	https://api.data.igvf.org/sequence-files/IGVFFI0169BUDZ/
mv -n	igvf_003/nova1/Sublibrary_13_S12_L003_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B13_D_nova_N1_L003_I1.fastq.gz		#fb5ae2b7b972e0f8453dc9baf62787cd
mv -n	igvf_003/nova1/Sublibrary_13_S12_L003_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B13_D_nova_N1_L003_R1.fastq.gz		#7ee86e7d89d40e411a67c2f5ed16056f	https://api.data.igvf.org/sequence-files/IGVFFI3631IVCC/
mv -n	igvf_003/nova1/Sublibrary_13_S12_L003_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B13_D_nova_N1_L003_R2.fastq.gz		#84af322fbb61ee928f5bfe13facdb991	https://api.data.igvf.org/sequence-files/IGVFFI0134BWIU/
mv -n	igvf_003/nova1/Sublibrary_13_S12_L004_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B13_D_nova_N1_L004_I1.fastq.gz		#fe625115543396dda05add6061329288
mv -n	igvf_003/nova1/Sublibrary_13_S12_L004_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B13_D_nova_N1_L004_R1.fastq.gz		#3801fc9892d4df912abf9b2b0c9a2344	https://api.data.igvf.org/sequence-files/IGVFFI4673HYZJ/
mv -n	igvf_003/nova1/Sublibrary_13_S12_L004_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B13_D_nova_N1_L004_R2.fastq.gz		#caecfdcd35f88f7791707f7ea95189b3	https://api.data.igvf.org/sequence-files/IGVFFI2077WDIP/
mv -n	igvf_003/nova1/Sublibrary_14_S13_L001_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B14_D_nova_N1_L001_I1.fastq.gz		#21b9447db448ea4896e8383492f0bb90
mv -n	igvf_003/nova1/Sublibrary_14_S13_L001_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B14_D_nova_N1_L001_R1.fastq.gz		#f4f4612b3d716ceaded8d4bd7cac1253	https://api.data.igvf.org/sequence-files/IGVFFI6647GGNL/
mv -n	igvf_003/nova1/Sublibrary_14_S13_L001_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B14_D_nova_N1_L001_R2.fastq.gz		#10e7d0e9e7269e1edfe9a7383e85414a	https://api.data.igvf.org/sequence-files/IGVFFI3902HPZP/
mv -n	igvf_003/nova1/Sublibrary_14_S13_L002_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B14_D_nova_N1_L002_I1.fastq.gz		#d37ae2334583f5168372b206d706ec9d
mv -n	igvf_003/nova1/Sublibrary_14_S13_L002_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B14_D_nova_N1_L002_R1.fastq.gz		#cc1557cc0da137d1bc27c9e819e51119	https://api.data.igvf.org/sequence-files/IGVFFI6861BDKN/
mv -n	igvf_003/nova1/Sublibrary_14_S13_L002_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B14_D_nova_N1_L002_R2.fastq.gz		#726ad26575de049b7394114040605392	https://api.data.igvf.org/sequence-files/IGVFFI2801DEXE/
mv -n	igvf_003/nova1/Sublibrary_14_S13_L003_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B14_D_nova_N1_L003_I1.fastq.gz		#bdd3a6cc50df1e3dab253ff152ae7142
mv -n	igvf_003/nova1/Sublibrary_14_S13_L003_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B14_D_nova_N1_L003_R1.fastq.gz		#4e294fd4246d9293105e70bdc5911721	https://api.data.igvf.org/sequence-files/IGVFFI3290BFJB/
mv -n	igvf_003/nova1/Sublibrary_14_S13_L003_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B14_D_nova_N1_L003_R2.fastq.gz		#c7fd524da3d55ff97099c5b9a9a02553	https://api.data.igvf.org/sequence-files/IGVFFI0591NQIT/
mv -n	igvf_003/nova1/Sublibrary_14_S13_L004_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B14_D_nova_N1_L004_I1.fastq.gz		#1a683a93bb22c674e57331429ddad48c
mv -n	igvf_003/nova1/Sublibrary_14_S13_L004_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B14_D_nova_N1_L004_R1.fastq.gz		#ff956cfe8a11656a17fd9ebb2a2f8e83	https://api.data.igvf.org/sequence-files/IGVFFI1490CGNG/
mv -n	igvf_003/nova1/Sublibrary_14_S13_L004_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B14_D_nova_N1_L004_R2.fastq.gz		#fbba74f1792b93eb74e0586e405814b0	https://api.data.igvf.org/sequence-files/IGVFFI1253KAKX/
mv -n	igvf_003/nova1/Sublibrary_15_S14_L001_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B15_D_nova_N1_L001_I1.fastq.gz		#20e64069d3fe7c7b4cc8b95dbd1458dd
mv -n	igvf_003/nova1/Sublibrary_15_S14_L001_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B15_D_nova_N1_L001_R1.fastq.gz		#ce9f50918608ff71f726f42511ce29cc	https://api.data.igvf.org/sequence-files/IGVFFI2428WPXH/
mv -n	igvf_003/nova1/Sublibrary_15_S14_L001_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B15_D_nova_N1_L001_R2.fastq.gz		#1e7060cdb99943b54b2fac7fe73222c0	https://api.data.igvf.org/sequence-files/IGVFFI4273GXAG/
mv -n	igvf_003/nova1/Sublibrary_15_S14_L002_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B15_D_nova_N1_L002_I1.fastq.gz		#4a3e140319e6f57b866696ae3e088eec
mv -n	igvf_003/nova1/Sublibrary_15_S14_L002_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B15_D_nova_N1_L002_R1.fastq.gz		#94329a9dbc4bb520469711436fb0bcc9	https://api.data.igvf.org/sequence-files/IGVFFI0783WURA/
mv -n	igvf_003/nova1/Sublibrary_15_S14_L002_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B15_D_nova_N1_L002_R2.fastq.gz		#9ca77a811c53df186d074a3691c0bc31	https://api.data.igvf.org/sequence-files/IGVFFI1422UGTK/
mv -n	igvf_003/nova1/Sublibrary_15_S14_L003_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B15_D_nova_N1_L003_I1.fastq.gz		#e52c3380dfaf2eff584af19502d52a80
mv -n	igvf_003/nova1/Sublibrary_15_S14_L003_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B15_D_nova_N1_L003_R1.fastq.gz		#2ddbaad9045cbd9396394a2add4be433	https://api.data.igvf.org/sequence-files/IGVFFI9923LGKV/
mv -n	igvf_003/nova1/Sublibrary_15_S14_L003_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B15_D_nova_N1_L003_R2.fastq.gz		#7a4a937dbcd1c9990539e741a354582b	https://api.data.igvf.org/sequence-files/IGVFFI5054VYEX/
mv -n	igvf_003/nova1/Sublibrary_15_S14_L004_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B15_D_nova_N1_L004_I1.fastq.gz		#4a2d5dfaca53576710248fdff290881c
mv -n	igvf_003/nova1/Sublibrary_15_S14_L004_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B15_D_nova_N1_L004_R1.fastq.gz		#c52f145ecbaed12172e3d7e0844132f0	https://api.data.igvf.org/sequence-files/IGVFFI7075KIKW/
mv -n	igvf_003/nova1/Sublibrary_15_S14_L004_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B15_D_nova_N1_L004_R2.fastq.gz		#ff374a2cdfdb2dddbfa72bbba143c90a	https://api.data.igvf.org/sequence-files/IGVFFI6788DTAD/
mv -n	igvf_003/nova1/Sublibrary_16_S15_L001_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B16_D_nova_N1_L001_I1.fastq.gz		#bb637ae51012b9af41a2fabf5829cc8b
mv -n	igvf_003/nova1/Sublibrary_16_S15_L001_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B16_D_nova_N1_L001_R1.fastq.gz		#f29000bdb8002cabf85cc9a85115cb24	https://api.data.igvf.org/sequence-files/IGVFFI9479KEOW/
mv -n	igvf_003/nova1/Sublibrary_16_S15_L001_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B16_D_nova_N1_L001_R2.fastq.gz		#4d1332f3283cff72453d9d8832989a80	https://api.data.igvf.org/sequence-files/IGVFFI2272PGRU/
mv -n	igvf_003/nova1/Sublibrary_16_S15_L002_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B16_D_nova_N1_L002_I1.fastq.gz		#77b9c39ad56d74dc15b85a5a5f7742ca
mv -n	igvf_003/nova1/Sublibrary_16_S15_L002_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B16_D_nova_N1_L002_R1.fastq.gz		#c9624167641e177089df4608d22fc880	https://api.data.igvf.org/sequence-files/IGVFFI6471UEXE/
mv -n	igvf_003/nova1/Sublibrary_16_S15_L002_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B16_D_nova_N1_L002_R2.fastq.gz		#2047adbe30b114732709ec50703dd9a0	https://api.data.igvf.org/sequence-files/IGVFFI7868MDSY/
mv -n	igvf_003/nova1/Sublibrary_16_S15_L003_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B16_D_nova_N1_L003_I1.fastq.gz		#a33200d646e283f9086b17e933609413
mv -n	igvf_003/nova1/Sublibrary_16_S15_L003_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B16_D_nova_N1_L003_R1.fastq.gz		#c454289df035287040b3aaafca81c4f2	https://api.data.igvf.org/sequence-files/IGVFFI6359WLBV/
mv -n	igvf_003/nova1/Sublibrary_16_S15_L003_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B16_D_nova_N1_L003_R2.fastq.gz		#0d38791d3697a22038aa1eae935e200c	https://api.data.igvf.org/sequence-files/IGVFFI8713GJGP/
mv -n	igvf_003/nova1/Sublibrary_16_S15_L004_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B16_D_nova_N1_L004_I1.fastq.gz		#cd450f0c9650b269901525819101e3d1
mv -n	igvf_003/nova1/Sublibrary_16_S15_L004_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B16_D_nova_N1_L004_R1.fastq.gz		#00867bb8a77551a6e4a9570f96019e48	https://api.data.igvf.org/sequence-files/IGVFFI0425XWLE/
mv -n	igvf_003/nova1/Sublibrary_16_S15_L004_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B16_D_nova_N1_L004_R2.fastq.gz		#e07216b5cd2dc86345f46c5e8774d633	https://api.data.igvf.org/sequence-files/IGVFFI5376KEUL/
mv -n	igvf_003/nova1/Sublibrary_2_S1_L001_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B02_D_nova_N1_L001_I1.fastq.gz		#689cb6a48d74fdc4d72ceac68543180a
mv -n	igvf_003/nova1/Sublibrary_2_S1_L001_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B02_D_nova_N1_L001_R1.fastq.gz		#bdcd855e7857c68fe36ac4cfc1b98cfe	https://api.data.igvf.org/sequence-files/IGVFFI6327ZGLG/
mv -n	igvf_003/nova1/Sublibrary_2_S1_L001_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B02_D_nova_N1_L001_R2.fastq.gz		#a1bf3d7319a6cddce8f980229811b83e	https://api.data.igvf.org/sequence-files/IGVFFI9541HLET/
mv -n	igvf_003/nova1/Sublibrary_2_S1_L002_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B02_D_nova_N1_L002_I1.fastq.gz		#919810469bc1385d1e0a76e810826b67
mv -n	igvf_003/nova1/Sublibrary_2_S1_L002_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B02_D_nova_N1_L002_R1.fastq.gz		#57d3270d53368892fa496bbee5f6f3d2	https://api.data.igvf.org/sequence-files/IGVFFI4188RUEN/
mv -n	igvf_003/nova1/Sublibrary_2_S1_L002_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B02_D_nova_N1_L002_R2.fastq.gz		#1f598759407dcc1552bf4576234121bd	https://api.data.igvf.org/sequence-files/IGVFFI3936OMVK/
mv -n	igvf_003/nova1/Sublibrary_2_S1_L003_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B02_D_nova_N1_L003_I1.fastq.gz		#d36fc0f0bea47abb9264d61efcaee19e
mv -n	igvf_003/nova1/Sublibrary_2_S1_L003_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B02_D_nova_N1_L003_R1.fastq.gz		#bd97abaa6c1b80bf68f4f04af584ecd6	https://api.data.igvf.org/sequence-files/IGVFFI5842DOMM/
mv -n	igvf_003/nova1/Sublibrary_2_S1_L003_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B02_D_nova_N1_L003_R2.fastq.gz		#2f02d7f2c95e20265be962c419665edd	https://api.data.igvf.org/sequence-files/IGVFFI2578AMXG/
mv -n	igvf_003/nova1/Sublibrary_2_S1_L004_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B02_D_nova_N1_L004_I1.fastq.gz		#add0d65bfcb9266aa63208a43e08913d
mv -n	igvf_003/nova1/Sublibrary_2_S1_L004_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B02_D_nova_N1_L004_R1.fastq.gz		#48032f97529e20fc281aa7e704c63bfa	https://api.data.igvf.org/sequence-files/IGVFFI3256PWNT/
mv -n	igvf_003/nova1/Sublibrary_2_S1_L004_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B02_D_nova_N1_L004_R2.fastq.gz		#97a58bb3ebcdd4a82e692f08db6b2e3a	https://api.data.igvf.org/sequence-files/IGVFFI2745GPXP/
mv -n	igvf_003/nova1/Sublibrary_3_S2_L001_I1_001.fastq.gz	igvf_003/nova1/igvf_003_B03_D_nova_N1_L001_I1.fastq.gz		#e648ccf9022748732f8ba1b9ce6c3041
mv -n	igvf_003/nova1/Sublibrary_3_S2_L001_R1_001.fastq.gz	igvf_003/nova1/igvf_003_B03_D_nova_N1_L001_R1.fastq.gz		#db7c22a452a5e69d20e38c6e0c498bc5	https://api.data.igvf.org/sequence-files/IGVFFI0354NDEN/
mv -n	igvf_003/nova1/Sublibrary_3_S2_L001_R2_001.fastq.gz	igvf_003/nova1/igvf_003_B03_D_nova_N1_L001_R2.fastq.gz		#c98081e60b87de011b906699340490e2	https://api.data.igvf.org/sequence-files/IGVFFI0946ORGQ/

mv -n	igvf_004/nova1/Sublibrary_12_S11_L001_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B12_D_nova_N1_L001_R1.fastq.gz		#a355e2eda77543b1446c55569e84f082	https://api.data.igvf.org/sequence-files/IGVFFI2463AKSF/
mv -n	igvf_004/nova1/Sublibrary_12_S11_L001_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B12_D_nova_N1_L001_R2.fastq.gz		#dc80f2b4b2a4eaaeec93528edd97e902	https://api.data.igvf.org/sequence-files/IGVFFI2842PLJB/
mv -n	igvf_004/nova1/Sublibrary_12_S11_L002_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B12_D_nova_N1_L002_I1.fastq.gz		#0c2b06780e9524591359bbb4558e33e1
mv -n	igvf_004/nova1/Sublibrary_12_S11_L002_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B12_D_nova_N1_L002_R1.fastq.gz		#1bdd813ee656c008a1e67e460ca3bf48	https://api.data.igvf.org/sequence-files/IGVFFI5105WGDO/
mv -n	igvf_004/nova1/Sublibrary_12_S11_L002_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B12_D_nova_N1_L002_R2.fastq.gz		#833f7751cccce848423a966040c962c7	https://api.data.igvf.org/sequence-files/IGVFFI4752XESZ/
mv -n	igvf_004/nova1/Sublibrary_12_S11_L003_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B12_D_nova_N1_L003_I1.fastq.gz		#52ef3053c522a17b72bed5bec0470994
mv -n	igvf_004/nova1/Sublibrary_12_S11_L003_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B12_D_nova_N1_L003_R1.fastq.gz		#71f0b220f5923f3e22a3fd21e2e2be70	https://api.data.igvf.org/sequence-files/IGVFFI9035VVNU/
mv -n	igvf_004/nova1/Sublibrary_12_S11_L003_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B12_D_nova_N1_L003_R2.fastq.gz		#d4fa690460de2d6da24d4049dddecb7f	https://api.data.igvf.org/sequence-files/IGVFFI1259DRCS/
mv -n	igvf_004/nova1/Sublibrary_12_S11_L004_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B12_D_nova_N1_L004_I1.fastq.gz		#5454b05bee941bf9a90d6d0691edc577
mv -n	igvf_004/nova1/Sublibrary_12_S11_L004_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B12_D_nova_N1_L004_R1.fastq.gz		#7c4eb82b8520fdb1ccc87408d4f819f6	https://api.data.igvf.org/sequence-files/IGVFFI3865XYTO/
mv -n	igvf_004/nova1/Sublibrary_12_S11_L004_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B12_D_nova_N1_L004_R2.fastq.gz		#d61f88556bce54e4eef42864f745b3fa	https://api.data.igvf.org/sequence-files/IGVFFI6864DNYV/
mv -n	igvf_004/nova1/Sublibrary_13_S12_L001_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B13_D_nova_N1_L001_I1.fastq.gz		#b82b4152f025f1d13d8eb0353390f542
mv -n	igvf_004/nova1/Sublibrary_13_S12_L001_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B13_D_nova_N1_L001_R1.fastq.gz		#c458912637161c38ded725eb6a55ffc1	https://api.data.igvf.org/sequence-files/IGVFFI1422IYYU/
mv -n	igvf_004/nova1/Sublibrary_13_S12_L001_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B13_D_nova_N1_L001_R2.fastq.gz		#95f6616d7e397af8bdfd5705756f3a52	https://api.data.igvf.org/sequence-files/IGVFFI3866QPFJ/
mv -n	igvf_004/nova1/Sublibrary_13_S12_L002_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B13_D_nova_N1_L002_I1.fastq.gz		#cd624d946e8d4e6a6c8ddef0167bc677
mv -n	igvf_004/nova1/Sublibrary_13_S12_L002_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B13_D_nova_N1_L002_R1.fastq.gz		#f37a20e2ac3e8cfae798ae096c0f32f9	https://api.data.igvf.org/sequence-files/IGVFFI1220OWPR/
mv -n	igvf_004/nova1/Sublibrary_13_S12_L002_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B13_D_nova_N1_L002_R2.fastq.gz		#097e0d31ca2b61a1ccacbb0791496fb4	https://api.data.igvf.org/sequence-files/IGVFFI8976TDKZ/
mv -n	igvf_004/nova1/Sublibrary_13_S12_L003_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B13_D_nova_N1_L003_I1.fastq.gz		#7bc55a5e231bf8e9f8c500328b6509c9
mv -n	igvf_004/nova1/Sublibrary_13_S12_L003_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B13_D_nova_N1_L003_R1.fastq.gz		#fa9d19728c2ffbd0bf2469147dc37923	https://api.data.igvf.org/sequence-files/IGVFFI2858PUIB/
mv -n	igvf_004/nova1/Sublibrary_13_S12_L003_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B13_D_nova_N1_L003_R2.fastq.gz		#c7684d783a2e6961f1571dea736b05c9	https://api.data.igvf.org/sequence-files/IGVFFI7566MOKZ/
mv -n	igvf_004/nova1/Sublibrary_13_S12_L004_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B13_D_nova_N1_L004_I1.fastq.gz		#614981e6d9debb907659dd378b2960cf
mv -n	igvf_004/nova1/Sublibrary_13_S12_L004_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B13_D_nova_N1_L004_R1.fastq.gz		#13dbd506207489e1bfb7fb90e649a584	https://api.data.igvf.org/sequence-files/IGVFFI1050RNRE/
mv -n	igvf_004/nova1/Sublibrary_13_S12_L004_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B13_D_nova_N1_L004_R2.fastq.gz		#26bf10852d89435075c836c5e023deb0	https://api.data.igvf.org/sequence-files/IGVFFI1961YBUX/
mv -n	igvf_004/nova1/Sublibrary_14_S13_L001_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B14_D_nova_N1_L001_I1.fastq.gz		#5915ba9af96d0f574b2369e74be923f8
mv -n	igvf_004/nova1/Sublibrary_14_S13_L001_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B14_D_nova_N1_L001_R1.fastq.gz		#f20d4009fcad973ce697a0442eac9bab	https://api.data.igvf.org/sequence-files/IGVFFI5526GZOC/
mv -n	igvf_004/nova1/Sublibrary_14_S13_L001_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B14_D_nova_N1_L001_R2.fastq.gz		#1ab10a8ada340e5fc6fa3ab0f1872fd7	https://api.data.igvf.org/sequence-files/IGVFFI7594RBZM/
mv -n	igvf_004/nova1/Sublibrary_14_S13_L002_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B14_D_nova_N1_L002_I1.fastq.gz		#4965300de3d4ae531dabeb06eb061e23
mv -n	igvf_004/nova1/Sublibrary_14_S13_L002_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B14_D_nova_N1_L002_R1.fastq.gz		#94ffc3f5237a5f1a6b7def58ef902ed3	https://api.data.igvf.org/sequence-files/IGVFFI4942LTRT/
mv -n	igvf_004/nova1/Sublibrary_14_S13_L002_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B14_D_nova_N1_L002_R2.fastq.gz		#7ec50b47ae513298a78d69d9eb1d5327	https://api.data.igvf.org/sequence-files/IGVFFI2213YBYG/
mv -n	igvf_004/nova1/Sublibrary_14_S13_L003_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B14_D_nova_N1_L003_I1.fastq.gz		#bb0decc0ed82a5b5a7e0de1b8c81c701
mv -n	igvf_004/nova1/Sublibrary_14_S13_L003_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B14_D_nova_N1_L003_R1.fastq.gz		#35e2b5686a2949193a0ed1cdb7c04a76	https://api.data.igvf.org/sequence-files/IGVFFI1360UGYH/
mv -n	igvf_004/nova1/Sublibrary_14_S13_L003_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B14_D_nova_N1_L003_R2.fastq.gz		#a6e803195c78882074158d68ae5576f3	https://api.data.igvf.org/sequence-files/IGVFFI8073EUID/
mv -n	igvf_004/nova1/Sublibrary_14_S13_L004_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B14_D_nova_N1_L004_I1.fastq.gz		#de3dba02ee74bb72ace84a4bb39f7881
mv -n	igvf_004/nova1/Sublibrary_14_S13_L004_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B14_D_nova_N1_L004_R1.fastq.gz		#90340f0f7f754d7340b47c61580c6bc7	https://api.data.igvf.org/sequence-files/IGVFFI9486AODK/
mv -n	igvf_004/nova1/Sublibrary_14_S13_L004_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B14_D_nova_N1_L004_R2.fastq.gz		#e7fd2d4ea79dc75023e98c870cc43f61	https://api.data.igvf.org/sequence-files/IGVFFI1153QWWI/
mv -n	igvf_004/nova1/Sublibrary_15_S14_L001_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B15_D_nova_N1_L001_I1.fastq.gz		#d3b40d98077097a3a214e7124255a37c
mv -n	igvf_004/nova1/Sublibrary_15_S14_L001_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B15_D_nova_N1_L001_R1.fastq.gz		#6c7ac6397613436ba4195472273c49d2	https://api.data.igvf.org/sequence-files/IGVFFI1221HBMP/
mv -n	igvf_004/nova1/Sublibrary_15_S14_L001_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B15_D_nova_N1_L001_R2.fastq.gz		#72478d810741c82e8b00685bc0a6f770	https://api.data.igvf.org/sequence-files/IGVFFI5586TGPT/
mv -n	igvf_004/nova1/Sublibrary_15_S14_L002_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B15_D_nova_N1_L002_I1.fastq.gz		#ac28692750a67a1dec7a4dfaecf8e460
mv -n	igvf_004/nova1/Sublibrary_15_S14_L002_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B15_D_nova_N1_L002_R1.fastq.gz		#18d5c41cf55d35a46538c1db30fbff6d	https://api.data.igvf.org/sequence-files/IGVFFI5947ORGE/
mv -n	igvf_004/nova1/Sublibrary_15_S14_L002_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B15_D_nova_N1_L002_R2.fastq.gz		#346f1a54be26735545ff691037fc385d	https://api.data.igvf.org/sequence-files/IGVFFI7116EAFT/
mv -n	igvf_004/nova1/Sublibrary_15_S14_L003_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B15_D_nova_N1_L003_I1.fastq.gz		#4bea6983dd68b039c9c2582c978d0afb
mv -n	igvf_004/nova1/Sublibrary_15_S14_L003_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B15_D_nova_N1_L003_R1.fastq.gz		#a25eb265531fac082de597c20106b568	https://api.data.igvf.org/sequence-files/IGVFFI7419FMGK/
mv -n	igvf_004/nova1/Sublibrary_15_S14_L003_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B15_D_nova_N1_L003_R2.fastq.gz		#b2e9d73cb56073ef8a24b157f8aa5b80	https://api.data.igvf.org/sequence-files/IGVFFI6986PXBM/
mv -n	igvf_004/nova1/Sublibrary_15_S14_L004_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B15_D_nova_N1_L004_I1.fastq.gz		#622a1e5546416a28d936e38b395a7c1d
mv -n	igvf_004/nova1/Sublibrary_15_S14_L004_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B15_D_nova_N1_L004_R1.fastq.gz		#7583b04d4ec7cdeec06e270b61219a8a	https://api.data.igvf.org/sequence-files/IGVFFI9684TAYY/
mv -n	igvf_004/nova1/Sublibrary_15_S14_L004_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B15_D_nova_N1_L004_R2.fastq.gz		#f4fd6f1dc375d214bde6361ef2d4eed4	https://api.data.igvf.org/sequence-files/IGVFFI0720BPXV/
mv -n	igvf_004/nova1/Sublibrary_16_S15_L001_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B16_D_nova_N1_L001_I1.fastq.gz		#dc1f0699d0a7c3716a260965afac89dc
mv -n	igvf_004/nova1/Sublibrary_16_S15_L001_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B16_D_nova_N1_L001_R1.fastq.gz		#0a47fd72289f4c7bdf55bdeac44d3c09	https://api.data.igvf.org/sequence-files/IGVFFI9607JQYM/
mv -n	igvf_004/nova1/Sublibrary_16_S15_L001_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B16_D_nova_N1_L001_R2.fastq.gz		#028c6220881164fc5e2a8a6ad8e974ed	https://api.data.igvf.org/sequence-files/IGVFFI5695OMGG/
mv -n	igvf_004/nova1/Sublibrary_16_S15_L002_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B16_D_nova_N1_L002_I1.fastq.gz		#a44c269151d63141874ea773baa407a4
mv -n	igvf_004/nova1/Sublibrary_16_S15_L002_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B16_D_nova_N1_L002_R1.fastq.gz		#093e74e1d2d09818b8b45041ac3122ff	https://api.data.igvf.org/sequence-files/IGVFFI0795WXUM/
mv -n	igvf_004/nova1/Sublibrary_16_S15_L002_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B16_D_nova_N1_L002_R2.fastq.gz		#e87b44e2dbbf5e589afd971ba7469173	https://api.data.igvf.org/sequence-files/IGVFFI6539AGFZ/
mv -n	igvf_004/nova1/Sublibrary_16_S15_L003_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B16_D_nova_N1_L003_I1.fastq.gz		#83b491560fa6c11fd6d6267572ed1eaa
mv -n	igvf_004/nova1/Sublibrary_16_S15_L003_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B16_D_nova_N1_L003_R1.fastq.gz		#3936dee09b0f4809821f639f80e89b19	https://api.data.igvf.org/sequence-files/IGVFFI0664DQSU/
mv -n	igvf_004/nova1/Sublibrary_16_S15_L003_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B16_D_nova_N1_L003_R2.fastq.gz		#23a6ed489fe53accba6db235f307d79f	https://api.data.igvf.org/sequence-files/IGVFFI6320KMWF/
mv -n	igvf_004/nova1/Sublibrary_16_S15_L004_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B16_D_nova_N1_L004_I1.fastq.gz		#05a35a649c9d8280b2109965c3a5d9d1
mv -n	igvf_004/nova1/Sublibrary_16_S15_L004_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B16_D_nova_N1_L004_R1.fastq.gz		#f851ea47ed44bfefec97ff9822c363fe	https://api.data.igvf.org/sequence-files/IGVFFI6451KLUX/
mv -n	igvf_004/nova1/Sublibrary_16_S15_L004_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B16_D_nova_N1_L004_R2.fastq.gz		#5d26d55eff99cda323f784b782481f6b	https://api.data.igvf.org/sequence-files/IGVFFI0785UZJX/
mv -n	igvf_004/nova1/Sublibrary_2_S1_L001_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B02_D_nova_N1_L001_I1.fastq.gz		#6bf9142779214776cdc9fa06cc081b22
mv -n	igvf_004/nova1/Sublibrary_2_S1_L001_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B02_D_nova_N1_L001_R1.fastq.gz		#091ce70e2a81a67cab829a8ad950a05c	https://api.data.igvf.org/sequence-files/IGVFFI7230WRUB/
mv -n	igvf_004/nova1/Sublibrary_2_S1_L001_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B02_D_nova_N1_L001_R2.fastq.gz		#9fc966f9a65017ed8d08253358f9838a	https://api.data.igvf.org/sequence-files/IGVFFI8079TNAG/
mv -n	igvf_004/nova1/Sublibrary_2_S1_L002_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B02_D_nova_N1_L002_I1.fastq.gz		#dd14ff651e62ea4b56a8eba69129bd6a
mv -n	igvf_004/nova1/Sublibrary_2_S1_L002_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B02_D_nova_N1_L002_R1.fastq.gz		#a71346fbebadc9cd919371c635fbc4a7	https://api.data.igvf.org/sequence-files/IGVFFI9936KMXK/
mv -n	igvf_004/nova1/Sublibrary_2_S1_L002_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B02_D_nova_N1_L002_R2.fastq.gz		#b7d9ee19e2e3d326d806185d309bd751	https://api.data.igvf.org/sequence-files/IGVFFI6301PPMM/
mv -n	igvf_004/nova1/Sublibrary_2_S1_L003_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B02_D_nova_N1_L003_I1.fastq.gz		#a880761765a94baae2d0b5a075c6544c
mv -n	igvf_004/nova1/Sublibrary_2_S1_L003_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B02_D_nova_N1_L003_R1.fastq.gz		#42fc16a794c9f570eca9eca1393672a2	https://api.data.igvf.org/sequence-files/IGVFFI2005DKQW/
mv -n	igvf_004/nova1/Sublibrary_2_S1_L003_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B02_D_nova_N1_L003_R2.fastq.gz		#a898c9dbb5173d72304dcdda3e693d71	https://api.data.igvf.org/sequence-files/IGVFFI1205PJAX/
mv -n	igvf_004/nova1/Sublibrary_2_S1_L004_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B02_D_nova_N1_L004_I1.fastq.gz		#5adfd8b7a48ad2c208f9acbc776d0913
mv -n	igvf_004/nova1/Sublibrary_2_S1_L004_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B02_D_nova_N1_L004_R1.fastq.gz		#32113bed6290500ee58281936ebadc0a	https://api.data.igvf.org/sequence-files/IGVFFI7396VOAU/
mv -n	igvf_004/nova1/Sublibrary_2_S1_L004_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B02_D_nova_N1_L004_R2.fastq.gz		#de9bc2b72383f85a2779c6f90fc1ff96	https://api.data.igvf.org/sequence-files/IGVFFI6944UJFB/
mv -n	igvf_004/nova1/Sublibrary_3_S2_L001_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B03_D_nova_N1_L001_I1.fastq.gz		#d36f3fff2ba017c69d356c3a5fb15118
mv -n	igvf_004/nova1/Sublibrary_3_S2_L001_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B03_D_nova_N1_L001_R1.fastq.gz		#be0419eb87c252b1b35f7f62a23d0476	https://api.data.igvf.org/sequence-files/IGVFFI0835BNXJ/
mv -n	igvf_004/nova1/Sublibrary_3_S2_L001_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B03_D_nova_N1_L001_R2.fastq.gz		#2219b962c5c81feddc0b63bb38605728	https://api.data.igvf.org/sequence-files/IGVFFI3258UBUX/
mv -n	igvf_004/nova1/Sublibrary_3_S2_L002_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B03_D_nova_N1_L002_I1.fastq.gz		#38c72febb5b737237f6c4058fce0fd05
mv -n	igvf_004/nova1/Sublibrary_3_S2_L002_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B03_D_nova_N1_L002_R1.fastq.gz		#096237a6e997f226244978eb1d908a93	https://api.data.igvf.org/sequence-files/IGVFFI9168RAQG/
mv -n	igvf_004/nova1/Sublibrary_3_S2_L002_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B03_D_nova_N1_L002_R2.fastq.gz		#9d0708779041d8315ac46b8534f2b15c	https://api.data.igvf.org/sequence-files/IGVFFI6396GSLZ/
mv -n	igvf_004/nova1/Sublibrary_3_S2_L003_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B03_D_nova_N1_L003_I1.fastq.gz		#7af517bf561519776d5965d66d3cd696
mv -n	igvf_004/nova1/Sublibrary_3_S2_L003_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B03_D_nova_N1_L003_R1.fastq.gz		#63d8f3ec621aecf7569cf8eeb2b94ab9	https://api.data.igvf.org/sequence-files/IGVFFI2927CZQQ/
mv -n	igvf_004/nova1/Sublibrary_3_S2_L003_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B03_D_nova_N1_L003_R2.fastq.gz		#399c2a49c7ff22d3e494924371d6b4a7	https://api.data.igvf.org/sequence-files/IGVFFI8512QQEF/
mv -n	igvf_004/nova1/Sublibrary_3_S2_L004_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B03_D_nova_N1_L004_I1.fastq.gz		#a1f95613124e7c1d1ed82a08fdb329a8
mv -n	igvf_004/nova1/Sublibrary_3_S2_L004_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B03_D_nova_N1_L004_R1.fastq.gz		#b159a646077c4ebe60baba76e03e9a30	https://api.data.igvf.org/sequence-files/IGVFFI5772STBT/
mv -n	igvf_004/nova1/Sublibrary_3_S2_L004_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B03_D_nova_N1_L004_R2.fastq.gz		#831b4c80b3855f671072e2fa9a4aa401	https://api.data.igvf.org/sequence-files/IGVFFI2827XWCU/
mv -n	igvf_004/nova1/Sublibrary_4_S3_L001_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B04_D_nova_N1_L001_I1.fastq.gz		#c677ecc68afd14827dca2255997dcc48
mv -n	igvf_004/nova1/Sublibrary_4_S3_L001_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B04_D_nova_N1_L001_R1.fastq.gz		#1ae43c9897223dbb15ff3e2b0fa53008	https://api.data.igvf.org/sequence-files/IGVFFI8910ICXB/
mv -n	igvf_004/nova1/Sublibrary_4_S3_L001_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B04_D_nova_N1_L001_R2.fastq.gz		#f01181fa31093a024ad42e6237babe8d	https://api.data.igvf.org/sequence-files/IGVFFI1411UUXD/
mv -n	igvf_004/nova1/Sublibrary_4_S3_L002_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B04_D_nova_N1_L002_I1.fastq.gz		#937121de4b37e5650e340cbef96351b8
mv -n	igvf_004/nova1/Sublibrary_4_S3_L002_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B04_D_nova_N1_L002_R1.fastq.gz		#e4ba135dba9d7e7cd5f8f73bd0bbfd25	https://api.data.igvf.org/sequence-files/IGVFFI0387UWPG/
mv -n	igvf_004/nova1/Sublibrary_4_S3_L002_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B04_D_nova_N1_L002_R2.fastq.gz		#67a28c6b7eee5dd5355317995eff23ca	https://api.data.igvf.org/sequence-files/IGVFFI9051PCFO/
mv -n	igvf_004/nova1/Sublibrary_4_S3_L003_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B04_D_nova_N1_L003_I1.fastq.gz		#0b62989933f0be48375a6052f1959d90
mv -n	igvf_004/nova1/Sublibrary_4_S3_L003_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B04_D_nova_N1_L003_R1.fastq.gz		#ba8f751700841d0e5e35e7192aeef8b4	https://api.data.igvf.org/sequence-files/IGVFFI4051MODF/
mv -n	igvf_004/nova1/Sublibrary_4_S3_L003_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B04_D_nova_N1_L003_R2.fastq.gz		#fae45bef661ebdaffc8bd988ad973bb7	https://api.data.igvf.org/sequence-files/IGVFFI3376VHFM/
mv -n	igvf_004/nova1/Sublibrary_4_S3_L004_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B04_D_nova_N1_L004_I1.fastq.gz		#6ed9b5c34b193f8adca1dba6300400ba
mv -n	igvf_004/nova1/Sublibrary_4_S3_L004_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B04_D_nova_N1_L004_R1.fastq.gz		#58b5ad20d04cca18a4f9b90e1445c1b4	https://api.data.igvf.org/sequence-files/IGVFFI7332PZXC/
mv -n	igvf_004/nova1/Sublibrary_4_S3_L004_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B04_D_nova_N1_L004_R2.fastq.gz		#793ace3aab7fde1ead9d2cd803d960ce	https://api.data.igvf.org/sequence-files/IGVFFI6648ERSI/
mv -n	igvf_004/nova1/Sublibrary_5_S4_L001_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B05_D_nova_N1_L001_I1.fastq.gz		#2f0a3575b1c83617c34317818b08648c
mv -n	igvf_004/nova1/Sublibrary_5_S4_L001_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B05_D_nova_N1_L001_R1.fastq.gz		#dbde1caebe27de7d9fc029f787078559	https://api.data.igvf.org/sequence-files/IGVFFI6204TVDF/
mv -n	igvf_004/nova1/Sublibrary_5_S4_L001_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B05_D_nova_N1_L001_R2.fastq.gz		#11665291c0200154ce4970a564b0eebd	https://api.data.igvf.org/sequence-files/IGVFFI0825OHYS/
mv -n	igvf_004/nova1/Sublibrary_5_S4_L002_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B05_D_nova_N1_L002_I1.fastq.gz		#5f4bd7eee03b43486d6cfc870ee73387
mv -n	igvf_004/nova1/Sublibrary_5_S4_L002_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B05_D_nova_N1_L002_R1.fastq.gz		#c3ead83fa41c61c7543f0edad22e1795	https://api.data.igvf.org/sequence-files/IGVFFI3742VQQV/
mv -n	igvf_004/nova1/Sublibrary_5_S4_L002_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B05_D_nova_N1_L002_R2.fastq.gz		#f996476af14ef27280793059f19ce129	https://api.data.igvf.org/sequence-files/IGVFFI9746DVHN/
mv -n	igvf_004/nova1/Sublibrary_5_S4_L003_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B05_D_nova_N1_L003_I1.fastq.gz		#f2460f2a161c46522eeb2ec49e6fbe8b
mv -n	igvf_004/nova1/Sublibrary_5_S4_L003_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B05_D_nova_N1_L003_R1.fastq.gz		#a52ffd9922caa7a148f56e0ae66039da	https://api.data.igvf.org/sequence-files/IGVFFI0397UIUP/
mv -n	igvf_004/nova1/Sublibrary_5_S4_L003_R2_001.fastq.gz	igvf_004/nova1/igvf_004_B05_D_nova_N1_L003_R2.fastq.gz		#94f59a944c03d87e8d58f49032dc2ea2	https://api.data.igvf.org/sequence-files/IGVFFI7315MONF/
mv -n	igvf_004/nova1/Sublibrary_5_S4_L004_I1_001.fastq.gz	igvf_004/nova1/igvf_004_B05_D_nova_N1_L004_I1.fastq.gz		#846f22f0fcdda31a0653ec578c314656
mv -n	igvf_004/nova1/Sublibrary_5_S4_L004_R1_001.fastq.gz	igvf_004/nova1/igvf_004_B05_D_nova_N1_L004_R1.fastq.gz		#48879d0646b604ce71263578dbe97a13	https://api.data.igvf.org/sequence-files/IGVFFI9818VACA/

mv -n	igvf_005/nova1/Sublibrary_6_S5_L004_I1_001.fastq.gz	igvf_005/nova1/igvf_005_B06_D_nova_N1_L004_I1.fastq.gz		#1aeb39214f7dd9d7c9250f5f01882593
mv -n	igvf_005/nova1/Sublibrary_6_S5_L004_R1_001.fastq.gz	igvf_005/nova1/igvf_005_B06_D_nova_N1_L004_R1.fastq.gz		#8f947dcc0ed0bafda54343ba697bae78	https://api.data.igvf.org/sequence-files/IGVFFI7976ERLA/
mv -n	igvf_005/nova1/Sublibrary_6_S5_L004_R2_001.fastq.gz	igvf_005/nova1/igvf_005_B06_D_nova_N1_L004_R2.fastq.gz		#fa5cc54d55647c4ecb10526f43339f96	https://api.data.igvf.org/sequence-files/IGVFFI1404RRLZ/
mv -n	igvf_005/nova1/Sublibrary_7_S6_L001_I1_001.fastq.gz	igvf_005/nova1/igvf_005_B07_D_nova_N1_L001_I1.fastq.gz		#9e7879872cc7148e03b55ba694b76d3f
mv -n	igvf_005/nova1/Sublibrary_7_S6_L001_R1_001.fastq.gz	igvf_005/nova1/igvf_005_B07_D_nova_N1_L001_R1.fastq.gz		#2141ff31d3124d55f43361e0bf541430	https://api.data.igvf.org/sequence-files/IGVFFI6749XMCZ/
mv -n	igvf_005/nova1/Sublibrary_7_S6_L001_R2_001.fastq.gz	igvf_005/nova1/igvf_005_B07_D_nova_N1_L001_R2.fastq.gz		#ab6f286b88669e2209b38a1655e52d1e	https://api.data.igvf.org/sequence-files/IGVFFI1812SBYW/
mv -n	igvf_005/nova1/Sublibrary_7_S6_L002_I1_001.fastq.gz	igvf_005/nova1/igvf_005_B07_D_nova_N1_L002_I1.fastq.gz		#c9477c90ceb44de0c41d1a48351116c7
mv -n	igvf_005/nova1/Sublibrary_7_S6_L002_R1_001.fastq.gz	igvf_005/nova1/igvf_005_B07_D_nova_N1_L002_R1.fastq.gz		#efe3057072170569a853310b20c7ce93	https://api.data.igvf.org/sequence-files/IGVFFI6215NTXP/
mv -n	igvf_005/nova1/Sublibrary_7_S6_L002_R2_001.fastq.gz	igvf_005/nova1/igvf_005_B07_D_nova_N1_L002_R2.fastq.gz		#f2f56485c8867565a5cf6c4d623ede69	https://api.data.igvf.org/sequence-files/IGVFFI1683IZTX/
mv -n	igvf_005/nova1/Sublibrary_7_S6_L003_I1_001.fastq.gz	igvf_005/nova1/igvf_005_B07_D_nova_N1_L003_I1.fastq.gz		#06ecf4cc85a28d6a09a29aeb98d7db84
mv -n	igvf_005/nova1/Sublibrary_7_S6_L003_R1_001.fastq.gz	igvf_005/nova1/igvf_005_B07_D_nova_N1_L003_R1.fastq.gz		#ac1d30fb5d3a10343859de254463373a	https://api.data.igvf.org/sequence-files/IGVFFI6843SJLO/
mv -n	igvf_005/nova1/Sublibrary_7_S6_L003_R2_001.fastq.gz	igvf_005/nova1/igvf_005_B07_D_nova_N1_L003_R2.fastq.gz		#0c0e9808989b0d894597e0980b5b1f07	https://api.data.igvf.org/sequence-files/IGVFFI7276YUTA/
mv -n	igvf_005/nova1/Sublibrary_7_S6_L004_I1_001.fastq.gz	igvf_005/nova1/igvf_005_B07_D_nova_N1_L004_I1.fastq.gz		#52e961f3245d5e6dab241d3214bbbcf6
mv -n	igvf_005/nova1/Sublibrary_7_S6_L004_R1_001.fastq.gz	igvf_005/nova1/igvf_005_B07_D_nova_N1_L004_R1.fastq.gz		#561346e58b8257b3e588c159909755af	https://api.data.igvf.org/sequence-files/IGVFFI8473NQDG/
mv -n	igvf_005/nova1/Sublibrary_7_S6_L004_R2_001.fastq.gz	igvf_005/nova1/igvf_005_B07_D_nova_N1_L004_R2.fastq.gz		#25fb1af8540109d997dda7b6bdbaca83	https://api.data.igvf.org/sequence-files/IGVFFI1521XXZJ/
mv -n	igvf_005/nova1/Sublibrary_8_S7_L001_I1_001.fastq.gz	igvf_005/nova1/igvf_005_B08_D_nova_N1_L001_I1.fastq.gz		#bae9f84a373ef38c0f14585c81770d3d
mv -n	igvf_005/nova1/Sublibrary_8_S7_L001_R1_001.fastq.gz	igvf_005/nova1/igvf_005_B08_D_nova_N1_L001_R1.fastq.gz		#88e2f7b21437945a59d902b5989d520c	https://api.data.igvf.org/sequence-files/IGVFFI8243RVXU/
mv -n	igvf_005/nova1/Sublibrary_8_S7_L001_R2_001.fastq.gz	igvf_005/nova1/igvf_005_B08_D_nova_N1_L001_R2.fastq.gz		#e099451db469777cd12a9c5eaa2d393e	https://api.data.igvf.org/sequence-files/IGVFFI4035YXUS/
mv -n	igvf_005/nova1/Sublibrary_8_S7_L002_I1_001.fastq.gz	igvf_005/nova1/igvf_005_B08_D_nova_N1_L002_I1.fastq.gz		#fcf5f76cf902ad129dabb137cee8cc7b
mv -n	igvf_005/nova1/Sublibrary_8_S7_L002_R1_001.fastq.gz	igvf_005/nova1/igvf_005_B08_D_nova_N1_L002_R1.fastq.gz		#174fa4104c605eca8a9205ee9619f078	https://api.data.igvf.org/sequence-files/IGVFFI7369DMPZ/
mv -n	igvf_005/nova1/Sublibrary_8_S7_L002_R2_001.fastq.gz	igvf_005/nova1/igvf_005_B08_D_nova_N1_L002_R2.fastq.gz		#fb97266acd289e295a7838d7e0e60693	https://api.data.igvf.org/sequence-files/IGVFFI8174EGJB/
mv -n	igvf_005/nova1/Sublibrary_8_S7_L003_I1_001.fastq.gz	igvf_005/nova1/igvf_005_B08_D_nova_N1_L003_I1.fastq.gz		#43b7193abea66504245e4f57a6d62432
mv -n	igvf_005/nova1/Sublibrary_8_S7_L003_R1_001.fastq.gz	igvf_005/nova1/igvf_005_B08_D_nova_N1_L003_R1.fastq.gz		#7ca6c548e5f34ca8a49a5fd309445de0	https://api.data.igvf.org/sequence-files/IGVFFI2499SRGG/
mv -n	igvf_005/nova1/Sublibrary_8_S7_L003_R2_001.fastq.gz	igvf_005/nova1/igvf_005_B08_D_nova_N1_L003_R2.fastq.gz		#7460852cb11f1e2f890efc06a4a1d972	https://api.data.igvf.org/sequence-files/IGVFFI3679AVIC/
mv -n	igvf_005/nova1/Sublibrary_8_S7_L004_I1_001.fastq.gz	igvf_005/nova1/igvf_005_B08_D_nova_N1_L004_I1.fastq.gz		#93b7d94ccc2604eff01eed746c3327ad
mv -n	igvf_005/nova1/Sublibrary_8_S7_L004_R1_001.fastq.gz	igvf_005/nova1/igvf_005_B08_D_nova_N1_L004_R1.fastq.gz		#ded679536c9d783080cf9ed4ca1a02c2	https://api.data.igvf.org/sequence-files/IGVFFI0946JQFC/
mv -n	igvf_005/nova1/Sublibrary_8_S7_L004_R2_001.fastq.gz	igvf_005/nova1/igvf_005_B08_D_nova_N1_L004_R2.fastq.gz		#78fa59a04d383414f59e9cfda98d8871	https://api.data.igvf.org/sequence-files/IGVFFI4109VXVO/
mv -n	igvf_005/nova1/Sublibrary_9_S8_L001_I1_001.fastq.gz	igvf_005/nova1/igvf_005_B09_D_nova_N1_L001_I1.fastq.gz		#0054c3def0e4ad9fb8af830ed5207c2e
mv -n	igvf_005/nova1/Sublibrary_9_S8_L001_R1_001.fastq.gz	igvf_005/nova1/igvf_005_B09_D_nova_N1_L001_R1.fastq.gz		#f5c449c0ade8ae417875d9249e298d73	https://api.data.igvf.org/sequence-files/IGVFFI5434YCJY/
mv -n	igvf_005/nova1/Sublibrary_9_S8_L001_R2_001.fastq.gz	igvf_005/nova1/igvf_005_B09_D_nova_N1_L001_R2.fastq.gz		#1fddd12449e1b417535d785f9da605f0	https://api.data.igvf.org/sequence-files/IGVFFI7401FWEA/
mv -n	igvf_005/nova1/Sublibrary_9_S8_L002_I1_001.fastq.gz	igvf_005/nova1/igvf_005_B09_D_nova_N1_L002_I1.fastq.gz		#7cc6744c17ee6309d3989cf5b6e2827a
mv -n	igvf_005/nova1/Sublibrary_9_S8_L002_R1_001.fastq.gz	igvf_005/nova1/igvf_005_B09_D_nova_N1_L002_R1.fastq.gz		#00733641a74a1d17de4a8092ebd977a1	https://api.data.igvf.org/sequence-files/IGVFFI1311YKGH/
mv -n	igvf_005/nova1/Sublibrary_9_S8_L002_R2_001.fastq.gz	igvf_005/nova1/igvf_005_B09_D_nova_N1_L002_R2.fastq.gz		#3274cc512b7d083423eca10c93f5a071	https://api.data.igvf.org/sequence-files/IGVFFI2448ZGYI/
mv -n	igvf_005/nova1/Sublibrary_9_S8_L003_I1_001.fastq.gz	igvf_005/nova1/igvf_005_B09_D_nova_N1_L003_I1.fastq.gz		#2d08cf3a9f41b6d310c513d60dd6255d
mv -n	igvf_005/nova1/Sublibrary_9_S8_L003_R1_001.fastq.gz	igvf_005/nova1/igvf_005_B09_D_nova_N1_L003_R1.fastq.gz		#2f2be48603af4a18389d0655a6a30d96	https://api.data.igvf.org/sequence-files/IGVFFI4810SPHL/
mv -n	igvf_005/nova1/Sublibrary_9_S8_L003_R2_001.fastq.gz	igvf_005/nova1/igvf_005_B09_D_nova_N1_L003_R2.fastq.gz		#154e0ce9d800cc83816bc494c4a35cea	https://api.data.igvf.org/sequence-files/IGVFFI4058RJUN/
mv -n	igvf_005/nova1/Sublibrary_9_S8_L004_I1_001.fastq.gz	igvf_005/nova1/igvf_005_B09_D_nova_N1_L004_I1.fastq.gz		#e85d883c104f8d5d5f17d465563cd1c8
mv -n	igvf_005/nova1/Sublibrary_9_S8_L004_R1_001.fastq.gz	igvf_005/nova1/igvf_005_B09_D_nova_N1_L004_R1.fastq.gz		#e84bd1ed5b025ace3d8b0d25f7f0ca0d	https://api.data.igvf.org/sequence-files/IGVFFI9700JJAG/
mv -n	igvf_005/nova1/Sublibrary_9_S8_L004_R2_001.fastq.gz	igvf_005/nova1/igvf_005_B09_D_nova_N1_L004_R2.fastq.gz		#f43ca2540cfa36fe6799660fd619e4ba	https://api.data.igvf.org/sequence-files/IGVFFI2965DNEL/
mv -n	igvf_005/nova2/Sublibrary_10_S9_L001_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B10_D_nova_N2_L001_I1.fastq.gz		#b0ddf7c85e4f66c8adab5be016d304b5
mv -n	igvf_005/nova2/Sublibrary_10_S9_L001_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B10_D_nova_N2_L001_R1.fastq.gz		#d4236a9133a6efbf939aaa75c5c03fec	https://api.data.igvf.org/sequence-files/IGVFFI9705MLCF/
mv -n	igvf_005/nova2/Sublibrary_10_S9_L001_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B10_D_nova_N2_L001_R2.fastq.gz		#01d72d748a3ebece737d7d9036688945	https://api.data.igvf.org/sequence-files/IGVFFI3660SUSI/
mv -n	igvf_005/nova2/Sublibrary_10_S9_L002_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B10_D_nova_N2_L002_I1.fastq.gz		#575322efa5ac9949c4d1a1beb44cc408
mv -n	igvf_005/nova2/Sublibrary_10_S9_L002_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B10_D_nova_N2_L002_R1.fastq.gz		#271b2b099a3e42687a92a2e6fdc973c8	https://api.data.igvf.org/sequence-files/IGVFFI1708RNBS/
mv -n	igvf_005/nova2/Sublibrary_10_S9_L002_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B10_D_nova_N2_L002_R2.fastq.gz		#9b692d76442e0935f95f2255630ca7ca	https://api.data.igvf.org/sequence-files/IGVFFI6501BJYS/
mv -n	igvf_005/nova2/Sublibrary_10_S9_L003_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B10_D_nova_N2_L003_I1.fastq.gz		#dc41f68368d479dc467fc81a2522b323
mv -n	igvf_005/nova2/Sublibrary_10_S9_L003_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B10_D_nova_N2_L003_R1.fastq.gz		#955143a8c2327ac492c366c5eecff1ab	https://api.data.igvf.org/sequence-files/IGVFFI1013DLNJ/
mv -n	igvf_005/nova2/Sublibrary_10_S9_L003_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B10_D_nova_N2_L003_R2.fastq.gz		#975c34734f74b8774f08564642c0b52f	https://api.data.igvf.org/sequence-files/IGVFFI3565WQNZ/
mv -n	igvf_005/nova2/Sublibrary_10_S9_L004_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B10_D_nova_N2_L004_I1.fastq.gz		#0fb1ab3b5a30f69896853ae3b45ab2f3
mv -n	igvf_005/nova2/Sublibrary_10_S9_L004_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B10_D_nova_N2_L004_R1.fastq.gz		#8cda10b36f05edd117afcc7a79c423ed	https://api.data.igvf.org/sequence-files/IGVFFI5993XTCF/
mv -n	igvf_005/nova2/Sublibrary_10_S9_L004_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B10_D_nova_N2_L004_R2.fastq.gz		#fc9e44b1e2195416e3bada4662372847	https://api.data.igvf.org/sequence-files/IGVFFI9699OFPS/
mv -n	igvf_005/nova2/Sublibrary_11_S10_L001_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B11_D_nova_N2_L001_I1.fastq.gz		#5c63126e2c42e6e9b89184265eb2ea01
mv -n	igvf_005/nova2/Sublibrary_11_S10_L001_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B11_D_nova_N2_L001_R1.fastq.gz		#bf57823f6b067b31e46888d18c6d6569	https://api.data.igvf.org/sequence-files/IGVFFI3497IEEM/
mv -n	igvf_005/nova2/Sublibrary_11_S10_L001_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B11_D_nova_N2_L001_R2.fastq.gz		#f8dfb37904355508398ec1f6cbeaeb73	https://api.data.igvf.org/sequence-files/IGVFFI4471DENP/

mv -n	igvf_005/nova2/Sublibrary_11_S10_L002_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B11_D_nova_N2_L002_I1.fastq.gz		#209d1b8133fad1f9ae8b4175b8d51caa
mv -n	igvf_005/nova2/Sublibrary_11_S10_L002_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B11_D_nova_N2_L002_R1.fastq.gz		#9ed7561106f42d0af5efbee69c1da8b0	https://api.data.igvf.org/sequence-files/IGVFFI1380GMCV/
mv -n	igvf_005/nova2/Sublibrary_11_S10_L002_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B11_D_nova_N2_L002_R2.fastq.gz		#21e611873c273154e14d4cf8c7143ca3	https://api.data.igvf.org/sequence-files/IGVFFI0390CQUL/
mv -n	igvf_005/nova2/Sublibrary_11_S10_L003_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B11_D_nova_N2_L003_I1.fastq.gz		#d231b8c84cf5e3ddede32ce828a52e93
mv -n	igvf_005/nova2/Sublibrary_11_S10_L003_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B11_D_nova_N2_L003_R1.fastq.gz		#5edcccf9da8978669c049576db7d4016	https://api.data.igvf.org/sequence-files/IGVFFI3203LXON/
mv -n	igvf_005/nova2/Sublibrary_11_S10_L003_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B11_D_nova_N2_L003_R2.fastq.gz		#1480eb5b91fe36a80043047674a5af03	https://api.data.igvf.org/sequence-files/IGVFFI1254CZAZ/
mv -n	igvf_005/nova2/Sublibrary_11_S10_L004_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B11_D_nova_N2_L004_I1.fastq.gz		#bff049d0102ace1902c9a0cdd2cee658
mv -n	igvf_005/nova2/Sublibrary_11_S10_L004_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B11_D_nova_N2_L004_R1.fastq.gz		#114497c1d87ea020a3292f33e3c861dc	https://api.data.igvf.org/sequence-files/IGVFFI0259WOAQ/
mv -n	igvf_005/nova2/Sublibrary_11_S10_L004_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B11_D_nova_N2_L004_R2.fastq.gz		#7e06b2b7fea52931e21a325205e4916e	https://api.data.igvf.org/sequence-files/IGVFFI1511XBVS/
mv -n	igvf_005/nova2/Sublibrary_12_S11_L001_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B12_D_nova_N2_L001_I1.fastq.gz		#d50878e0801e0548b8ca2eb39cbe82b8
mv -n	igvf_005/nova2/Sublibrary_12_S11_L001_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B12_D_nova_N2_L001_R1.fastq.gz		#d595c37f2a889bb128279cdfea67635a	https://api.data.igvf.org/sequence-files/IGVFFI2041AUPW/
mv -n	igvf_005/nova2/Sublibrary_12_S11_L001_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B12_D_nova_N2_L001_R2.fastq.gz		#7b44b8a9229d208753c36dd6463a04e5	https://api.data.igvf.org/sequence-files/IGVFFI2971FMHZ/
mv -n	igvf_005/nova2/Sublibrary_12_S11_L002_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B12_D_nova_N2_L002_I1.fastq.gz		#1336753a0225f109ba652609d9d81976
mv -n	igvf_005/nova2/Sublibrary_12_S11_L002_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B12_D_nova_N2_L002_R1.fastq.gz		#016a94820d0a2f2e6317e6958d5ee9c6	https://api.data.igvf.org/sequence-files/IGVFFI3389ADLU/
mv -n	igvf_005/nova2/Sublibrary_12_S11_L002_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B12_D_nova_N2_L002_R2.fastq.gz		#7b7d7d9c5989b395cb897a47af285546	https://api.data.igvf.org/sequence-files/IGVFFI7985HLQH/
mv -n	igvf_005/nova2/Sublibrary_12_S11_L003_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B12_D_nova_N2_L003_I1.fastq.gz		#3b7300f8b9b8acae9880443d5ec1eeeb
mv -n	igvf_005/nova2/Sublibrary_12_S11_L003_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B12_D_nova_N2_L003_R1.fastq.gz		#144911cb3f9e2c24b8d70538768c2502	https://api.data.igvf.org/sequence-files/IGVFFI1796XQJU/
mv -n	igvf_005/nova2/Sublibrary_12_S11_L003_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B12_D_nova_N2_L003_R2.fastq.gz		#f7a0562085fbf37e2d3c94106ec84190	https://api.data.igvf.org/sequence-files/IGVFFI4798CTYS/
mv -n	igvf_005/nova2/Sublibrary_12_S11_L004_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B12_D_nova_N2_L004_I1.fastq.gz		#d4bbbe77b4570ba44273aef14a838260
mv -n	igvf_005/nova2/Sublibrary_12_S11_L004_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B12_D_nova_N2_L004_R1.fastq.gz		#3bedf329ba14a748a0035bab170c7ed0	https://api.data.igvf.org/sequence-files/IGVFFI5305YJRW/
mv -n	igvf_005/nova2/Sublibrary_12_S11_L004_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B12_D_nova_N2_L004_R2.fastq.gz		#23f012599dc4aa33689b400fcc2a845d	https://api.data.igvf.org/sequence-files/IGVFFI2161CSNQ/
mv -n	igvf_005/nova2/Sublibrary_13_S12_L001_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B13_D_nova_N2_L001_I1.fastq.gz		#ec39e8d349b128e4d2f89d8a4744e279
mv -n	igvf_005/nova2/Sublibrary_13_S12_L001_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B13_D_nova_N2_L001_R1.fastq.gz		#11b29e96b0f228995accd89721f4e0a0	https://api.data.igvf.org/sequence-files/IGVFFI8559UKEP/
mv -n	igvf_005/nova2/Sublibrary_13_S12_L001_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B13_D_nova_N2_L001_R2.fastq.gz		#b63c2f0d6f7c27a1765c8c3ed193a681	https://api.data.igvf.org/sequence-files/IGVFFI3927EZKE/
mv -n	igvf_005/nova2/Sublibrary_13_S12_L002_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B13_D_nova_N2_L002_I1.fastq.gz		#c0a7e44f8c31641cb104109c86676f89
mv -n	igvf_005/nova2/Sublibrary_13_S12_L002_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B13_D_nova_N2_L002_R1.fastq.gz		#d940ce954a0ef71bd8d1a97aa4da8d2f	https://api.data.igvf.org/sequence-files/IGVFFI0075MOVB/
mv -n	igvf_005/nova2/Sublibrary_13_S12_L002_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B13_D_nova_N2_L002_R2.fastq.gz		#3d45e5aad4123bf7ab9d981fd9c65c9c	https://api.data.igvf.org/sequence-files/IGVFFI5028VHPS/
mv -n	igvf_005/nova2/Sublibrary_13_S12_L003_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B13_D_nova_N2_L003_I1.fastq.gz		#e89c9aea3cbcd5d6dc173b710a20db78
mv -n	igvf_005/nova2/Sublibrary_13_S12_L003_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B13_D_nova_N2_L003_R1.fastq.gz		#81554a419906ef6ebf4b30d60a74f8b0	https://api.data.igvf.org/sequence-files/IGVFFI3577OMBM/
mv -n	igvf_005/nova2/Sublibrary_13_S12_L003_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B13_D_nova_N2_L003_R2.fastq.gz		#a017ddb6668d9f36dec1078a57a5fd7a	https://api.data.igvf.org/sequence-files/IGVFFI6921TGAX/
mv -n	igvf_005/nova2/Sublibrary_13_S12_L004_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B13_D_nova_N2_L004_I1.fastq.gz		#cf71609c902a45b8f5e9d0cd61fd88db
mv -n	igvf_005/nova2/Sublibrary_13_S12_L004_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B13_D_nova_N2_L004_R1.fastq.gz		#bfe4d1f60936b8bfda2f695d9223cd4d	https://api.data.igvf.org/sequence-files/IGVFFI3846RPTV/
mv -n	igvf_005/nova2/Sublibrary_13_S12_L004_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B13_D_nova_N2_L004_R2.fastq.gz		#bff9c3e33c792c5b54791610307cd887	https://api.data.igvf.org/sequence-files/IGVFFI9245XUZI/
mv -n	igvf_005/nova2/Sublibrary_14_S13_L001_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B14_D_nova_N2_L001_I1.fastq.gz		#50c2d974d1988b64a88fa5d0435421e2
mv -n	igvf_005/nova2/Sublibrary_14_S13_L001_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B14_D_nova_N2_L001_R1.fastq.gz		#cad8e744cd257077972fee1942e6cbdc	https://api.data.igvf.org/sequence-files/IGVFFI9278LERT/
mv -n	igvf_005/nova2/Sublibrary_14_S13_L001_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B14_D_nova_N2_L001_R2.fastq.gz		#58190e86412f359e4a19557e1bc99af9	https://api.data.igvf.org/sequence-files/IGVFFI4519RAQN/
mv -n	igvf_005/nova2/Sublibrary_14_S13_L002_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B14_D_nova_N2_L002_I1.fastq.gz		#2722690a56ad01eeb547fafacec91c0c
mv -n	igvf_005/nova2/Sublibrary_14_S13_L002_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B14_D_nova_N2_L002_R1.fastq.gz		#6f16af1530b4d561e876384eb9ea249d	https://api.data.igvf.org/sequence-files/IGVFFI1377SKQT/
mv -n	igvf_005/nova2/Sublibrary_14_S13_L002_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B14_D_nova_N2_L002_R2.fastq.gz		#d954313605a35e192950bc4bf8cc90f7	https://api.data.igvf.org/sequence-files/IGVFFI6272EFPO/
mv -n	igvf_005/nova2/Sublibrary_14_S13_L003_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B14_D_nova_N2_L003_I1.fastq.gz		#93f62abc926df7d4052a7a9bfb9ca207
mv -n	igvf_005/nova2/Sublibrary_14_S13_L003_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B14_D_nova_N2_L003_R1.fastq.gz		#a581386c2e0db4322348cae3da90b079	https://api.data.igvf.org/sequence-files/IGVFFI8829KSWB/
mv -n	igvf_005/nova2/Sublibrary_14_S13_L003_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B14_D_nova_N2_L003_R2.fastq.gz		#b8560133ed3d9aa66662a1703d353a06	https://api.data.igvf.org/sequence-files/IGVFFI9102ZFSR/
mv -n	igvf_005/nova2/Sublibrary_14_S13_L004_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B14_D_nova_N2_L004_I1.fastq.gz		#68257b93b03b95c0294c7c6ba4665703
mv -n	igvf_005/nova2/Sublibrary_14_S13_L004_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B14_D_nova_N2_L004_R1.fastq.gz		#079758e2a1b69969bc0b69ef971b22b4	https://api.data.igvf.org/sequence-files/IGVFFI8701NROQ/
mv -n	igvf_005/nova2/Sublibrary_14_S13_L004_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B14_D_nova_N2_L004_R2.fastq.gz		#788b8f969f1fc9a6262e53341e64c42d	https://api.data.igvf.org/sequence-files/IGVFFI2709RFYH/
mv -n	igvf_005/nova2/Sublibrary_15_S14_L001_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B15_D_nova_N2_L001_I1.fastq.gz		#100f6aae9e3e3d78182fb920868da45f
mv -n	igvf_005/nova2/Sublibrary_15_S14_L001_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B15_D_nova_N2_L001_R1.fastq.gz		#7f0e3f2138dc72f0efcdf315f7b3d6de	https://api.data.igvf.org/sequence-files/IGVFFI8040VLNZ/
mv -n	igvf_005/nova2/Sublibrary_15_S14_L001_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B15_D_nova_N2_L001_R2.fastq.gz		#b88f96ffd653d73ed4fdc0d19eae4c05	https://api.data.igvf.org/sequence-files/IGVFFI9354WGKK/
mv -n	igvf_005/nova2/Sublibrary_15_S14_L002_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B15_D_nova_N2_L002_I1.fastq.gz		#0a211d015bff17f6c43d49b99be55ae5
mv -n	igvf_005/nova2/Sublibrary_15_S14_L002_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B15_D_nova_N2_L002_R1.fastq.gz		#389ecf2fafcdcf8fc1a4052433b14636	https://api.data.igvf.org/sequence-files/IGVFFI1967XCVC/
mv -n	igvf_005/nova2/Sublibrary_15_S14_L002_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B15_D_nova_N2_L002_R2.fastq.gz		#0d8774b2c388fb63a1d4431c51dee59f	https://api.data.igvf.org/sequence-files/IGVFFI6418LTGO/
mv -n	igvf_005/nova2/Sublibrary_15_S14_L003_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B15_D_nova_N2_L003_I1.fastq.gz		#c51c3007fa85950a88223a4b85284a83
mv -n	igvf_005/nova2/Sublibrary_15_S14_L003_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B15_D_nova_N2_L003_R1.fastq.gz		#b22c5de90e4db5924bbc360906eb81ee	https://api.data.igvf.org/sequence-files/IGVFFI8044HAYP/
mv -n	igvf_005/nova2/Sublibrary_15_S14_L003_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B15_D_nova_N2_L003_R2.fastq.gz		#bec5783cda545b96a6387469895d2a5b	https://api.data.igvf.org/sequence-files/IGVFFI6631YJON/
mv -n	igvf_005/nova2/Sublibrary_15_S14_L004_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B15_D_nova_N2_L004_I1.fastq.gz		#a3db2bbb7913ce93f0048b2ddc8bdf98
mv -n	igvf_005/nova2/Sublibrary_15_S14_L004_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B15_D_nova_N2_L004_R1.fastq.gz		#21e41bb405172d11148dc40079b8a7e1	https://api.data.igvf.org/sequence-files/IGVFFI8355MWZT/
mv -n	igvf_005/nova2/Sublibrary_15_S14_L004_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B15_D_nova_N2_L004_R2.fastq.gz		#834b995756fa7132758430ce33b32ad0	https://api.data.igvf.org/sequence-files/IGVFFI0941SOLM/
mv -n	igvf_005/nova2/Sublibrary_16_S15_L001_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B16_D_nova_N2_L001_I1.fastq.gz		#f45ef3de3fea3d84c5282aa1d4020530
mv -n	igvf_005/nova2/Sublibrary_16_S15_L001_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B16_D_nova_N2_L001_R1.fastq.gz		#5d8c319b485b1bea5f80cf5b49726409	https://api.data.igvf.org/sequence-files/IGVFFI1618XYMU/
mv -n	igvf_005/nova2/Sublibrary_16_S15_L001_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B16_D_nova_N2_L001_R2.fastq.gz		#682a74a22574ee1b95c407d284af2fa0	https://api.data.igvf.org/sequence-files/IGVFFI9843EFCF/
mv -n	igvf_005/nova2/Sublibrary_16_S15_L002_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B16_D_nova_N2_L002_I1.fastq.gz		#fe1583fe0601e59fce2609e81b3c15eb
mv -n	igvf_005/nova2/Sublibrary_16_S15_L002_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B16_D_nova_N2_L002_R1.fastq.gz		#ee28e2c0003466391055e848ca16da54	https://api.data.igvf.org/sequence-files/IGVFFI7141BRRQ/
mv -n	igvf_005/nova2/Sublibrary_16_S15_L002_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B16_D_nova_N2_L002_R2.fastq.gz		#fa9766938ac11fbffbf20366e6f3e2f4	https://api.data.igvf.org/sequence-files/IGVFFI4648KNLQ/
mv -n	igvf_005/nova2/Sublibrary_16_S15_L003_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B16_D_nova_N2_L003_I1.fastq.gz		#a1b2d9d5928cf6a7868a4d33def27a5e
mv -n	igvf_005/nova2/Sublibrary_16_S15_L003_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B16_D_nova_N2_L003_R1.fastq.gz		#9b31b23a0dea52d9961ba6f8a2c84c82	https://api.data.igvf.org/sequence-files/IGVFFI5294CRXQ/
mv -n	igvf_005/nova2/Sublibrary_16_S15_L003_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B16_D_nova_N2_L003_R2.fastq.gz		#0d31c6628e9c0439a4e2301203e156bd	https://api.data.igvf.org/sequence-files/IGVFFI7380QXCT/
mv -n	igvf_005/nova2/Sublibrary_16_S15_L004_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B16_D_nova_N2_L004_I1.fastq.gz		#982c34eae876117801140590a2e3edb0
mv -n	igvf_005/nova2/Sublibrary_16_S15_L004_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B16_D_nova_N2_L004_R1.fastq.gz		#150b69d1a185bba90d6972b39e0a1a52	https://api.data.igvf.org/sequence-files/IGVFFI8340WUII/
mv -n	igvf_005/nova2/Sublibrary_16_S15_L004_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B16_D_nova_N2_L004_R2.fastq.gz		#b18e09fd9d874563295707ea0d190e78	https://api.data.igvf.org/sequence-files/IGVFFI9153TZNP/
mv -n	igvf_005/nova2/Sublibrary_2_S1_L001_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B02_D_nova_N2_L001_I1.fastq.gz		#274bb9d257d59c4e9f21e2463572e390
mv -n	igvf_005/nova2/Sublibrary_2_S1_L001_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B02_D_nova_N2_L001_R1.fastq.gz		#76831c060e1886edf90e2ee158ad79a4	https://api.data.igvf.org/sequence-files/IGVFFI1072IPCN/
mv -n	igvf_005/nova2/Sublibrary_2_S1_L001_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B02_D_nova_N2_L001_R2.fastq.gz		#00d05a91aae90cbcfcd27e7c5339ba61	https://api.data.igvf.org/sequence-files/IGVFFI6732GVIW/
mv -n	igvf_005/nova2/Sublibrary_2_S1_L002_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B02_D_nova_N2_L002_I1.fastq.gz		#16fff07f787f1f84e06ad6634b44128f
mv -n	igvf_005/nova2/Sublibrary_2_S1_L002_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B02_D_nova_N2_L002_R1.fastq.gz		#79a9ff5ada609cfdee87296b2fa8f5cc	https://api.data.igvf.org/sequence-files/IGVFFI1362SVPH/
mv -n	igvf_005/nova2/Sublibrary_2_S1_L002_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B02_D_nova_N2_L002_R2.fastq.gz		#0d35e56ceb47313957d3161f115b0fc6	https://api.data.igvf.org/sequence-files/IGVFFI1069LCBI/
mv -n	igvf_005/nova2/Sublibrary_2_S1_L003_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B02_D_nova_N2_L003_I1.fastq.gz		#11c05272b7843f70b5ea6154ab9f3a81
mv -n	igvf_005/nova2/Sublibrary_2_S1_L003_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B02_D_nova_N2_L003_R1.fastq.gz		#0a19b2067d693d18078907dca5f7b564	https://api.data.igvf.org/sequence-files/IGVFFI2274LVST/
mv -n	igvf_005/nova2/Sublibrary_2_S1_L003_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B02_D_nova_N2_L003_R2.fastq.gz		#7565549a49e57257ebc0cbcabd82c626	https://api.data.igvf.org/sequence-files/IGVFFI2424IMYP/
mv -n	igvf_005/nova2/Sublibrary_2_S1_L004_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B02_D_nova_N2_L004_I1.fastq.gz		#8aad2aa592d066ffdb21d873940fe04d
mv -n	igvf_005/nova2/Sublibrary_2_S1_L004_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B02_D_nova_N2_L004_R1.fastq.gz		#becaa28c7b9694ff4e0779f7c0c17447	https://api.data.igvf.org/sequence-files/IGVFFI7114USQO/
mv -n	igvf_005/nova2/Sublibrary_2_S1_L004_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B02_D_nova_N2_L004_R2.fastq.gz		#6f6afb9e6d4ea5b6ef9120deb14cce47	https://api.data.igvf.org/sequence-files/IGVFFI5931WBNI/
mv -n	igvf_005/nova2/Sublibrary_3_S2_L001_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B03_D_nova_N2_L001_I1.fastq.gz		#8dfd41f04481d2316408213284c948c3
mv -n	igvf_005/nova2/Sublibrary_3_S2_L001_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B03_D_nova_N2_L001_R1.fastq.gz		#9c0707c63936b1826eb0caf519efcfb2	https://api.data.igvf.org/sequence-files/IGVFFI8851GRMY/
mv -n	igvf_005/nova2/Sublibrary_3_S2_L001_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B03_D_nova_N2_L001_R2.fastq.gz		#d371d9731167550f3de38b800ceb6609	https://api.data.igvf.org/sequence-files/IGVFFI0084ZZAH/
mv -n	igvf_005/nova2/Sublibrary_3_S2_L002_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B03_D_nova_N2_L002_I1.fastq.gz		#fd681c40fd17e7c6074b6809d9cc84a1
mv -n	igvf_005/nova2/Sublibrary_3_S2_L002_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B03_D_nova_N2_L002_R1.fastq.gz		#f900d75b9c4f5352f2379bd023698c49	https://api.data.igvf.org/sequence-files/IGVFFI9324HTPG/
mv -n	igvf_005/nova2/Sublibrary_3_S2_L002_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B03_D_nova_N2_L002_R2.fastq.gz		#70b3d3233278e3b068b3c59fbec46b4d	https://api.data.igvf.org/sequence-files/IGVFFI8270FJNT/
mv -n	igvf_005/nova2/Sublibrary_3_S2_L003_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B03_D_nova_N2_L003_I1.fastq.gz		#b5ce88916811b3af4bd437496752cd6c
mv -n	igvf_005/nova2/Sublibrary_3_S2_L003_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B03_D_nova_N2_L003_R1.fastq.gz		#7acc52845d9a27f64727828b31f384fc	https://api.data.igvf.org/sequence-files/IGVFFI2190VOWM/
mv -n	igvf_005/nova2/Sublibrary_3_S2_L003_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B03_D_nova_N2_L003_R2.fastq.gz		#16cfc025ba266f3212088a7730ea54a6	https://api.data.igvf.org/sequence-files/IGVFFI3132PGIV/
mv -n	igvf_005/nova2/Sublibrary_3_S2_L004_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B03_D_nova_N2_L004_I1.fastq.gz		#8c5f4caf094d6568518dd666ad22c99f
mv -n	igvf_005/nova2/Sublibrary_3_S2_L004_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B03_D_nova_N2_L004_R1.fastq.gz		#fcbae83c93935997d31cee3a8c315418	https://api.data.igvf.org/sequence-files/IGVFFI2862ESZW/
mv -n	igvf_005/nova2/Sublibrary_3_S2_L004_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B03_D_nova_N2_L004_R2.fastq.gz		#6728c2594b91a43a3ce08a20def15b0e	https://api.data.igvf.org/sequence-files/IGVFFI1755OHOY/
mv -n	igvf_005/nova2/Sublibrary_4_S3_L001_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B04_D_nova_N2_L001_I1.fastq.gz		#be9755ed1230e48066ab7c68166eb6db
mv -n	igvf_005/nova2/Sublibrary_4_S3_L001_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B04_D_nova_N2_L001_R1.fastq.gz		#5651aef2d8cddb9539e370aba6d0b2d3	https://api.data.igvf.org/sequence-files/IGVFFI7552IRYM/
mv -n	igvf_005/nova2/Sublibrary_4_S3_L001_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B04_D_nova_N2_L001_R2.fastq.gz		#59040625cd953b0ff722ee21bfeac2ba	https://api.data.igvf.org/sequence-files/IGVFFI7135VNOS/
mv -n	igvf_005/nova2/Sublibrary_4_S3_L002_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B04_D_nova_N2_L002_I1.fastq.gz		#4436ba5918117db04751dfaf02c1dc66
mv -n	igvf_005/nova2/Sublibrary_4_S3_L002_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B04_D_nova_N2_L002_R1.fastq.gz		#9031ecc1d6d2cdf1d3b90fce7fd99e7c	https://api.data.igvf.org/sequence-files/IGVFFI4049XVCT/
mv -n	igvf_005/nova2/Sublibrary_4_S3_L002_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B04_D_nova_N2_L002_R2.fastq.gz		#3072a2b5c5272724d482d9c27837795b	https://api.data.igvf.org/sequence-files/IGVFFI2728SOEX/
mv -n	igvf_005/nova2/Sublibrary_4_S3_L003_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B04_D_nova_N2_L003_I1.fastq.gz		#1f253b700c465f281f12b8f033409d3d
mv -n	igvf_005/nova2/Sublibrary_4_S3_L003_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B04_D_nova_N2_L003_R1.fastq.gz		#af4a5ec5c75ec9b9a1f5059a9171c85a	https://api.data.igvf.org/sequence-files/IGVFFI8707OEJU/
mv -n	igvf_005/nova2/Sublibrary_4_S3_L003_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B04_D_nova_N2_L003_R2.fastq.gz		#c2dc3603fe1696c2d50be06f349e4591	https://api.data.igvf.org/sequence-files/IGVFFI1450XQBJ/
mv -n	igvf_005/nova2/Sublibrary_4_S3_L004_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B04_D_nova_N2_L004_I1.fastq.gz		#ffe11e9d0091c9eb2916a29b02f29d4d
mv -n	igvf_005/nova2/Sublibrary_4_S3_L004_R1_001.fastq.gz	igvf_005/nova2/igvf_005_B04_D_nova_N2_L004_R1.fastq.gz		#61ef5ea008e3b87fb68f7238baba050b	https://api.data.igvf.org/sequence-files/IGVFFI8009IJUH/
mv -n	igvf_005/nova2/Sublibrary_4_S3_L004_R2_001.fastq.gz	igvf_005/nova2/igvf_005_B04_D_nova_N2_L004_R2.fastq.gz		#3aaa276c0aa30a7220c1fb53c7eaefa0	https://api.data.igvf.org/sequence-files/IGVFFI1467QAQW/
mv -n	igvf_005/nova2/Sublibrary_5_S4_L001_I1_001.fastq.gz	igvf_005/nova2/igvf_005_B05_D_nova_N2_L001_I1.fastq.gz		#8bd8674a26ec6d36e6415f0079b9afb0

mv -n	igvf_007/nova1/Sublibrary_14_S13_L003_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B14_D_nova_N1_L003_I1.fastq.gz		#e155fb3cd6d9de4f5528bd18baac80cb
mv -n	igvf_007/nova1/Sublibrary_14_S13_L003_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B14_D_nova_N1_L003_R1.fastq.gz		#d51eedac57c9837d388864cb35b8af55	https://api.data.igvf.org/sequence-files/IGVFFI9368ZOAM/
mv -n	igvf_007/nova1/Sublibrary_14_S13_L003_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B14_D_nova_N1_L003_R2.fastq.gz		#5b947ccd5e1671507dd40abc81a3a61e	https://api.data.igvf.org/sequence-files/IGVFFI5410EZVQ/
mv -n	igvf_007/nova1/Sublibrary_14_S13_L004_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B14_D_nova_N1_L004_I1.fastq.gz		#00a3cb3e6be1c4988f831f61d670e272
mv -n	igvf_007/nova1/Sublibrary_14_S13_L004_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B14_D_nova_N1_L004_R1.fastq.gz		#beb4a87a1279c6911a0a5476f3760134	https://api.data.igvf.org/sequence-files/IGVFFI8801VAJL/
mv -n	igvf_007/nova1/Sublibrary_14_S13_L004_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B14_D_nova_N1_L004_R2.fastq.gz		#95dc28d09491d2f90e5540cc8649bb20	https://api.data.igvf.org/sequence-files/IGVFFI4017NYBI/
mv -n	igvf_007/nova1/Sublibrary_15_S14_L001_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B15_D_nova_N1_L001_I1.fastq.gz		#7cce267bf5cb42bce769b0baf6953985
mv -n	igvf_007/nova1/Sublibrary_15_S14_L001_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B15_D_nova_N1_L001_R1.fastq.gz		#2de11259d425bcf4bbd07e5dc1148140	https://api.data.igvf.org/sequence-files/IGVFFI2223AVGO/
mv -n	igvf_007/nova1/Sublibrary_15_S14_L001_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B15_D_nova_N1_L001_R2.fastq.gz		#3ca5b2fab2e2e7001a4b45b95f9d705e	https://api.data.igvf.org/sequence-files/IGVFFI3612HXOZ/
mv -n	igvf_007/nova1/Sublibrary_15_S14_L002_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B15_D_nova_N1_L002_I1.fastq.gz		#786cf34f6907d948ea4837ad94ce9406
mv -n	igvf_007/nova1/Sublibrary_15_S14_L002_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B15_D_nova_N1_L002_R1.fastq.gz		#c23ff3785e8a9b84f923d5df9e7db25d	https://api.data.igvf.org/sequence-files/IGVFFI9904CJGN/
mv -n	igvf_007/nova1/Sublibrary_15_S14_L002_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B15_D_nova_N1_L002_R2.fastq.gz		#f17fa461f3cc920672b930556fbd2156	https://api.data.igvf.org/sequence-files/IGVFFI5650REVQ/
mv -n	igvf_007/nova1/Sublibrary_15_S14_L003_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B15_D_nova_N1_L003_I1.fastq.gz		#17225b024b7a063c7e019d82d891e10b
mv -n	igvf_007/nova1/Sublibrary_15_S14_L003_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B15_D_nova_N1_L003_R1.fastq.gz		#d7160b846a2f2a768df534cba6e913e4	https://api.data.igvf.org/sequence-files/IGVFFI5293TLXT/
mv -n	igvf_007/nova1/Sublibrary_15_S14_L003_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B15_D_nova_N1_L003_R2.fastq.gz		#7e8f88267286bc33d7bcbe48ca1fcb5d	https://api.data.igvf.org/sequence-files/IGVFFI7014EPFJ/
mv -n	igvf_007/nova1/Sublibrary_15_S14_L004_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B15_D_nova_N1_L004_I1.fastq.gz		#4a6c571549cb4ebd7cc460cd1579c195
mv -n	igvf_007/nova1/Sublibrary_15_S14_L004_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B15_D_nova_N1_L004_R1.fastq.gz		#d60372da2ca617dcdadcc908bdff2bc6	https://api.data.igvf.org/sequence-files/IGVFFI6465CASR/
mv -n	igvf_007/nova1/Sublibrary_15_S14_L004_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B15_D_nova_N1_L004_R2.fastq.gz		#d5fbedba3da9f02d41d72d83b1cf4f14	https://api.data.igvf.org/sequence-files/IGVFFI1793UJQM/
mv -n	igvf_007/nova1/Sublibrary_16_S15_L001_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B16_D_nova_N1_L001_I1.fastq.gz		#47ea28f866de33ad23c56043d81ca7f7
mv -n	igvf_007/nova1/Sublibrary_16_S15_L001_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B16_D_nova_N1_L001_R1.fastq.gz		#185a4323152897bdbfe621f6db467ea6	https://api.data.igvf.org/sequence-files/IGVFFI5925FUGX/
mv -n	igvf_007/nova1/Sublibrary_16_S15_L001_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B16_D_nova_N1_L001_R2.fastq.gz		#d4ecd203ca465e835f5e6c48238f3dc2	https://api.data.igvf.org/sequence-files/IGVFFI7585CMJH/
mv -n	igvf_007/nova1/Sublibrary_16_S15_L002_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B16_D_nova_N1_L002_I1.fastq.gz		#70640bc73f046ad040372220290c4c3a
mv -n	igvf_007/nova1/Sublibrary_16_S15_L002_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B16_D_nova_N1_L002_R1.fastq.gz		#d9f29534e8b8d8ec9fd9d594ca5facde	https://api.data.igvf.org/sequence-files/IGVFFI9891QGVB/
mv -n	igvf_007/nova1/Sublibrary_16_S15_L002_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B16_D_nova_N1_L002_R2.fastq.gz		#2814853e0e0c7a2ba980dc69eacab182	https://api.data.igvf.org/sequence-files/IGVFFI1424ATCG/
mv -n	igvf_007/nova1/Sublibrary_16_S15_L003_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B16_D_nova_N1_L003_I1.fastq.gz		#50622c40382adb63b9b68a2b07bc2671
mv -n	igvf_007/nova1/Sublibrary_16_S15_L003_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B16_D_nova_N1_L003_R1.fastq.gz		#b122ee2fa3a43f43d02069ed4ce5df27	https://api.data.igvf.org/sequence-files/IGVFFI7466SRTL/
mv -n	igvf_007/nova1/Sublibrary_16_S15_L003_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B16_D_nova_N1_L003_R2.fastq.gz		#a4ddac1ad00557a58ae42d6c5164129c	https://api.data.igvf.org/sequence-files/IGVFFI0779LLWK/
mv -n	igvf_007/nova1/Sublibrary_16_S15_L004_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B16_D_nova_N1_L004_I1.fastq.gz		#e6c2087a418de23c00a095896bc05972
mv -n	igvf_007/nova1/Sublibrary_16_S15_L004_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B16_D_nova_N1_L004_R1.fastq.gz		#839bae71df01a0c2dfad6335bb724591	https://api.data.igvf.org/sequence-files/IGVFFI3019FQHN/
mv -n	igvf_007/nova1/Sublibrary_16_S15_L004_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B16_D_nova_N1_L004_R2.fastq.gz		#f4a4e94e70262cde4044d8d6b5fe9021	https://api.data.igvf.org/sequence-files/IGVFFI1065OLDA/
mv -n	igvf_007/nova1/Sublibrary_2_S1_L001_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B02_D_nova_N1_L001_I1.fastq.gz		#cfbbbb93050993c685361b824e0784ee
mv -n	igvf_007/nova1/Sublibrary_2_S1_L001_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B02_D_nova_N1_L001_R1.fastq.gz		#3799795af8c4e30073a277ba16ac704d	https://api.data.igvf.org/sequence-files/IGVFFI3604TVIC/
mv -n	igvf_007/nova1/Sublibrary_2_S1_L001_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B02_D_nova_N1_L001_R2.fastq.gz		#9c7ffb753183d74241091921bf833b77	https://api.data.igvf.org/sequence-files/IGVFFI2097PAWV/
mv -n	igvf_007/nova1/Sublibrary_2_S1_L002_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B02_D_nova_N1_L002_I1.fastq.gz		#61c0b11af5db4fa8aeddc6649b3d6459
mv -n	igvf_007/nova1/Sublibrary_2_S1_L002_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B02_D_nova_N1_L002_R1.fastq.gz		#da1e3960e6595d47558ec744431b4d69	https://api.data.igvf.org/sequence-files/IGVFFI7677TQEJ/
mv -n	igvf_007/nova1/Sublibrary_2_S1_L002_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B02_D_nova_N1_L002_R2.fastq.gz		#f02b5c5517243ed981b5e82d795e4121	https://api.data.igvf.org/sequence-files/IGVFFI1575TELL/
mv -n	igvf_007/nova1/Sublibrary_2_S1_L003_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B02_D_nova_N1_L003_I1.fastq.gz		#e3d9d8e0172e96370b993134c5510ed3
mv -n	igvf_007/nova1/Sublibrary_2_S1_L003_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B02_D_nova_N1_L003_R1.fastq.gz		#682cc0f9f49992a85cd311df37531925	https://api.data.igvf.org/sequence-files/IGVFFI2379APFS/
mv -n	igvf_007/nova1/Sublibrary_2_S1_L003_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B02_D_nova_N1_L003_R2.fastq.gz		#884697756fa470e7110a32ee9d3d92f7	https://api.data.igvf.org/sequence-files/IGVFFI7815KEQR/
mv -n	igvf_007/nova1/Sublibrary_2_S1_L004_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B02_D_nova_N1_L004_I1.fastq.gz		#c7c41aa8ec1419ef23af7d789921695b
mv -n	igvf_007/nova1/Sublibrary_2_S1_L004_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B02_D_nova_N1_L004_R1.fastq.gz		#20562b1be3d2e1858e52d79d703ae41b	https://api.data.igvf.org/sequence-files/IGVFFI6190SGTD/
mv -n	igvf_007/nova1/Sublibrary_2_S1_L004_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B02_D_nova_N1_L004_R2.fastq.gz		#fa07484bb1d54c840a2ceb9e1f661511	https://api.data.igvf.org/sequence-files/IGVFFI0802JJNZ/
mv -n	igvf_007/nova1/Sublibrary_3_S2_L001_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B03_D_nova_N1_L001_I1.fastq.gz		#ea037a376d8df797ebe55a40a1c5adde
mv -n	igvf_007/nova1/Sublibrary_3_S2_L001_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B03_D_nova_N1_L001_R1.fastq.gz		#7d1fc07641d0cf6eda68437f993a857c	https://api.data.igvf.org/sequence-files/IGVFFI5335XXTU/
mv -n	igvf_007/nova1/Sublibrary_3_S2_L001_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B03_D_nova_N1_L001_R2.fastq.gz		#0e258873566d1a84d6dc72ff948bd80d	https://api.data.igvf.org/sequence-files/IGVFFI6222ZUAD/
mv -n	igvf_007/nova1/Sublibrary_3_S2_L002_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B03_D_nova_N1_L002_I1.fastq.gz		#53e457cd6b8eeeefbd3d7768bc5554b1
mv -n	igvf_007/nova1/Sublibrary_3_S2_L002_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B03_D_nova_N1_L002_R1.fastq.gz		#e8bcdbb6d6e07725a209330cadd32b9d	https://api.data.igvf.org/sequence-files/IGVFFI2543EZVF/
mv -n	igvf_007/nova1/Sublibrary_3_S2_L002_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B03_D_nova_N1_L002_R2.fastq.gz		#dc82343f9c9e3f94d62a1adea6850040	https://api.data.igvf.org/sequence-files/IGVFFI0141OYLS/
mv -n	igvf_007/nova1/Sublibrary_3_S2_L003_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B03_D_nova_N1_L003_I1.fastq.gz		#50b5d43b394fa86d75b8dc4b29a4837b
mv -n	igvf_007/nova1/Sublibrary_3_S2_L003_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B03_D_nova_N1_L003_R1.fastq.gz		#af66f7b80740b2d6e624f76deb7f7960	https://api.data.igvf.org/sequence-files/IGVFFI2366EVVN/
mv -n	igvf_007/nova1/Sublibrary_3_S2_L003_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B03_D_nova_N1_L003_R2.fastq.gz		#67c462afc50d9fd3eee7c8cb4121d26b	https://api.data.igvf.org/sequence-files/IGVFFI2590TZXN/
mv -n	igvf_007/nova1/Sublibrary_3_S2_L004_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B03_D_nova_N1_L004_I1.fastq.gz		#17d6d4d559496d10b15f70fc559a08a4
mv -n	igvf_007/nova1/Sublibrary_3_S2_L004_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B03_D_nova_N1_L004_R1.fastq.gz		#87a3836365215932ab60b01a1b45a3d9	https://api.data.igvf.org/sequence-files/IGVFFI8959LETE/
mv -n	igvf_007/nova1/Sublibrary_3_S2_L004_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B03_D_nova_N1_L004_R2.fastq.gz		#cea2744fdbe97af693099a9fc844c299	https://api.data.igvf.org/sequence-files/IGVFFI0189BIPE/
mv -n	igvf_007/nova1/Sublibrary_4_S3_L001_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B04_D_nova_N1_L001_I1.fastq.gz		#8fc002e888efdbe71cf70bb343d54926
mv -n	igvf_007/nova1/Sublibrary_4_S3_L001_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B04_D_nova_N1_L001_R1.fastq.gz		#5a0f65b93cf5302105b29ff17f02f043	https://api.data.igvf.org/sequence-files/IGVFFI7301UUHL/
mv -n	igvf_007/nova1/Sublibrary_4_S3_L001_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B04_D_nova_N1_L001_R2.fastq.gz		#80af6a4f3e499ff0f3af3d487d7e027b	https://api.data.igvf.org/sequence-files/IGVFFI3818DCVH/
mv -n	igvf_007/nova1/Sublibrary_4_S3_L002_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B04_D_nova_N1_L002_I1.fastq.gz		#612f257bb455ef40884bda13b447c451
mv -n	igvf_007/nova1/Sublibrary_4_S3_L002_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B04_D_nova_N1_L002_R1.fastq.gz		#c098895e19d457697cfea78430983687	https://api.data.igvf.org/sequence-files/IGVFFI2221LLYQ/
mv -n	igvf_007/nova1/Sublibrary_4_S3_L002_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B04_D_nova_N1_L002_R2.fastq.gz		#744c6b0f3f9846be495a61e085ab40af	https://api.data.igvf.org/sequence-files/IGVFFI0621WOVX/
mv -n	igvf_007/nova1/Sublibrary_4_S3_L003_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B04_D_nova_N1_L003_I1.fastq.gz		#1f0154ec7aa5793bc30caa7a5b5f1c1e
mv -n	igvf_007/nova1/Sublibrary_4_S3_L003_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B04_D_nova_N1_L003_R1.fastq.gz		#1bce5f3d7624eedcdc0ff4cee2942ba6	https://api.data.igvf.org/sequence-files/IGVFFI4383CNBB/
mv -n	igvf_007/nova1/Sublibrary_4_S3_L003_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B04_D_nova_N1_L003_R2.fastq.gz		#b802cc448fdb3730e1b8f1f1720f3507	https://api.data.igvf.org/sequence-files/IGVFFI2533LCIX/
mv -n	igvf_007/nova1/Sublibrary_4_S3_L004_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B04_D_nova_N1_L004_I1.fastq.gz		#ab037dc8bcf73012292ef497f38b627e
mv -n	igvf_007/nova1/Sublibrary_4_S3_L004_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B04_D_nova_N1_L004_R1.fastq.gz		#8c14036e33214a1197244b745307e7d9	https://api.data.igvf.org/sequence-files/IGVFFI4287QYUB/
mv -n	igvf_007/nova1/Sublibrary_4_S3_L004_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B04_D_nova_N1_L004_R2.fastq.gz		#0195f9d709e07e01523e359baa71a0fd	https://api.data.igvf.org/sequence-files/IGVFFI2347VQFR/
mv -n	igvf_007/nova1/Sublibrary_5_S4_L001_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B05_D_nova_N1_L001_I1.fastq.gz		#094f6bb5ef78f7d4bb1dc9289c0d740c
mv -n	igvf_007/nova1/Sublibrary_5_S4_L001_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B05_D_nova_N1_L001_R1.fastq.gz		#51193373e4ddafa399305ba48ce70929	https://api.data.igvf.org/sequence-files/IGVFFI7177NHYO/
mv -n	igvf_007/nova1/Sublibrary_5_S4_L001_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B05_D_nova_N1_L001_R2.fastq.gz		#707a9eebcd8455036793a9e7dbfc1cc9	https://api.data.igvf.org/sequence-files/IGVFFI3881LNEO/
mv -n	igvf_007/nova1/Sublibrary_5_S4_L002_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B05_D_nova_N1_L002_I1.fastq.gz		#00be15c9319b4dcd129d7bd54c9414e0
mv -n	igvf_007/nova1/Sublibrary_5_S4_L002_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B05_D_nova_N1_L002_R1.fastq.gz		#32462eca85529e540b1c4471677e7a89	https://api.data.igvf.org/sequence-files/IGVFFI1428OIVR/
mv -n	igvf_007/nova1/Sublibrary_5_S4_L002_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B05_D_nova_N1_L002_R2.fastq.gz		#0de7973d87c40d1a36840bb0c062c930	https://api.data.igvf.org/sequence-files/IGVFFI3573MKWS/
mv -n	igvf_007/nova1/Sublibrary_5_S4_L003_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B05_D_nova_N1_L003_I1.fastq.gz		#c3588a9b78811b19708896d703adc741
mv -n	igvf_007/nova1/Sublibrary_5_S4_L003_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B05_D_nova_N1_L003_R1.fastq.gz		#9e2d1db3970e75683953367254d2d964	https://api.data.igvf.org/sequence-files/IGVFFI1603PXEF/
mv -n	igvf_007/nova1/Sublibrary_5_S4_L003_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B05_D_nova_N1_L003_R2.fastq.gz		#73b9a51b39442520327786e2506bbd0d	https://api.data.igvf.org/sequence-files/IGVFFI0993CBVI/
mv -n	igvf_007/nova1/Sublibrary_5_S4_L004_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B05_D_nova_N1_L004_I1.fastq.gz		#f4b6c5a2b5853f5c31bd5759d31354c2
mv -n	igvf_007/nova1/Sublibrary_5_S4_L004_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B05_D_nova_N1_L004_R1.fastq.gz		#44fd8ed818020fb60f3800543b276465	https://api.data.igvf.org/sequence-files/IGVFFI7304YZEJ/
mv -n	igvf_007/nova1/Sublibrary_5_S4_L004_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B05_D_nova_N1_L004_R2.fastq.gz		#cfd0fb7a88f7f428cb992b8204edf5e6	https://api.data.igvf.org/sequence-files/IGVFFI7159NIPO/
mv -n	igvf_007/nova1/Sublibrary_6_S5_L001_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B06_D_nova_N1_L001_I1.fastq.gz		#12f0bebab6951109365bf58fa3caef0c

mv -n	igvf_007/nova1/Sublibrary_6_S5_L001_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B06_D_nova_N1_L001_R1.fastq.gz		#c29751a4bcbc4f720fd9e8123e2bbef0	https://api.data.igvf.org/sequence-files/IGVFFI3703VEEK/
mv -n	igvf_007/nova1/Sublibrary_6_S5_L001_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B06_D_nova_N1_L001_R2.fastq.gz		#a42057f8deebaca7815b42c192988e10	https://api.data.igvf.org/sequence-files/IGVFFI8577YCTI/
mv -n	igvf_007/nova1/Sublibrary_6_S5_L002_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B06_D_nova_N1_L002_I1.fastq.gz		#c4dacd710bc05d01cd31a214608e00e9
mv -n	igvf_007/nova1/Sublibrary_6_S5_L002_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B06_D_nova_N1_L002_R1.fastq.gz		#3688823f1e3143fdbe162d413a199d6b	https://api.data.igvf.org/sequence-files/IGVFFI2953POTB/
mv -n	igvf_007/nova1/Sublibrary_6_S5_L002_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B06_D_nova_N1_L002_R2.fastq.gz		#9ea0e3cb5bb754039a230878b156d74c	https://api.data.igvf.org/sequence-files/IGVFFI0850ZBOA/
mv -n	igvf_007/nova1/Sublibrary_6_S5_L003_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B06_D_nova_N1_L003_I1.fastq.gz		#9d95f6a2fe8237014ca7bcd78131a56a
mv -n	igvf_007/nova1/Sublibrary_6_S5_L003_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B06_D_nova_N1_L003_R1.fastq.gz		#0468b4fea19bc90c8689e29f3e3ca593	https://api.data.igvf.org/sequence-files/IGVFFI2067CTMH/
mv -n	igvf_007/nova1/Sublibrary_6_S5_L003_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B06_D_nova_N1_L003_R2.fastq.gz		#d5d494a650ae9c4f1f61a0a3742837bd	https://api.data.igvf.org/sequence-files/IGVFFI5550JTNZ/
mv -n	igvf_007/nova1/Sublibrary_6_S5_L004_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B06_D_nova_N1_L004_I1.fastq.gz		#0ab18fee09d8a703a1fc068fb726782b
mv -n	igvf_007/nova1/Sublibrary_6_S5_L004_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B06_D_nova_N1_L004_R1.fastq.gz		#52f3c97e6ea5d472ee174cd28cc350c9	https://api.data.igvf.org/sequence-files/IGVFFI4682UHQN/
mv -n	igvf_007/nova1/Sublibrary_6_S5_L004_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B06_D_nova_N1_L004_R2.fastq.gz		#f6309ab9cd1fa5c4faa36206e3d84f03	https://api.data.igvf.org/sequence-files/IGVFFI5783KSKH/
mv -n	igvf_007/nova1/Sublibrary_7_S6_L001_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B07_D_nova_N1_L001_I1.fastq.gz		#329480adf175c2e27011bff271c32ad5
mv -n	igvf_007/nova1/Sublibrary_7_S6_L001_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B07_D_nova_N1_L001_R1.fastq.gz		#f730d80e1c44aa1ce80009c2187bb93f	https://api.data.igvf.org/sequence-files/IGVFFI6293KSRS/
mv -n	igvf_007/nova1/Sublibrary_7_S6_L001_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B07_D_nova_N1_L001_R2.fastq.gz		#7e0a25fafe04a42099135132c007aed0	https://api.data.igvf.org/sequence-files/IGVFFI6376THPR/
mv -n	igvf_007/nova1/Sublibrary_7_S6_L002_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B07_D_nova_N1_L002_I1.fastq.gz		#af8487433568919524fa6d7fad27f29e
mv -n	igvf_007/nova1/Sublibrary_7_S6_L002_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B07_D_nova_N1_L002_R1.fastq.gz		#f98564b13df2bd544a54b5995d464e10	https://api.data.igvf.org/sequence-files/IGVFFI6504UMWZ/
mv -n	igvf_007/nova1/Sublibrary_7_S6_L002_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B07_D_nova_N1_L002_R2.fastq.gz		#8bb354d41575daed8fe2186a2c68cffb	https://api.data.igvf.org/sequence-files/IGVFFI2911NEJP/
mv -n	igvf_007/nova1/Sublibrary_7_S6_L003_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B07_D_nova_N1_L003_I1.fastq.gz		#356b92a74bd78ed1145a817afccc8025
mv -n	igvf_007/nova1/Sublibrary_7_S6_L003_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B07_D_nova_N1_L003_R1.fastq.gz		#2ee4ecd7434786fd80f1fa3e8f7b34b5	https://api.data.igvf.org/sequence-files/IGVFFI9264JCWL/
mv -n	igvf_007/nova1/Sublibrary_7_S6_L003_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B07_D_nova_N1_L003_R2.fastq.gz		#38acff41ba6d53aa2656b18014f26e58	https://api.data.igvf.org/sequence-files/IGVFFI7481LLQJ/
mv -n	igvf_007/nova1/Sublibrary_7_S6_L004_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B07_D_nova_N1_L004_I1.fastq.gz		#3edbb93330f4111ce2c475720329b10a
mv -n	igvf_007/nova1/Sublibrary_7_S6_L004_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B07_D_nova_N1_L004_R1.fastq.gz		#1222e3e69d8cf5b5e8c63f0393e98517	https://api.data.igvf.org/sequence-files/IGVFFI6551ANDR/
mv -n	igvf_007/nova1/Sublibrary_7_S6_L004_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B07_D_nova_N1_L004_R2.fastq.gz		#27b1cf8e0819ce0f9ae1a82c719556ef	https://api.data.igvf.org/sequence-files/IGVFFI5536BLVI/
mv -n	igvf_007/nova1/Sublibrary_8_S7_L001_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B08_D_nova_N1_L001_I1.fastq.gz		#18c66b0d64aea2607f42457eb1175f0c
mv -n	igvf_007/nova1/Sublibrary_8_S7_L001_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B08_D_nova_N1_L001_R1.fastq.gz		#0950db74808d08e98c66104359d356ab	https://api.data.igvf.org/sequence-files/IGVFFI2608ZRCF/
mv -n	igvf_007/nova1/Sublibrary_8_S7_L001_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B08_D_nova_N1_L001_R2.fastq.gz		#70a2acf5766712986dfd2205f1deec03	https://api.data.igvf.org/sequence-files/IGVFFI0722LVXG/
mv -n	igvf_007/nova1/Sublibrary_8_S7_L002_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B08_D_nova_N1_L002_I1.fastq.gz		#32913c58402066275fb30d78758c026d
mv -n	igvf_007/nova1/Sublibrary_8_S7_L002_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B08_D_nova_N1_L002_R1.fastq.gz		#a744ec4c6c44df29f20aa3adfd6bda34	https://api.data.igvf.org/sequence-files/IGVFFI7639EOYN/
mv -n	igvf_007/nova1/Sublibrary_8_S7_L002_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B08_D_nova_N1_L002_R2.fastq.gz		#44b390c51d96bd87be9ce9da991d0ddc	https://api.data.igvf.org/sequence-files/IGVFFI0517UQIJ/
mv -n	igvf_007/nova1/Sublibrary_8_S7_L003_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B08_D_nova_N1_L003_I1.fastq.gz		#1eb63c0172745860957395c0b65f7f7c
mv -n	igvf_007/nova1/Sublibrary_8_S7_L003_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B08_D_nova_N1_L003_R1.fastq.gz		#37070c25399637d91f9ed9eaab0b59ab	https://api.data.igvf.org/sequence-files/IGVFFI5739WLFQ/
mv -n	igvf_007/nova1/Sublibrary_8_S7_L003_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B08_D_nova_N1_L003_R2.fastq.gz		#623423cee4d6429ccb4f38a1107a5857	https://api.data.igvf.org/sequence-files/IGVFFI9677GBYB/
mv -n	igvf_007/nova1/Sublibrary_8_S7_L004_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B08_D_nova_N1_L004_I1.fastq.gz		#6be1b4c17af2e2b9fe78552790bef321
mv -n	igvf_007/nova1/Sublibrary_8_S7_L004_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B08_D_nova_N1_L004_R1.fastq.gz		#5a69f2682944669eba13eb324cdf490f	https://api.data.igvf.org/sequence-files/IGVFFI7061ONPZ/
mv -n	igvf_007/nova1/Sublibrary_8_S7_L004_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B08_D_nova_N1_L004_R2.fastq.gz		#33665f7c9346b7e884eefa212efb801e	https://api.data.igvf.org/sequence-files/IGVFFI6620CEFM/
mv -n	igvf_007/nova1/Sublibrary_9_S8_L001_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B09_D_nova_N1_L001_I1.fastq.gz		#9ae6a5c589d97921e379782148ba7e20
mv -n	igvf_007/nova1/Sublibrary_9_S8_L001_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B09_D_nova_N1_L001_R1.fastq.gz		#498493909f62e9af57d62604a009c0b0	https://api.data.igvf.org/sequence-files/IGVFFI8415BTQM/
mv -n	igvf_007/nova1/Sublibrary_9_S8_L001_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B09_D_nova_N1_L001_R2.fastq.gz		#8da7e1922cda57984cf38dd3c4b4d2bc	https://api.data.igvf.org/sequence-files/IGVFFI6550FDIT/
mv -n	igvf_007/nova1/Sublibrary_9_S8_L002_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B09_D_nova_N1_L002_I1.fastq.gz		#cc7b6e30eab6f7e8bb55b84c8ec66d63
mv -n	igvf_007/nova1/Sublibrary_9_S8_L002_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B09_D_nova_N1_L002_R1.fastq.gz		#ee3d4293b25a0c6dfed811d772685438	https://api.data.igvf.org/sequence-files/IGVFFI5417QKAW/
mv -n	igvf_007/nova1/Sublibrary_9_S8_L002_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B09_D_nova_N1_L002_R2.fastq.gz		#0b36ade568a183f5d20d30baf297325f	https://api.data.igvf.org/sequence-files/IGVFFI9813NXGD/
mv -n	igvf_007/nova1/Sublibrary_9_S8_L003_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B09_D_nova_N1_L003_I1.fastq.gz		#2504ccf45393aebc0d8fb36fee772ac7
mv -n	igvf_007/nova1/Sublibrary_9_S8_L003_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B09_D_nova_N1_L003_R1.fastq.gz		#190c87d79a127a491743b8d40a82cc4d	https://api.data.igvf.org/sequence-files/IGVFFI4683SMQI/
mv -n	igvf_007/nova1/Sublibrary_9_S8_L003_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B09_D_nova_N1_L003_R2.fastq.gz		#fa1ae7b0b49d85be3c446b39b2a4462f	https://api.data.igvf.org/sequence-files/IGVFFI7744XEGO/
mv -n	igvf_007/nova1/Sublibrary_9_S8_L004_I1_001.fastq.gz	igvf_007/nova1/igvf_007_B09_D_nova_N1_L004_I1.fastq.gz		#b748b2768bbf286b11c178cc568ada97
mv -n	igvf_007/nova1/Sublibrary_9_S8_L004_R1_001.fastq.gz	igvf_007/nova1/igvf_007_B09_D_nova_N1_L004_R1.fastq.gz		#c7d347791e3e9e838286cee9c06b0be9	https://api.data.igvf.org/sequence-files/IGVFFI9857ESBA/
mv -n	igvf_007/nova1/Sublibrary_9_S8_L004_R2_001.fastq.gz	igvf_007/nova1/igvf_007_B09_D_nova_N1_L004_R2.fastq.gz		#b3c615945cfed4ac23a17d475bef4b88	https://api.data.igvf.org/sequence-files/IGVFFI0562OFLL/
mv -n	igvf_007/nova2/Sublibrary_10_S9_L001_I1_001.fastq.gz	igvf_007/nova2/igvf_007_B10_D_nova_N2_L001_I1.fastq.gz		#04f3b3e33e35595db50bcbf3b9661846
mv -n	igvf_007/nova2/Sublibrary_10_S9_L001_R1_001.fastq.gz	igvf_007/nova2/igvf_007_B10_D_nova_N2_L001_R1.fastq.gz		#3b8ddefdeec330acef07deb33c11f16c	https://api.data.igvf.org/sequence-files/IGVFFI1637VNUD/
mv -n	igvf_007/nova2/Sublibrary_10_S9_L001_R2_001.fastq.gz	igvf_007/nova2/igvf_007_B10_D_nova_N2_L001_R2.fastq.gz		#60c07ab18f31f2b47f999414a2efb768	https://api.data.igvf.org/sequence-files/IGVFFI5617ROZS/
mv -n	igvf_007/nova2/Sublibrary_10_S9_L002_I1_001.fastq.gz	igvf_007/nova2/igvf_007_B10_D_nova_N2_L002_I1.fastq.gz		#e1c5fa1532c995621447daf714d55110
mv -n	igvf_007/nova2/Sublibrary_10_S9_L002_R1_001.fastq.gz	igvf_007/nova2/igvf_007_B10_D_nova_N2_L002_R1.fastq.gz		#a59d4a101e0cfe7ff08abfd1eb452a2f	https://api.data.igvf.org/sequence-files/IGVFFI5101KKQS/
mv -n	igvf_007/nova2/Sublibrary_10_S9_L002_R2_001.fastq.gz	igvf_007/nova2/igvf_007_B10_D_nova_N2_L002_R2.fastq.gz		#df16065efa9e0fb2d36471d42d256f99	https://api.data.igvf.org/sequence-files/IGVFFI7945USYF/
mv -n	igvf_007/nova2/Sublibrary_10_S9_L003_I1_001.fastq.gz	igvf_007/nova2/igvf_007_B10_D_nova_N2_L003_I1.fastq.gz		#05f58a5ddcbb50eff880143eb0aafdaf
mv -n	igvf_007/nova2/Sublibrary_10_S9_L003_R1_001.fastq.gz	igvf_007/nova2/igvf_007_B10_D_nova_N2_L003_R1.fastq.gz		#a2dd7d0d880f12d6fa73eb1b5e6d612a	https://api.data.igvf.org/sequence-files/IGVFFI0112FDDC/
mv -n	igvf_007/nova2/Sublibrary_10_S9_L003_R2_001.fastq.gz	igvf_007/nova2/igvf_007_B10_D_nova_N2_L003_R2.fastq.gz		#c73b65be8f9949c103f89c66b5f78555	https://api.data.igvf.org/sequence-files/IGVFFI8789IRII/
mv -n	igvf_007/nova2/Sublibrary_10_S9_L004_I1_001.fastq.gz	igvf_007/nova2/igvf_007_B10_D_nova_N2_L004_I1.fastq.gz		#c28b1247bf25914fb5c67511e509eaba
mv -n	igvf_007/nova2/Sublibrary_10_S9_L004_R1_001.fastq.gz	igvf_007/nova2/igvf_007_B10_D_nova_N2_L004_R1.fastq.gz		#77411e68d437d568a3c88fca2b7afac5	https://api.data.igvf.org/sequence-files/IGVFFI7824LTUV/
mv -n	igvf_007/nova2/Sublibrary_10_S9_L004_R2_001.fastq.gz	igvf_007/nova2/igvf_007_B10_D_nova_N2_L004_R2.fastq.gz		#8a5a31db2494a44d703c4fab6ad09ded	https://api.data.igvf.org/sequence-files/IGVFFI6096LILF/
mv -n	igvf_007/nova2/Sublibrary_11_S10_L001_I1_001.fastq.gz	igvf_007/nova2/igvf_007_B11_D_nova_N2_L001_I1.fastq.gz		#7cc7617bf9ea4e4f23d446487bb1640d
mv -n	igvf_007/nova2/Sublibrary_11_S10_L001_R1_001.fastq.gz	igvf_007/nova2/igvf_007_B11_D_nova_N2_L001_R1.fastq.gz		#08ce43758b54b873d59904bc5f11a93e	https://api.data.igvf.org/sequence-files/IGVFFI2783ADEW/
mv -n	igvf_007/nova2/Sublibrary_11_S10_L001_R2_001.fastq.gz	igvf_007/nova2/igvf_007_B11_D_nova_N2_L001_R2.fastq.gz		#ee412dc5c05a547684f460d03eba698f	https://api.data.igvf.org/sequence-files/IGVFFI6931FVXC/
mv -n	igvf_007/nova2/Sublibrary_11_S10_L002_I1_001.fastq.gz	igvf_007/nova2/igvf_007_B11_D_nova_N2_L002_I1.fastq.gz		#5f1ccb9c3a559e8e41b2cec027e23b58
mv -n	igvf_007/nova2/Sublibrary_11_S10_L002_R1_001.fastq.gz	igvf_007/nova2/igvf_007_B11_D_nova_N2_L002_R1.fastq.gz		#4eadc5cd108c6690a6c4b064bf85197d	https://api.data.igvf.org/sequence-files/IGVFFI6232DKZP/
mv -n	igvf_007/nova2/Sublibrary_11_S10_L002_R2_001.fastq.gz	igvf_007/nova2/igvf_007_B11_D_nova_N2_L002_R2.fastq.gz		#3221440bf0b6398c5514a2ba28650597	https://api.data.igvf.org/sequence-files/IGVFFI7074BYAG/
mv -n	igvf_007/nova2/Sublibrary_11_S10_L003_I1_001.fastq.gz	igvf_007/nova2/igvf_007_B11_D_nova_N2_L003_I1.fastq.gz		#a8973672e1a8529487ca04ff4fb8ebb3
mv -n	igvf_007/nova2/Sublibrary_11_S10_L003_R1_001.fastq.gz	igvf_007/nova2/igvf_007_B11_D_nova_N2_L003_R1.fastq.gz		#087ac1a049a9050525e4c7179700b02c	https://api.data.igvf.org/sequence-files/IGVFFI1612BHPY/
mv -n	igvf_007/nova2/Sublibrary_11_S10_L003_R2_001.fastq.gz	igvf_007/nova2/igvf_007_B11_D_nova_N2_L003_R2.fastq.gz		#0d56580f132cc6510f6cf4dd89ec246e	https://api.data.igvf.org/sequence-files/IGVFFI7542TBWE/
mv -n	igvf_007/nova2/Sublibrary_11_S10_L004_I1_001.fastq.gz	igvf_007/nova2/igvf_007_B11_D_nova_N2_L004_I1.fastq.gz		#ad29648bc62f570202e35397d8132d6e
mv -n	igvf_007/nova2/Sublibrary_11_S10_L004_R1_001.fastq.gz	igvf_007/nova2/igvf_007_B11_D_nova_N2_L004_R1.fastq.gz		#7ce555945181e088179898334c54f175	https://api.data.igvf.org/sequence-files/IGVFFI5055BIAJ/
mv -n	igvf_007/nova2/Sublibrary_11_S10_L004_R2_001.fastq.gz	igvf_007/nova2/igvf_007_B11_D_nova_N2_L004_R2.fastq.gz		#bb8c670ae2a6c23d8fdcce8cf0cdc9f2	https://api.data.igvf.org/sequence-files/IGVFFI8350ERZV/
mv -n	igvf_007/nova2/Sublibrary_12_S11_L001_I1_001.fastq.gz	igvf_007/nova2/igvf_007_B12_D_nova_N2_L001_I1.fastq.gz		#81a9b8c76d334a32758158da4f5359c9
mv -n	igvf_007/nova2/Sublibrary_12_S11_L001_R1_001.fastq.gz	igvf_007/nova2/igvf_007_B12_D_nova_N2_L001_R1.fastq.gz		#e35c07bb6be131fd736d56a946ae96e5	https://api.data.igvf.org/sequence-files/IGVFFI6556BMKX/
mv -n	igvf_007/nova2/Sublibrary_12_S11_L001_R2_001.fastq.gz	igvf_007/nova2/igvf_007_B12_D_nova_N2_L001_R2.fastq.gz		#15d305a9359dc6b237962e432bf8d8a5	https://api.data.igvf.org/sequence-files/IGVFFI1763UDWD/
mv -n	igvf_007/nova2/Sublibrary_12_S11_L002_I1_001.fastq.gz	igvf_007/nova2/igvf_007_B12_D_nova_N2_L002_I1.fastq.gz		#3f9393c2b1eeb72615b051248a9e2cdd
mv -n	igvf_007/nova2/Sublibrary_12_S11_L002_R1_001.fastq.gz	igvf_007/nova2/igvf_007_B12_D_nova_N2_L002_R1.fastq.gz		#bc98d77c98007a2a0a6f1a87c6c26ec9	https://api.data.igvf.org/sequence-files/IGVFFI9877KFTM/
mv -n	igvf_007/nova2/Sublibrary_12_S11_L002_R2_001.fastq.gz	igvf_007/nova2/igvf_007_B12_D_nova_N2_L002_R2.fastq.gz		#0c48928f7c37dc4e8655d17571ef230f	https://api.data.igvf.org/sequence-files/IGVFFI6504PSAT/
mv -n	igvf_007/nova2/Sublibrary_12_S11_L003_I1_001.fastq.gz	igvf_007/nova2/igvf_007_B12_D_nova_N2_L003_I1.fastq.gz		#3b6cdefa1487be81893c4dcc6fc72e03
mv -n	igvf_007/nova2/Sublibrary_12_S11_L003_R1_001.fastq.gz	igvf_007/nova2/igvf_007_B12_D_nova_N2_L003_R1.fastq.gz		#6fa0147489fa12206e52e39559ea4eb2	https://api.data.igvf.org/sequence-files/IGVFFI8745ITSB/
mv -n	igvf_007/nova2/Sublibrary_12_S11_L003_R2_001.fastq.gz	igvf_007/nova2/igvf_007_B12_D_nova_N2_L003_R2.fastq.gz		#4d2dcff1f654596199b43001505eed43	https://api.data.igvf.org/sequence-files/IGVFFI8757AXQC/
mv -n	igvf_007/nova2/Sublibrary_12_S11_L004_I1_001.fastq.gz	igvf_007/nova2/igvf_007_B12_D_nova_N2_L004_I1.fastq.gz		#8740d096f15bc557b6c6dc5889bc52b1
mv -n	igvf_007/nova2/Sublibrary_12_S11_L004_R1_001.fastq.gz	igvf_007/nova2/igvf_007_B12_D_nova_N2_L004_R1.fastq.gz		#2a65a02e9bdb236f726185b06a8be2c3	https://api.data.igvf.org/sequence-files/IGVFFI0375GHAS/
mv -n	igvf_007/nova2/Sublibrary_12_S11_L004_R2_001.fastq.gz	igvf_007/nova2/igvf_007_B12_D_nova_N2_L004_R2.fastq.gz		#4ff2d64bebbca8f945d4e454c07e1459	https://api.data.igvf.org/sequence-files/IGVFFI1829WSZP/
mv -n	igvf_007/nova2/Sublibrary_13_S12_L001_I1_001.fastq.gz	igvf_007/nova2/igvf_007_B13_D_nova_N2_L001_I1.fastq.gz		#31896f5d7c04b7d7d3e5b21ccaa53dfc
mv -n	igvf_007/nova2/Sublibrary_13_S12_L001_R1_001.fastq.gz	igvf_007/nova2/igvf_007_B13_D_nova_N2_L001_R1.fastq.gz		#2d8118c924665b37be85ff65843a63b1	https://api.data.igvf.org/sequence-files/IGVFFI2397WKLI/
mv -n	igvf_007/nova2/Sublibrary_13_S12_L001_R2_001.fastq.gz	igvf_007/nova2/igvf_007_B13_D_nova_N2_L001_R2.fastq.gz		#9fce639669cc3e0a38f827df5c5563e6	https://api.data.igvf.org/sequence-files/IGVFFI0869UKQY/
mv -n	igvf_007/nova2/Sublibrary_13_S12_L002_I1_001.fastq.gz	igvf_007/nova2/igvf_007_B13_D_nova_N2_L002_I1.fastq.gz		#b8aefb585013fe14d561b1e10554ff6a
mv -n	igvf_007/nova2/Sublibrary_13_S12_L002_R1_001.fastq.gz	igvf_007/nova2/igvf_007_B13_D_nova_N2_L002_R1.fastq.gz		#40ddce88bb8dc3104c02f6f3d6c0e3bc	https://api.data.igvf.org/sequence-files/IGVFFI2900KLVY/
mv -n	igvf_007/nova2/Sublibrary_13_S12_L002_R2_001.fastq.gz	igvf_007/nova2/igvf_007_B13_D_nova_N2_L002_R2.fastq.gz		#6524015bde1de724e975ca06e15e4559	https://api.data.igvf.org/sequence-files/IGVFFI8190HXEA/
mv -n	igvf_007/nova2/Sublibrary_13_S12_L003_I1_001.fastq.gz	igvf_007/nova2/igvf_007_B13_D_nova_N2_L003_I1.fastq.gz		#723c240ae7bcc1840a98cdbdbceeca3c
mv -n	igvf_007/nova2/Sublibrary_13_S12_L003_R1_001.fastq.gz	igvf_007/nova2/igvf_007_B13_D_nova_N2_L003_R1.fastq.gz		#9a5cfe3e651680f1010417554c352e5b	https://api.data.igvf.org/sequence-files/IGVFFI0559WNME/
mv -n	igvf_007/nova2/Sublibrary_13_S12_L003_R2_001.fastq.gz	igvf_007/nova2/igvf_007_B13_D_nova_N2_L003_R2.fastq.gz		#1e56b8124128a4c72887443f91017279	https://api.data.igvf.org/sequence-files/IGVFFI4003JXZS/
mv -n	igvf_007/nova2/Sublibrary_13_S12_L004_I1_001.fastq.gz	igvf_007/nova2/igvf_007_B13_D_nova_N2_L004_I1.fastq.gz		#967fecf7a475026487902ae35b166a4e
mv -n	igvf_007/nova2/Sublibrary_13_S12_L004_R1_001.fastq.gz	igvf_007/nova2/igvf_007_B13_D_nova_N2_L004_R1.fastq.gz		#9bc00e52a7af5a5d36be54340a352772	https://api.data.igvf.org/sequence-files/IGVFFI8472YLTQ/
mv -n	igvf_007/nova2/Sublibrary_13_S12_L004_R2_001.fastq.gz	igvf_007/nova2/igvf_007_B13_D_nova_N2_L004_R2.fastq.gz		#e083772373e5fc23456ba13150880b86	https://api.data.igvf.org/sequence-files/IGVFFI5618YTFY/
mv -n	igvf_007/nova2/Sublibrary_14_S13_L001_I1_001.fastq.gz	igvf_007/nova2/igvf_007_B14_D_nova_N2_L001_I1.fastq.gz		#e500cc82923c8fe5e105778ee43a3437
mv -n	igvf_007/nova2/Sublibrary_14_S13_L001_R1_001.fastq.gz	igvf_007/nova2/igvf_007_B14_D_nova_N2_L001_R1.fastq.gz		#31ee6e640df306a9520ac39e04ba7394	https://api.data.igvf.org/sequence-files/IGVFFI5226FZIK/
mv -n	igvf_007/nova2/Sublibrary_14_S13_L001_R2_001.fastq.gz	igvf_007/nova2/igvf_007_B14_D_nova_N2_L001_R2.fastq.gz		#d9ea1c552cbf1f73cd123644a059a020	https://api.data.igvf.org/sequence-files/IGVFFI7211LYFW/
mv -n	igvf_007/nova2/Sublibrary_14_S13_L002_I1_001.fastq.gz	igvf_007/nova2/igvf_007_B14_D_nova_N2_L002_I1.fastq.gz		#13169f6485f695ff0f29ee5b027b7701
mv -n	igvf_007/nova2/Sublibrary_14_S13_L002_R1_001.fastq.gz	igvf_007/nova2/igvf_007_B14_D_nova_N2_L002_R1.fastq.gz		#a6787d60098baa2f41141c0d53e01e1c	https://api.data.igvf.org/sequence-files/IGVFFI4545GQLU/
mv -n	igvf_007/nova2/Sublibrary_14_S13_L002_R2_001.fastq.gz	igvf_007/nova2/igvf_007_B14_D_nova_N2_L002_R2.fastq.gz		#1e592a959761c66873065cbfa44c7141	https://api.data.igvf.org/sequence-files/IGVFFI2566HQIM/
mv -n	igvf_007/nova2/Sublibrary_14_S13_L003_I1_001.fastq.gz	igvf_007/nova2/igvf_007_B14_D_nova_N2_L003_I1.fastq.gz		#5909ff7b8a0a8551d0643b7c154fd91a
mv -n	igvf_007/nova2/Sublibrary_14_S13_L003_R1_001.fastq.gz	igvf_007/nova2/igvf_007_B14_D_nova_N2_L003_R1.fastq.gz		#845f48c45db6f2e57bb4563b66016ad0	https://api.data.igvf.org/sequence-files/IGVFFI7172LZUP/
mv -n	igvf_007/nova2/Sublibrary_14_S13_L003_R2_001.fastq.gz	igvf_007/nova2/igvf_007_B14_D_nova_N2_L003_R2.fastq.gz		#dc410b4341e40b341d761a57045f8935	https://api.data.igvf.org/sequence-files/IGVFFI5392LKJA/
mv -n	igvf_007/nova2/Sublibrary_14_S13_L004_I1_001.fastq.gz	igvf_007/nova2/igvf_007_B14_D_nova_N2_L004_I1.fastq.gz		#6d00b792a98ce64c124c0fbfb8ed8029
mv -n	igvf_007/nova2/Sublibrary_14_S13_L004_R1_001.fastq.gz	igvf_007/nova2/igvf_007_B14_D_nova_N2_L004_R1.fastq.gz		#cee1716266454aa94e84702a6506020a	https://api.data.igvf.org/sequence-files/IGVFFI3343KJYP/

mv -n	igvf_008b/nova1/Sublibrary_10_S9_L001_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B10_D_nova_N1_L001_I1.fastq.gz		#b8fce06ccea8773d9b4ce770268b623b
mv -n	igvf_008b/nova1/Sublibrary_10_S9_L001_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B10_D_nova_N1_L001_R1.fastq.gz		#42d86ba16df9f1980066776da0826080	https://api.data.igvf.org/sequence-files/IGVFFI2837DXAT/
mv -n	igvf_008b/nova1/Sublibrary_10_S9_L001_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B10_D_nova_N1_L001_R2.fastq.gz		#f9c776770f2b6157beb690c1550c325c	https://api.data.igvf.org/sequence-files/IGVFFI1778NKML/
mv -n	igvf_008b/nova1/Sublibrary_10_S9_L002_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B10_D_nova_N1_L002_I1.fastq.gz		#113ec9809f7ce645121c67d778eb48d8
mv -n	igvf_008b/nova1/Sublibrary_10_S9_L002_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B10_D_nova_N1_L002_R1.fastq.gz		#4e1f79b3e650d171d985d6d76c0ad2ed	https://api.data.igvf.org/sequence-files/IGVFFI7325XUYZ/
mv -n	igvf_008b/nova1/Sublibrary_10_S9_L002_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B10_D_nova_N1_L002_R2.fastq.gz		#c762b6f00219e28316b086311096255b	https://api.data.igvf.org/sequence-files/IGVFFI9947EJIA/
mv -n	igvf_008b/nova1/Sublibrary_10_S9_L003_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B10_D_nova_N1_L003_I1.fastq.gz		#6c1a41deb46d9b3e86e478abf1ddb681
mv -n	igvf_008b/nova1/Sublibrary_10_S9_L003_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B10_D_nova_N1_L003_R1.fastq.gz		#1b08df925c8db997e48ed21309131a35	https://api.data.igvf.org/sequence-files/IGVFFI7643QDOT/
mv -n	igvf_008b/nova1/Sublibrary_10_S9_L003_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B10_D_nova_N1_L003_R2.fastq.gz		#f5ad9fd52397be4d348a094a296538e1	https://api.data.igvf.org/sequence-files/IGVFFI6370OKOT/
mv -n	igvf_008b/nova1/Sublibrary_10_S9_L004_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B10_D_nova_N1_L004_I1.fastq.gz		#554462dd522853b06a4c9fc963232292
mv -n	igvf_008b/nova1/Sublibrary_10_S9_L004_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B10_D_nova_N1_L004_R1.fastq.gz		#94efca466a3513319d11fd46d482c412	https://api.data.igvf.org/sequence-files/IGVFFI7111HUND/
mv -n	igvf_008b/nova1/Sublibrary_10_S9_L004_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B10_D_nova_N1_L004_R2.fastq.gz		#3974713c38f1ff74d654030eef0268d4	https://api.data.igvf.org/sequence-files/IGVFFI1421OMPD/
mv -n	igvf_008b/nova1/Sublibrary_11_S10_L001_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B11_D_nova_N1_L001_I1.fastq.gz		#8b34cbd2724220c21c7954659075f980
mv -n	igvf_008b/nova1/Sublibrary_11_S10_L001_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B11_D_nova_N1_L001_R1.fastq.gz		#03d2403e4d09b04ac295850d6f3649a3	https://api.data.igvf.org/sequence-files/IGVFFI7218HHXW/
mv -n	igvf_008b/nova1/Sublibrary_11_S10_L001_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B11_D_nova_N1_L001_R2.fastq.gz		#dacabac78b0fcca5e854fe55890d4032	https://api.data.igvf.org/sequence-files/IGVFFI0053SDZV/
mv -n	igvf_008b/nova1/Sublibrary_11_S10_L002_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B11_D_nova_N1_L002_I1.fastq.gz		#e42a4eaf9f386ca8e11757d3ed22675f
mv -n	igvf_008b/nova1/Sublibrary_11_S10_L002_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B11_D_nova_N1_L002_R1.fastq.gz		#be9bccf4944524f059abad331656c820	https://api.data.igvf.org/sequence-files/IGVFFI8956AUYR/
mv -n	igvf_008b/nova1/Sublibrary_11_S10_L002_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B11_D_nova_N1_L002_R2.fastq.gz		#850c9f4e615c3ee49ba11a9448815f3c	https://api.data.igvf.org/sequence-files/IGVFFI8701OCFY/
mv -n	igvf_008b/nova1/Sublibrary_11_S10_L003_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B11_D_nova_N1_L003_I1.fastq.gz		#fc9e976acc1ca559107de3464dd84507
mv -n	igvf_008b/nova1/Sublibrary_11_S10_L003_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B11_D_nova_N1_L003_R1.fastq.gz		#04a7122ce344798846a2b62844230e0c	https://api.data.igvf.org/sequence-files/IGVFFI8864GAWT/
mv -n	igvf_008b/nova1/Sublibrary_11_S10_L003_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B11_D_nova_N1_L003_R2.fastq.gz		#c82285555621e2fd915ce29337432c0b	https://api.data.igvf.org/sequence-files/IGVFFI2159BFCO/
mv -n	igvf_008b/nova1/Sublibrary_11_S10_L004_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B11_D_nova_N1_L004_I1.fastq.gz		#c9947e38bda38cb5a25513f8beb55212
mv -n	igvf_008b/nova1/Sublibrary_11_S10_L004_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B11_D_nova_N1_L004_R1.fastq.gz		#76c9afc72b46641a99ca4cbe7d6eb8b7	https://api.data.igvf.org/sequence-files/IGVFFI6954OFQV/
mv -n	igvf_008b/nova1/Sublibrary_11_S10_L004_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B11_D_nova_N1_L004_R2.fastq.gz		#a92110076804847f2ec761742aa8c585	https://api.data.igvf.org/sequence-files/IGVFFI9388JLCZ/
mv -n	igvf_008b/nova1/Sublibrary_2_S1_L001_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B02_D_nova_N1_L001_I1.fastq.gz		#49bbb6439a4c971c37aa4eba32a47ea1
mv -n	igvf_008b/nova1/Sublibrary_2_S1_L001_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B02_D_nova_N1_L001_R1.fastq.gz		#be4e47d8022ba596a6ba97d2a920017f	https://api.data.igvf.org/sequence-files/IGVFFI4277GSNQ/
mv -n	igvf_008b/nova1/Sublibrary_2_S1_L001_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B02_D_nova_N1_L001_R2.fastq.gz		#a4dc0a278db75a3adfb968a97d0d126a	https://api.data.igvf.org/sequence-files/IGVFFI3098EGEE/
mv -n	igvf_008b/nova1/Sublibrary_2_S1_L002_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B02_D_nova_N1_L002_I1.fastq.gz		#dba0189d7cc15c5d7ae10fc4b09c29dc
mv -n	igvf_008b/nova1/Sublibrary_2_S1_L002_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B02_D_nova_N1_L002_R1.fastq.gz		#460a963e5d035a6c5bd476de60413ce8	https://api.data.igvf.org/sequence-files/IGVFFI8341SOWH/
mv -n	igvf_008b/nova1/Sublibrary_2_S1_L002_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B02_D_nova_N1_L002_R2.fastq.gz		#c3a85ed7d217baa20497a9c519116646	https://api.data.igvf.org/sequence-files/IGVFFI6389RFUQ/
mv -n	igvf_008b/nova1/Sublibrary_2_S1_L003_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B02_D_nova_N1_L003_I1.fastq.gz		#2367c221ecfa2bb9f0f6a3f8f92f2178
mv -n	igvf_008b/nova1/Sublibrary_2_S1_L003_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B02_D_nova_N1_L003_R1.fastq.gz		#c0f9661d21c2b0c3f73ff5b46c75888e	https://api.data.igvf.org/sequence-files/IGVFFI8636VWDT/
mv -n	igvf_008b/nova1/Sublibrary_2_S1_L003_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B02_D_nova_N1_L003_R2.fastq.gz		#fca7ea6e7a8a7d8f26fd605d3db066ab	https://api.data.igvf.org/sequence-files/IGVFFI9229GRTK/
mv -n	igvf_008b/nova1/Sublibrary_2_S1_L004_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B02_D_nova_N1_L004_I1.fastq.gz		#61c60ec1852ccc21de11876b0651276f
mv -n	igvf_008b/nova1/Sublibrary_2_S1_L004_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B02_D_nova_N1_L004_R1.fastq.gz		#e65354084b08386d9c405d341c15925e	https://api.data.igvf.org/sequence-files/IGVFFI7013CAMY/
mv -n	igvf_008b/nova1/Sublibrary_2_S1_L004_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B02_D_nova_N1_L004_R2.fastq.gz		#8144053ee734e9bf02f292c160e4eb9e	https://api.data.igvf.org/sequence-files/IGVFFI4229QUSP/
mv -n	igvf_008b/nova1/Sublibrary_3_S2_L001_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B03_D_nova_N1_L001_I1.fastq.gz		#a5a631c66eda233b8e4079ed1b85ded2
mv -n	igvf_008b/nova1/Sublibrary_3_S2_L001_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B03_D_nova_N1_L001_R1.fastq.gz		#7945ff803298f01e7aec4305763ff705	https://api.data.igvf.org/sequence-files/IGVFFI0954ZHJL/
mv -n	igvf_008b/nova1/Sublibrary_3_S2_L001_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B03_D_nova_N1_L001_R2.fastq.gz		#4aeedeceebac58ed7f2112808992e05f	https://api.data.igvf.org/sequence-files/IGVFFI3768XDLF/
mv -n	igvf_008b/nova1/Sublibrary_3_S2_L002_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B03_D_nova_N1_L002_I1.fastq.gz		#41ae422af512e9d0d19778dea1c5d554
mv -n	igvf_008b/nova1/Sublibrary_3_S2_L002_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B03_D_nova_N1_L002_R1.fastq.gz		#1b4f786076311323b5c8d4eebd3c9971	https://api.data.igvf.org/sequence-files/IGVFFI9744MTLW/
mv -n	igvf_008b/nova1/Sublibrary_3_S2_L002_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B03_D_nova_N1_L002_R2.fastq.gz		#16690a8afc5275e580db365c6850d644	https://api.data.igvf.org/sequence-files/IGVFFI5509OXUP/
mv -n	igvf_008b/nova1/Sublibrary_3_S2_L003_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B03_D_nova_N1_L003_I1.fastq.gz		#f49f0d5586a6d663529cc56138123551
mv -n	igvf_008b/nova1/Sublibrary_3_S2_L003_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B03_D_nova_N1_L003_R1.fastq.gz		#5fcf63fd92f745bbf911b57be03dbb6b	https://api.data.igvf.org/sequence-files/IGVFFI3570KVQX/
mv -n	igvf_008b/nova1/Sublibrary_3_S2_L003_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B03_D_nova_N1_L003_R2.fastq.gz		#b778c7f2d0c9885591bb90ef4a24a4d7	https://api.data.igvf.org/sequence-files/IGVFFI2187IBCO/
mv -n	igvf_008b/nova1/Sublibrary_3_S2_L004_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B03_D_nova_N1_L004_I1.fastq.gz		#a2257b727bee02ca2e780c94e51800c3
mv -n	igvf_008b/nova1/Sublibrary_3_S2_L004_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B03_D_nova_N1_L004_R1.fastq.gz		#7f763facaa2b68698bb30243a70c52a7	https://api.data.igvf.org/sequence-files/IGVFFI4697PWFT/
mv -n	igvf_008b/nova1/Sublibrary_3_S2_L004_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B03_D_nova_N1_L004_R2.fastq.gz		#d14e2a99c2a072ee31002a7b50ae7631	https://api.data.igvf.org/sequence-files/IGVFFI2602URPD/
mv -n	igvf_008b/nova1/Sublibrary_4_S3_L001_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B04_D_nova_N1_L001_I1.fastq.gz		#56434aefa2c6062ab94687806fe69575
mv -n	igvf_008b/nova1/Sublibrary_4_S3_L001_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B04_D_nova_N1_L001_R1.fastq.gz		#0b1325d883cdba23cc5f57d6a0201d83	https://api.data.igvf.org/sequence-files/IGVFFI7844YXOD/
mv -n	igvf_008b/nova1/Sublibrary_4_S3_L001_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B04_D_nova_N1_L001_R2.fastq.gz		#b9ab617386c3ca9a525ffa95c07608c5	https://api.data.igvf.org/sequence-files/IGVFFI8539UVGV/
mv -n	igvf_008b/nova1/Sublibrary_4_S3_L002_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B04_D_nova_N1_L002_I1.fastq.gz		#07ab052528d17e67d76a25d783fea610
mv -n	igvf_008b/nova1/Sublibrary_4_S3_L002_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B04_D_nova_N1_L002_R1.fastq.gz		#35b78b48b4eefdce3c3400afae3b0591	https://api.data.igvf.org/sequence-files/IGVFFI4126OISM/
mv -n	igvf_008b/nova1/Sublibrary_4_S3_L002_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B04_D_nova_N1_L002_R2.fastq.gz		#fe318ae02e80d572cb05b4779d7470a6	https://api.data.igvf.org/sequence-files/IGVFFI2570AACX/
mv -n	igvf_008b/nova1/Sublibrary_4_S3_L003_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B04_D_nova_N1_L003_I1.fastq.gz		#40e2d80c3aeebd6bc5ddc4b2d5494600
mv -n	igvf_008b/nova1/Sublibrary_4_S3_L003_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B04_D_nova_N1_L003_R1.fastq.gz		#b4da7c49c0dd6621da6685badeee5731	https://api.data.igvf.org/sequence-files/IGVFFI3450EIJS/
mv -n	igvf_008b/nova1/Sublibrary_4_S3_L003_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B04_D_nova_N1_L003_R2.fastq.gz		#2097d89d365be3de6de1d38134953281	https://api.data.igvf.org/sequence-files/IGVFFI4192PJAR/
mv -n	igvf_008b/nova1/Sublibrary_4_S3_L004_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B04_D_nova_N1_L004_I1.fastq.gz		#8a32c0ffaef67315f5142bf8470af08e
mv -n	igvf_008b/nova1/Sublibrary_4_S3_L004_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B04_D_nova_N1_L004_R1.fastq.gz		#3ef83451107228b6220e8d26d6ca8404	https://api.data.igvf.org/sequence-files/IGVFFI8490DMXP/
mv -n	igvf_008b/nova1/Sublibrary_4_S3_L004_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B04_D_nova_N1_L004_R2.fastq.gz		#049bd5645dc2cd33971060e27e5ada99	https://api.data.igvf.org/sequence-files/IGVFFI9187MWLF/
mv -n	igvf_008b/nova1/Sublibrary_5_S4_L001_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B05_D_nova_N1_L001_I1.fastq.gz		#7380bbf28648ee11069e3d16d9a0efbe
mv -n	igvf_008b/nova1/Sublibrary_5_S4_L001_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B05_D_nova_N1_L001_R1.fastq.gz		#a5980c70055beab28eddc5d90d5f9019	https://api.data.igvf.org/sequence-files/IGVFFI5228GWQS/
mv -n	igvf_008b/nova1/Sublibrary_5_S4_L001_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B05_D_nova_N1_L001_R2.fastq.gz		#a3711ef7937fe4f517eee7dce07a9d00	https://api.data.igvf.org/sequence-files/IGVFFI5887VIPP/
mv -n	igvf_008b/nova1/Sublibrary_5_S4_L002_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B05_D_nova_N1_L002_I1.fastq.gz		#e95de651bd1b42e584fd9ce61050d546
mv -n	igvf_008b/nova1/Sublibrary_5_S4_L002_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B05_D_nova_N1_L002_R1.fastq.gz		#87b9b9c914463f61c2473e9b6143958b	https://api.data.igvf.org/sequence-files/IGVFFI2345VHVH/
mv -n	igvf_008b/nova1/Sublibrary_5_S4_L002_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B05_D_nova_N1_L002_R2.fastq.gz		#05faa4ac8d7fc98a222e3355017ec1b3	https://api.data.igvf.org/sequence-files/IGVFFI9408WZWT/
mv -n	igvf_008b/nova1/Sublibrary_5_S4_L003_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B05_D_nova_N1_L003_I1.fastq.gz		#2ec85533ffa51c4778f81857fd624582
mv -n	igvf_008b/nova1/Sublibrary_5_S4_L003_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B05_D_nova_N1_L003_R1.fastq.gz		#a4e70fa0649b81a9b2f3e6c9ac4ba1bc	https://api.data.igvf.org/sequence-files/IGVFFI2557QYSI/
mv -n	igvf_008b/nova1/Sublibrary_5_S4_L003_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B05_D_nova_N1_L003_R2.fastq.gz		#a6da97e60cab73c223c071817f544939	https://api.data.igvf.org/sequence-files/IGVFFI2983LSRF/
mv -n	igvf_008b/nova1/Sublibrary_5_S4_L004_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B05_D_nova_N1_L004_I1.fastq.gz		#1ad03a2f290bf3071dadf759dd493c53

mv -n	igvf_008b/nova1/Sublibrary_5_S4_L004_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B05_D_nova_N1_L004_R1.fastq.gz		#032cb02886ffc25508ac2ecf309696fb	https://api.data.igvf.org/sequence-files/IGVFFI7257ZIIO/
mv -n	igvf_008b/nova1/Sublibrary_5_S4_L004_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B05_D_nova_N1_L004_R2.fastq.gz		#cb3e66c8c24738177fa75268d47ea5a4	https://api.data.igvf.org/sequence-files/IGVFFI8777ACJI/
mv -n	igvf_008b/nova1/Sublibrary_6_S5_L001_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B06_D_nova_N1_L001_I1.fastq.gz		#d3d9fe491fb3f5daa5017113a5ecf9bd
mv -n	igvf_008b/nova1/Sublibrary_6_S5_L001_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B06_D_nova_N1_L001_R1.fastq.gz		#9fc27f22dc4b1c6a600657efd8e6e589	https://api.data.igvf.org/sequence-files/IGVFFI8146VMBU/
mv -n	igvf_008b/nova1/Sublibrary_6_S5_L001_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B06_D_nova_N1_L001_R2.fastq.gz		#e88a5866c9c17de51dc90b94dffe6c4a	https://api.data.igvf.org/sequence-files/IGVFFI6260JUFJ/
mv -n	igvf_008b/nova1/Sublibrary_6_S5_L002_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B06_D_nova_N1_L002_I1.fastq.gz		#21707aee2de01e4a8fb3bb9cb49cf499
mv -n	igvf_008b/nova1/Sublibrary_6_S5_L002_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B06_D_nova_N1_L002_R1.fastq.gz		#eea46c0b13892c333777ebf3206691ac	https://api.data.igvf.org/sequence-files/IGVFFI0140WDGT/
mv -n	igvf_008b/nova1/Sublibrary_6_S5_L002_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B06_D_nova_N1_L002_R2.fastq.gz		#cb96a7e71c9a218f503219ef1ad777b2	https://api.data.igvf.org/sequence-files/IGVFFI7672RWMT/
mv -n	igvf_008b/nova1/Sublibrary_6_S5_L003_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B06_D_nova_N1_L003_I1.fastq.gz		#d5c7c9df621071f145a57ea7242d05bf
mv -n	igvf_008b/nova1/Sublibrary_6_S5_L003_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B06_D_nova_N1_L003_R1.fastq.gz		#bbd5c3a30f8cab0fa4a901f0bdec27ab	https://api.data.igvf.org/sequence-files/IGVFFI5528AAOW/
mv -n	igvf_008b/nova1/Sublibrary_6_S5_L003_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B06_D_nova_N1_L003_R2.fastq.gz		#993f1ce3616568a8135e3d0f12e8aa58	https://api.data.igvf.org/sequence-files/IGVFFI0326SXBB/
mv -n	igvf_008b/nova1/Sublibrary_6_S5_L004_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B06_D_nova_N1_L004_I1.fastq.gz		#c6ba67c6bf1cf13a2921f176f1296f90
mv -n	igvf_008b/nova1/Sublibrary_6_S5_L004_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B06_D_nova_N1_L004_R1.fastq.gz		#86f541085c9ca78806ac643c26580a52	https://api.data.igvf.org/sequence-files/IGVFFI7607JKXF/
mv -n	igvf_008b/nova1/Sublibrary_6_S5_L004_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B06_D_nova_N1_L004_R2.fastq.gz		#7399ff3c44d6a306426d46fa4f0dfba8	https://api.data.igvf.org/sequence-files/IGVFFI9321KTYR/
mv -n	igvf_008b/nova1/Sublibrary_7_S6_L001_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B07_D_nova_N1_L001_I1.fastq.gz		#a4964f72b0667c8df37978d3106843d4
mv -n	igvf_008b/nova1/Sublibrary_7_S6_L001_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B07_D_nova_N1_L001_R1.fastq.gz		#9545eda7c40ef3d133ad015640a740fd	https://api.data.igvf.org/sequence-files/IGVFFI9349JXBK/
mv -n	igvf_008b/nova1/Sublibrary_7_S6_L001_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B07_D_nova_N1_L001_R2.fastq.gz		#730e7f168b2b79310337087105beea30	https://api.data.igvf.org/sequence-files/IGVFFI1771XDBX/
mv -n	igvf_008b/nova1/Sublibrary_7_S6_L002_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B07_D_nova_N1_L002_I1.fastq.gz		#427c83ad8f6013bab83eaf3a2fd7d34d
mv -n	igvf_008b/nova1/Sublibrary_7_S6_L002_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B07_D_nova_N1_L002_R1.fastq.gz		#2bf574c01db16ff895638f36fac21f84	https://api.data.igvf.org/sequence-files/IGVFFI9220VWZL/
mv -n	igvf_008b/nova1/Sublibrary_7_S6_L002_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B07_D_nova_N1_L002_R2.fastq.gz		#43ab1a6fafd451df8ceda56761a7343e	https://api.data.igvf.org/sequence-files/IGVFFI9045ZKQS/
mv -n	igvf_008b/nova1/Sublibrary_7_S6_L003_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B07_D_nova_N1_L003_I1.fastq.gz		#d4a206baca59d37cb937e11dbfc96b0e
mv -n	igvf_008b/nova1/Sublibrary_7_S6_L003_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B07_D_nova_N1_L003_R1.fastq.gz		#c4a39e0071a2ee9485278278f62178d8	https://api.data.igvf.org/sequence-files/IGVFFI1798BBKZ/
mv -n	igvf_008b/nova1/Sublibrary_7_S6_L003_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B07_D_nova_N1_L003_R2.fastq.gz		#3f2924f7079316690743f767a59da068	https://api.data.igvf.org/sequence-files/IGVFFI6271OPZD/
mv -n	igvf_008b/nova1/Sublibrary_7_S6_L004_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B07_D_nova_N1_L004_I1.fastq.gz		#9e5457a108778627f0eb4e48886901df
mv -n	igvf_008b/nova1/Sublibrary_7_S6_L004_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B07_D_nova_N1_L004_R1.fastq.gz		#69c167a0aecd0145a67529736fafab21	https://api.data.igvf.org/sequence-files/IGVFFI7988SEJS/
mv -n	igvf_008b/nova1/Sublibrary_7_S6_L004_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B07_D_nova_N1_L004_R2.fastq.gz		#9f47172d033f382748ea1507200ce077	https://api.data.igvf.org/sequence-files/IGVFFI4623ODCA/
mv -n	igvf_008b/nova1/Sublibrary_8_S7_L001_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B08_D_nova_N1_L001_I1.fastq.gz		#40ca1f98aa5b127d56bd19842a43fefd
mv -n	igvf_008b/nova1/Sublibrary_8_S7_L001_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B08_D_nova_N1_L001_R1.fastq.gz		#82f39d94ba41ebd3b0b785bd9b15755b	https://api.data.igvf.org/sequence-files/IGVFFI7744MBUF/
mv -n	igvf_008b/nova1/Sublibrary_8_S7_L001_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B08_D_nova_N1_L001_R2.fastq.gz		#456efff66c9f60762b5f51b27126d5bc	https://api.data.igvf.org/sequence-files/IGVFFI6601JHAY/
mv -n	igvf_008b/nova1/Sublibrary_8_S7_L002_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B08_D_nova_N1_L002_I1.fastq.gz		#413d3e14c0d542893f0446221d4f88f1
mv -n	igvf_008b/nova1/Sublibrary_8_S7_L002_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B08_D_nova_N1_L002_R1.fastq.gz		#279584a06817a1d0fb24b0ae1f946555	https://api.data.igvf.org/sequence-files/IGVFFI8188QVSO/
mv -n	igvf_008b/nova1/Sublibrary_8_S7_L002_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B08_D_nova_N1_L002_R2.fastq.gz		#710fe7d0fa7f249f14e3fab20e66ddb3	https://api.data.igvf.org/sequence-files/IGVFFI3159BBKZ/
mv -n	igvf_008b/nova1/Sublibrary_8_S7_L003_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B08_D_nova_N1_L003_I1.fastq.gz		#1127f1b56d5b208b578e5b4212a36965
mv -n	igvf_008b/nova1/Sublibrary_8_S7_L003_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B08_D_nova_N1_L003_R1.fastq.gz		#16ea973fa88ba932171751ca00d9172f	https://api.data.igvf.org/sequence-files/IGVFFI7705SSQC/
mv -n	igvf_008b/nova1/Sublibrary_8_S7_L003_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B08_D_nova_N1_L003_R2.fastq.gz		#0b14f5a9abbc10265efe185425f7088a	https://api.data.igvf.org/sequence-files/IGVFFI9056OVDT/
mv -n	igvf_008b/nova1/Sublibrary_8_S7_L004_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B08_D_nova_N1_L004_I1.fastq.gz		#933718d66e572fbc040b9fcf71eebd3a
mv -n	igvf_008b/nova1/Sublibrary_8_S7_L004_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B08_D_nova_N1_L004_R1.fastq.gz		#380b062556e2776b387e35d1dcb9c573	https://api.data.igvf.org/sequence-files/IGVFFI2003XTIS/
mv -n	igvf_008b/nova1/Sublibrary_8_S7_L004_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B08_D_nova_N1_L004_R2.fastq.gz		#128ea6af7f44dc6cafcfb1a882b8e7be	https://api.data.igvf.org/sequence-files/IGVFFI3555UMLA/
mv -n	igvf_008b/nova1/Sublibrary_9_S8_L001_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B09_D_nova_N1_L001_I1.fastq.gz		#1f6008803d596757183a4ac4cb5b893a
mv -n	igvf_008b/nova1/Sublibrary_9_S8_L001_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B09_D_nova_N1_L001_R1.fastq.gz		#e018883aa4b8e912466109785687e394	https://api.data.igvf.org/sequence-files/IGVFFI8883RGKL/
mv -n	igvf_008b/nova1/Sublibrary_9_S8_L001_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B09_D_nova_N1_L001_R2.fastq.gz		#70b05431eaea4b72a9ca2e1a9b302bbe	https://api.data.igvf.org/sequence-files/IGVFFI1369DXLC/
mv -n	igvf_008b/nova1/Sublibrary_9_S8_L002_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B09_D_nova_N1_L002_I1.fastq.gz		#9828c0851e74e2f4d0fd6037c2bf2aa7
mv -n	igvf_008b/nova1/Sublibrary_9_S8_L002_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B09_D_nova_N1_L002_R1.fastq.gz		#28d2546d7f8f5616e4716dcb0260a410	https://api.data.igvf.org/sequence-files/IGVFFI9386ZOIC/
mv -n	igvf_008b/nova1/Sublibrary_9_S8_L002_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B09_D_nova_N1_L002_R2.fastq.gz		#7d068149631d4d7d602cb0c1e42f30f2	https://api.data.igvf.org/sequence-files/IGVFFI2009ACET/
mv -n	igvf_008b/nova1/Sublibrary_9_S8_L003_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B09_D_nova_N1_L003_I1.fastq.gz		#43339861ccc6d6c1d63d2b3bf7af05c3
mv -n	igvf_008b/nova1/Sublibrary_9_S8_L003_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B09_D_nova_N1_L003_R1.fastq.gz		#2eda8304c4accc0d03f4cd3cda31fc55	https://api.data.igvf.org/sequence-files/IGVFFI4410QFJM/
mv -n	igvf_008b/nova1/Sublibrary_9_S8_L003_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B09_D_nova_N1_L003_R2.fastq.gz		#e43a6947bbb56376de65e34f25d2cddf	https://api.data.igvf.org/sequence-files/IGVFFI3955JXHG/
mv -n	igvf_008b/nova1/Sublibrary_9_S8_L004_I1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B09_D_nova_N1_L004_I1.fastq.gz		#dd9f6e58256704ec28e64d915994687f
mv -n	igvf_008b/nova1/Sublibrary_9_S8_L004_R1_001.fastq.gz	igvf_008b/nova1/igvf_008b_B09_D_nova_N1_L004_R1.fastq.gz		#813da3a111489b1639ed273695fed199	https://api.data.igvf.org/sequence-files/IGVFFI7803VEYQ/
mv -n	igvf_008b/nova1/Sublibrary_9_S8_L004_R2_001.fastq.gz	igvf_008b/nova1/igvf_008b_B09_D_nova_N1_L004_R2.fastq.gz		#c6ec956ce24ae4dde34bbd9cd07af259	https://api.data.igvf.org/sequence-files/IGVFFI8141IHSS/
mv -n	igvf_009/nextseq/009_67A_R1.fastq.gz	igvf_009/nextseq/igvf_009_B02_D_next_N1_R1.fastq.gz		#d953a6098b3f5853efe240a3fbeb550b	https://api.data.igvf.org/sequence-files/IGVFFI9224ZULD/
mv -n	igvf_009/nextseq/009_67A_R2.fastq.gz	igvf_009/nextseq/igvf_009_B02_D_next_N1_R2.fastq.gz		#6d0ec7460f2e6104c4c8988b3831e8eb	https://api.data.igvf.org/sequence-files/IGVFFI1700IFDP/
mv -n	igvf_009/nextseq/009_67O_R1.fastq.gz	igvf_009/nextseq/igvf_009_B16_D_next_N1_R1.fastq.gz		#5869bb5af98dcc55ee1f9200e85a314e	https://api.data.igvf.org/sequence-files/IGVFFI5575BZCI/
mv -n	igvf_009/nextseq/009_67O_R2.fastq.gz	igvf_009/nextseq/igvf_009_B16_D_next_N1_R2.fastq.gz		#9986d4a81b0ea7f487ee168b9eff14e1	https://api.data.igvf.org/sequence-files/IGVFFI0260YEOG/
mv -n	igvf_009/nextseq2/009_13A_R1.fastq.gz	igvf_009/nextseq2/igvf_009_B06_E_next_N2_R1.fastq.gz		#d997b81e5f818ca50855ec5843c20f25	https://api.data.igvf.org/sequence-files/IGVFFI3195ZPCF/
mv -n	igvf_009/nextseq2/009_13A_R2.fastq.gz	igvf_009/nextseq2/igvf_009_B06_E_next_N2_R2.fastq.gz		#a5ce5de5aa3cce9c0556db279dbe2ef7	https://api.data.igvf.org/sequence-files/IGVFFI3084GNHN/
mv -n	igvf_009/nova1/Sublibrary_10_S9_L001_I1_001.fastq.gz	igvf_009/nova1/igvf_009_B10_D_nova_N1_L001_I1.fastq.gz		#fd730ede154fd908f6bc879316d1ccb8
mv -n	igvf_009/nova1/Sublibrary_10_S9_L001_R1_001.fastq.gz	igvf_009/nova1/igvf_009_B10_D_nova_N1_L001_R1.fastq.gz		#91b4bd5f83c9f7224a848d2a096658f6	https://api.data.igvf.org/sequence-files/IGVFFI9533NMQU/
mv -n	igvf_009/nova1/Sublibrary_10_S9_L001_R2_001.fastq.gz	igvf_009/nova1/igvf_009_B10_D_nova_N1_L001_R2.fastq.gz		#0c213f55bd9f99b5c5ba932b8d8bfc80	https://api.data.igvf.org/sequence-files/IGVFFI8007OPVU/
mv -n	igvf_009/nova1/Sublibrary_10_S9_L002_I1_001.fastq.gz	igvf_009/nova1/igvf_009_B10_D_nova_N1_L002_I1.fastq.gz		#ac301adda66b743b93ad1bcd3354f313
mv -n	igvf_009/nova1/Sublibrary_10_S9_L002_R1_001.fastq.gz	igvf_009/nova1/igvf_009_B10_D_nova_N1_L002_R1.fastq.gz		#a3a263647512c8c695383a1b2b7bee89	https://api.data.igvf.org/sequence-files/IGVFFI0480KOPC/
mv -n	igvf_009/nova1/Sublibrary_10_S9_L002_R2_001.fastq.gz	igvf_009/nova1/igvf_009_B10_D_nova_N1_L002_R2.fastq.gz		#207a88e5ba34289bf0a9dd8e22c3aff7	https://api.data.igvf.org/sequence-files/IGVFFI8200ARVL/
mv -n	igvf_009/nova1/Sublibrary_10_S9_L003_I1_001.fastq.gz	igvf_009/nova1/igvf_009_B10_D_nova_N1_L003_I1.fastq.gz		#b120bd6a91c2cf2d83cd26dfafb9d377
mv -n	igvf_009/nova1/Sublibrary_10_S9_L003_R1_001.fastq.gz	igvf_009/nova1/igvf_009_B10_D_nova_N1_L003_R1.fastq.gz		#3c963cc1b8b0dff115f87f6edf0a251a	https://api.data.igvf.org/sequence-files/IGVFFI5298NTVO/
mv -n	igvf_009/nova1/Sublibrary_10_S9_L003_R2_001.fastq.gz	igvf_009/nova1/igvf_009_B10_D_nova_N1_L003_R2.fastq.gz		#a535b69ec15c9b98f87d0a0ccb5b6a00	https://api.data.igvf.org/sequence-files/IGVFFI0435QKHP/
mv -n	igvf_009/nova1/Sublibrary_10_S9_L004_I1_001.fastq.gz	igvf_009/nova1/igvf_009_B10_D_nova_N1_L004_I1.fastq.gz		#68571783f00d7934f2316fe01166ab04
mv -n	igvf_009/nova1/Sublibrary_10_S9_L004_R1_001.fastq.gz	igvf_009/nova1/igvf_009_B10_D_nova_N1_L004_R1.fastq.gz		#961abaa59e07d472cea5df25ecfe18b0	https://api.data.igvf.org/sequence-files/IGVFFI4778XAVF/
mv -n	igvf_009/nova1/Sublibrary_10_S9_L004_R2_001.fastq.gz	igvf_009/nova1/igvf_009_B10_D_nova_N1_L004_R2.fastq.gz		#19a449d4c4e0087a26f39c78f557a8a4	https://api.data.igvf.org/sequence-files/IGVFFI4956AQNK/
mv -n	igvf_009/nova1/Sublibrary_11_S10_L001_I1_001.fastq.gz	igvf_009/nova1/igvf_009_B11_D_nova_N1_L001_I1.fastq.gz		#d630c2631f5d37fe85010f09c776911e
mv -n	igvf_009/nova1/Sublibrary_11_S10_L001_R1_001.fastq.gz	igvf_009/nova1/igvf_009_B11_D_nova_N1_L001_R1.fastq.gz		#f644060ce1c8dab74632f456f080230d	https://api.data.igvf.org/sequence-files/IGVFFI0246UMVF/
mv -n	igvf_009/nova1/Sublibrary_11_S10_L001_R2_001.fastq.gz	igvf_009/nova1/igvf_009_B11_D_nova_N1_L001_R2.fastq.gz		#398bb6c5733236a998e8c0b8654476fc	https://api.data.igvf.org/sequence-files/IGVFFI4330INNX/
mv -n	igvf_009/nova1/Sublibrary_11_S10_L002_I1_001.fastq.gz	igvf_009/nova1/igvf_009_B11_D_nova_N1_L002_I1.fastq.gz		#23b3fd7215a2235000b775c0fcd9ec1f
mv -n	igvf_009/nova1/Sublibrary_11_S10_L002_R1_001.fastq.gz	igvf_009/nova1/igvf_009_B11_D_nova_N1_L002_R1.fastq.gz		#5cb556d0e47395e7c9c8de2efb3d1d44	https://api.data.igvf.org/sequence-files/IGVFFI7801MEJS/
mv -n	igvf_009/nova1/Sublibrary_11_S10_L002_R2_001.fastq.gz	igvf_009/nova1/igvf_009_B11_D_nova_N1_L002_R2.fastq.gz		#8dbd9362111ae47383dfc585dbad53a6	https://api.data.igvf.org/sequence-files/IGVFFI8423CEWM/
mv -n	igvf_009/nova1/Sublibrary_11_S10_L003_I1_001.fastq.gz	igvf_009/nova1/igvf_009_B11_D_nova_N1_L003_I1.fastq.gz		#81f4fdce108c4e893b93ba376488a3bb
mv -n	igvf_009/nova1/Sublibrary_11_S10_L003_R1_001.fastq.gz	igvf_009/nova1/igvf_009_B11_D_nova_N1_L003_R1.fastq.gz		#1292e0cac323a168fd389bb359cce7da	https://api.data.igvf.org/sequence-files/IGVFFI6631IFSP/
mv -n	igvf_009/nova1/Sublibrary_11_S10_L003_R2_001.fastq.gz	igvf_009/nova1/igvf_009_B11_D_nova_N1_L003_R2.fastq.gz		#94cfd7d7c91a86234d44a54276489a1d	https://api.data.igvf.org/sequence-files/IGVFFI1245HAUZ/
mv -n	igvf_009/nova1/Sublibrary_11_S10_L004_I1_001.fastq.gz	igvf_009/nova1/igvf_009_B11_D_nova_N1_L004_I1.fastq.gz		#7bdfd8ce6c5bb4ec081a4c01f20c38d3
mv -n	igvf_009/nova1/Sublibrary_11_S10_L004_R1_001.fastq.gz	igvf_009/nova1/igvf_009_B11_D_nova_N1_L004_R1.fastq.gz		#0110065828da808e5d71964e9e0b9d13	https://api.data.igvf.org/sequence-files/IGVFFI1691XCEP/
mv -n	igvf_009/nova1/Sublibrary_11_S10_L004_R2_001.fastq.gz	igvf_009/nova1/igvf_009_B11_D_nova_N1_L004_R2.fastq.gz		#b3b067f1e49807c49fc496a4c1da0a55	https://api.data.igvf.org/sequence-files/IGVFFI4879ZKYW/
mv -n	igvf_009/nova1/Sublibrary_12_S11_L001_I1_001.fastq.gz	igvf_009/nova1/igvf_009_B12_D_nova_N1_L001_I1.fastq.gz		#9f8fb3ce03d63a7e4e88084381b90280
mv -n	igvf_009/nova1/Sublibrary_12_S11_L001_R1_001.fastq.gz	igvf_009/nova1/igvf_009_B12_D_nova_N1_L001_R1.fastq.gz		#b78fb4c4cf3a562056c11e83974fe6c5	https://api.data.igvf.org/sequence-files/IGVFFI7354VOOV/
mv -n	igvf_009/nova1/Sublibrary_12_S11_L001_R2_001.fastq.gz	igvf_009/nova1/igvf_009_B12_D_nova_N1_L001_R2.fastq.gz		#54ae58b929617b6747c4d30daa0b8d31	https://api.data.igvf.org/sequence-files/IGVFFI3697JTWY/
mv -n	igvf_009/nova1/Sublibrary_12_S11_L002_I1_001.fastq.gz	igvf_009/nova1/igvf_009_B12_D_nova_N1_L002_I1.fastq.gz		#184e6b176392b1684764b47666c2e3d9
mv -n	igvf_009/nova1/Sublibrary_12_S11_L002_R1_001.fastq.gz	igvf_009/nova1/igvf_009_B12_D_nova_N1_L002_R1.fastq.gz		#13d3b526edc37c7049a64a1f2e573472	https://api.data.igvf.org/sequence-files/IGVFFI0089MLLI/
mv -n	igvf_009/nova1/Sublibrary_12_S11_L002_R2_001.fastq.gz	igvf_009/nova1/igvf_009_B12_D_nova_N1_L002_R2.fastq.gz		#de2733aed132da701aa5bbdff7e251cc	https://api.data.igvf.org/sequence-files/IGVFFI1915FIQT/
mv -n	igvf_009/nova1/Sublibrary_12_S11_L003_I1_001.fastq.gz	igvf_009/nova1/igvf_009_B12_D_nova_N1_L003_I1.fastq.gz		#45baf41537500a9eca70308347aedbda
mv -n	igvf_009/nova1/Sublibrary_12_S11_L003_R1_001.fastq.gz	igvf_009/nova1/igvf_009_B12_D_nova_N1_L003_R1.fastq.gz		#5dd785dd4734ac82691d236768380c81	https://api.data.igvf.org/sequence-files/IGVFFI5224RTBL/
mv -n	igvf_009/nova1/Sublibrary_12_S11_L003_R2_001.fastq.gz	igvf_009/nova1/igvf_009_B12_D_nova_N1_L003_R2.fastq.gz		#5a7b86d6292b142ceeb4dfd3d02f5032	https://api.data.igvf.org/sequence-files/IGVFFI3683LLSW/
mv -n	igvf_009/nova1/Sublibrary_12_S11_L004_I1_001.fastq.gz	igvf_009/nova1/igvf_009_B12_D_nova_N1_L004_I1.fastq.gz		#4e9f6e8360976a07f7c28ac8a82edd60
mv -n	igvf_009/nova1/Sublibrary_12_S11_L004_R1_001.fastq.gz	igvf_009/nova1/igvf_009_B12_D_nova_N1_L004_R1.fastq.gz		#a8a4df84de1dbba4e1174b9c6d3a9c9d	https://api.data.igvf.org/sequence-files/IGVFFI4640GKIB/
mv -n	igvf_009/nova1/Sublibrary_12_S11_L004_R2_001.fastq.gz	igvf_009/nova1/igvf_009_B12_D_nova_N1_L004_R2.fastq.gz		#c7a1120101cf30abf8b52c378dc40e06	https://api.data.igvf.org/sequence-files/IGVFFI9545YIUW/
mv -n	igvf_009/nova1/Sublibrary_13_S12_L001_I1_001.fastq.gz	igvf_009/nova1/igvf_009_B13_D_nova_N1_L001_I1.fastq.gz		#a849214b6552ab8c1a51e19ccb64ca98
mv -n	igvf_009/nova1/Sublibrary_13_S12_L001_R1_001.fastq.gz	igvf_009/nova1/igvf_009_B13_D_nova_N1_L001_R1.fastq.gz		#e5ba848ae775d16d613e2903d822b079	https://api.data.igvf.org/sequence-files/IGVFFI2068BOPH/
mv -n	igvf_009/nova1/Sublibrary_13_S12_L001_R2_001.fastq.gz	igvf_009/nova1/igvf_009_B13_D_nova_N1_L001_R2.fastq.gz		#8f2f9a6688c6709a35217c49eb59925d	https://api.data.igvf.org/sequence-files/IGVFFI3923WWRP/
mv -n	igvf_009/nova1/Sublibrary_13_S12_L002_I1_001.fastq.gz	igvf_009/nova1/igvf_009_B13_D_nova_N1_L002_I1.fastq.gz		#afc0d1f6f90db2023a070dba1d024c10
mv -n	igvf_009/nova1/Sublibrary_13_S12_L002_R1_001.fastq.gz	igvf_009/nova1/igvf_009_B13_D_nova_N1_L002_R1.fastq.gz		#9f57e00e75646c4315a7fa5f439c5692	https://api.data.igvf.org/sequence-files/IGVFFI5266ZEFR/
mv -n	igvf_009/nova1/Sublibrary_13_S12_L002_R2_001.fastq.gz	igvf_009/nova1/igvf_009_B13_D_nova_N1_L002_R2.fastq.gz		#ee3c8854c9cf4cca4ff6dc8929ac33d1	https://api.data.igvf.org/sequence-files/IGVFFI7969AUMJ/
mv -n	igvf_009/nova1/Sublibrary_13_S12_L003_I1_001.fastq.gz	igvf_009/nova1/igvf_009_B13_D_nova_N1_L003_I1.fastq.gz		#b5bcfbf6f91f801356b521136cf87cf8
mv -n	igvf_009/nova1/Sublibrary_13_S12_L003_R1_001.fastq.gz	igvf_009/nova1/igvf_009_B13_D_nova_N1_L003_R1.fastq.gz		#e44e95d74b0ee885c45b0cd8b50fd4a7	https://api.data.igvf.org/sequence-files/IGVFFI2231UCCY/
mv -n	igvf_009/nova1/Sublibrary_13_S12_L003_R2_001.fastq.gz	igvf_009/nova1/igvf_009_B13_D_nova_N1_L003_R2.fastq.gz		#195e6b1453d5d236b78f33d8229ad5ae	https://api.data.igvf.org/sequence-files/IGVFFI1830FJAM/
mv -n	igvf_009/nova1/Sublibrary_13_S12_L004_I1_001.fastq.gz	igvf_009/nova1/igvf_009_B13_D_nova_N1_L004_I1.fastq.gz		#119680094ce0615b2e765877bc1da9fd
mv -n	igvf_009/nova1/Sublibrary_13_S12_L004_R1_001.fastq.gz	igvf_009/nova1/igvf_009_B13_D_nova_N1_L004_R1.fastq.gz		#754e2ad63e0e18137d0dd251a00923a3	https://api.data.igvf.org/sequence-files/IGVFFI8403KWOF/
mv -n	igvf_009/nova1/Sublibrary_13_S12_L004_R2_001.fastq.gz	igvf_009/nova1/igvf_009_B13_D_nova_N1_L004_R2.fastq.gz		#fe2f6e129590022f4a3c8f72c6b88c18	https://api.data.igvf.org/sequence-files/IGVFFI8863LGOW/
mv -n	igvf_009/nova1/Sublibrary_14_S13_L001_I1_001.fastq.gz	igvf_009/nova1/igvf_009_B14_D_nova_N1_L001_I1.fastq.gz		#9a4118341eb31c57bc0b8f9d7d39b814
mv -n	igvf_009/nova1/Sublibrary_14_S13_L001_R1_001.fastq.gz	igvf_009/nova1/igvf_009_B14_D_nova_N1_L001_R1.fastq.gz		#dc38a1712cde6cca5b0ef00e7b37f2a2	https://api.data.igvf.org/sequence-files/IGVFFI3264LJDY/

mv -n	igvf_009/nova2/Sublibrary_4_S3_L004_R1_001.fastq.gz	igvf_009/nova2/igvf_009_B04_D_nova_N2_L004_R1.fastq.gz		#9ed0c798b7665b3e795a70864fd61c23	https://api.data.igvf.org/sequence-files/IGVFFI1180PVFY/
mv -n	igvf_009/nova2/Sublibrary_4_S3_L004_R2_001.fastq.gz	igvf_009/nova2/igvf_009_B04_D_nova_N2_L004_R2.fastq.gz		#ed451793ba179be45b037c608e70b563	https://api.data.igvf.org/sequence-files/IGVFFI4423TIPJ/
mv -n	igvf_009/nova2/Sublibrary_5_S4_L001_I1_001.fastq.gz	igvf_009/nova2/igvf_009_B05_D_nova_N2_L001_I1.fastq.gz		#9821a221e05e73014184ddb27349df37
mv -n	igvf_009/nova2/Sublibrary_5_S4_L001_R1_001.fastq.gz	igvf_009/nova2/igvf_009_B05_D_nova_N2_L001_R1.fastq.gz		#013a5387d0fa1072d5e8d478c84c89d6	https://api.data.igvf.org/sequence-files/IGVFFI5230XDFN/
mv -n	igvf_009/nova2/Sublibrary_5_S4_L001_R2_001.fastq.gz	igvf_009/nova2/igvf_009_B05_D_nova_N2_L001_R2.fastq.gz		#260c95d55dfe2fac1041bf66cfea29fb	https://api.data.igvf.org/sequence-files/IGVFFI1362KPQO/
mv -n	igvf_009/nova2/Sublibrary_5_S4_L002_I1_001.fastq.gz	igvf_009/nova2/igvf_009_B05_D_nova_N2_L002_I1.fastq.gz		#a6b743f7e51828b1f31cafc2cae23ddf
mv -n	igvf_009/nova2/Sublibrary_5_S4_L002_R1_001.fastq.gz	igvf_009/nova2/igvf_009_B05_D_nova_N2_L002_R1.fastq.gz		#abb6be2ff68e8de02e4e29293e27d532	https://api.data.igvf.org/sequence-files/IGVFFI2948KVHG/
mv -n	igvf_009/nova2/Sublibrary_5_S4_L002_R2_001.fastq.gz	igvf_009/nova2/igvf_009_B05_D_nova_N2_L002_R2.fastq.gz		#db7ec6b40e51e327900f646eedb05065	https://api.data.igvf.org/sequence-files/IGVFFI7595JQDU/
mv -n	igvf_009/nova2/Sublibrary_5_S4_L003_I1_001.fastq.gz	igvf_009/nova2/igvf_009_B05_D_nova_N2_L003_I1.fastq.gz		#d0790a3a078c22e462fdc43ea396b070
mv -n	igvf_009/nova2/Sublibrary_5_S4_L003_R1_001.fastq.gz	igvf_009/nova2/igvf_009_B05_D_nova_N2_L003_R1.fastq.gz		#c0addd1d5625a9ed39f823c446382328	https://api.data.igvf.org/sequence-files/IGVFFI7861MKBV/
mv -n	igvf_009/nova2/Sublibrary_5_S4_L003_R2_001.fastq.gz	igvf_009/nova2/igvf_009_B05_D_nova_N2_L003_R2.fastq.gz		#9dd4dfd5f36ae8e2c6b1c005b0cb3063	https://api.data.igvf.org/sequence-files/IGVFFI3905DOTP/
mv -n	igvf_009/nova2/Sublibrary_5_S4_L004_I1_001.fastq.gz	igvf_009/nova2/igvf_009_B05_D_nova_N2_L004_I1.fastq.gz		#30fde2fc2dde23f27b94d621c3b38d41
mv -n	igvf_009/nova2/Sublibrary_5_S4_L004_R1_001.fastq.gz	igvf_009/nova2/igvf_009_B05_D_nova_N2_L004_R1.fastq.gz		#cad8ce8659a2d798fad261983a4aa942	https://api.data.igvf.org/sequence-files/IGVFFI7113LNRI/
mv -n	igvf_009/nova2/Sublibrary_5_S4_L004_R2_001.fastq.gz	igvf_009/nova2/igvf_009_B05_D_nova_N2_L004_R2.fastq.gz		#a0d33e95302b0af22f44e1a7179e0172	https://api.data.igvf.org/sequence-files/IGVFFI1059LPMB/
mv -n	igvf_009/nova2/Sublibrary_6_S5_L001_I1_001.fastq.gz	igvf_009/nova2/igvf_009_B06_D_nova_N2_L001_I1.fastq.gz		#9f255c52ca4aa5150dfed5bbfb575566
mv -n	igvf_009/nova2/Sublibrary_6_S5_L001_R1_001.fastq.gz	igvf_009/nova2/igvf_009_B06_D_nova_N2_L001_R1.fastq.gz		#96f36840d0ef6a0bdba225ce751020b7	https://api.data.igvf.org/sequence-files/IGVFFI0546IEMJ/
mv -n	igvf_009/nova2/Sublibrary_6_S5_L001_R2_001.fastq.gz	igvf_009/nova2/igvf_009_B06_D_nova_N2_L001_R2.fastq.gz		#cb6fdd2de89218aa572be541dd019f4d	https://api.data.igvf.org/sequence-files/IGVFFI7890TKLE/
mv -n	igvf_009/nova2/Sublibrary_6_S5_L002_I1_001.fastq.gz	igvf_009/nova2/igvf_009_B06_D_nova_N2_L002_I1.fastq.gz		#11854fb50c41abbe08bd4f0892fe3b04
mv -n	igvf_009/nova2/Sublibrary_6_S5_L002_R1_001.fastq.gz	igvf_009/nova2/igvf_009_B06_D_nova_N2_L002_R1.fastq.gz		#461482c6eba05c7295d664e76ff95eb4	https://api.data.igvf.org/sequence-files/IGVFFI2446LQYD/
mv -n	igvf_009/nova2/Sublibrary_6_S5_L002_R2_001.fastq.gz	igvf_009/nova2/igvf_009_B06_D_nova_N2_L002_R2.fastq.gz		#6da00c216a7299f88cff2996782aaeaf	https://api.data.igvf.org/sequence-files/IGVFFI7836EYIQ/
mv -n	igvf_009/nova2/Sublibrary_6_S5_L003_I1_001.fastq.gz	igvf_009/nova2/igvf_009_B06_D_nova_N2_L003_I1.fastq.gz		#06a2bec06ba6285b0e0ceceb42f3eabc
mv -n	igvf_009/nova2/Sublibrary_6_S5_L003_R1_001.fastq.gz	igvf_009/nova2/igvf_009_B06_D_nova_N2_L003_R1.fastq.gz		#3c2681b68f283c2f0203fc4e1549379f	https://api.data.igvf.org/sequence-files/IGVFFI0776VZHW/
mv -n	igvf_009/nova2/Sublibrary_6_S5_L003_R2_001.fastq.gz	igvf_009/nova2/igvf_009_B06_D_nova_N2_L003_R2.fastq.gz		#880be43979c3b9650543eeb32d01dc92	https://api.data.igvf.org/sequence-files/IGVFFI4909HGIZ/
mv -n	igvf_009/nova2/Sublibrary_6_S5_L004_I1_001.fastq.gz	igvf_009/nova2/igvf_009_B06_D_nova_N2_L004_I1.fastq.gz		#07b79cb62f6da678aeef5fd4d0778a8c
mv -n	igvf_009/nova2/Sublibrary_6_S5_L004_R1_001.fastq.gz	igvf_009/nova2/igvf_009_B06_D_nova_N2_L004_R1.fastq.gz		#82a94f6d33364673dd4bf95b5e0ae367	https://api.data.igvf.org/sequence-files/IGVFFI8498LWMX/
mv -n	igvf_009/nova2/Sublibrary_6_S5_L004_R2_001.fastq.gz	igvf_009/nova2/igvf_009_B06_D_nova_N2_L004_R2.fastq.gz		#101a2f42c5edaa7a8f072decb0f63d13	https://api.data.igvf.org/sequence-files/IGVFFI6586LVNY/
mv -n	igvf_009/nova2/Sublibrary_7_S6_L001_I1_001.fastq.gz	igvf_009/nova2/igvf_009_B07_D_nova_N2_L001_I1.fastq.gz		#223acaf72ce574292f915dd6df33ed38
mv -n	igvf_009/nova2/Sublibrary_7_S6_L001_R1_001.fastq.gz	igvf_009/nova2/igvf_009_B07_D_nova_N2_L001_R1.fastq.gz		#8cb19af5f174af8c60664097ad973878	https://api.data.igvf.org/sequence-files/IGVFFI8262YILV/
mv -n	igvf_009/nova2/Sublibrary_7_S6_L001_R2_001.fastq.gz	igvf_009/nova2/igvf_009_B07_D_nova_N2_L001_R2.fastq.gz		#8647cad8883b71404d1aedeb318a8a45	https://api.data.igvf.org/sequence-files/IGVFFI1349BOKL/
mv -n	igvf_009/nova2/Sublibrary_7_S6_L002_I1_001.fastq.gz	igvf_009/nova2/igvf_009_B07_D_nova_N2_L002_I1.fastq.gz		#708c1ee494aa145f828705b31144647d
mv -n	igvf_009/nova2/Sublibrary_7_S6_L002_R1_001.fastq.gz	igvf_009/nova2/igvf_009_B07_D_nova_N2_L002_R1.fastq.gz		#deae56c3b1f57869b203bf32634bf5f1	https://api.data.igvf.org/sequence-files/IGVFFI1643ATJF/
mv -n	igvf_009/nova2/Sublibrary_7_S6_L002_R2_001.fastq.gz	igvf_009/nova2/igvf_009_B07_D_nova_N2_L002_R2.fastq.gz		#2119217a3a61e330fc2eed6f53f0aa99	https://api.data.igvf.org/sequence-files/IGVFFI3366YLCR/
mv -n	igvf_009/nova2/Sublibrary_7_S6_L003_I1_001.fastq.gz	igvf_009/nova2/igvf_009_B07_D_nova_N2_L003_I1.fastq.gz		#d8f716c8e4e66f687ae4bb1326c88aa9
mv -n	igvf_009/nova2/Sublibrary_7_S6_L003_R1_001.fastq.gz	igvf_009/nova2/igvf_009_B07_D_nova_N2_L003_R1.fastq.gz		#5cfb2693b3db724fe160afbaa94c95ea	https://api.data.igvf.org/sequence-files/IGVFFI9703FJJE/
mv -n	igvf_009/nova2/Sublibrary_7_S6_L003_R2_001.fastq.gz	igvf_009/nova2/igvf_009_B07_D_nova_N2_L003_R2.fastq.gz		#a802a9222c5d5231887272a5935c1e92	https://api.data.igvf.org/sequence-files/IGVFFI6685TKRE/
mv -n	igvf_009/nova2/Sublibrary_7_S6_L004_I1_001.fastq.gz	igvf_009/nova2/igvf_009_B07_D_nova_N2_L004_I1.fastq.gz		#9618a8b8b81c78643cff3e0645e10cff
mv -n	igvf_009/nova2/Sublibrary_7_S6_L004_R1_001.fastq.gz	igvf_009/nova2/igvf_009_B07_D_nova_N2_L004_R1.fastq.gz		#d9d449cca568d22ed1c3a1c3f5d00c1a	https://api.data.igvf.org/sequence-files/IGVFFI6161WLXQ/
mv -n	igvf_009/nova2/Sublibrary_7_S6_L004_R2_001.fastq.gz	igvf_009/nova2/igvf_009_B07_D_nova_N2_L004_R2.fastq.gz		#a809df9f413b27d74d6352d642fb4178	https://api.data.igvf.org/sequence-files/IGVFFI9393AYOA/
mv -n	igvf_009/nova2/Sublibrary_8_S7_L001_I1_001.fastq.gz	igvf_009/nova2/igvf_009_B08_D_nova_N2_L001_I1.fastq.gz		#ec5037fb70aac25bcbfa7b12ad1ff3a3
mv -n	igvf_009/nova2/Sublibrary_8_S7_L001_R1_001.fastq.gz	igvf_009/nova2/igvf_009_B08_D_nova_N2_L001_R1.fastq.gz		#f06c57008cafe7a9df9cdd07e764b708	https://api.data.igvf.org/sequence-files/IGVFFI4951PRZL/
mv -n	igvf_009/nova2/Sublibrary_8_S7_L001_R2_001.fastq.gz	igvf_009/nova2/igvf_009_B08_D_nova_N2_L001_R2.fastq.gz		#c0fd82d063b42afd2ee6dcc77aab444a	https://api.data.igvf.org/sequence-files/IGVFFI5726KMBS/
mv -n	igvf_009/nova2/Sublibrary_8_S7_L002_I1_001.fastq.gz	igvf_009/nova2/igvf_009_B08_D_nova_N2_L002_I1.fastq.gz		#f8a82fc66b9d2fc48c26a9d348edb144
mv -n	igvf_009/nova2/Sublibrary_8_S7_L002_R1_001.fastq.gz	igvf_009/nova2/igvf_009_B08_D_nova_N2_L002_R1.fastq.gz		#14a326e14fea479b229159e70395561e	https://api.data.igvf.org/sequence-files/IGVFFI9672DRRX/
mv -n	igvf_009/nova2/Sublibrary_8_S7_L002_R2_001.fastq.gz	igvf_009/nova2/igvf_009_B08_D_nova_N2_L002_R2.fastq.gz		#87adb5a4e0ae16fcb51e4e2a73be4d05	https://api.data.igvf.org/sequence-files/IGVFFI1221QXEU/
mv -n	igvf_009/nova2/Sublibrary_8_S7_L003_I1_001.fastq.gz	igvf_009/nova2/igvf_009_B08_D_nova_N2_L003_I1.fastq.gz		#013b914e12f9ecc312ba8859b2f82595
mv -n	igvf_009/nova2/Sublibrary_8_S7_L003_R1_001.fastq.gz	igvf_009/nova2/igvf_009_B08_D_nova_N2_L003_R1.fastq.gz		#2f9fedbbbc6e78be25692b90329c7874	https://api.data.igvf.org/sequence-files/IGVFFI6103KKIO/
mv -n	igvf_009/nova2/Sublibrary_8_S7_L003_R2_001.fastq.gz	igvf_009/nova2/igvf_009_B08_D_nova_N2_L003_R2.fastq.gz		#6b620b4ef2b8940a60b879aa68d0567e	https://api.data.igvf.org/sequence-files/IGVFFI3365DPZI/
mv -n	igvf_009/nova2/Sublibrary_8_S7_L004_I1_001.fastq.gz	igvf_009/nova2/igvf_009_B08_D_nova_N2_L004_I1.fastq.gz		#36496865a407d9fe20062aa21b82e32b
mv -n	igvf_009/nova2/Sublibrary_8_S7_L004_R1_001.fastq.gz	igvf_009/nova2/igvf_009_B08_D_nova_N2_L004_R1.fastq.gz		#18bbc5d7950b0fd07591cebd03c31933	https://api.data.igvf.org/sequence-files/IGVFFI1556GYJW/
mv -n	igvf_009/nova2/Sublibrary_8_S7_L004_R2_001.fastq.gz	igvf_009/nova2/igvf_009_B08_D_nova_N2_L004_R2.fastq.gz		#186c83e4caba31590449d31a04967817	https://api.data.igvf.org/sequence-files/IGVFFI8901WTSD/
mv -n	igvf_009/nova2/Sublibrary_9_S8_L001_I1_001.fastq.gz	igvf_009/nova2/igvf_009_B09_D_nova_N2_L001_I1.fastq.gz		#50da56d216d23ad0749d4008b76b5507
mv -n	igvf_009/nova2/Sublibrary_9_S8_L001_R1_001.fastq.gz	igvf_009/nova2/igvf_009_B09_D_nova_N2_L001_R1.fastq.gz		#8a03d290bbd46321cae0864c85738caf	https://api.data.igvf.org/sequence-files/IGVFFI6440EIJG/
mv -n	igvf_009/nova2/Sublibrary_9_S8_L001_R2_001.fastq.gz	igvf_009/nova2/igvf_009_B09_D_nova_N2_L001_R2.fastq.gz		#93807860576f3456e771b8ffcd30d7f6	https://api.data.igvf.org/sequence-files/IGVFFI5360GVGZ/
mv -n	igvf_009/nova2/Sublibrary_9_S8_L002_I1_001.fastq.gz	igvf_009/nova2/igvf_009_B09_D_nova_N2_L002_I1.fastq.gz		#94a4b77fd7ac7446cf00933e0c8d59cd
mv -n	igvf_009/nova2/Sublibrary_9_S8_L002_R1_001.fastq.gz	igvf_009/nova2/igvf_009_B09_D_nova_N2_L002_R1.fastq.gz		#8b763323cc945f0dde0a528fd992ac12	https://api.data.igvf.org/sequence-files/IGVFFI1478MAUG/
mv -n	igvf_009/nova2/Sublibrary_9_S8_L002_R2_001.fastq.gz	igvf_009/nova2/igvf_009_B09_D_nova_N2_L002_R2.fastq.gz		#15005a742424121f063401f84e16dbde	https://api.data.igvf.org/sequence-files/IGVFFI9988ZQEV/
mv -n	igvf_009/nova2/Sublibrary_9_S8_L003_I1_001.fastq.gz	igvf_009/nova2/igvf_009_B09_D_nova_N2_L003_I1.fastq.gz		#9673d8325e5868f5185eee6016257b7b
mv -n	igvf_009/nova2/Sublibrary_9_S8_L003_R1_001.fastq.gz	igvf_009/nova2/igvf_009_B09_D_nova_N2_L003_R1.fastq.gz		#8e4528a6291d609103475057726bf8bb	https://api.data.igvf.org/sequence-files/IGVFFI7124FWES/
mv -n	igvf_009/nova2/Sublibrary_9_S8_L003_R2_001.fastq.gz	igvf_009/nova2/igvf_009_B09_D_nova_N2_L003_R2.fastq.gz		#740647d68bdeb7a86da0e7fc06bb94c6	https://api.data.igvf.org/sequence-files/IGVFFI4944EADG/
mv -n	igvf_009/nova2/Sublibrary_9_S8_L004_I1_001.fastq.gz	igvf_009/nova2/igvf_009_B09_D_nova_N2_L004_I1.fastq.gz		#7c3d0fdd92cb8e8988ccc1733c967e50
mv -n	igvf_009/nova2/Sublibrary_9_S8_L004_R1_001.fastq.gz	igvf_009/nova2/igvf_009_B09_D_nova_N2_L004_R1.fastq.gz		#0df6d258decb1f847beff1db15d67feb	https://api.data.igvf.org/sequence-files/IGVFFI7913RBDD/
mv -n	igvf_009/nova2/Sublibrary_9_S8_L004_R2_001.fastq.gz	igvf_009/nova2/igvf_009_B09_D_nova_N2_L004_R2.fastq.gz		#a0c6a4e77b66a1d2cf66bc4fb24481f4	https://api.data.igvf.org/sequence-files/IGVFFI5883NUWN/
mv -n	igvf_010/nextseq/010_67D_R1.fastq.gz	igvf_010/nextseq/igvf_010_B05_D_next_N1_R1.fastq.gz		#7c67259f01c6060e30c9e9b4c2d31bac	https://api.data.igvf.org/sequence-files/IGVFFI6710OCYD/
mv -n	igvf_010/nextseq/010_67D_R2.fastq.gz	igvf_010/nextseq/igvf_010_B05_D_next_N1_R2.fastq.gz		#ffc8bfad82784a0ce5cf4e2fec55b2ee	https://api.data.igvf.org/sequence-files/IGVFFI3418ZQUY/
mv -n	igvf_010/nextseq/010_67O_R1.fastq.gz	igvf_010/nextseq/igvf_010_B16_D_next_N1_R1.fastq.gz		#c0d645e759809ec5422e4849fb2cd294	https://api.data.igvf.org/sequence-files/IGVFFI9028PLYA/
mv -n	igvf_010/nextseq/010_67O_R2.fastq.gz	igvf_010/nextseq/igvf_010_B16_D_next_N1_R2.fastq.gz		#f2a345718531cae5e567f13092259480	https://api.data.igvf.org/sequence-files/IGVFFI7551EVMC/

mv -n	igvf_010/nextseq2/010_13A_R1.fastq.gz	igvf_010/nextseq2/igvf_010_B07_E_next_N2_R1.fastq.gz		#ab6a95e43234701e4feac682e627517c	https://api.data.igvf.org/sequence-files/IGVFFI2235MCOP/
mv -n	igvf_010/nextseq2/010_13A_R2.fastq.gz	igvf_010/nextseq2/igvf_010_B07_E_next_N2_R2.fastq.gz		#46dfe5ce2abb19863c63ea3855bbbb31	https://api.data.igvf.org/sequence-files/IGVFFI3650UECM/
mv -n	igvf_010/nova1/Sublibrary_10_S9_L001_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B10_D_nova_N1_L001_I1.fastq.gz		#4d193266ad0ccfde8a75085a47d40800
mv -n	igvf_010/nova1/Sublibrary_10_S9_L001_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B10_D_nova_N1_L001_R1.fastq.gz		#20b096fc703b2b90d8113034dae96ca5	https://api.data.igvf.org/sequence-files/IGVFFI8471EXAF/
mv -n	igvf_010/nova1/Sublibrary_10_S9_L001_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B10_D_nova_N1_L001_R2.fastq.gz		#bf2ae866b88f1732773141ae4af1c015	https://api.data.igvf.org/sequence-files/IGVFFI4453WDKD/
mv -n	igvf_010/nova1/Sublibrary_10_S9_L002_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B10_D_nova_N1_L002_I1.fastq.gz		#4c262e952fd5a6f50e69fd579f7a2900
mv -n	igvf_010/nova1/Sublibrary_10_S9_L002_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B10_D_nova_N1_L002_R1.fastq.gz		#a10261d9e7872c219fa6801e9890b24c	https://api.data.igvf.org/sequence-files/IGVFFI1677ZWLA/
mv -n	igvf_010/nova1/Sublibrary_10_S9_L002_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B10_D_nova_N1_L002_R2.fastq.gz		#3471a6d3cf482a09125a65a93aa39615	https://api.data.igvf.org/sequence-files/IGVFFI0234FTOL/
mv -n	igvf_010/nova1/Sublibrary_10_S9_L003_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B10_D_nova_N1_L003_I1.fastq.gz		#530997896a0d738d73e8f40eda972f63
mv -n	igvf_010/nova1/Sublibrary_10_S9_L003_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B10_D_nova_N1_L003_R1.fastq.gz		#deeae424788772a39b17d2008a32bd54	https://api.data.igvf.org/sequence-files/IGVFFI0930QPFX/
mv -n	igvf_010/nova1/Sublibrary_10_S9_L003_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B10_D_nova_N1_L003_R2.fastq.gz		#f48715353a58291916f69aea0096af7b	https://api.data.igvf.org/sequence-files/IGVFFI8411DKVB/
mv -n	igvf_010/nova1/Sublibrary_10_S9_L004_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B10_D_nova_N1_L004_I1.fastq.gz		#c7c2d9c391ae837d87e55f95c0943b95
mv -n	igvf_010/nova1/Sublibrary_10_S9_L004_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B10_D_nova_N1_L004_R1.fastq.gz		#986dc0d482a375f2e59de630d87aa951	https://api.data.igvf.org/sequence-files/IGVFFI0152WVJC/
mv -n	igvf_010/nova1/Sublibrary_10_S9_L004_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B10_D_nova_N1_L004_R2.fastq.gz		#f79a23219ab521d38f969954e1ef0c6a	https://api.data.igvf.org/sequence-files/IGVFFI2686ZSEO/
mv -n	igvf_010/nova1/Sublibrary_11_S10_L001_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B11_D_nova_N1_L001_I1.fastq.gz		#e96fbd45735bce60fa3f876a2f058170
mv -n	igvf_010/nova1/Sublibrary_11_S10_L001_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B11_D_nova_N1_L001_R1.fastq.gz		#08abdad4bf3d5c6788ed1d04e78a7605	https://api.data.igvf.org/sequence-files/IGVFFI4195BZAM/
mv -n	igvf_010/nova1/Sublibrary_11_S10_L001_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B11_D_nova_N1_L001_R2.fastq.gz		#92f7a3f1206769f07f717f5a6955f5b6	https://api.data.igvf.org/sequence-files/IGVFFI5517FLDK/
mv -n	igvf_010/nova1/Sublibrary_11_S10_L002_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B11_D_nova_N1_L002_I1.fastq.gz		#2cabf9f0b51d8b6329f32aabd8d7dd63
mv -n	igvf_010/nova1/Sublibrary_11_S10_L002_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B11_D_nova_N1_L002_R1.fastq.gz		#b819ebdebaa99fb1fb2bcf9eeeaeb501	https://api.data.igvf.org/sequence-files/IGVFFI0058ARVM/
mv -n	igvf_010/nova1/Sublibrary_11_S10_L002_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B11_D_nova_N1_L002_R2.fastq.gz		#bd165197f49af1eede80110b93da53a6	https://api.data.igvf.org/sequence-files/IGVFFI6451FHXP/
mv -n	igvf_010/nova1/Sublibrary_11_S10_L003_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B11_D_nova_N1_L003_I1.fastq.gz		#b58858300b74fc16a755eb09d1dbed72
mv -n	igvf_010/nova1/Sublibrary_11_S10_L003_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B11_D_nova_N1_L003_R1.fastq.gz		#f06e58c0ccbe6c4e2b769503439f7bb8	https://api.data.igvf.org/sequence-files/IGVFFI8775WMVN/
mv -n	igvf_010/nova1/Sublibrary_11_S10_L003_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B11_D_nova_N1_L003_R2.fastq.gz		#1ef32542945f20455e00951361a28ede	https://api.data.igvf.org/sequence-files/IGVFFI8527DTXT/
mv -n	igvf_010/nova1/Sublibrary_11_S10_L004_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B11_D_nova_N1_L004_I1.fastq.gz		#1adc3952194efd20dc108fa145f61de1
mv -n	igvf_010/nova1/Sublibrary_11_S10_L004_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B11_D_nova_N1_L004_R1.fastq.gz		#0c8f8950a2ffa807af09eec2f8d437ff	https://api.data.igvf.org/sequence-files/IGVFFI1386VVMM/
mv -n	igvf_010/nova1/Sublibrary_11_S10_L004_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B11_D_nova_N1_L004_R2.fastq.gz		#c9d94a5497b83fd334d1cd841b540824	https://api.data.igvf.org/sequence-files/IGVFFI6200XPVL/
mv -n	igvf_010/nova1/Sublibrary_12_S11_L001_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B12_D_nova_N1_L001_I1.fastq.gz		#b5a444198bc3f1b86be62df5e7caccb3
mv -n	igvf_010/nova1/Sublibrary_12_S11_L001_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B12_D_nova_N1_L001_R1.fastq.gz		#0b6e157993571310c04b3243668f10dc	https://api.data.igvf.org/sequence-files/IGVFFI6862XLTF/
mv -n	igvf_010/nova1/Sublibrary_12_S11_L001_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B12_D_nova_N1_L001_R2.fastq.gz		#5f627ecde8a3a4bbaeff3719724d510a	https://api.data.igvf.org/sequence-files/IGVFFI0377CFUX/
mv -n	igvf_010/nova1/Sublibrary_12_S11_L002_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B12_D_nova_N1_L002_I1.fastq.gz		#c9341853212185148fdf3aba70d4a3e8
mv -n	igvf_010/nova1/Sublibrary_12_S11_L002_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B12_D_nova_N1_L002_R1.fastq.gz		#58bebd5991dd2aa3a16811513aae4261	https://api.data.igvf.org/sequence-files/IGVFFI1997JTFH/
mv -n	igvf_010/nova1/Sublibrary_12_S11_L002_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B12_D_nova_N1_L002_R2.fastq.gz		#d7c7ca79ad1f39b2ad1d43e90f0d4ce7	https://api.data.igvf.org/sequence-files/IGVFFI6567ZMHQ/
mv -n	igvf_010/nova1/Sublibrary_12_S11_L003_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B12_D_nova_N1_L003_I1.fastq.gz		#6b407fb660302e9ce7ee6c84fe45d9e7
mv -n	igvf_010/nova1/Sublibrary_12_S11_L003_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B12_D_nova_N1_L003_R1.fastq.gz		#d5e4e8ded9e81440350ef51c0b8d3d96	https://api.data.igvf.org/sequence-files/IGVFFI6244LPAA/
mv -n	igvf_010/nova1/Sublibrary_12_S11_L003_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B12_D_nova_N1_L003_R2.fastq.gz		#12d1f281c104fa9ef9d46c4abde7a1e7	https://api.data.igvf.org/sequence-files/IGVFFI9031AWGU/
mv -n	igvf_010/nova1/Sublibrary_12_S11_L004_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B12_D_nova_N1_L004_I1.fastq.gz		#dd0b55bf1c092e71450304d9f3a3c5d0
mv -n	igvf_010/nova1/Sublibrary_12_S11_L004_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B12_D_nova_N1_L004_R1.fastq.gz		#f1bb59542becd2a09590a97a273a71ea	https://api.data.igvf.org/sequence-files/IGVFFI3601ZPFB/
mv -n	igvf_010/nova1/Sublibrary_12_S11_L004_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B12_D_nova_N1_L004_R2.fastq.gz		#eb5176fc213d4fedb8b7604db36ba396	https://api.data.igvf.org/sequence-files/IGVFFI4634MHKR/
mv -n	igvf_010/nova1/Sublibrary_13_S12_L001_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B13_D_nova_N1_L001_I1.fastq.gz		#dac56b26fdf375812ae625b3031452d7
mv -n	igvf_010/nova1/Sublibrary_13_S12_L001_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B13_D_nova_N1_L001_R1.fastq.gz		#58c8da7bf2587eac8184e051c3a57fbe	https://api.data.igvf.org/sequence-files/IGVFFI4279EBWR/
mv -n	igvf_010/nova1/Sublibrary_13_S12_L001_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B13_D_nova_N1_L001_R2.fastq.gz		#7e25ccc8a35a9bcf99d0396161391f0e	https://api.data.igvf.org/sequence-files/IGVFFI1654RAJZ/
mv -n	igvf_010/nova1/Sublibrary_13_S12_L002_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B13_D_nova_N1_L002_I1.fastq.gz		#1b637665496d74ae26d6320774667cd5
mv -n	igvf_010/nova1/Sublibrary_13_S12_L002_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B13_D_nova_N1_L002_R1.fastq.gz		#54cdeb7ec9c21ab0b95948edb2f63466	https://api.data.igvf.org/sequence-files/IGVFFI1065EMPW/
mv -n	igvf_010/nova1/Sublibrary_13_S12_L002_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B13_D_nova_N1_L002_R2.fastq.gz		#61776c215a7ed8f5134d5182046e3235	https://api.data.igvf.org/sequence-files/IGVFFI9712RDNE/
mv -n	igvf_010/nova1/Sublibrary_13_S12_L003_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B13_D_nova_N1_L003_I1.fastq.gz		#4890cd1ab5b840243ed259937c9c8f97
mv -n	igvf_010/nova1/Sublibrary_13_S12_L003_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B13_D_nova_N1_L003_R1.fastq.gz		#c24eb8c1ccb6a17f068ba26cecf06399	https://api.data.igvf.org/sequence-files/IGVFFI4632FUDJ/
mv -n	igvf_010/nova1/Sublibrary_13_S12_L003_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B13_D_nova_N1_L003_R2.fastq.gz		#f276027b214f4fbf85a789e37b6e80e4	https://api.data.igvf.org/sequence-files/IGVFFI0689IXAH/
mv -n	igvf_010/nova1/Sublibrary_13_S12_L004_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B13_D_nova_N1_L004_I1.fastq.gz		#2c196190cee96b91bbd75875673dc69b
mv -n	igvf_010/nova1/Sublibrary_13_S12_L004_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B13_D_nova_N1_L004_R1.fastq.gz		#2eb795f5c91f96dcbf48fa19f112a691	https://api.data.igvf.org/sequence-files/IGVFFI2960NFVJ/
mv -n	igvf_010/nova1/Sublibrary_13_S12_L004_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B13_D_nova_N1_L004_R2.fastq.gz		#c5298c3074bf75123d83c79894628544	https://api.data.igvf.org/sequence-files/IGVFFI6195KBDV/
mv -n	igvf_010/nova1/Sublibrary_14_S13_L001_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B14_D_nova_N1_L001_I1.fastq.gz		#bfcb117c9e6efebc28a7a7306ad6164a
mv -n	igvf_010/nova1/Sublibrary_14_S13_L001_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B14_D_nova_N1_L001_R1.fastq.gz		#b2a7a5b40bc01f20b25e4a2fd919a496	https://api.data.igvf.org/sequence-files/IGVFFI5879JFTG/
mv -n	igvf_010/nova1/Sublibrary_14_S13_L001_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B14_D_nova_N1_L001_R2.fastq.gz		#a0a808c2f17b508db3840af0ded9698a	https://api.data.igvf.org/sequence-files/IGVFFI1948QWVK/
mv -n	igvf_010/nova1/Sublibrary_14_S13_L002_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B14_D_nova_N1_L002_I1.fastq.gz		#a0a974ee918bd2157b4d2403ed5e2040
mv -n	igvf_010/nova1/Sublibrary_14_S13_L002_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B14_D_nova_N1_L002_R1.fastq.gz		#cf81bcaa3846ce7314cade12aa18ca3d	https://api.data.igvf.org/sequence-files/IGVFFI6571UQLZ/
mv -n	igvf_010/nova1/Sublibrary_14_S13_L002_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B14_D_nova_N1_L002_R2.fastq.gz		#8411e1810db124da6f20790346ea021f	https://api.data.igvf.org/sequence-files/IGVFFI9358TCPY/
mv -n	igvf_010/nova1/Sublibrary_14_S13_L003_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B14_D_nova_N1_L003_I1.fastq.gz		#58048d8aadaed6d3bb842dac17a4ffe5
mv -n	igvf_010/nova1/Sublibrary_14_S13_L003_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B14_D_nova_N1_L003_R1.fastq.gz		#9728172f2bdcbb309d4cef28e7763fd1	https://api.data.igvf.org/sequence-files/IGVFFI5289OTTW/
mv -n	igvf_010/nova1/Sublibrary_14_S13_L003_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B14_D_nova_N1_L003_R2.fastq.gz		#3a7cd48b943f95138b5d62143c6842f2	https://api.data.igvf.org/sequence-files/IGVFFI5813CSAB/
mv -n	igvf_010/nova1/Sublibrary_14_S13_L004_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B14_D_nova_N1_L004_I1.fastq.gz		#fbc479400381f0dedf7db45694540d80
mv -n	igvf_010/nova1/Sublibrary_14_S13_L004_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B14_D_nova_N1_L004_R1.fastq.gz		#c48e559115d9bf0dadfb12f631dce3f3	https://api.data.igvf.org/sequence-files/IGVFFI8753YPYT/
mv -n	igvf_010/nova1/Sublibrary_14_S13_L004_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B14_D_nova_N1_L004_R2.fastq.gz		#7d7f00e3985245cc4b1f0aa775a5e10b	https://api.data.igvf.org/sequence-files/IGVFFI4302TBGM/
mv -n	igvf_010/nova1/Sublibrary_15_S14_L001_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B15_D_nova_N1_L001_I1.fastq.gz		#934e0a83d878db98a3c40caa8f44b801
mv -n	igvf_010/nova1/Sublibrary_15_S14_L001_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B15_D_nova_N1_L001_R1.fastq.gz		#4c27657108e623ea71fca19e877f9fb2	https://api.data.igvf.org/sequence-files/IGVFFI2061MHLW/
mv -n	igvf_010/nova1/Sublibrary_15_S14_L001_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B15_D_nova_N1_L001_R2.fastq.gz		#b262b374487a3e2ea699bf0ff376a4ee	https://api.data.igvf.org/sequence-files/IGVFFI5190KSWS/
mv -n	igvf_010/nova1/Sublibrary_15_S14_L002_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B15_D_nova_N1_L002_I1.fastq.gz		#346546e7c12dcd65a192ada53bead667
mv -n	igvf_010/nova1/Sublibrary_15_S14_L002_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B15_D_nova_N1_L002_R1.fastq.gz		#eab8b9b707af5e1486b96b410f0bc771	https://api.data.igvf.org/sequence-files/IGVFFI0939JEJI/
mv -n	igvf_010/nova1/Sublibrary_15_S14_L002_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B15_D_nova_N1_L002_R2.fastq.gz		#e0a93c214037c192779fb4a5d5a77f53	https://api.data.igvf.org/sequence-files/IGVFFI2262GARY/
mv -n	igvf_010/nova1/Sublibrary_15_S14_L003_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B15_D_nova_N1_L003_I1.fastq.gz		#e53790858ce004382ef1c66865f3bb3b
mv -n	igvf_010/nova1/Sublibrary_15_S14_L003_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B15_D_nova_N1_L003_R1.fastq.gz		#a374ca0d6e96a4a0bf058a67e1ce9fa0	https://api.data.igvf.org/sequence-files/IGVFFI9485UNYH/
mv -n	igvf_010/nova1/Sublibrary_15_S14_L003_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B15_D_nova_N1_L003_R2.fastq.gz		#dfdcb595796d21bb3f08f01320726713	https://api.data.igvf.org/sequence-files/IGVFFI4440VAIU/
mv -n	igvf_010/nova1/Sublibrary_15_S14_L004_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B15_D_nova_N1_L004_I1.fastq.gz		#c5a1c3b58f211c6d57c307d33dda70da
mv -n	igvf_010/nova1/Sublibrary_15_S14_L004_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B15_D_nova_N1_L004_R1.fastq.gz		#a9baf99b0b88101dac6f70bb9fdf300c	https://api.data.igvf.org/sequence-files/IGVFFI7584PRYR/
mv -n	igvf_010/nova1/Sublibrary_15_S14_L004_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B15_D_nova_N1_L004_R2.fastq.gz		#ec959eb803faa23122a01678e60c5b58	https://api.data.igvf.org/sequence-files/IGVFFI3300QTVQ/
mv -n	igvf_010/nova1/Sublibrary_16_S15_L001_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B16_D_nova_N1_L001_I1.fastq.gz		#26a7e10f4c3838a9986ef56729af0c3c
mv -n	igvf_010/nova1/Sublibrary_16_S15_L001_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B16_D_nova_N1_L001_R1.fastq.gz		#43b292cab9d1fe333e6d3397b32bc8c1	https://api.data.igvf.org/sequence-files/IGVFFI3980HFTD/
mv -n	igvf_010/nova1/Sublibrary_16_S15_L001_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B16_D_nova_N1_L001_R2.fastq.gz		#69e9b19492ef20e301497721c27c08d7	https://api.data.igvf.org/sequence-files/IGVFFI5862IXNW/
mv -n	igvf_010/nova1/Sublibrary_16_S15_L002_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B16_D_nova_N1_L002_I1.fastq.gz		#cf452813a308d5405f26c74b6018c05e
mv -n	igvf_010/nova1/Sublibrary_16_S15_L002_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B16_D_nova_N1_L002_R1.fastq.gz		#6bdb113ab268f32438a1dfc20a2b6d80	https://api.data.igvf.org/sequence-files/IGVFFI1461KJEB/
mv -n	igvf_010/nova1/Sublibrary_16_S15_L002_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B16_D_nova_N1_L002_R2.fastq.gz		#c1412e9e390e58dabc77ed029c3b56a2	https://api.data.igvf.org/sequence-files/IGVFFI9020MSYE/
mv -n	igvf_010/nova1/Sublibrary_16_S15_L003_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B16_D_nova_N1_L003_I1.fastq.gz		#895eab3b0f28d769dc081b3035c787af
mv -n	igvf_010/nova1/Sublibrary_16_S15_L003_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B16_D_nova_N1_L003_R1.fastq.gz		#36c37d77420670d18e4df2aea5aa84a6	https://api.data.igvf.org/sequence-files/IGVFFI6077TAFK/
mv -n	igvf_010/nova1/Sublibrary_16_S15_L003_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B16_D_nova_N1_L003_R2.fastq.gz		#21f53d916548998ca19f41cf215e88b4	https://api.data.igvf.org/sequence-files/IGVFFI6299LPOW/
mv -n	igvf_010/nova1/Sublibrary_16_S15_L004_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B16_D_nova_N1_L004_I1.fastq.gz		#a7342ad686e39208895d9ba3448c8fd7
mv -n	igvf_010/nova1/Sublibrary_16_S15_L004_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B16_D_nova_N1_L004_R1.fastq.gz		#5abd49e91b134b58b452f98324fad34d	https://api.data.igvf.org/sequence-files/IGVFFI6101MABS/
mv -n	igvf_010/nova1/Sublibrary_16_S15_L004_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B16_D_nova_N1_L004_R2.fastq.gz		#5ae07ef3f73041bd5da5dec338f5a0eb	https://api.data.igvf.org/sequence-files/IGVFFI6300NDVK/
mv -n	igvf_010/nova1/Sublibrary_2_S1_L001_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B02_D_nova_N1_L001_I1.fastq.gz		#28651808e9ed8d51e5c252ebcfdb22f1
mv -n	igvf_010/nova1/Sublibrary_2_S1_L001_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B02_D_nova_N1_L001_R1.fastq.gz		#228e4a4c2e2849aa0c6d9f270e4a2c3a	https://api.data.igvf.org/sequence-files/IGVFFI8036ADLG/
mv -n	igvf_010/nova1/Sublibrary_2_S1_L001_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B02_D_nova_N1_L001_R2.fastq.gz		#d6843262f1db8f71b45ccc95e929102d	https://api.data.igvf.org/sequence-files/IGVFFI8608VYRJ/
mv -n	igvf_010/nova1/Sublibrary_2_S1_L002_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B02_D_nova_N1_L002_I1.fastq.gz		#4608e04ff666601294916be46ecfe96c
mv -n	igvf_010/nova1/Sublibrary_2_S1_L002_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B02_D_nova_N1_L002_R1.fastq.gz		#4932493de7069f02442ec4819460acf9	https://api.data.igvf.org/sequence-files/IGVFFI2638AWAU/
mv -n	igvf_010/nova1/Sublibrary_2_S1_L002_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B02_D_nova_N1_L002_R2.fastq.gz		#8653fb4a362686f3b95d325648efa787	https://api.data.igvf.org/sequence-files/IGVFFI6743VKTD/
mv -n	igvf_010/nova1/Sublibrary_2_S1_L003_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B02_D_nova_N1_L003_I1.fastq.gz		#061242f2dfa96cbafb9003e5dd4e9ea0
mv -n	igvf_010/nova1/Sublibrary_2_S1_L003_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B02_D_nova_N1_L003_R1.fastq.gz		#4c165b87699f8ed5c617523267dc45a5	https://api.data.igvf.org/sequence-files/IGVFFI8955VRHU/
mv -n	igvf_010/nova1/Sublibrary_2_S1_L003_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B02_D_nova_N1_L003_R2.fastq.gz		#fe4649487de761f5971c423edb57c8e8	https://api.data.igvf.org/sequence-files/IGVFFI5845KZHC/
mv -n	igvf_010/nova1/Sublibrary_2_S1_L004_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B02_D_nova_N1_L004_I1.fastq.gz		#5279fb593cb7b11c0fdd8f0e18e83814
mv -n	igvf_010/nova1/Sublibrary_2_S1_L004_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B02_D_nova_N1_L004_R1.fastq.gz		#e6150e36b83da2bde2d61512fe73f3fb	https://api.data.igvf.org/sequence-files/IGVFFI1118SRPZ/
mv -n	igvf_010/nova1/Sublibrary_2_S1_L004_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B02_D_nova_N1_L004_R2.fastq.gz		#9c08374dc044b2643359d85932f345e7	https://api.data.igvf.org/sequence-files/IGVFFI2775QXAW/
mv -n	igvf_010/nova1/Sublibrary_3_S2_L001_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B03_D_nova_N1_L001_I1.fastq.gz		#bcfec3df5a1990beea32d39394348689
mv -n	igvf_010/nova1/Sublibrary_3_S2_L001_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B03_D_nova_N1_L001_R1.fastq.gz		#bd826669af0d8625594bea0b6b11e324	https://api.data.igvf.org/sequence-files/IGVFFI4969JUAP/
mv -n	igvf_010/nova1/Sublibrary_3_S2_L001_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B03_D_nova_N1_L001_R2.fastq.gz		#ce24fa7f49e766d06bc8ef405fd45fb6	https://api.data.igvf.org/sequence-files/IGVFFI2158LYKO/
mv -n	igvf_010/nova1/Sublibrary_3_S2_L002_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B03_D_nova_N1_L002_I1.fastq.gz		#de17016e9fc306efa92f7b535d352618
mv -n	igvf_010/nova1/Sublibrary_3_S2_L002_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B03_D_nova_N1_L002_R1.fastq.gz		#ec7b711a1482c47df666837fb0e16a7e	https://api.data.igvf.org/sequence-files/IGVFFI6816UYJR/
mv -n	igvf_010/nova1/Sublibrary_3_S2_L002_R2_001.fastq.gz	igvf_010/nova1/igvf_010_B03_D_nova_N1_L002_R2.fastq.gz		#f4ab4118695c4a72b861dc5e34d7e6df	https://api.data.igvf.org/sequence-files/IGVFFI5613PHRT/
mv -n	igvf_010/nova1/Sublibrary_3_S2_L003_I1_001.fastq.gz	igvf_010/nova1/igvf_010_B03_D_nova_N1_L003_I1.fastq.gz		#9558dd32450b69880bba9eae0899b014
mv -n	igvf_010/nova1/Sublibrary_3_S2_L003_R1_001.fastq.gz	igvf_010/nova1/igvf_010_B03_D_nova_N1_L003_R1.fastq.gz		#c6bafc53cf0ef6c14b80d247995bc310	https://api.data.igvf.org/sequence-files/IGVFFI6941NTCB/

mv -n	igvf_010/nova2/Sublibrary_9_S8_L003_R2_001.fastq.gz	igvf_010/nova2/igvf_010_B09_D_nova_N2_L003_R2.fastq.gz		#aabf438de20c0591423159e9145f3ed8	https://api.data.igvf.org/sequence-files/IGVFFI3567GIOG/
mv -n	igvf_010/nova2/Sublibrary_9_S8_L004_I1_001.fastq.gz	igvf_010/nova2/igvf_010_B09_D_nova_N2_L004_I1.fastq.gz		#56d1e55245bd351403940c23f81b5d20
mv -n	igvf_010/nova2/Sublibrary_9_S8_L004_R1_001.fastq.gz	igvf_010/nova2/igvf_010_B09_D_nova_N2_L004_R1.fastq.gz		#bde6062e6dc17d346d1c276f93383de9	https://api.data.igvf.org/sequence-files/IGVFFI6447ZISS/
mv -n	igvf_010/nova2/Sublibrary_9_S8_L004_R2_001.fastq.gz	igvf_010/nova2/igvf_010_B09_D_nova_N2_L004_R2.fastq.gz		#09f27cf379d08d9d98ac96b6e4d5cb46	https://api.data.igvf.org/sequence-files/IGVFFI6280LIFM/
mv -n	igvf_011/nextseq/011_67M_R1.fastq.gz	igvf_011/nextseq/igvf_011_B14_D_next_N1_R1.fastq.gz		#1a42061f3fbac12749718ba52148a8b7	https://api.data.igvf.org/sequence-files/IGVFFI0091JSEG/
mv -n	igvf_011/nextseq/011_67M_R2.fastq.gz	igvf_011/nextseq/igvf_011_B14_D_next_N1_R2.fastq.gz		#72f38f0ecd8da1c460afa0287134d939	https://api.data.igvf.org/sequence-files/IGVFFI3943BRJL/
mv -n	igvf_011/nextseq/011_67O_R1.fastq.gz	igvf_011/nextseq/igvf_011_B16_D_next_N1_R1.fastq.gz		#b9cf24739bcdfe40dd19d57e19a9b9f0	https://api.data.igvf.org/sequence-files/IGVFFI7326JANR/
mv -n	igvf_011/nextseq/011_67O_R2.fastq.gz	igvf_011/nextseq/igvf_011_B16_D_next_N1_R2.fastq.gz		#5dcdea813ff44b132576e701c4c9ca28	https://api.data.igvf.org/sequence-files/IGVFFI3829CWJR/
mv -n	igvf_011/nextseq2/011_13A_R1.fastq.gz	igvf_011/nextseq2/igvf_011_B08_E_next_N2_R1.fastq.gz		#70ba7afe5665a0f95ff54bbd80423f21	https://api.data.igvf.org/sequence-files/IGVFFI0033UEAZ/
mv -n	igvf_011/nextseq2/011_13A_R2.fastq.gz	igvf_011/nextseq2/igvf_011_B08_E_next_N2_R2.fastq.gz		#c3fcd90107dccf23955b39d32ee1a29d	https://api.data.igvf.org/sequence-files/IGVFFI8010UCBF/
mv -n	igvf_011/nova1/Sublibrary_10_S9_L001_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B10_D_nova_N1_L001_I1.fastq.gz		#0ac2dcde28a9871256956d91bd24cf27
mv -n	igvf_011/nova1/Sublibrary_10_S9_L001_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B10_D_nova_N1_L001_R1.fastq.gz		#a04cf96e5ed200463c5cfccd49f33f43	https://api.data.igvf.org/sequence-files/IGVFFI5637EJLC/
mv -n	igvf_011/nova1/Sublibrary_10_S9_L001_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B10_D_nova_N1_L001_R2.fastq.gz		#eabdaae981b6fb34078602b4b98b3dd6	https://api.data.igvf.org/sequence-files/IGVFFI7546YGNX/
mv -n	igvf_011/nova1/Sublibrary_10_S9_L002_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B10_D_nova_N1_L002_I1.fastq.gz		#d877f0b4343dbbc3d6f82ba71555f200
mv -n	igvf_011/nova1/Sublibrary_10_S9_L002_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B10_D_nova_N1_L002_R1.fastq.gz		#84f0813f65e40033a9bceeecd5a882ce	https://api.data.igvf.org/sequence-files/IGVFFI8314ZZME/
mv -n	igvf_011/nova1/Sublibrary_10_S9_L002_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B10_D_nova_N1_L002_R2.fastq.gz		#5b3b8a8c0481279d6a8e68f0651795bb	https://api.data.igvf.org/sequence-files/IGVFFI1030NZLJ/
mv -n	igvf_011/nova1/Sublibrary_10_S9_L003_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B10_D_nova_N1_L003_I1.fastq.gz		#338e7c80794d7ffd5a7fc232434fd04c
mv -n	igvf_011/nova1/Sublibrary_10_S9_L003_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B10_D_nova_N1_L003_R1.fastq.gz		#d1cc3d85525c3f2169b71427f0430432	https://api.data.igvf.org/sequence-files/IGVFFI9092KHWQ/
mv -n	igvf_011/nova1/Sublibrary_10_S9_L003_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B10_D_nova_N1_L003_R2.fastq.gz		#f5f762ce0148dd9f433512a4c300d52e	https://api.data.igvf.org/sequence-files/IGVFFI9683VYNI/
mv -n	igvf_011/nova1/Sublibrary_10_S9_L004_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B10_D_nova_N1_L004_I1.fastq.gz		#551dc2bab8069e1bc01f698706955568
mv -n	igvf_011/nova1/Sublibrary_10_S9_L004_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B10_D_nova_N1_L004_R1.fastq.gz		#59bed2f6eb2dcd8313d7a3086ddea4b0	https://api.data.igvf.org/sequence-files/IGVFFI2152NJLF/
mv -n	igvf_011/nova1/Sublibrary_10_S9_L004_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B10_D_nova_N1_L004_R2.fastq.gz		#5f3fe0d079ce2609df5aa4edc09eafd9	https://api.data.igvf.org/sequence-files/IGVFFI6008OCER/
mv -n	igvf_011/nova1/Sublibrary_11_S10_L001_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B11_D_nova_N1_L001_I1.fastq.gz		#708af70b02a118eab94bff40041dafac
mv -n	igvf_011/nova1/Sublibrary_11_S10_L001_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B11_D_nova_N1_L001_R1.fastq.gz		#299075428b40e31871514f72016b0b3d	https://api.data.igvf.org/sequence-files/IGVFFI8998MFOM/
mv -n	igvf_011/nova1/Sublibrary_11_S10_L001_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B11_D_nova_N1_L001_R2.fastq.gz		#16d7d0667fdbfb7d07db258d3f3b98d5	https://api.data.igvf.org/sequence-files/IGVFFI0425YMUX/
mv -n	igvf_011/nova1/Sublibrary_11_S10_L002_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B11_D_nova_N1_L002_I1.fastq.gz		#be4f15fe10c188ee09fb61d9175e0f6f
mv -n	igvf_011/nova1/Sublibrary_11_S10_L002_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B11_D_nova_N1_L002_R1.fastq.gz		#788559ddf0e7490f897ae1cb22274ef0	https://api.data.igvf.org/sequence-files/IGVFFI4825GTDU/
mv -n	igvf_011/nova1/Sublibrary_11_S10_L002_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B11_D_nova_N1_L002_R2.fastq.gz		#af28b10d279baf1bb46e163bf319945a	https://api.data.igvf.org/sequence-files/IGVFFI9688OBJX/
mv -n	igvf_011/nova1/Sublibrary_11_S10_L003_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B11_D_nova_N1_L003_I1.fastq.gz		#5c6fbf9e0937b7e1ace7124ab4861c21
mv -n	igvf_011/nova1/Sublibrary_11_S10_L003_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B11_D_nova_N1_L003_R1.fastq.gz		#af5e3f14c0c143abd0ace97a481ba17d	https://api.data.igvf.org/sequence-files/IGVFFI4469KAFG/
mv -n	igvf_011/nova1/Sublibrary_11_S10_L003_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B11_D_nova_N1_L003_R2.fastq.gz		#bc45488923d6a65b87cab8f30505549d	https://api.data.igvf.org/sequence-files/IGVFFI3100HHUI/
mv -n	igvf_011/nova1/Sublibrary_11_S10_L004_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B11_D_nova_N1_L004_I1.fastq.gz		#945aba3cb7de9b205e87a57f56ddf068
mv -n	igvf_011/nova1/Sublibrary_11_S10_L004_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B11_D_nova_N1_L004_R1.fastq.gz		#6aeb5bbd1ccfc28c053b3a3bd30d5238	https://api.data.igvf.org/sequence-files/IGVFFI0723SSXJ/
mv -n	igvf_011/nova1/Sublibrary_11_S10_L004_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B11_D_nova_N1_L004_R2.fastq.gz		#76cf8c3eb3f6000123f095a06ad92728	https://api.data.igvf.org/sequence-files/IGVFFI7150FRVL/
mv -n	igvf_011/nova1/Sublibrary_12_S11_L001_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B12_D_nova_N1_L001_I1.fastq.gz		#0eb1ccb0d2e91f9990aa5d3649048668
mv -n	igvf_011/nova1/Sublibrary_12_S11_L001_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B12_D_nova_N1_L001_R1.fastq.gz		#138255adec0e5858487f6af57787854b	https://api.data.igvf.org/sequence-files/IGVFFI1601QWHS/
mv -n	igvf_011/nova1/Sublibrary_12_S11_L001_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B12_D_nova_N1_L001_R2.fastq.gz		#596b7ec44328ed37b88679dd9aad2968	https://api.data.igvf.org/sequence-files/IGVFFI1533INOX/
mv -n	igvf_011/nova1/Sublibrary_12_S11_L002_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B12_D_nova_N1_L002_I1.fastq.gz		#b34e88caa5ddc06b8b0f06b150ec68a4
mv -n	igvf_011/nova1/Sublibrary_12_S11_L002_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B12_D_nova_N1_L002_R1.fastq.gz		#bde815cf4ff1ee2a35defb4ae43713a5	https://api.data.igvf.org/sequence-files/IGVFFI6617JDXR/
mv -n	igvf_011/nova1/Sublibrary_12_S11_L002_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B12_D_nova_N1_L002_R2.fastq.gz		#96c674f5d7a292f9db315bbe6912e41a	https://api.data.igvf.org/sequence-files/IGVFFI1616CSXJ/
mv -n	igvf_011/nova1/Sublibrary_12_S11_L003_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B12_D_nova_N1_L003_I1.fastq.gz		#476f45bb59eb2ddc5e32c25fd3501ebc
mv -n	igvf_011/nova1/Sublibrary_12_S11_L003_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B12_D_nova_N1_L003_R1.fastq.gz		#029e109259e2f8d65ec8f334f58c099b	https://api.data.igvf.org/sequence-files/IGVFFI8891MCOD/
mv -n	igvf_011/nova1/Sublibrary_12_S11_L003_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B12_D_nova_N1_L003_R2.fastq.gz		#cb10646441b8d821d991ec74281a9925	https://api.data.igvf.org/sequence-files/IGVFFI2703KGPI/
mv -n	igvf_011/nova1/Sublibrary_12_S11_L004_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B12_D_nova_N1_L004_I1.fastq.gz		#c138d0f3cb3ae094c97feb031e6f56d9
mv -n	igvf_011/nova1/Sublibrary_12_S11_L004_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B12_D_nova_N1_L004_R1.fastq.gz		#0af649c1d4c9d5dee3644d544fe93c16	https://api.data.igvf.org/sequence-files/IGVFFI1579TQHE/
mv -n	igvf_011/nova1/Sublibrary_12_S11_L004_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B12_D_nova_N1_L004_R2.fastq.gz		#b8933ba4fd0b520ebee902cfc3d4f7ab	https://api.data.igvf.org/sequence-files/IGVFFI3962IUTR/
mv -n	igvf_011/nova1/Sublibrary_13_S12_L001_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B13_D_nova_N1_L001_I1.fastq.gz		#26e38701157419a3b76e08142de3ddb2
mv -n	igvf_011/nova1/Sublibrary_13_S12_L001_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B13_D_nova_N1_L001_R1.fastq.gz		#6f90f52a757132c56a63e20628b2edbb	https://api.data.igvf.org/sequence-files/IGVFFI8518OSVG/
mv -n	igvf_011/nova1/Sublibrary_13_S12_L001_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B13_D_nova_N1_L001_R2.fastq.gz		#dc7dd133ac733f534213deffb7f2988b	https://api.data.igvf.org/sequence-files/IGVFFI2498DIMG/
mv -n	igvf_011/nova1/Sublibrary_13_S12_L002_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B13_D_nova_N1_L002_I1.fastq.gz		#368485d76c2dc2e265b60d9decbb442c
mv -n	igvf_011/nova1/Sublibrary_13_S12_L002_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B13_D_nova_N1_L002_R1.fastq.gz		#c8ec37f7d66e007f17faf50aa1a5db81	https://api.data.igvf.org/sequence-files/IGVFFI7621QDGG/
mv -n	igvf_011/nova1/Sublibrary_13_S12_L002_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B13_D_nova_N1_L002_R2.fastq.gz		#748ac34d22b4e7838891755c75ebf76f	https://api.data.igvf.org/sequence-files/IGVFFI7069BXMM/
mv -n	igvf_011/nova1/Sublibrary_13_S12_L003_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B13_D_nova_N1_L003_I1.fastq.gz		#0be8523686bdd53ca5f9ef543eab8868
mv -n	igvf_011/nova1/Sublibrary_13_S12_L003_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B13_D_nova_N1_L003_R1.fastq.gz		#e1e39557ac37d4a490166bd6152fb269	https://api.data.igvf.org/sequence-files/IGVFFI7496LHOT/
mv -n	igvf_011/nova1/Sublibrary_13_S12_L003_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B13_D_nova_N1_L003_R2.fastq.gz		#29f81a65f9fed5c9d837bd664387fd7c	https://api.data.igvf.org/sequence-files/IGVFFI0843EINI/
mv -n	igvf_011/nova1/Sublibrary_13_S12_L004_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B13_D_nova_N1_L004_I1.fastq.gz		#0160502921418d5d46a57d3cad9b2fed
mv -n	igvf_011/nova1/Sublibrary_13_S12_L004_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B13_D_nova_N1_L004_R1.fastq.gz		#7e8edd195e5e15df328ad295c1b4fc43	https://api.data.igvf.org/sequence-files/IGVFFI3888YAVP/
mv -n	igvf_011/nova1/Sublibrary_13_S12_L004_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B13_D_nova_N1_L004_R2.fastq.gz		#c8f2f4cc39612a664b602d9bb0bcaf68	https://api.data.igvf.org/sequence-files/IGVFFI2641RZXI/

mv -n	igvf_011/nova1/Sublibrary_14_S13_L001_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B14_D_nova_N1_L001_I1.fastq.gz		#056f159e153bd0d8ec019de48c11c227
mv -n	igvf_011/nova1/Sublibrary_14_S13_L001_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B14_D_nova_N1_L001_R1.fastq.gz		#7d41cbb379750bfb303cc4672a6797fc	https://api.data.igvf.org/sequence-files/IGVFFI1629IPLY/
mv -n	igvf_011/nova1/Sublibrary_14_S13_L001_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B14_D_nova_N1_L001_R2.fastq.gz		#91ae2e7dce791bdf6e6dee044271b72e	https://api.data.igvf.org/sequence-files/IGVFFI6018WMYW/
mv -n	igvf_011/nova1/Sublibrary_14_S13_L002_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B14_D_nova_N1_L002_I1.fastq.gz		#d6ab071cb0a6c08367771be854742a1f
mv -n	igvf_011/nova1/Sublibrary_14_S13_L002_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B14_D_nova_N1_L002_R1.fastq.gz		#6f0a9dd863d593d0b04ade91de7322fd	https://api.data.igvf.org/sequence-files/IGVFFI6437VRFR/
mv -n	igvf_011/nova1/Sublibrary_14_S13_L002_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B14_D_nova_N1_L002_R2.fastq.gz		#9ab77ea433bebe76916c126ee06f1169	https://api.data.igvf.org/sequence-files/IGVFFI2254WKVF/
mv -n	igvf_011/nova1/Sublibrary_14_S13_L003_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B14_D_nova_N1_L003_I1.fastq.gz		#f6901df90b10c0e82b87dfee364b6d33
mv -n	igvf_011/nova1/Sublibrary_14_S13_L003_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B14_D_nova_N1_L003_R1.fastq.gz		#bc8c14befd268d6aac2bcebe3e92f9ee	https://api.data.igvf.org/sequence-files/IGVFFI8535KQQQ/
mv -n	igvf_011/nova1/Sublibrary_14_S13_L003_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B14_D_nova_N1_L003_R2.fastq.gz		#7737c132f81af63b39569e294a911cfa	https://api.data.igvf.org/sequence-files/IGVFFI1640KJAU/
mv -n	igvf_011/nova1/Sublibrary_14_S13_L004_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B14_D_nova_N1_L004_I1.fastq.gz		#bdc0862cfd50523664d2d9884d6bb5bc
mv -n	igvf_011/nova1/Sublibrary_14_S13_L004_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B14_D_nova_N1_L004_R1.fastq.gz		#9444827c3efdafaa9588d83a4ebe9b8a	https://api.data.igvf.org/sequence-files/IGVFFI7938SSLI/
mv -n	igvf_011/nova1/Sublibrary_14_S13_L004_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B14_D_nova_N1_L004_R2.fastq.gz		#a049029cfe311adb092f6e7ee947c8f7	https://api.data.igvf.org/sequence-files/IGVFFI6009KGGV/
mv -n	igvf_011/nova1/Sublibrary_15_S14_L001_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B15_D_nova_N1_L001_I1.fastq.gz		#bb1ba4a0efaf24241fbfd7ac98513d11
mv -n	igvf_011/nova1/Sublibrary_15_S14_L001_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B15_D_nova_N1_L001_R1.fastq.gz		#85e57293ea8b273769162bc75b4401b8	https://api.data.igvf.org/sequence-files/IGVFFI1797OAWP/
mv -n	igvf_011/nova1/Sublibrary_15_S14_L001_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B15_D_nova_N1_L001_R2.fastq.gz		#89c3f79f24fe2571d4a21fc73f6f737e	https://api.data.igvf.org/sequence-files/IGVFFI5005UZHZ/
mv -n	igvf_011/nova1/Sublibrary_15_S14_L002_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B15_D_nova_N1_L002_I1.fastq.gz		#e0a06c75b75c4f0a336e20b1804a4b72
mv -n	igvf_011/nova1/Sublibrary_15_S14_L002_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B15_D_nova_N1_L002_R1.fastq.gz		#dbb0f6ab5d5b6ef13ce77b535e871cb1	https://api.data.igvf.org/sequence-files/IGVFFI2445UMFB/
mv -n	igvf_011/nova1/Sublibrary_15_S14_L002_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B15_D_nova_N1_L002_R2.fastq.gz		#76ffeed3d751ced0e507ff3b7bb2ab97	https://api.data.igvf.org/sequence-files/IGVFFI1536FIWH/
mv -n	igvf_011/nova1/Sublibrary_15_S14_L003_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B15_D_nova_N1_L003_I1.fastq.gz		#587f130eefc8005dd17a88de8f2a4f84
mv -n	igvf_011/nova1/Sublibrary_15_S14_L003_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B15_D_nova_N1_L003_R1.fastq.gz		#aa907296da0d7cf75951517f608eb451	https://api.data.igvf.org/sequence-files/IGVFFI8152TSTF/
mv -n	igvf_011/nova1/Sublibrary_15_S14_L003_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B15_D_nova_N1_L003_R2.fastq.gz		#b0be2046c8a0df8b9c19cd2a7fd98f6e	https://api.data.igvf.org/sequence-files/IGVFFI5772FXOS/
mv -n	igvf_011/nova1/Sublibrary_15_S14_L004_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B15_D_nova_N1_L004_I1.fastq.gz		#25f94bbf6d16d22e151ab4851c7349f3
mv -n	igvf_011/nova1/Sublibrary_15_S14_L004_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B15_D_nova_N1_L004_R1.fastq.gz		#ff4b53f1e1de32b9cddff23a801a39ae	https://api.data.igvf.org/sequence-files/IGVFFI6222KCUY/
mv -n	igvf_011/nova1/Sublibrary_15_S14_L004_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B15_D_nova_N1_L004_R2.fastq.gz		#a511152dc9134395b657205c4df34d8a	https://api.data.igvf.org/sequence-files/IGVFFI0701HZEC/
mv -n	igvf_011/nova1/Sublibrary_16_S15_L001_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B16_D_nova_N1_L001_I1.fastq.gz		#28d6a0e41a03bc08549fa0d3c0f52869
mv -n	igvf_011/nova1/Sublibrary_16_S15_L001_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B16_D_nova_N1_L001_R1.fastq.gz		#387f7239d054de50b88491bb81a823a6	https://api.data.igvf.org/sequence-files/IGVFFI6581DGRJ/
mv -n	igvf_011/nova1/Sublibrary_16_S15_L001_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B16_D_nova_N1_L001_R2.fastq.gz		#cdd97d559948e54689fc32cb6b3220b2	https://api.data.igvf.org/sequence-files/IGVFFI9640WWDV/
mv -n	igvf_011/nova1/Sublibrary_16_S15_L002_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B16_D_nova_N1_L002_I1.fastq.gz		#58130fe7833521d98c26b28a47d55cc1
mv -n	igvf_011/nova1/Sublibrary_16_S15_L002_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B16_D_nova_N1_L002_R1.fastq.gz		#a073f5e9ca382ac934fbf01c8fab2540	https://api.data.igvf.org/sequence-files/IGVFFI0034HSRH/
mv -n	igvf_011/nova1/Sublibrary_16_S15_L002_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B16_D_nova_N1_L002_R2.fastq.gz		#5c00f01dadaf90b5c13b00f309457d31	https://api.data.igvf.org/sequence-files/IGVFFI9597NQRB/
mv -n	igvf_011/nova1/Sublibrary_16_S15_L003_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B16_D_nova_N1_L003_I1.fastq.gz		#98a3631ce5ad53464d995368f55e19fe
mv -n	igvf_011/nova1/Sublibrary_16_S15_L003_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B16_D_nova_N1_L003_R1.fastq.gz		#4cdd4edcca49d6bec9d62a31d7886be6	https://api.data.igvf.org/sequence-files/IGVFFI1399LXZR/
mv -n	igvf_011/nova1/Sublibrary_16_S15_L003_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B16_D_nova_N1_L003_R2.fastq.gz		#db6cb3d9607b1f0c27a7ed81fef70b26	https://api.data.igvf.org/sequence-files/IGVFFI6216TKIT/
mv -n	igvf_011/nova1/Sublibrary_16_S15_L004_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B16_D_nova_N1_L004_I1.fastq.gz		#481aaf089a4a932a0009e7a333859e57
mv -n	igvf_011/nova1/Sublibrary_16_S15_L004_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B16_D_nova_N1_L004_R1.fastq.gz		#5191c61ab4a0e4c453e5a8393e0a16f2	https://api.data.igvf.org/sequence-files/IGVFFI3060TSGV/
mv -n	igvf_011/nova1/Sublibrary_16_S15_L004_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B16_D_nova_N1_L004_R2.fastq.gz		#b5fc73eda0c85480c1379df79edd8763	https://api.data.igvf.org/sequence-files/IGVFFI8666KMHM/
mv -n	igvf_011/nova1/Sublibrary_2_S1_L001_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B02_D_nova_N1_L001_I1.fastq.gz		#e9e4e78da738fa9f0f70c69c45d08f32
mv -n	igvf_011/nova1/Sublibrary_2_S1_L001_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B02_D_nova_N1_L001_R1.fastq.gz		#880da4aa0e287ccdd322e478f09a35aa	https://api.data.igvf.org/sequence-files/IGVFFI1541LXPA/
mv -n	igvf_011/nova1/Sublibrary_2_S1_L001_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B02_D_nova_N1_L001_R2.fastq.gz		#d5f3fcbda9959e5d7a03a7535ef008a0	https://api.data.igvf.org/sequence-files/IGVFFI5824JBBS/
mv -n	igvf_011/nova1/Sublibrary_2_S1_L002_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B02_D_nova_N1_L002_I1.fastq.gz		#38b84a6eee9115905b718cd53c8de209
mv -n	igvf_011/nova1/Sublibrary_2_S1_L002_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B02_D_nova_N1_L002_R1.fastq.gz		#66f2e45fd381d601c527b59db16c848c	https://api.data.igvf.org/sequence-files/IGVFFI2539OEUK/
mv -n	igvf_011/nova1/Sublibrary_2_S1_L002_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B02_D_nova_N1_L002_R2.fastq.gz		#10e3529f75783d4207dcee1257e3136b	https://api.data.igvf.org/sequence-files/IGVFFI9016JSHU/
mv -n	igvf_011/nova1/Sublibrary_2_S1_L003_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B02_D_nova_N1_L003_I1.fastq.gz		#8a182ee547dc5e2136a9f168b73a951c
mv -n	igvf_011/nova1/Sublibrary_2_S1_L003_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B02_D_nova_N1_L003_R1.fastq.gz		#25cb7fdcd9b5f7598af0b7466d566ebe	https://api.data.igvf.org/sequence-files/IGVFFI3504PITV/
mv -n	igvf_011/nova1/Sublibrary_2_S1_L003_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B02_D_nova_N1_L003_R2.fastq.gz		#d3182419a2434ed631b413519ac73e78	https://api.data.igvf.org/sequence-files/IGVFFI7486PFWA/
mv -n	igvf_011/nova1/Sublibrary_2_S1_L004_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B02_D_nova_N1_L004_I1.fastq.gz		#6b42e3786c1d25481c64feff93536452
mv -n	igvf_011/nova1/Sublibrary_2_S1_L004_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B02_D_nova_N1_L004_R1.fastq.gz		#b37bac26ac7fd6a3bd4750414e9dee16	https://api.data.igvf.org/sequence-files/IGVFFI8562JFTO/
mv -n	igvf_011/nova1/Sublibrary_2_S1_L004_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B02_D_nova_N1_L004_R2.fastq.gz		#04b02af6376e395fe6003cae65689d31	https://api.data.igvf.org/sequence-files/IGVFFI4529YJFW/
mv -n	igvf_011/nova1/Sublibrary_3_S2_L001_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B03_D_nova_N1_L001_I1.fastq.gz		#2fa6248e6e8b29c0a6f990eabe3ff35f
mv -n	igvf_011/nova1/Sublibrary_3_S2_L001_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B03_D_nova_N1_L001_R1.fastq.gz		#245ae6ecaf6cf7bdf9bbce386c92b6be	https://api.data.igvf.org/sequence-files/IGVFFI5036OXDW/
mv -n	igvf_011/nova1/Sublibrary_3_S2_L001_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B03_D_nova_N1_L001_R2.fastq.gz		#030164967bdcfe8ebd71a5f9df61dc70	https://api.data.igvf.org/sequence-files/IGVFFI6007IYPM/
mv -n	igvf_011/nova1/Sublibrary_3_S2_L002_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B03_D_nova_N1_L002_I1.fastq.gz		#0f9bc317cb6c673a79e8c34c4e5b0df3
mv -n	igvf_011/nova1/Sublibrary_3_S2_L002_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B03_D_nova_N1_L002_R1.fastq.gz		#8f9653b43dc2daf915e579d418b4a899	https://api.data.igvf.org/sequence-files/IGVFFI4832IACA/
mv -n	igvf_011/nova1/Sublibrary_3_S2_L002_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B03_D_nova_N1_L002_R2.fastq.gz		#9750785b7bb52d4e00a9a4da6e2c9880	https://api.data.igvf.org/sequence-files/IGVFFI0587NZVR/
mv -n	igvf_011/nova1/Sublibrary_3_S2_L003_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B03_D_nova_N1_L003_I1.fastq.gz		#7476870f232729653d1a55977e143a44
mv -n	igvf_011/nova1/Sublibrary_3_S2_L003_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B03_D_nova_N1_L003_R1.fastq.gz		#0579c18d6590d8eac2c6849e389238cc	https://api.data.igvf.org/sequence-files/IGVFFI3328CPUT/
mv -n	igvf_011/nova1/Sublibrary_3_S2_L003_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B03_D_nova_N1_L003_R2.fastq.gz		#2815255fadb4fd562941fb3c5a675ca9	https://api.data.igvf.org/sequence-files/IGVFFI8782NCZL/
mv -n	igvf_011/nova1/Sublibrary_3_S2_L004_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B03_D_nova_N1_L004_I1.fastq.gz		#06ed5f9296fe627d8497be2f48f99435
mv -n	igvf_011/nova1/Sublibrary_3_S2_L004_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B03_D_nova_N1_L004_R1.fastq.gz		#1f0b1da4a2ff0f159e5fec231cc236ba	https://api.data.igvf.org/sequence-files/IGVFFI9585KEZY/
mv -n	igvf_011/nova1/Sublibrary_3_S2_L004_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B03_D_nova_N1_L004_R2.fastq.gz		#29a7f53250508bc14e2e2d0afb5e82e5	https://api.data.igvf.org/sequence-files/IGVFFI4803EKJL/
mv -n	igvf_011/nova1/Sublibrary_4_S3_L001_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B04_D_nova_N1_L001_I1.fastq.gz		#46fe76fa724fc8c9962a16470c000a84
mv -n	igvf_011/nova1/Sublibrary_4_S3_L001_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B04_D_nova_N1_L001_R1.fastq.gz		#2d6fe3d2bbe2939404e54be2b9b76e79	https://api.data.igvf.org/sequence-files/IGVFFI6055ZPOC/
mv -n	igvf_011/nova1/Sublibrary_4_S3_L001_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B04_D_nova_N1_L001_R2.fastq.gz		#0306981a9b84b1826da99cc98dad3ef6	https://api.data.igvf.org/sequence-files/IGVFFI1382YXDT/
mv -n	igvf_011/nova1/Sublibrary_4_S3_L002_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B04_D_nova_N1_L002_I1.fastq.gz		#f3a4e102e3e46d9e45e329b68b968558
mv -n	igvf_011/nova1/Sublibrary_4_S3_L002_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B04_D_nova_N1_L002_R1.fastq.gz		#7aecede6e48011a83f9b23b015b9ddf9	https://api.data.igvf.org/sequence-files/IGVFFI6507CBLG/
mv -n	igvf_011/nova1/Sublibrary_4_S3_L002_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B04_D_nova_N1_L002_R2.fastq.gz		#36940cbe740d2d9b7ad7520784405fd2	https://api.data.igvf.org/sequence-files/IGVFFI4676LJSJ/
mv -n	igvf_011/nova1/Sublibrary_4_S3_L003_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B04_D_nova_N1_L003_I1.fastq.gz		#c1e0b318075893c77a38e5d259f9a257
mv -n	igvf_011/nova1/Sublibrary_4_S3_L003_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B04_D_nova_N1_L003_R1.fastq.gz		#ae5d8a1ceb1a9059a7ae0fe61a8ac16a	https://api.data.igvf.org/sequence-files/IGVFFI2942UWJL/
mv -n	igvf_011/nova1/Sublibrary_4_S3_L003_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B04_D_nova_N1_L003_R2.fastq.gz		#02c983181cc596fc8f134ff2534f68b0	https://api.data.igvf.org/sequence-files/IGVFFI3448MYZD/
mv -n	igvf_011/nova1/Sublibrary_4_S3_L004_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B04_D_nova_N1_L004_I1.fastq.gz		#d1b1a89bf6cf1f219bdbdc9a2959a724
mv -n	igvf_011/nova1/Sublibrary_4_S3_L004_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B04_D_nova_N1_L004_R1.fastq.gz		#de5ad3faf025a989d0202faa288a4050	https://api.data.igvf.org/sequence-files/IGVFFI6854ZUAV/
mv -n	igvf_011/nova1/Sublibrary_4_S3_L004_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B04_D_nova_N1_L004_R2.fastq.gz		#d39cb63b23bd4fc8a526a9eeaacd5fd0	https://api.data.igvf.org/sequence-files/IGVFFI1008KNHI/
mv -n	igvf_011/nova1/Sublibrary_5_S4_L001_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B05_D_nova_N1_L001_I1.fastq.gz		#c41c174e48b0952e8d6b3cc540db2da1
mv -n	igvf_011/nova1/Sublibrary_5_S4_L001_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B05_D_nova_N1_L001_R1.fastq.gz		#57e9d66683163520a149031277da85f5	https://api.data.igvf.org/sequence-files/IGVFFI6880XAKF/
mv -n	igvf_011/nova1/Sublibrary_5_S4_L001_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B05_D_nova_N1_L001_R2.fastq.gz		#423d17d7f8069de2ec4f224ee50f2733	https://api.data.igvf.org/sequence-files/IGVFFI7790XVBX/
mv -n	igvf_011/nova1/Sublibrary_5_S4_L002_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B05_D_nova_N1_L002_I1.fastq.gz		#511772df6ca2fb30833b96dd2faefd86
mv -n	igvf_011/nova1/Sublibrary_5_S4_L002_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B05_D_nova_N1_L002_R1.fastq.gz		#c8801b2da30a24bd5638318f18d4236e	https://api.data.igvf.org/sequence-files/IGVFFI0408FWLR/
mv -n	igvf_011/nova1/Sublibrary_5_S4_L002_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B05_D_nova_N1_L002_R2.fastq.gz		#c8f665b971e4684d2ada08904a01b478	https://api.data.igvf.org/sequence-files/IGVFFI3535YSVJ/
mv -n	igvf_011/nova1/Sublibrary_5_S4_L003_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B05_D_nova_N1_L003_I1.fastq.gz		#fc60996dac8b6fd7459bc511fa479399
mv -n	igvf_011/nova1/Sublibrary_5_S4_L003_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B05_D_nova_N1_L003_R1.fastq.gz		#b03af15b101e6e84b6b3dd33d04ecc80	https://api.data.igvf.org/sequence-files/IGVFFI6400JYXB/
mv -n	igvf_011/nova1/Sublibrary_5_S4_L003_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B05_D_nova_N1_L003_R2.fastq.gz		#3e58f25cadb42e40778e271ced8760f8	https://api.data.igvf.org/sequence-files/IGVFFI3717YAML/
mv -n	igvf_011/nova1/Sublibrary_5_S4_L004_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B05_D_nova_N1_L004_I1.fastq.gz		#ced9dd01fcd7a8de451f5f0f7062c19b
mv -n	igvf_011/nova1/Sublibrary_5_S4_L004_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B05_D_nova_N1_L004_R1.fastq.gz		#02dbe3dbb4814873784d62c845d3e735	https://api.data.igvf.org/sequence-files/IGVFFI9385VMQW/
mv -n	igvf_011/nova1/Sublibrary_5_S4_L004_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B05_D_nova_N1_L004_R2.fastq.gz		#d023ace0ea2193facefd73aae89d8e60	https://api.data.igvf.org/sequence-files/IGVFFI1859EBAX/
mv -n	igvf_011/nova1/Sublibrary_6_S5_L001_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B06_D_nova_N1_L001_I1.fastq.gz		#98c41cf1c300e77d969d3e27af158060
mv -n	igvf_011/nova1/Sublibrary_6_S5_L001_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B06_D_nova_N1_L001_R1.fastq.gz		#ffd55bdc84fd1c43c92b1ba5235c3942	https://api.data.igvf.org/sequence-files/IGVFFI2437MXAC/
mv -n	igvf_011/nova1/Sublibrary_6_S5_L001_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B06_D_nova_N1_L001_R2.fastq.gz		#09edcfdd82e202249fa9e0191fabbf44	https://api.data.igvf.org/sequence-files/IGVFFI6858VXBZ/
mv -n	igvf_011/nova1/Sublibrary_6_S5_L002_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B06_D_nova_N1_L002_I1.fastq.gz		#670990ad0b7e7cd487d17ba000aa98a3
mv -n	igvf_011/nova1/Sublibrary_6_S5_L002_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B06_D_nova_N1_L002_R1.fastq.gz		#785c955d6ffb9a2d4ed7ab1542cb25ef	https://api.data.igvf.org/sequence-files/IGVFFI4631OLIO/
mv -n	igvf_011/nova1/Sublibrary_6_S5_L002_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B06_D_nova_N1_L002_R2.fastq.gz		#c922a5e4f6142ca52d342ed9d6ed5a5d	https://api.data.igvf.org/sequence-files/IGVFFI1611BHRS/
mv -n	igvf_011/nova1/Sublibrary_6_S5_L003_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B06_D_nova_N1_L003_I1.fastq.gz		#6b7602094bc67264c53b18dd50b72e9f
mv -n	igvf_011/nova1/Sublibrary_6_S5_L003_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B06_D_nova_N1_L003_R1.fastq.gz		#c864059cf47951d719f90b95eff904d4	https://api.data.igvf.org/sequence-files/IGVFFI1607FWXX/
mv -n	igvf_011/nova1/Sublibrary_6_S5_L003_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B06_D_nova_N1_L003_R2.fastq.gz		#70bbc939668db4c5608b85edb10497b9	https://api.data.igvf.org/sequence-files/IGVFFI1332HXZY/
mv -n	igvf_011/nova1/Sublibrary_6_S5_L004_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B06_D_nova_N1_L004_I1.fastq.gz		#f8712f16f633b49996521d62e12a1894
mv -n	igvf_011/nova1/Sublibrary_6_S5_L004_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B06_D_nova_N1_L004_R1.fastq.gz		#d0d044ee3d06eed580c7e4ebdfe37b91	https://api.data.igvf.org/sequence-files/IGVFFI3252ETYO/
mv -n	igvf_011/nova1/Sublibrary_6_S5_L004_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B06_D_nova_N1_L004_R2.fastq.gz		#ab538275404973a70c5600df9fc324de	https://api.data.igvf.org/sequence-files/IGVFFI2577MOHX/
mv -n	igvf_011/nova1/Sublibrary_7_S6_L001_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B07_D_nova_N1_L001_I1.fastq.gz		#67de4177b65492221f4689e0fa8b1226
mv -n	igvf_011/nova1/Sublibrary_7_S6_L001_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B07_D_nova_N1_L001_R1.fastq.gz		#0e0061c883926929bd2855e165b98705	https://api.data.igvf.org/sequence-files/IGVFFI3131QZCS/
mv -n	igvf_011/nova1/Sublibrary_7_S6_L001_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B07_D_nova_N1_L001_R2.fastq.gz		#fb20ef75855a244379c92b377fad29c0	https://api.data.igvf.org/sequence-files/IGVFFI2140YXXK/
mv -n	igvf_011/nova1/Sublibrary_7_S6_L002_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B07_D_nova_N1_L002_I1.fastq.gz		#166641eb4b160dda7dc7f91165a1b8e3
mv -n	igvf_011/nova1/Sublibrary_7_S6_L002_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B07_D_nova_N1_L002_R1.fastq.gz		#e052e7f73e73b5eab620a0e8532df059	https://api.data.igvf.org/sequence-files/IGVFFI1986UIVF/
mv -n	igvf_011/nova1/Sublibrary_7_S6_L002_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B07_D_nova_N1_L002_R2.fastq.gz		#3534ae300d666789eb0dab5461fe37ee	https://api.data.igvf.org/sequence-files/IGVFFI6928TOIO/
mv -n	igvf_011/nova1/Sublibrary_7_S6_L003_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B07_D_nova_N1_L003_I1.fastq.gz		#8eb5884a64b172055e428dec65e3101f
mv -n	igvf_011/nova1/Sublibrary_7_S6_L003_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B07_D_nova_N1_L003_R1.fastq.gz		#6d2b5f9144a776ef4ad4039984f101aa	https://api.data.igvf.org/sequence-files/IGVFFI1240PHBV/
mv -n	igvf_011/nova1/Sublibrary_7_S6_L003_R2_001.fastq.gz	igvf_011/nova1/igvf_011_B07_D_nova_N1_L003_R2.fastq.gz		#cf422ef2e8e9864e579c1f09f1505916	https://api.data.igvf.org/sequence-files/IGVFFI2000QOOZ/
mv -n	igvf_011/nova1/Sublibrary_7_S6_L004_I1_001.fastq.gz	igvf_011/nova1/igvf_011_B07_D_nova_N1_L004_I1.fastq.gz		#124d8ddc510044f52ca815a92ca48784
mv -n	igvf_011/nova1/Sublibrary_7_S6_L004_R1_001.fastq.gz	igvf_011/nova1/igvf_011_B07_D_nova_N1_L004_R1.fastq.gz		#36151feca35c189503dcaeb08b0882f4	https://api.data.igvf.org/sequence-files/IGVFFI8233TZER/

mv -n	igvf_013/nova1/Sublibrary_11_S10_L001_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI11_D_nova_N1_L001_R1.fastq.gz		#fbe180e344b12170276455fe0c379f05	https://api.data.igvf.org/sequence-files/IGVFFI3393MRMQ/
mv -n	igvf_013/nova1/Sublibrary_11_S10_L001_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI11_D_nova_N1_L001_R2.fastq.gz		#c217359da67ed1e4aa47fb6f7dfb938d	https://api.data.igvf.org/sequence-files/IGVFFI5888IJXV/
mv -n	igvf_013/nova1/Sublibrary_11_S10_L002_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI11_D_nova_N1_L002_I1.fastq.gz		#62e54c54f12761c9a4eb55efd4634786
mv -n	igvf_013/nova1/Sublibrary_11_S10_L002_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI11_D_nova_N1_L002_I2.fastq.gz		#28a3e5d54a5a3abb9474044087d6f8e6	https://api.data.igvf.org/sequence-files/IGVFFI3645MBBE/
mv -n	igvf_013/nova1/Sublibrary_11_S10_L002_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI11_D_nova_N1_L002_R1.fastq.gz		#64d8f880781051e79d492749028df9d6	https://api.data.igvf.org/sequence-files/IGVFFI3386XZVC/
mv -n	igvf_013/nova1/Sublibrary_11_S10_L002_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI11_D_nova_N1_L002_R2.fastq.gz		#e67782dfa6a757230b5f25e8778c41a9	https://api.data.igvf.org/sequence-files/IGVFFI5237PUBZ/
mv -n	igvf_013/nova1/Sublibrary_11_S10_L003_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI11_D_nova_N1_L003_I1.fastq.gz		#47080e9c7381c4cb9d329be1c7588623
mv -n	igvf_013/nova1/Sublibrary_11_S10_L003_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI11_D_nova_N1_L003_I2.fastq.gz		#4a7691487476015c0664c2df684ca6a8	https://api.data.igvf.org/sequence-files/IGVFFI4324QEPV/
mv -n	igvf_013/nova1/Sublibrary_11_S10_L003_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI11_D_nova_N1_L003_R1.fastq.gz		#a23cf44976828631e7133e9432422245	https://api.data.igvf.org/sequence-files/IGVFFI6937RZTZ/
mv -n	igvf_013/nova1/Sublibrary_11_S10_L003_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI11_D_nova_N1_L003_R2.fastq.gz		#9f83e4f06ef0a9bd0fe2defb61cc1484	https://api.data.igvf.org/sequence-files/IGVFFI2098QHJQ/
mv -n	igvf_013/nova1/Sublibrary_11_S10_L004_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI11_D_nova_N1_L004_I1.fastq.gz		#d96264cd5d781882ac9a75898506cdab
mv -n	igvf_013/nova1/Sublibrary_11_S10_L004_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI11_D_nova_N1_L004_I2.fastq.gz		#0652ac9cecda9cdc334bb6c491ac8c20	https://api.data.igvf.org/sequence-files/IGVFFI5479JGGH/
mv -n	igvf_013/nova1/Sublibrary_11_S10_L004_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI11_D_nova_N1_L004_R1.fastq.gz		#62b619325df1a0a4e1a220d28964be0d	https://api.data.igvf.org/sequence-files/IGVFFI8641BWTL/
mv -n	igvf_013/nova1/Sublibrary_11_S10_L004_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI11_D_nova_N1_L004_R2.fastq.gz		#95eaee807cf5ccc52c93a2f5b42e8fa1	https://api.data.igvf.org/sequence-files/IGVFFI5071RJSE/
mv -n	igvf_013/nova1/Sublibrary_12_S11_L001_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI12_D_nova_N1_L001_I1.fastq.gz		#25dcac217d7b0258faace7181d5136c5
mv -n	igvf_013/nova1/Sublibrary_12_S11_L001_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI12_D_nova_N1_L001_I2.fastq.gz		#71dd9ddd2634e76f73fc5900a921aa17	https://api.data.igvf.org/sequence-files/IGVFFI1533XVHQ/
mv -n	igvf_013/nova1/Sublibrary_12_S11_L001_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI12_D_nova_N1_L001_R1.fastq.gz		#65d193365103bbc31fe9cc0214fac791	https://api.data.igvf.org/sequence-files/IGVFFI8239ZJAV/
mv -n	igvf_013/nova1/Sublibrary_12_S11_L001_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI12_D_nova_N1_L001_R2.fastq.gz		#b936acdd9ee51e23cb96fc97f340c3ed	https://api.data.igvf.org/sequence-files/IGVFFI9025DBIR/
mv -n	igvf_013/nova1/Sublibrary_12_S11_L002_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI12_D_nova_N1_L002_I1.fastq.gz		#163d4990714f9c5c546d840d3dd5c2e6
mv -n	igvf_013/nova1/Sublibrary_12_S11_L002_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI12_D_nova_N1_L002_I2.fastq.gz		#189d64da8719b23ddda09de5cf79d628	https://api.data.igvf.org/sequence-files/IGVFFI9148SQYN/
mv -n	igvf_013/nova1/Sublibrary_12_S11_L002_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI12_D_nova_N1_L002_R1.fastq.gz		#8efb402478b0a671f5630734b4a3effa	https://api.data.igvf.org/sequence-files/IGVFFI5360BSME/
mv -n	igvf_013/nova1/Sublibrary_12_S11_L002_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI12_D_nova_N1_L002_R2.fastq.gz		#21f653e11f4478e8f40064e46d34229b	https://api.data.igvf.org/sequence-files/IGVFFI9865ZFQH/
mv -n	igvf_013/nova1/Sublibrary_12_S11_L003_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI12_D_nova_N1_L003_I1.fastq.gz		#6fdfd5322bbb9057a768531fc391dd2f
mv -n	igvf_013/nova1/Sublibrary_12_S11_L003_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI12_D_nova_N1_L003_I2.fastq.gz		#02727a1710a565e8bd26004f8be12b52	https://api.data.igvf.org/sequence-files/IGVFFI5899LGQV/
mv -n	igvf_013/nova1/Sublibrary_12_S11_L003_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI12_D_nova_N1_L003_R1.fastq.gz		#efdcf967954260d71a7fca18971fd468	https://api.data.igvf.org/sequence-files/IGVFFI5661UTOE/
mv -n	igvf_013/nova1/Sublibrary_12_S11_L003_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI12_D_nova_N1_L003_R2.fastq.gz		#57b99a7c1b7b120e0c8ef2f0e368dfa5	https://api.data.igvf.org/sequence-files/IGVFFI8289ZAQD/
mv -n	igvf_013/nova1/Sublibrary_12_S11_L004_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI12_D_nova_N1_L004_I1.fastq.gz		#7325972479979be050d796b486e5b429
mv -n	igvf_013/nova1/Sublibrary_12_S11_L004_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI12_D_nova_N1_L004_I2.fastq.gz		#ab47d959ac4b3b3d6715cffff3ba0fe0	https://api.data.igvf.org/sequence-files/IGVFFI4360FEYH/
mv -n	igvf_013/nova1/Sublibrary_12_S11_L004_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI12_D_nova_N1_L004_R1.fastq.gz		#efb812d6650e66db20899138375482e9	https://api.data.igvf.org/sequence-files/IGVFFI4819QAGO/
mv -n	igvf_013/nova1/Sublibrary_12_S11_L004_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI12_D_nova_N1_L004_R2.fastq.gz		#f227292c44bc89cf9b78c1f44215cd15	https://api.data.igvf.org/sequence-files/IGVFFI9919ADTC/
mv -n	igvf_013/nova1/Sublibrary_13_S12_L001_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI13_D_nova_N1_L001_I1.fastq.gz		#b8ef4f09a49edf5b112110e05fe61dad
mv -n	igvf_013/nova1/Sublibrary_13_S12_L001_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI13_D_nova_N1_L001_I2.fastq.gz		#1552155d6b9da192c3acf86448ac95c1	https://api.data.igvf.org/sequence-files/IGVFFI0124OXPD/
mv -n	igvf_013/nova1/Sublibrary_13_S12_L001_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI13_D_nova_N1_L001_R1.fastq.gz		#b0cc80fee7c3a5a801e674a9ab596e08	https://api.data.igvf.org/sequence-files/IGVFFI9101NHMB/
mv -n	igvf_013/nova1/Sublibrary_13_S12_L001_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI13_D_nova_N1_L001_R2.fastq.gz		#f8c2c9ff7d82d649c8da19d8e8049ac6	https://api.data.igvf.org/sequence-files/IGVFFI5307BXUT/
mv -n	igvf_013/nova1/Sublibrary_13_S12_L002_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI13_D_nova_N1_L002_I1.fastq.gz		#b119083873e935acfaa04dcf537dd609
mv -n	igvf_013/nova1/Sublibrary_13_S12_L002_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI13_D_nova_N1_L002_I2.fastq.gz		#2ed1352a45f5f4d496e8b6ee3078fd24	https://api.data.igvf.org/sequence-files/IGVFFI5248KFZO/
mv -n	igvf_013/nova1/Sublibrary_13_S12_L002_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI13_D_nova_N1_L002_R1.fastq.gz		#0d60e47fa7dc599b5f6e42ff8231ffce	https://api.data.igvf.org/sequence-files/IGVFFI4485FWBF/
mv -n	igvf_013/nova1/Sublibrary_13_S12_L002_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI13_D_nova_N1_L002_R2.fastq.gz		#134af6b02656cb368be82a61a3c068dd	https://api.data.igvf.org/sequence-files/IGVFFI9084TFNB/
mv -n	igvf_013/nova1/Sublibrary_13_S12_L003_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI13_D_nova_N1_L003_I1.fastq.gz		#5bc2147038231123fab153102e248b2a
mv -n	igvf_013/nova1/Sublibrary_13_S12_L003_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI13_D_nova_N1_L003_I2.fastq.gz		#50b66092abf55a91c9646bb06ef7d0ae	https://api.data.igvf.org/sequence-files/IGVFFI2556NMUE/
mv -n	igvf_013/nova1/Sublibrary_13_S12_L003_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI13_D_nova_N1_L003_R1.fastq.gz		#75f94006b26d53b4e0767db932bf9f89	https://api.data.igvf.org/sequence-files/IGVFFI4150JCIJ/
mv -n	igvf_013/nova1/Sublibrary_13_S12_L003_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI13_D_nova_N1_L003_R2.fastq.gz		#7e4a04332872b3002c1a71fe6b2533ba	https://api.data.igvf.org/sequence-files/IGVFFI7649QBGQ/
mv -n	igvf_013/nova1/Sublibrary_13_S12_L004_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI13_D_nova_N1_L004_I1.fastq.gz		#8d0c712eeeb3c3648939a7418bc73299
mv -n	igvf_013/nova1/Sublibrary_13_S12_L004_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI13_D_nova_N1_L004_I2.fastq.gz		#d26c742c63fe49b84cd53749887d97fd	https://api.data.igvf.org/sequence-files/IGVFFI3705BMYC/
mv -n	igvf_013/nova1/Sublibrary_13_S12_L004_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI13_D_nova_N1_L004_R1.fastq.gz		#9d4c3bc1d1ed44b57a865c8d0119b9a8	https://api.data.igvf.org/sequence-files/IGVFFI7834SKEO/
mv -n	igvf_013/nova1/Sublibrary_13_S12_L004_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI13_D_nova_N1_L004_R2.fastq.gz		#f3a7f2e7084c2fe75e9b48c63e21348e	https://api.data.igvf.org/sequence-files/IGVFFI0650XTUO/
mv -n	igvf_013/nova1/Sublibrary_14_S13_L001_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI14_D_nova_N1_L001_I1.fastq.gz		#73a5b0f24a3a0d598f6428ca02569693
mv -n	igvf_013/nova1/Sublibrary_14_S13_L001_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI14_D_nova_N1_L001_I2.fastq.gz		#d9666644f35319c5a4ab2fa2228d3dd1	https://api.data.igvf.org/sequence-files/IGVFFI0960YHZN/

mv -n	igvf_013/nova1/Sublibrary_14_S13_L001_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI14_D_nova_N1_L001_R1.fastq.gz		#95b31852af7b1f095051ec54ccda6077	https://api.data.igvf.org/sequence-files/IGVFFI6413FURD/
mv -n	igvf_013/nova1/Sublibrary_14_S13_L001_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI14_D_nova_N1_L001_R2.fastq.gz		#6291efed7d81296298c580297ccd3d20	https://api.data.igvf.org/sequence-files/IGVFFI3740TMNI/
mv -n	igvf_013/nova1/Sublibrary_14_S13_L002_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI14_D_nova_N1_L002_I1.fastq.gz		#4b6a2d41ecf5c19082ce2f91b646d71a
mv -n	igvf_013/nova1/Sublibrary_14_S13_L002_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI14_D_nova_N1_L002_I2.fastq.gz		#2c6502375d585b94b25d309689baba05	https://api.data.igvf.org/sequence-files/IGVFFI5266OMEM/
mv -n	igvf_013/nova1/Sublibrary_14_S13_L002_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI14_D_nova_N1_L002_R1.fastq.gz		#ce32e6bce65f03bc15ebbf9d01c2a5ff	https://api.data.igvf.org/sequence-files/IGVFFI7784OEKM/
mv -n	igvf_013/nova1/Sublibrary_14_S13_L002_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI14_D_nova_N1_L002_R2.fastq.gz		#1bca4fe06f70207ebe7b1cb52fc0fc00	https://api.data.igvf.org/sequence-files/IGVFFI5926DPKP/
mv -n	igvf_013/nova1/Sublibrary_14_S13_L003_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI14_D_nova_N1_L003_I1.fastq.gz		#fdd5d9357cbde884db2297062fa113b2
mv -n	igvf_013/nova1/Sublibrary_14_S13_L003_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI14_D_nova_N1_L003_I2.fastq.gz		#c1005c8c71a04ec4a4a0100d1616e183	https://api.data.igvf.org/sequence-files/IGVFFI9253SGOC/
mv -n	igvf_013/nova1/Sublibrary_14_S13_L003_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI14_D_nova_N1_L003_R1.fastq.gz		#e2fb3bd1fc53e70927811970a099384e	https://api.data.igvf.org/sequence-files/IGVFFI7768FCGT/
mv -n	igvf_013/nova1/Sublibrary_14_S13_L003_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI14_D_nova_N1_L003_R2.fastq.gz		#36b8b44f4948f5562c80e87d305a7948	https://api.data.igvf.org/sequence-files/IGVFFI9925KXJG/
mv -n	igvf_013/nova1/Sublibrary_14_S13_L004_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI14_D_nova_N1_L004_I1.fastq.gz		#99fc0edb9f4e30792569943a89ad41cf
mv -n	igvf_013/nova1/Sublibrary_14_S13_L004_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI14_D_nova_N1_L004_I2.fastq.gz		#7ac02f8e5255658fd222e42375576a02	https://api.data.igvf.org/sequence-files/IGVFFI4418MCBZ/
mv -n	igvf_013/nova1/Sublibrary_14_S13_L004_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI14_D_nova_N1_L004_R1.fastq.gz		#ba9a94b820a12e2c724a3d59317e6f85	https://api.data.igvf.org/sequence-files/IGVFFI3625OAJI/
mv -n	igvf_013/nova1/Sublibrary_14_S13_L004_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI14_D_nova_N1_L004_R2.fastq.gz		#3046535e555456182e1bea85dd4ff91b	https://api.data.igvf.org/sequence-files/IGVFFI1255AMKC/
mv -n	igvf_013/nova1/Sublibrary_15_S14_L001_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI15_D_nova_N1_L001_I1.fastq.gz		#8fb6635f177e57e54c9322455a440ac5
mv -n	igvf_013/nova1/Sublibrary_15_S14_L001_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI15_D_nova_N1_L001_I2.fastq.gz		#95d250828ec83d063af361cc2e8575fe	https://api.data.igvf.org/sequence-files/IGVFFI4598YRJK/
mv -n	igvf_013/nova1/Sublibrary_15_S14_L001_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI15_D_nova_N1_L001_R1.fastq.gz		#efa26fe9701b943811eafc3d462dde5c	https://api.data.igvf.org/sequence-files/IGVFFI5478DXLB/
mv -n	igvf_013/nova1/Sublibrary_15_S14_L001_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI15_D_nova_N1_L001_R2.fastq.gz		#2738c859d07f2b6a3a36f60034ac1887	https://api.data.igvf.org/sequence-files/IGVFFI1707NWGK/
mv -n	igvf_013/nova1/Sublibrary_15_S14_L002_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI15_D_nova_N1_L002_I1.fastq.gz		#160a357e1c88c8906d1802dadf7bc3c5
mv -n	igvf_013/nova1/Sublibrary_15_S14_L002_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI15_D_nova_N1_L002_I2.fastq.gz		#aae97358ab48b394128f83131f936a04	https://api.data.igvf.org/sequence-files/IGVFFI9093QULX/
mv -n	igvf_013/nova1/Sublibrary_15_S14_L002_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI15_D_nova_N1_L002_R1.fastq.gz		#a8417650c088160066f725587a43cc10	https://api.data.igvf.org/sequence-files/IGVFFI7526VGKA/
mv -n	igvf_013/nova1/Sublibrary_15_S14_L002_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI15_D_nova_N1_L002_R2.fastq.gz		#a25d757b83f1e341dc7fc5529e7d8afb	https://api.data.igvf.org/sequence-files/IGVFFI2965EDOT/
mv -n	igvf_013/nova1/Sublibrary_15_S14_L003_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI15_D_nova_N1_L003_I1.fastq.gz		#297a4be2501216f51c033f0f6ad1c3e9
mv -n	igvf_013/nova1/Sublibrary_15_S14_L003_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI15_D_nova_N1_L003_I2.fastq.gz		#1a200a9d9e0a08ca469c9ae133d8ad78	https://api.data.igvf.org/sequence-files/IGVFFI7308OUXS/
mv -n	igvf_013/nova1/Sublibrary_15_S14_L003_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI15_D_nova_N1_L003_R1.fastq.gz		#5014a7782ba788a40ad17ea55e5bb7ae	https://api.data.igvf.org/sequence-files/IGVFFI2592GYIO/
mv -n	igvf_013/nova1/Sublibrary_15_S14_L003_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI15_D_nova_N1_L003_R2.fastq.gz		#ff4272a3b68ef9bbc324ccd40adb1758	https://api.data.igvf.org/sequence-files/IGVFFI8418OGUC/
mv -n	igvf_013/nova1/Sublibrary_15_S14_L004_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI15_D_nova_N1_L004_I1.fastq.gz		#78449467d36683524709c5509ed53d50
mv -n	igvf_013/nova1/Sublibrary_15_S14_L004_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI15_D_nova_N1_L004_I2.fastq.gz		#b4c15559ed94bb85fe3af00eb3c4f43c	https://api.data.igvf.org/sequence-files/IGVFFI0917HBSU/
mv -n	igvf_013/nova1/Sublibrary_15_S14_L004_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI15_D_nova_N1_L004_R1.fastq.gz		#b04f3ba6deacaace2215e09fa38372b8	https://api.data.igvf.org/sequence-files/IGVFFI4834AVBV/
mv -n	igvf_013/nova1/Sublibrary_15_S14_L004_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI15_D_nova_N1_L004_R2.fastq.gz		#b14587409546feeb3dbc99caedf6e049	https://api.data.igvf.org/sequence-files/IGVFFI1448QZWL/
mv -n	igvf_013/nova1/Sublibrary_2_S1_L001_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI02_D_nova_N1_L001_I1.fastq.gz		#aadf746f61fb578806d9af8c15fcc2ab
mv -n	igvf_013/nova1/Sublibrary_2_S1_L001_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI02_D_nova_N1_L001_I2.fastq.gz		#112260379a6d0e4439bfbccfc07f625a	https://api.data.igvf.org/sequence-files/IGVFFI5837AFIC/
mv -n	igvf_013/nova1/Sublibrary_2_S1_L001_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI02_D_nova_N1_L001_R1.fastq.gz		#1cf9f70bf9a23dc9406f06ea21779ea7	https://api.data.igvf.org/sequence-files/IGVFFI4785ZAGU/
mv -n	igvf_013/nova1/Sublibrary_2_S1_L001_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI02_D_nova_N1_L001_R2.fastq.gz		#5c517756aebd96fbaac6452bef694542	https://api.data.igvf.org/sequence-files/IGVFFI7351ZSOH/
mv -n	igvf_013/nova1/Sublibrary_2_S1_L002_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI02_D_nova_N1_L002_I1.fastq.gz		#a9909da6b03d23e51f5438bb899814fb
mv -n	igvf_013/nova1/Sublibrary_2_S1_L002_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI02_D_nova_N1_L002_I2.fastq.gz		#4fa197e7e3f87f04317a88bc27bb337b	https://api.data.igvf.org/sequence-files/IGVFFI2514ZMCP/
mv -n	igvf_013/nova1/Sublibrary_2_S1_L002_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI02_D_nova_N1_L002_R1.fastq.gz		#16ffbe7afa61632c1848dbcfa1597767	https://api.data.igvf.org/sequence-files/IGVFFI1188RSQW/
mv -n	igvf_013/nova1/Sublibrary_2_S1_L002_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI02_D_nova_N1_L002_R2.fastq.gz		#7af4e11c6ca14d4ec0e07e82e3d1c74b	https://api.data.igvf.org/sequence-files/IGVFFI3918KNJE/
mv -n	igvf_013/nova1/Sublibrary_2_S1_L003_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI02_D_nova_N1_L003_I1.fastq.gz		#25a885fc0aab1850777f2994c696eece
mv -n	igvf_013/nova1/Sublibrary_2_S1_L003_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI02_D_nova_N1_L003_I2.fastq.gz		#1447bfbc1501d836cd03332698b4aeb7	https://api.data.igvf.org/sequence-files/IGVFFI4438HKNO/
mv -n	igvf_013/nova1/Sublibrary_2_S1_L003_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI02_D_nova_N1_L003_R1.fastq.gz		#3ecbdc7502f4247720d4abd7ea403fd3	https://api.data.igvf.org/sequence-files/IGVFFI9293RPVI/
mv -n	igvf_013/nova1/Sublibrary_2_S1_L003_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI02_D_nova_N1_L003_R2.fastq.gz		#611601bc69a36248b146dc34d541dc9b	https://api.data.igvf.org/sequence-files/IGVFFI5403MDEJ/
mv -n	igvf_013/nova1/Sublibrary_2_S1_L004_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI02_D_nova_N1_L004_I1.fastq.gz		#40e2155feef57ae10598818cbf5fca10
mv -n	igvf_013/nova1/Sublibrary_2_S1_L004_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI02_D_nova_N1_L004_I2.fastq.gz		#75a78f748623491576e4acdbb420b9a4	https://api.data.igvf.org/sequence-files/IGVFFI2072XACP/
mv -n	igvf_013/nova1/Sublibrary_2_S1_L004_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI02_D_nova_N1_L004_R1.fastq.gz		#85fd869ddf30c372b9da570604b41662	https://api.data.igvf.org/sequence-files/IGVFFI2983FZXW/
mv -n	igvf_013/nova1/Sublibrary_2_S1_L004_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI02_D_nova_N1_L004_R2.fastq.gz		#9721d0899a542a58581420fd0ad700fd	https://api.data.igvf.org/sequence-files/IGVFFI3929NPTG/
mv -n	igvf_013/nova1/Sublibrary_3_S2_L001_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI03_D_nova_N1_L001_I1.fastq.gz		#20f1bc9137ef84ad3d949636a6dee498
mv -n	igvf_013/nova1/Sublibrary_3_S2_L001_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI03_D_nova_N1_L001_I2.fastq.gz		#b7d2d0105742450b92770d7819bba189	https://api.data.igvf.org/sequence-files/IGVFFI0490CNGB/
mv -n	igvf_013/nova1/Sublibrary_3_S2_L001_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI03_D_nova_N1_L001_R1.fastq.gz		#004a9c124461e7a8eb4fbb69ed386da1	https://api.data.igvf.org/sequence-files/IGVFFI4716UKLI/
mv -n	igvf_013/nova1/Sublibrary_3_S2_L001_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI03_D_nova_N1_L001_R2.fastq.gz		#aa71434a4bb451bf5dc64985dc834ff4	https://api.data.igvf.org/sequence-files/IGVFFI7342RPGU/
mv -n	igvf_013/nova1/Sublibrary_3_S2_L002_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI03_D_nova_N1_L002_I1.fastq.gz		#243a67274c4b41fc10118e4dd4b41073
mv -n	igvf_013/nova1/Sublibrary_3_S2_L002_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI03_D_nova_N1_L002_I2.fastq.gz		#3cd70996f5aff688dfc357d5e3d7869b	https://api.data.igvf.org/sequence-files/IGVFFI4040NTRA/
mv -n	igvf_013/nova1/Sublibrary_3_S2_L002_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI03_D_nova_N1_L002_R1.fastq.gz		#25147421f5f6085476350c41f480b832	https://api.data.igvf.org/sequence-files/IGVFFI4186JXBV/
mv -n	igvf_013/nova1/Sublibrary_3_S2_L002_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI03_D_nova_N1_L002_R2.fastq.gz		#f5a28404413a313e28ed09f9086a2089	https://api.data.igvf.org/sequence-files/IGVFFI4318VTIA/
mv -n	igvf_013/nova1/Sublibrary_3_S2_L003_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI03_D_nova_N1_L003_I1.fastq.gz		#79d77c859f68c40467f212e7418a6390
mv -n	igvf_013/nova1/Sublibrary_3_S2_L003_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI03_D_nova_N1_L003_I2.fastq.gz		#4d3b9aa09f77b8bb8b2363b848a4cd32	https://api.data.igvf.org/sequence-files/IGVFFI3316BTXB/
mv -n	igvf_013/nova1/Sublibrary_3_S2_L003_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI03_D_nova_N1_L003_R1.fastq.gz		#a7dc0bc5e4664fffa50e07a2ba4df091	https://api.data.igvf.org/sequence-files/IGVFFI6092CTRF/
mv -n	igvf_013/nova1/Sublibrary_3_S2_L003_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI03_D_nova_N1_L003_R2.fastq.gz		#f449d958b03745be171206de3ac26053	https://api.data.igvf.org/sequence-files/IGVFFI2690SDLG/
mv -n	igvf_013/nova1/Sublibrary_3_S2_L004_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI03_D_nova_N1_L004_I1.fastq.gz		#3348edf5234b5c5b9c3d00baee451d71
mv -n	igvf_013/nova1/Sublibrary_3_S2_L004_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI03_D_nova_N1_L004_I2.fastq.gz		#75fd49df6926e368f624825be4ed3a05	https://api.data.igvf.org/sequence-files/IGVFFI0298FAVO/
mv -n	igvf_013/nova1/Sublibrary_3_S2_L004_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI03_D_nova_N1_L004_R1.fastq.gz		#78e83651fc9bd67f3bf1ba8ebe6693f3	https://api.data.igvf.org/sequence-files/IGVFFI9423OTQB/
mv -n	igvf_013/nova1/Sublibrary_3_S2_L004_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI03_D_nova_N1_L004_R2.fastq.gz		#8636933ca0fc406a7d8a2089882dff94	https://api.data.igvf.org/sequence-files/IGVFFI8922KXWR/
mv -n	igvf_013/nova1/Sublibrary_4_S3_L001_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI04_D_nova_N1_L001_I1.fastq.gz		#04648b80a381719c7ce3baf24e07fd42
mv -n	igvf_013/nova1/Sublibrary_4_S3_L001_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI04_D_nova_N1_L001_I2.fastq.gz		#694e946c66f7ce7870313b4321bf6e0b	https://api.data.igvf.org/sequence-files/IGVFFI7385NFFX/
mv -n	igvf_013/nova1/Sublibrary_4_S3_L001_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI04_D_nova_N1_L001_R1.fastq.gz		#80f964fbcf62634e0589b8b248eeb1f4	https://api.data.igvf.org/sequence-files/IGVFFI0434TAZR/
mv -n	igvf_013/nova1/Sublibrary_4_S3_L001_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI04_D_nova_N1_L001_R2.fastq.gz		#df7edd9219c22996e40e06d431bb85b2	https://api.data.igvf.org/sequence-files/IGVFFI8373XDAM/
mv -n	igvf_013/nova1/Sublibrary_4_S3_L002_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI04_D_nova_N1_L002_I1.fastq.gz		#c0b73d7f6351cd542eac5e192badf12e
mv -n	igvf_013/nova1/Sublibrary_4_S3_L002_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI04_D_nova_N1_L002_I2.fastq.gz		#044f42cb50f710d5e16d8f877dd6ad77	https://api.data.igvf.org/sequence-files/IGVFFI6943PPZG/
mv -n	igvf_013/nova1/Sublibrary_4_S3_L002_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI04_D_nova_N1_L002_R1.fastq.gz		#88c6648430c64a3dcd0ad69e131885b3	https://api.data.igvf.org/sequence-files/IGVFFI0172VOJL/
mv -n	igvf_013/nova1/Sublibrary_4_S3_L002_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI04_D_nova_N1_L002_R2.fastq.gz		#d4267f6eb820b9f7f9ed110ee07dca09	https://api.data.igvf.org/sequence-files/IGVFFI2283MAKL/
mv -n	igvf_013/nova1/Sublibrary_4_S3_L003_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI04_D_nova_N1_L003_I1.fastq.gz		#94535dc835cb013a5ef110b04ae46abb
mv -n	igvf_013/nova1/Sublibrary_4_S3_L003_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI04_D_nova_N1_L003_I2.fastq.gz		#0be07fab4d2c02b5e7240fc2188540e5	https://api.data.igvf.org/sequence-files/IGVFFI0843JHDC/
mv -n	igvf_013/nova1/Sublibrary_4_S3_L003_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI04_D_nova_N1_L003_R1.fastq.gz		#53a89fe9af68896cf4713ce230c1d1d2	https://api.data.igvf.org/sequence-files/IGVFFI4951OZLJ/
mv -n	igvf_013/nova1/Sublibrary_4_S3_L003_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI04_D_nova_N1_L003_R2.fastq.gz		#4200c656a785a06fed16c897e243ebcb	https://api.data.igvf.org/sequence-files/IGVFFI1645XIYR/
mv -n	igvf_013/nova1/Sublibrary_4_S3_L004_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI04_D_nova_N1_L004_I1.fastq.gz		#473bc6ee17e9105982c3e73b92aa27ad
mv -n	igvf_013/nova1/Sublibrary_4_S3_L004_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI04_D_nova_N1_L004_I2.fastq.gz		#69f4b7db42cfdce6b3016ffeeacfcfe6	https://api.data.igvf.org/sequence-files/IGVFFI0695RLRM/
mv -n	igvf_013/nova1/Sublibrary_4_S3_L004_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI04_D_nova_N1_L004_R1.fastq.gz		#35a3181b2bef142a283293c8b2278567	https://api.data.igvf.org/sequence-files/IGVFFI7186DGZE/
mv -n	igvf_013/nova1/Sublibrary_4_S3_L004_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI04_D_nova_N1_L004_R2.fastq.gz		#04a55fe91222be12d2ea27ef7a438924	https://api.data.igvf.org/sequence-files/IGVFFI2354GMVH/
mv -n	igvf_013/nova1/Sublibrary_5_S4_L001_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI05_D_nova_N1_L001_I1.fastq.gz		#11e64849323b072ebfc0ecc7448eb562
mv -n	igvf_013/nova1/Sublibrary_5_S4_L001_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI05_D_nova_N1_L001_I2.fastq.gz		#3e8eae187e5161b6e5f753cee1632d5c	https://api.data.igvf.org/sequence-files/IGVFFI6539OHKG/
mv -n	igvf_013/nova1/Sublibrary_5_S4_L001_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI05_D_nova_N1_L001_R1.fastq.gz		#30f1d01baa37a890d3602ea69af8374d	https://api.data.igvf.org/sequence-files/IGVFFI9867VRFW/
mv -n	igvf_013/nova1/Sublibrary_5_S4_L001_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI05_D_nova_N1_L001_R2.fastq.gz		#4ad1f625749b158af444095f789736dd	https://api.data.igvf.org/sequence-files/IGVFFI7753SPIS/
mv -n	igvf_013/nova1/Sublibrary_5_S4_L002_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI05_D_nova_N1_L002_I1.fastq.gz		#9d35afed7df81320cbe292b139f3f2f2
mv -n	igvf_013/nova1/Sublibrary_5_S4_L002_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI05_D_nova_N1_L002_I2.fastq.gz		#2b4d8280db1a32bfe3fedfa0bffa2fd8	https://api.data.igvf.org/sequence-files/IGVFFI4616IDPM/
mv -n	igvf_013/nova1/Sublibrary_5_S4_L002_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI05_D_nova_N1_L002_R1.fastq.gz		#cc9d83478f0b6fdad82b257f15daf5f1	https://api.data.igvf.org/sequence-files/IGVFFI5840YZOB/
mv -n	igvf_013/nova1/Sublibrary_5_S4_L002_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI05_D_nova_N1_L002_R2.fastq.gz		#4d425edcd25d75f78fa59b0c0b53c58b	https://api.data.igvf.org/sequence-files/IGVFFI7472KLLE/
mv -n	igvf_013/nova1/Sublibrary_5_S4_L003_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI05_D_nova_N1_L003_I1.fastq.gz		#48c18d8f0167b66124189f50918d0dc9
mv -n	igvf_013/nova1/Sublibrary_5_S4_L003_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI05_D_nova_N1_L003_I2.fastq.gz		#ca59b6e75d245c6ec42446f74662f1a7	https://api.data.igvf.org/sequence-files/IGVFFI8615XDGA/
mv -n	igvf_013/nova1/Sublibrary_5_S4_L003_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI05_D_nova_N1_L003_R1.fastq.gz		#e59d0e68afe4abf845dd2e7c4182c355	https://api.data.igvf.org/sequence-files/IGVFFI4207XDNY/
mv -n	igvf_013/nova1/Sublibrary_5_S4_L003_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI05_D_nova_N1_L003_R2.fastq.gz		#95c4e171a70d84a598f14b888c67df60	https://api.data.igvf.org/sequence-files/IGVFFI6525DMJZ/
mv -n	igvf_013/nova1/Sublibrary_5_S4_L004_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI05_D_nova_N1_L004_I1.fastq.gz		#1cb55c26841dcda28d619381c42377bb
mv -n	igvf_013/nova1/Sublibrary_5_S4_L004_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI05_D_nova_N1_L004_I2.fastq.gz		#785b03bbed6c98a8a606f1546b02e5cc	https://api.data.igvf.org/sequence-files/IGVFFI4984ZYDC/
mv -n	igvf_013/nova1/Sublibrary_5_S4_L004_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI05_D_nova_N1_L004_R1.fastq.gz		#97a0550e45cbfa6cf54c232b659b8fa8	https://api.data.igvf.org/sequence-files/IGVFFI0423QMHX/
mv -n	igvf_013/nova1/Sublibrary_5_S4_L004_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI05_D_nova_N1_L004_R2.fastq.gz		#344a39f231f35744b859b41f9398c639	https://api.data.igvf.org/sequence-files/IGVFFI1586BHJH/
mv -n	igvf_013/nova1/Sublibrary_6_S5_L001_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI06_D_nova_N1_L001_I1.fastq.gz		#acc0baf740799fd26bb1eea178ead855
mv -n	igvf_013/nova1/Sublibrary_6_S5_L001_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI06_D_nova_N1_L001_I2.fastq.gz		#35f918c5f68bcc4df506c947fa4a586f	https://api.data.igvf.org/sequence-files/IGVFFI7043MHSI/
mv -n	igvf_013/nova1/Sublibrary_6_S5_L001_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI06_D_nova_N1_L001_R1.fastq.gz		#14a69ada48bfaf35369bf0d842999d43	https://api.data.igvf.org/sequence-files/IGVFFI4645UKVE/
mv -n	igvf_013/nova1/Sublibrary_6_S5_L001_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI06_D_nova_N1_L001_R2.fastq.gz		#0d3225fedd25c5b694eb762041740869	https://api.data.igvf.org/sequence-files/IGVFFI2342ZSCC/
mv -n	igvf_013/nova1/Sublibrary_6_S5_L002_I1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI06_D_nova_N1_L002_I1.fastq.gz		#8f4d2ad1f66225f3c3297646a3ddfb7b
mv -n	igvf_013/nova1/Sublibrary_6_S5_L002_I2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI06_D_nova_N1_L002_I2.fastq.gz		#b25c63a47c0173437b53dcea5929921f	https://api.data.igvf.org/sequence-files/IGVFFI8881JKVE/
mv -n	igvf_013/nova1/Sublibrary_6_S5_L002_R1_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI06_D_nova_N1_L002_R1.fastq.gz		#f7607a64fa9f80dfa9524e586f9af5c8	https://api.data.igvf.org/sequence-files/IGVFFI6738PCRY/
mv -n	igvf_013/nova1/Sublibrary_6_S5_L002_R2_001.fastq.gz	igvf_013/nova1/igvf_013_BUDI06_D_nova_N1_L002_R2.fastq.gz		#3e258904449cc7581fe1ae6112f4de51	https://api.data.igvf.org/sequence-files/IGVFFI2487TCEO/

In [11]:
%debug

ERROR:root:No traceback has been produced, nothing to debug.

In [12]:
for k in full_collisions:
    count = full_collisions[k]
    if count > 1:
        print(k, count)

In [13]:
for k in name_collisions:
    count = name_collisions[k]
    if count > 1:
        print(k, count)

In [14]:
# 0dbdc8a7fe445f8a9e6bbbd7a7d42cfd nanopore igvf003_8A_lig-ss_7.fastq.gz 
# dc68518d2246ead1d5931ac70db8e1c5 illumina fastq 008B_13A_R1

In [15]:
for f in files:
    if f["md5sum"] == "dc68518d2246ead1d5931ac70db8e1c5":
        break
#f

In [16]:
md5_collisions = {}
for f in files:
    md5_collisions.setdefault(f["md5sum"], []).append(f)
    
for md5sum in md5_collisions:
    if len(md5_collisions[md5sum]) > 1:
        for f in md5_collisions[md5sum]:
            print(f["md5sum"], f["filename"])

In [17]:
records

,source,target,md5sum,accession
2,igvf_003/nextseq/003_67A_R1.fastq.gz,igvf_003/nextseq/igvf_003_B02_D_next_N1_R1.fas...,35350d53cf858267d294bce69e475c83,https://api.data.igvf.org/sequence-files/IGVFF...
3,igvf_003/nextseq/003_67A_R2.fastq.gz,igvf_003/nextseq/igvf_003_B02_D_next_N1_R2.fas...,00c68ff0f9e0217d422c57e8948d4bb4,https://api.data.igvf.org/sequence-files/IGVFF...
4,igvf_003/nextseq/003_67B_R1.fastq.gz,igvf_003/nextseq/igvf_003_B03_D_next_N1_R1.fas...,79db765143bb23e14c613c9e1339e9f7,https://api.data.igvf.org/sequence-files/IGVFF...
5,igvf_003/nextseq/003_67B_R2.fastq.gz,igvf_003/nextseq/igvf_003_B03_D_next_N1_R2.fas...,c4787058f6b8304b1ddae0a55b48fb13,https://api.data.igvf.org/sequence-files/IGVFF...
6,igvf_003/nextseq/003_8A_R1.fastq.gz,igvf_003/nextseq/igvf_003_B01_D_next_N1_R1.fas...,bb696e63b6a8710ec8435b60ef6c81f8,
...,...,...,...,...
3098,igvf_b01/next2/B01_13F_R2.fastq.gz,igvf_b01/next2/igvf_b01_B06_D_next_N2_R2.fastq.gz,5f49893f54aaf88d06ca5834268a4e55,https://api.data.igvf.org/sequence-files/IGVFF...
3100,igvf_b01/next2/B01_13G_R1.fastq.gz,igvf_b01/next2/igvf_b01_B07_E_next_N2_R1.fastq.gz,2d4a0beb2e31d5981ebc56748297395b,https://api.data.igvf.org/sequence-files/IGVFF...
3102,igvf_b01/next2/B01_13G_R2.fastq.gz,igvf_b01/next2/igvf_b01_B07_E_next_N2_R2.fastq.gz,b3f5e2b91fc926c070c85c40e654cb0d,https://api.data.igvf.org/sequence-files/IGVFF...
3104,igvf_b01/next2/B01_13H_R1.fastq.gz,igvf_b01/next2/igvf_b01_B08_D_next_N2_R1.fastq.gz,cef06002f2986f0c305da0031910c1f0,https://api.data.igvf.org/sequence-files/IGVFF...
3106,igvf_b01/next2/B01_13H_R2.fastq.gz,igvf_b01/next2/igvf_b01_B08_D_next_N2_R2.fastq.gz,2a5a07155767a2f541cfb20e7d0636e0,https://api.data.igvf.org/sequence-files/IGVFF...