# Introduction

UCI has a complex google doc they've been using to track their samples so far.

https://docs.google.com/spreadsheets/d/13M6-Ry6oXgkx94BHZOGioYPI6F_hWDqjGgcaNu2JNYs/edit#gid=1838362486

Also there's a metadata spreadsheet for IGVF at
https://docs.google.com/spreadsheets/d/1BLMledzmqOqXnJHzpijgw91IOs-9tSlVeZDG_MtXddk/edit#gid=1284120531

In [1]:
import bz2
from collections import Counter, namedtuple
import datetime
from enum import IntEnum
from io import StringIO
import numpy
import os
import pandas
from pathlib import Path
import re
from subprocess import run, PIPE
import sys
import zoneinfo

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'mousedemo.settings')
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"

import django
from django.contrib.auth import get_user_model
from django.db import DEFAULT_DB_ALIAS

MOUSEDEMO = str(Path("mousedemo").absolute())
if MOUSEDEMO not in sys.path:
    sys.path.append(MOUSEDEMO)

# Pre-initialization setup

Backup the old ones and make a new database file before we initialize the database.

In [2]:
# Create a new database
result = run(["python3", "manage.py", "check"], capture_output=True)

if len(result.stderr) > 0:
    print(result.stderr.decode("utf-8"))
    
result.check_returncode()

In [3]:
initial = Path("igvf_mice/migrations/0001_initial.py")
if initial.exists():
    initial.unlink()
    
result = run(["python3", "manage.py", "makemigrations", "igvf_mice"], capture_output=True)

if len(result.stderr) > 0:
    print(result.stderr.decode("utf-8"))
    
result.check_returncode()

In [4]:
# Backup several old sqlite database files

db_name = Path("db.sqlite3")

backup_names = []
for i in range(0, 4):
    backup_names.append(Path("db{}.sqlite3".format(i+1)))

if backup_names[-1].exists():
    backup_names[-1].unlink()

if db_name.exists():    
    for i in reversed(range(0, 3)):
        if backup_names[i].exists():
            print("renaming {} to {}".format(backup_names[i], backup_names[i+1]))
            backup_names[i].rename(backup_names[i+1])

    db_name.rename(backup_names[0])
    print("renaming {} to {}".format(db_name, backup_names[0]))

renaming db3.sqlite3 to db4.sqlite3
renaming db2.sqlite3 to db3.sqlite3
renaming db1.sqlite3 to db2.sqlite3
renaming db.sqlite3 to db1.sqlite3

In [5]:
# Create a new database
result = run(["python3", "manage.py", "migrate"], capture_output=True)

if len(result.stderr) > 0:
    print(result.stderr.decode("utf-8"))
    
result.check_returncode()
    
assert Path("db.sqlite3").exists()

# Import django application code

We have to wait until the initial checks complete before we can start importing our application otherwise django has problems.

In [6]:
django.setup()

from django.contrib.auth.models import ContentType
from mousedemo import settings
from igvf_mice import models

from igvf_mice.io.validators import (
    validate_alias,
    validate_splitseq_cap_label,
)
from igvf_mice.io.converters import (
    date_or_none,
    datetime_or_none,
    float_or_none,
    int_or_none,
    positive_int_or_none,
    int_or_0,
    str_or_empty,
    str_or_none,
    normalize_barcode_index,
    normalize_plate_name,
    normalize_strain,
    normalize_subpool_submission_status,
    parse_mouse_name,
    join_mouse_name,
    parse_mouse_tissue,
    join_mouse_tissue,
    uci_tz_or_none,
    instrument_name_to_platform_id,
)
from igvf_mice.io.read_sheet import (
    import_mice,
    import_protocols,
    import_tissues,
    import_splitseq_samples,
    import_splitseq_ont_samples,
)
from igvf_mice.io.platelayout import (
    is_plate_name,
    PlateLayoutParser,
)
from igvf_mice.io.subpoolname import SubpoolName

# Setup users

Now that we have a fresh clean database, lets create user accounts

In [7]:
# Create accounts.
with open("pw", "rt") as instream:
    pw = instream.read().strip()

user_model = get_user_model()
user_model._default_manager.db_manager(DEFAULT_DB_ALIAS).create_superuser(
    username="diane",
    password=pw,   
)

# load igvf_mice permissions    
permissions = set()
for ct in ContentType.objects.filter(app_label="igvf_mice"):
    permissions.update(ct.permission_set.all())

with open("guest.pw", "rt") as instream:
    pw = instream.read().strip()

user_model = get_user_model()
guest = user_model._default_manager.db_manager(DEFAULT_DB_ALIAS).create_user(
    username="guest",
    password=pw,
    is_staff=True,
)
guest.user_permissions.set(permissions)
print(guest)

guest

In [8]:
guest = user_model._default_manager.db_manager(DEFAULT_DB_ALIAS).get(username="guest")
diane = guest = user_model._default_manager.db_manager(DEFAULT_DB_ALIAS).get(username="diane")

In [9]:
assert guest.is_staff

In [10]:
guest.user_permissions.all()

# Load data

In [11]:
#spreadsheet_name = "IGVF_Split-seq_20230118.xlsx"
# Sorce document https://docs.google.com/spreadsheets/d/13M6-Ry6oXgkx94BHZOGioYPI6F_hWDqjGgcaNu2JNYs/edit#gid=2088730991
lizs_sheet_name = "https://woldlab.caltech.edu/nextcloud/index.php/s/eEtjBfDqQFnLpSS/download"
# Source document https://docs.google.com/spreadsheets/d/1OJ8HETiLXF26ztb2CHPYIsBCO5A049ZV5OrXywOPsdI/edit#gid=1997889547
founder_sheet_name = "https://woldlab.caltech.edu/nextcloud/index.php/s/G7Ri92rDAi6oo68/download"
# source document https://docs.google.com/spreadsheets/d/1mCAcERVfwfNL7Th_8TXbP8Yoz5Udqq8gXn2aBn0Egcg/edit#gid=15587193
bridge_sheet_name = "https://woldlab.caltech.edu/nextcloud/index.php/s/TkgYZeFPJ97LDN8/download"
# F1 sheet source https://docs.google.com/spreadsheets/d/1eyMxMPlkSoOBc8BeU1bezPwgTn0fKqsKdRakBBo5ZSg/edit#gid=691742132
f1_sheet_name = "https://woldlab.caltech.edu/nextcloud/index.php/s/SymNiTR6g8fHYCx/download"

# Methylation sheet
ont_methylation = "https://woldlab.caltech.edu/nextcloud/index.php/s/SJQgqM4Ppzao4TW/download"

book = pandas.ExcelFile(lizs_sheet_name)
for name in book.sheet_names:
    print(name)

schedule - all
mice
Samples - CClines
CC Samples into experiment
Sheet95
Experiment
Plate setups
ONT Sequencing
sample_metadata
Sheet93
PBMCs - CClines
Protocols_description
Line information

# Sample sheet locations

In [12]:
sample_sheets = [
    (founder_sheet_name, "Samples - 8 founders"),
    (founder_sheet_name, "PBMCs - 8 founders"),
    (bridge_sheet_name, "Samples - Bridge"),
    (f1_sheet_name, "Samples - F1s"),
    (f1_sheet_name, "Samples - F1s_6mo"),
    (lizs_sheet_name, "Samples - CClines"),
]

# Load all submitted accession ids

In [13]:
def load_submitted_sheets():
    submitted_book_names = {
        # Sheets on sandbox
        "igvftst": {
            "IGVF_003": "https://woldlab.caltech.edu/nextcloud/index.php/s/nBnE6j2RBMkpM9i/download",
            "IGVF_b01": "https://woldlab.caltech.edu/nextcloud/index.php/s/5cJteSWgitN5BDM/download",
        },
        # Sheets on data. (production)
        "igvf": {
            "IGVF_b01": "https://woldlab.caltech.edu/nextcloud/index.php/s/HTbfN6btm3kqJXb/download",
            "IGVF_003": "https://woldlab.caltech.edu/nextcloud/index.php/s/wRFxdcknisFfM2t/download",
            "IGVF_004": "https://woldlab.caltech.edu/nextcloud/index.php/s/8ygLzeyjAQ9CxXn/download",
            "IGVF_005": "https://woldlab.caltech.edu/nextcloud/index.php/s/2Pba74eLFwmFfgS/download",
            # IGVF_006 failed.
            "IGVF_007": "https://woldlab.caltech.edu/nextcloud/index.php/s/7rQKGSTS7937kTW/download",
            "IGVF_008": "https://woldlab.caltech.edu/nextcloud/index.php/s/iECMTJF2iPMy3kT/download",
            "IGVF_008B": "https://woldlab.caltech.edu/nextcloud/index.php/s/YF46eNqSASJC8fr/download",
            "IGVF_009": "https://woldlab.caltech.edu/nextcloud/index.php/s/PtNn96zR9XbybFZ/download",
            "IGVF_010": "https://woldlab.caltech.edu/nextcloud/index.php/s/CocTP9pePJobyPs/download",
            "IGVF_011": "https://woldlab.caltech.edu/nextcloud/index.php/s/Sm72GtmdN4QsXJr/download",
            "IGVF_012": "https://woldlab.caltech.edu/nextcloud/index.php/s/MmatjmzQgofeM2Y/download",
            "IGVF_013": "https://woldlab.caltech.edu/nextcloud/index.php/s/EHret5a6Sjiro4q/download",
            "IGVF_014": "https://woldlab.caltech.edu/nextcloud/index.php/s/GRQCaSZ3WgeonzK/download",
        }
    }
    submitted_sheets = {}
    for accession_prefix in submitted_book_names:
        for book_name in submitted_book_names[accession_prefix]:
            print("reading {} {} {}".format(accession_prefix, book_name, submitted_book_names[accession_prefix][book_name]))
            book = pandas.ExcelFile(submitted_book_names[accession_prefix][book_name])

            for sheet_name in book.sheet_names:
                if sheet_name not in submitted_sheets.get(accession_prefix, {}):
                    submitted_sheets.setdefault(accession_prefix, {})[sheet_name] = book.parse(sheet_name)
                else:
                    previous_sheet = submitted_sheets[accession_prefix][sheet_name]
                    next_sheet = book.parse(sheet_name)
                    print("next_sheet {} {}".format(sheet_name, next_sheet.shape))
                    
                    already_seen = set(previous_sheet["accession"])
                    need_to_add = set(next_sheet["accession"]).difference(already_seen)
                    next_sheet = next_sheet[next_sheet["accession"].isin(need_to_add)]
                    print("next_sheet after duplicate filter {}".format(next_sheet.shape))
                    
                    submitted_sheets.setdefault(accession_prefix, {})[sheet_name] = pandas.concat([previous_sheet, next_sheet])
                print(accession_prefix, sheet_name, submitted_sheets[accession_prefix][sheet_name].shape)

    return submitted_sheets

submitted_sheets = load_submitted_sheets()

reading igvftst IGVF_003 https://woldlab.caltech.edu/nextcloud/index.php/s/nBnE6j2RBMkpM9i/download
igvftst rodent_donor (64, 25)
igvftst tissue (192, 9)
igvftst measurement_set (17, 12)
igvftst sequence_file (246, 14)
reading igvftst IGVF_b01 https://woldlab.caltech.edu/nextcloud/index.php/s/5cJteSWgitN5BDM/download
next_sheet rodent_donor (8, 25)
next_sheet after duplicate filter (8, 25)
igvftst rodent_donor (72, 25)
next_sheet tissue (8, 9)
next_sheet after duplicate filter (8, 9)
igvftst tissue (200, 9)
igvftst multiplexed_sample (8, 8)
next_sheet measurement_set (8, 13)
next_sheet after duplicate filter (8, 13)
igvftst measurement_set (25, 13)
next_sheet sequence_file (32, 14)
next_sheet after duplicate filter (32, 14)
igvftst sequence_file (278, 14)
igvftst configuration_file (16, 8)
reading igvf IGVF_b01 https://woldlab.caltech.edu/nextcloud/index.php/s/HTbfN6btm3kqJXb/download
igvf rodent_donor (8, 25)
igvf tissue (8, 9)
igvf multiplexed_sample (8, 7)
igvf measurement_set (10, 13)
igvf sequence_file (54, 22)
reading igvf IGVF_003 https://woldlab.caltech.edu/nextcloud/index.php/s/wRFxdcknisFfM2t/download
next_sheet rodent_donor (65, 25)
next_sheet after duplicate filter (65, 25)
igvf rodent_donor (73, 25)
next_sheet tissue (192, 9)
next_sheet after duplicate filter (192, 9)
igvf tissue (200, 9)
next_sheet multiplexed_sample (16, 7)
next_sheet after duplicate filter (16, 7)
igvf multiplexed_sample (24, 7)
next_sheet measurement_set (16, 13)
next_sheet after duplicate filter (16, 13)
igvf measurement_set (26, 16)
next_sheet sequence_file (246, 20)
next_sheet after duplicate filter (246, 20)
igvf sequence_file (300, 23)
reading igvf IGVF_004 https://woldlab.caltech.edu/nextcloud/index.php/s/8ygLzeyjAQ9CxXn/download
next_sheet rodent_donor (64, 25)
next_sheet after duplicate filter (0, 25)
igvf rodent_donor (73, 25)
next_sheet tissue (128, 9)
next_sheet after duplicate filter (64, 9)
igvf tissue (264, 9)
next_sheet multiplexed_sample (16, 7)
next_sheet after duplicate filter (16, 7)
igvf multiplexed_sample (40, 7)
next_sheet measurement_set (16, 13)
next_sheet after duplicate filter (16, 13)
igvf measurement_set (42, 16)
next_sheet sequence_file (246, 20)
next_sheet after duplicate filter (246, 20)
igvf sequence_file (546, 23)
reading igvf IGVF_005 https://woldlab.caltech.edu/nextcloud/index.php/s/2Pba74eLFwmFfgS/download
next_sheet rodent_donor (65, 25)
next_sheet after duplicate filter (0, 25)
igvf rodent_donor (73, 25)
next_sheet tissue (192, 9)
next_sheet after duplicate filter (128, 9)
igvf tissue (392, 9)
next_sheet multiplexed_sample (16, 7)
next_sheet after duplicate filter (16, 7)
igvf multiplexed_sample (56, 7)
next_sheet measurement_set (16, 13)
next_sheet after duplicate filter (16, 13)
igvf measurement_set (58, 16)
next_sheet sequence_file (242, 20)
next_sheet after duplicate filter (242, 20)
igvf sequence_file (788, 23)
reading igvf IGVF_007 https://woldlab.caltech.edu/nextcloud/index.php/s/7rQKGSTS7937kTW/download
next_sheet rodent_donor (65, 25)
next_sheet after duplicate filter (0, 25)
igvf rodent_donor (73, 25)
next_sheet tissue (256, 9)
next_sheet after duplicate filter (128, 9)
igvf tissue (520, 9)
next_sheet multiplexed_sample (16, 7)
next_sheet after duplicate filter (16, 7)
igvf multiplexed_sample (72, 7)
next_sheet measurement_set (16, 13)
next_sheet after duplicate filter (16, 13)
igvf measurement_set (74, 16)
next_sheet sequence_file (242, 20)
next_sheet after duplicate filter (242, 20)
igvf sequence_file (1030, 23)
reading igvf IGVF_008 https://woldlab.caltech.edu/nextcloud/index.php/s/iECMTJF2iPMy3kT/download
next_sheet rodent_donor (65, 25)
next_sheet after duplicate filter (1, 25)
igvf rodent_donor (74, 25)
next_sheet tissue (192, 9)
next_sheet after duplicate filter (64, 9)
igvf tissue (584, 9)
next_sheet multiplexed_sample (9, 7)
next_sheet after duplicate filter (9, 7)
igvf multiplexed_sample (81, 7)
next_sheet measurement_set (9, 13)
next_sheet after duplicate filter (9, 13)
igvf measurement_set (83, 16)
next_sheet sequence_file (76, 20)
next_sheet after duplicate filter (76, 20)
igvf sequence_file (1106, 23)
reading igvf IGVF_008B https://woldlab.caltech.edu/nextcloud/index.php/s/YF46eNqSASJC8fr/download
next_sheet rodent_donor (65, 25)
next_sheet after duplicate filter (0, 25)
igvf rodent_donor (74, 25)
next_sheet tissue (192, 9)
next_sheet after duplicate filter (0, 9)
igvf tissue (584, 9)
next_sheet multiplexed_sample (11, 7)
next_sheet after duplicate filter (11, 7)
igvf multiplexed_sample (92, 7)
next_sheet measurement_set (11, 13)
next_sheet after duplicate filter (11, 13)
igvf measurement_set (94, 16)
next_sheet sequence_file (86, 20)
next_sheet after duplicate filter (86, 20)
igvf sequence_file (1192, 23)
reading igvf IGVF_009 https://woldlab.caltech.edu/nextcloud/index.php/s/PtNn96zR9XbybFZ/download
next_sheet rodent_donor (65, 25)
next_sheet after duplicate filter (0, 25)
igvf rodent_donor (74, 25)
next_sheet tissue (128, 9)
next_sheet after duplicate filter (64, 9)
igvf tissue (648, 9)
next_sheet multiplexed_sample (16, 7)
next_sheet after duplicate filter (16, 7)
igvf multiplexed_sample (108, 7)
next_sheet measurement_set (16, 13)
next_sheet after duplicate filter (16, 13)
igvf measurement_set (110, 16)
next_sheet sequence_file (246, 20)
next_sheet after duplicate filter (246, 20)
igvf sequence_file (1438, 23)
reading igvf IGVF_010 https://woldlab.caltech.edu/nextcloud/index.php/s/CocTP9pePJobyPs/download
next_sheet rodent_donor (70, 25)
next_sheet after duplicate filter (5, 25)
igvf rodent_donor (79, 25)
next_sheet tissue (128, 9)
next_sheet after duplicate filter (64, 9)
igvf tissue (712, 9)
next_sheet multiplexed_sample (16, 7)
next_sheet after duplicate filter (16, 7)
igvf multiplexed_sample (124, 7)
next_sheet measurement_set (16, 13)
next_sheet after duplicate filter (16, 13)
igvf measurement_set (126, 16)
next_sheet sequence_file (246, 20)
next_sheet after duplicate filter (246, 20)
igvf sequence_file (1684, 23)
reading igvf IGVF_011 https://woldlab.caltech.edu/nextcloud/index.php/s/Sm72GtmdN4QsXJr/download
next_sheet rodent_donor (70, 25)
next_sheet after duplicate filter (0, 25)
igvf rodent_donor (79, 25)
next_sheet tissue (192, 9)
next_sheet after duplicate filter (0, 9)
igvf tissue (712, 9)
next_sheet multiplexed_sample (16, 7)
next_sheet after duplicate filter (16, 7)
igvf multiplexed_sample (140, 7)
next_sheet measurement_set (16, 13)
next_sheet after duplicate filter (16, 13)
igvf measurement_set (142, 16)
next_sheet sequence_file (246, 20)
next_sheet after duplicate filter (246, 20)
igvf sequence_file (1930, 23)
reading igvf IGVF_012 https://woldlab.caltech.edu/nextcloud/index.php/s/MmatjmzQgofeM2Y/download
next_sheet rodent_donor (11, 25)
next_sheet after duplicate filter (2, 25)
igvf rodent_donor (81, 25)
next_sheet tissue (14, 9)
next_sheet after duplicate filter (6, 9)
igvf tissue (718, 9)
next_sheet multiplexed_sample (8, 7)
next_sheet after duplicate filter (8, 7)
igvf multiplexed_sample (148, 7)
next_sheet measurement_set (8, 14)
next_sheet after duplicate filter (8, 14)
igvf measurement_set (150, 17)
next_sheet sequence_file (32, 20)
next_sheet after duplicate filter (32, 20)
igvf sequence_file (1962, 23)
reading igvf IGVF_013 https://woldlab.caltech.edu/nextcloud/index.php/s/EHret5a6Sjiro4q/download
next_sheet rodent_donor (96, 25)
next_sheet after duplicate filter (32, 25)
igvf rodent_donor (113, 25)
next_sheet tissue (96, 9)
next_sheet after duplicate filter (96, 9)
igvf tissue (814, 9)
next_sheet multiplexed_sample (15, 7)
next_sheet after duplicate filter (15, 7)
igvf multiplexed_sample (163, 7)
next_sheet measurement_set (15, 14)
next_sheet after duplicate filter (15, 14)
igvf measurement_set (165, 17)
next_sheet sequence_file (174, 20)
next_sheet after duplicate filter (174, 20)
igvf sequence_file (2136, 23)
reading igvf IGVF_014 https://woldlab.caltech.edu/nextcloud/index.php/s/GRQCaSZ3WgeonzK/download
next_sheet rodent_donor (8, 25)
next_sheet after duplicate filter (8, 25)
igvf rodent_donor (121, 25)
next_sheet tissue (8, 9)
next_sheet after duplicate filter (8, 9)
igvf tissue (822, 9)
next_sheet multiplexed_sample (8, 7)

next_sheet after duplicate filter (8, 7)
igvf multiplexed_sample (171, 7)
next_sheet measurement_set (8, 14)
next_sheet after duplicate filter (8, 14)
igvf measurement_set (173, 17)
next_sheet sequence_file (16, 20)
next_sheet after duplicate filter (16, 20)
igvf sequence_file (2152, 23)

# quick delete sql table

In [14]:
def truncate(model):
    table_name = model._meta.db_table
    assert "\\" not in table_name
    with django.db.connection.cursor() as cursor:
        # I don't know why the sql params didn't work. this is a sql vulnerability waiting to happen
        cursor.execute("delete from \"{}\"".format(table_name))
        cursor.execute("DELETE FROM SQLITE_SEQUENCE WHERE name=\"{}\"".format(table_name))
        cursor.fetchone()

# Initialize general use tables

These are fairly static tables that are mostly not currently coming from the spreadsheet.

Mouse strain used to but my and their needs drifted too far.

In [15]:
!{sys.executable} manage.py loaddata \
  source \
  platform \
  library_construction_reagent \
  librarybarcode \
  ontologyterm \
  mousestrain

Installed 523 object(s) from 6 fixture(s)

In [16]:
jax_source = models.Source.objects.get(name="jackson-labs")
unc_csbio_source = models.Source.objects.get(name="unc-csbio")

In [17]:
strain_code_to_name = {x.name: x.display_name for x in models.MouseStrain.objects.all()}
strain_code_to_name["B6129SF1J"] = strain_code_to_name["B6129S1F1J"]
strain_name_to_code = {x.display_name: x.name for x in models.MouseStrain.objects.all()}
strain_name_to_code["B6129SF1J"] = strain_name_to_code["B6129S1F1/J"]

# Check for new tissue terms

In [18]:
tissue_dissection_to_ontology_map = {
    'Hypothalamus/Pituitary': [("UBERON:0001898","hypothalamus"), ("UBERON:0000007","pituitary gland")],
    'Cerebellum': [("UBERON:0002037","cerebellum")],
    # Hippocampus might be:
    #   Hippocampal formation UBERON:0002421 https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002421
    #   Layer of hippocampus UBERON:0002305 https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002305
    'Cortex/Hippocampus left': [("NTR:0000646","left cerebral cortex"), ("NTR:0000750", "Hippocampal formation left")],
    'Cortex/Hippocampus right': [("NTR:0000647","right cerebral cortex"), ("NTR:0000751", "Hippocampal formation right")],
    'Liver': [("UBERON:0002107", "liver")],
    'Heart': [("UBERON:0000948","heart")],
    'Lung': [("UBERON:0002048","lung")],
    'Adrenal': [("UBERON:0002369","adrenal gland")],
    'Kidney': [("UBERON:0002113","kidney")],
    'Kidney left': [("UBERON:0002113","kidney")],
    'Kidney right': [("UBERON:0002113","kidney")],
    "Ovary": [("UBERON:0000992", "ovary")],    
    'Gonads -1 Ovary': [("UBERON:0000992", "ovary")],
    'Gonads -1 (Ovary)': [("UBERON:0000992", "ovary")],
    'Oviduct': [("UBERON:0000993","oviduct")],
    'Gonads -2 Oviduct': [("UBERON:0000993","oviduct")],
    'Gonads -2 (Oviduct)': [("UBERON:0000993","oviduct")],
    'Gonads - 2 (Oviduct)': [("UBERON:0000993","oviduct")],
    'Perigonadal fat': [("UBERON:0003428", "gonadal fat pad")], #"is closer" to dissection
    'Brown fat': [("UBERON:0001348","brown adipose tissue")], 
    'Soleus': [("UBERON:0001389","soleus muscle")],
    'Plantaris': [("UBERON:0011905","plantaris")],
    'Gastrocnemius': [("UBERON:0001388","gastrocnemius")],
    'Gastrocnemius left': [("UBERON:0001388","gastrocnemius")],
    'Gastrocnemius right': [("UBERON:0001388","gastrocnemius")],
    'TA': [("UBERON:0001385","tibialis anterior")],
    'TA left': [("UBERON:0001385","tibialis anterior")],
    'TA right': [("UBERON:0001385","tibialis anterior")],
    'EDL': [("UBERON:0001386","extensor digitorum longus")],
    'Tail': [("UBERON:0002415","tail")],
    'PBMC - WBC': [("CL:2000001", "peripheral blood mononuclear cell")],
    'Gonads -1 Testis': [("UBERON:0000473","testis")],
    'Gonads -2 Epididymis': [("UBERON:0001301","epididymis")],
    "Left cortex": [("NTR:0000646","left cerebral cortex"),],
    "Cortex left": [("NTR:0000646","left cerebral cortex"),],
    "Right cortex": [("NTR:0000647","right cerebral cortex"),],
    "Cortex right": [("NTR:0000647","right cerebral cortex"),],
    "Left hippocampus": [("NTR:0000750", "Hippocampal formation left")],
    "Hippocampus left": [("NTR:0000750", "Hippocampal formation left")],
    "Right hippocampus": [("NTR:0000751", "Hippocampal formation right")],
    "Hippocampus right": [("NTR:0000751", "Hippocampal formation right")],
    # does left & right matter?
    "Testis left": [("UBERON:0000473", "Testis")],
    "Testis right": [("UBERON:0000473", "Testis")],
    "Epididymis left": [("UBERON:0001301", "Epididymis")],
    "Epididymis right": [("UBERON:0001301", "Epididymis")],
    "Pancreas": [("UBERON:0001264", "Pancreas")],
    "Lungs": [("UBERON:0002048", "Lung")],
}

In [19]:
# We need to map the names used in the spreadsheet to names in the database.

def check_for_new_tissues():
    #term_names = {record.name for record in models.OntologyTerm.objects.all()}
    
    for book_url, sample_sheet_name in sample_sheets:
        tissue_sheet = pandas.read_excel(
            book_url, 
            sample_sheet_name,
            usecols=["Tissue"]).dropna(axis=0, how='all')

        for i, row in tissue_sheet.iterrows():
            if not pandas.isnull(row["Tissue"]):
                if not row["Tissue"] in tissue_dissection_to_ontology_map:
                    print(f"{row['Tissue']} is new first seen in {sample_sheet_name}")
                    term_names.add(row['Tissue'])

check_for_new_tissues()

# Load protocol links

In [20]:
def load_protocols():
    protocol_sheet = pandas.read_excel(
        lizs_sheet_name, 
        sheet_name="Protocols_description",
        header=0,
    ).dropna(axis=0, how="all")
    
    import_protocols(protocol_sheet)
    
    protocols = { x.name: x for x in models.ProtocolLink.objects.all()}
    return protocols

protocols = load_protocols()
print(len(protocols))

15

In [21]:
def load_submitted_mice():
    submitted_mice = {
    }

    for accession_prefix in submitted_sheets:
        for i, row in submitted_sheets[accession_prefix]["rodent_donor"].iterrows():
            if not pandas.isnull(row["accession"]):
                rodent_identifier = row["rodent_identifier"]
                if accession_prefix == "igvftst":
                    see_also_template = "https://api.sandbox.igvf.org/rodent-donors/{}/"
                elif accession_prefix == "igvf":
                    see_also_template = "https://api.data.igvf.org/rodent-donors/{}/"
                if pandas.notnull(row["accession"]):
                    submitted_mice.setdefault(rodent_identifier, []).append({
                        "accession_prefix": accession_prefix,
                        "name": row["accession"],
                        "uuid": row["uuid"],
                        "see_also": see_also_template.format(row["accession"]),
                    })

    print("Loaded {} submitted mice".format(len(submitted_mice)))
    return submitted_mice

In [22]:
def normalize_mice_date(date_column, time_column):
    for i, (date, time) in enumerate(zip(date_column, time_column)):
        if pandas.isnull(date):
            yield None
        elif pandas.isnull(time):
            yield None
        elif date == "-" or time == "-":
            yield None
        elif isinstance(date, str):
            raise ValueError(f"Invalid type in date row {i} {date} {type(date)}")
            yield None
        elif isinstance(date, datetime.time):
            raise ValueError(f"Time in date field on row {i} {date} {type(date)}")
            yield None
        elif isinstance(time, str):
            raise ValueError(f"Invalid type in time row {i} {time} {type(time)}")
            yield None
        else:
            yield datetime.datetime.combine(date, time)


def estrus_cycle(x):
    estrus_stage = {
        "unknown": str(models.EstrusCycle.UNKNOWN),
        "anestrus": str(models.EstrusCycle.ANESTRUS),
        "anestrus>proestrus": str(models.EstrusCycle.ANESTRUS_PROESTRUS),
        "proestrus": str(models.EstrusCycle.PROESTRUS),
        "proestrus/proestrus": str(models.EstrusCycle.PROESTRUS),
        "proestrus>estrus": str(models.EstrusCycle.PROESTRUS_ESTRUS),
        "estrus": str(models.EstrusCycle.ESTRUS),
        "estrus?": str(models.EstrusCycle.ESTRUS),
        "estrus/estrus": str(models.EstrusCycle.ESTRUS),
        "estrus/mestrus": str(models.EstrusCycle.ESTRUS_METESTRUS),
        "mestrus": str(models.EstrusCycle.ESTRUS_METESTRUS),
        "metestrus": str(models.EstrusCycle.METESTRUS),
        "metestrus/metestrus": str(models.EstrusCycle.METESTRUS),
        "metestrus>diestrus": str(models.EstrusCycle.METESTRUS_DIESTRUS),
        "metestrus/diestrus": str(models.EstrusCycle.METESTRUS_DIESTRUS),
        "diestrus/mestrus": str(models.EstrusCycle.METESTRUS_DIESTRUS),
        "diestrus": str(models.EstrusCycle.DIESTRUS),
        "diestrus/diestrus": str(models.EstrusCycle.DIESTRUS),
        "diestrus>proestrus": str(models.EstrusCycle.DIESTRUS_PROESTRUS),
    }
    
    if pandas.isnull(x):
        return "NA"
    else:
        return estrus_stage[x.lower()]

    
def get_sex_code(x):
    if pandas.isnull(x) or len(x) == 0:
        return None
    else:
        return {
            "female": str(models.SexEnum.FEMALE),
            "male": str(models.SexEnum.MALE),
            "other": str(models.SexEnum.OTHER),
        }[x.lower()]

def get_timepoint(x):
    if pandas.isnull(x) or len(x) == 0:
        return None
    else:
        return int_or_none(x.split()[0])

def get_timepoint_units(x):
    timepoints = {
        "days": str(models.TimeUnitsEnum.DAY),
        "weeks": str(models.TimeUnitsEnum.WEEK),
        "months": str(models.TimeUnitsEnum.MONTH),
        "years": str(models.TimeUnitsEnum.YEAR),        
    }
    
    if pandas.isnull(x) or len(x) == 0:
        return None
    else:
        return timepoints[x.split()[1]]

def normalize_mice_name(name):
    if pandas.isnull(name):
        return  name

    if name == "056_WSBJ_10F->PWKJ_9F":
        name = "056_PWKJ_9F"

    if not name[-1] in ("M", "F"):
        raise ValueError(f"Unrecognized sex field in {name}")        

    name_fields = name.split("_")

    # deal with TERM2R47HNSS_HO
    if len(name_fields) > 3:
        name_fields = [name_fields[0], "_".join(name_fields[1:-1]), name_fields[-1]]
        
    name_fields[1] = normalize_strain(name_fields[1])

    if not name_fields[1] in strain_code_to_name:
        raise ValueError(f"strain background in {name} not recognized line {i+1}")
        
    return "_".join(name_fields)


def normalize_mice_strain_name(x):
    if x in strain_name_to_code:
        return x
    elif x in strain_code_to_name:
        return strain_code_to_name[x]
    else:
        raise ValueError(f"Unrecognized strain name {x}")
        

def load_spreadsheet_mice():
    mice = pandas.read_excel(
        lizs_sheet_name, 
        sheet_name="mice", 
        converters={
            #"Dissection ID": int,
            #"RMS number": int_or_none,
            "Sex": get_sex_code,
            "Strain": normalize_mice_strain_name,
        }
    )
    
    print("Loaded", mice.shape[0])
    has_dissection = pandas.notnull(mice["Dissection ID"])
    has_name = pandas.notnull(mice["Mouse Name"])
    has_strain = pandas.notnull(mice["Strain"])
    has_sex = pandas.notnull(mice["Sex"])
    mice = mice[has_name & has_dissection & has_strain & has_sex]
    print("Filtered null rows", mice.shape[0])
    mice["Mouse Name"] = mice["Mouse Name"].apply(normalize_mice_name)
    mouse_name_fields = mice["Mouse Name"].apply(parse_mouse_name)
    mice["Mouse code"] = [x[1] for x in mouse_name_fields]
    for field_name in ["Dissection start time", "Dissection finish time"]:
        mice[field_name] = list(normalize_mice_date(mice["Dissection Date"], mice[field_name]))
    mice["estrus_cycle"] = mice["Estrus cycle stage"].apply(estrus_cycle)
    mice["Strain code"] = mice["Strain"].apply(strain_name_to_code.get)
    mice = mice.drop(columns=["Dissection Date", "Estrus cycle stage"])
    
    timepoints = mice["Timepoint"].apply(get_timepoint)
    timepoint_units = mice["Timepoint"].apply(get_timepoint_units)
    mice["Timepoint"] = timepoints
    mice["Timepoint unit"] = timepoint_units
    mice = mice[pandas.notnull(mice["Timepoint"])]
    
    for i, row in mice.iterrows():
        dissection_prefix = "{:03}".format(row["Dissection ID"])
        if not row["Mouse Name"].startswith(dissection_prefix):
            raise ValueError(f"mouse name {row['Mouse Name']} does not start with {dissection_prefix}")

        
    return mice

mice = load_spreadsheet_mice()
mice

Loaded 1000
Filtered null rows 719

,Dissection ID,Mouse Name,Strain,Sex,Timepoint,DOB,UNC,Operator,Dissection start time,Dissection finish time,Weight (g),Jax Stock number,RMS number,Housing number,Comments,Mouse code,estrus_cycle,Strain code,Timepoint unit
1,16,016_B6J_10F,C57BL/6J,F,10.0,2022-08-16,NaN,GM/SK/HL/ER/GF,2022-10-27 09:01:00,NaT,21.1,#000664,14669,400802.0,More fat around heart and lungs (in whole strain),B6J,D,B6J,W
2,17,017_B6J_10M,C57BL/6J,M,10.0,2022-08-16,NaN,GM/SK/HL/ER/GF,2022-10-27 11:44:00,NaT,26.3,#000664,14670,400803.0,NaN,B6J,NA,B6J,W
3,18,018_B6J_10F,C57BL/6J,F,10.0,2022-08-16,NaN,GM/SK/HL/ER/GF,2022-10-27 09:38:00,NaT,21.0,#000664,14669,400802.0,NaN,B6J,P,B6J,W
4,19,019_B6J_10M,C57BL/6J,M,10.0,2022-08-16,NaN,GM/SK/HL/ER/GF,2022-10-27 12:12:00,NaT,29.0,#000664,14670,400804.0,NaN,B6J,NA,B6J,W
5,20,020_B6J_10F,C57BL/6J,F,10.0,2022-08-16,NaN,GM/SK/HL/ER/GF,2022-10-27 10:14:00,NaT,18.5,#000664,14669,400802.0,NaN,B6J,D,B6J,W
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,735,735_CC057_10M,CC057,M,10.0,2023-12-02,NaN,SK/HL/GF,2024-02-14 13:02:00,2024-02-14 13:20:00,30.0,NaN,NaN,NaN,bigger head,CC057,NA,CC057,W
731,737,737_CC057_10M,CC057,M,10.0,2023-12-02,NaN,SK/HL/GF,2024-02-14 14:10:00,2024-02-14 14:27:00,28.9,NaN,NaN,NaN,NaN,CC057,NA,CC057,W
733,739,739_CC074_10M,CC074,M,10.0,2024-12-16,NaN,SK/HL/GF,2024-02-21 13:22:00,2024-02-21 13:43:00,22.3,NaN,NaN,NaN,"fragile, puffy brain, soft muscles, some parts...",CC074,NA,CC074,W
737,743,743_CC065_10M,CC065,M,10.0,2024-02-18,5907.0,SK/HL/GF,2024-04-29 14:18:00,2024-04-29 14:42:00,28.3,NaN,NaN,NaN,hypo tip wrap a little trunkated,CC065,NA,CC065,W
743,747,747_CC025_10M,CC025,M,10.0,NaT,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,CC025,NA,CC025,W

In [23]:
mice[mice["Mouse Name"] == "128_B6AF1J_10F"]

,Dissection ID,Mouse Name,Strain,Sex,Timepoint,DOB,UNC,Operator,Dissection start time,Dissection finish time,Weight (g),Jax Stock number,RMS number,Housing number,Comments,Mouse code,estrus_cycle,Strain code,Timepoint unit
115,128,128_B6AF1J_10F,B6AF1/J,F,10.0,2023-06-27,NaN,SK/HL/GF,2023-09-07 09:43:00,2023-09-07 10:05:00,18.3,NaN,NaN,NaN,NaN,B6AF1J,D,B6AF1J,W

## import mice into database

In [24]:
print("Added", import_mice(mice, load_submitted_mice()))

Loaded 121 submitted mice
Currently have 718 mice loaded
Added 718

# Tissues

In [25]:
sample_sheets

[('https://woldlab.caltech.edu/nextcloud/index.php/s/G7Ri92rDAi6oo68/download',
  'Samples - 8 founders'),
 ('https://woldlab.caltech.edu/nextcloud/index.php/s/G7Ri92rDAi6oo68/download',
  'PBMCs - 8 founders'),
 ('https://woldlab.caltech.edu/nextcloud/index.php/s/TkgYZeFPJ97LDN8/download',
  'Samples - Bridge'),
 ('https://woldlab.caltech.edu/nextcloud/index.php/s/SymNiTR6g8fHYCx/download',
  'Samples - F1s'),
 ('https://woldlab.caltech.edu/nextcloud/index.php/s/SymNiTR6g8fHYCx/download',
  'Samples - F1s_6mo'),
 ('https://woldlab.caltech.edu/nextcloud/index.php/s/eEtjBfDqQFnLpSS/download',
  'Samples - CClines')]

In [26]:

def validate_mouse_genotype_and_strain(genotype, strain):
    if genotype.upper() == "TREM2R47HNSS_HO":
        expected_genotype = "TREM2"
    else:
        expected_genotype = genotype
        
    if expected_genotype != strain:
        raise ValueError("Expected genotype {} does not match detected strain {}".format(
            expected_genotype, strain))
    
def load_tissue_sheets(mice):
    tissues = []
    for book_url, tissue_sheet in sample_sheets:
        tissue = pandas.read_excel(
            book_url, 
            sheet_name=tissue_sheet,
            header=0,
        ).dropna(axis=0, how="all")

        if "tube+tissue wight (g)" in tissue.columns:
            print(f"{tissue_sheet} has typoed wight column, renaming to weight")
            tissue = tissue.rename(columns={
                "tube+tissue wight (g)": "tube+tissue weight (g)"
            })
               
        tissue = tissue.rename(columns={
            "Approx. sac time": "Dissection start",
            "Dissection Start": "Dissection start",
            "Dissection End": "Dissection end",
            "Blood volume (mL)": "volume (mL)",
            "# PBMCs before fixation (x 10^6)": "cells before fixation (x 10^6)",
            "-80C box": "IGVF Sample BOX",
        })

        for time_name in ["Dissection start", "Dissection end"]:
            if time_name in tissue.columns:
                tissue[time_name] = list(normalize_mice_date(tissue["Dissection date"], tissue[time_name]))
            #else:
            #    tissue["Dissection end"] = [None] * tissue.shape[0]
            
        print(tissue_sheet, tissue.shape)
        tissues.append(tissue)

    combined = pandas.concat(tissues)
    # force column names to be lowercase
    combined.columns = [x.lower() for x in combined.columns]
    has_tissue_id = pandas.notnull(combined["mouse_tissue id"])
    has_tissue = pandas.notnull(combined["tissue"])
    has_box = combined["igvf sample box"].apply(lambda x: x != "DNA Extraction Optimization")
    has_genotype = pandas.notnull(combined["genotype"])
    combined = combined[has_tissue_id & has_tissue & has_box & has_genotype]
    print("Total after filtering", combined.shape)
    
    combined["mouse_tissue id"] = combined["mouse_tissue id"].apply(normalize_strain)

    mouse_tissue_name_fields = combined["mouse_tissue id"].apply(parse_mouse_tissue)
    #for row in mouse_tissue_name_fields:
    #    if not row.mouse_strain in mouse_strain_code_to_name:
    #        raise ValueError(f"tissue strain field in {row} not recognized")

    combined["mouse name"] = mouse_tissue_name_fields.apply(join_mouse_name)
    combined["tissue_name"] = combined["tissue"].apply(lambda tissue: [x[1] for x in tissue_dissection_to_ontology_map[tissue]])
    combined["tissue_id"] = combined["tissue"].apply(lambda tissue: [x[0] for x in tissue_dissection_to_ontology_map[tissue]])

    mice = mice.set_index("Mouse Name")
    mice_name = set(mice.index)
    combined_mice = set(combined["mouse name"])
    print("Dropping", sorted(combined_mice.difference(mice_name)))
    combined = combined[combined["mouse name"].isin(mice_name)]
    print("Total after filtering for mice", combined.shape)

    for i, row in combined.iterrows():
        # this is the "label swap" on spreadsheet rows 602-605.
        if row["mouse name"] == "092_CASTJ_10F":
            row["genotype"] = "CASTJ"
            #combined.loc[i, "Genotype"] = "CASTJ"
        # this is the other half the swap on spreadsheet rows 1522-1525
        elif row["mouse name"] == "046_NZOJ_10F":
            row["genotype"] = 'NZOJ'
            #combined.loc[i, "Genotype"] = 'NZOJ'
            
        validate_mouse_genotype_and_strain(row["genotype"], mice.loc[row["mouse name"], "Mouse code"])

    assert "tube+tissue wight (g)" not in combined.columns
    return combined

tissue_sheets = load_tissue_sheets(mice)
tissue_sheets.head()

Samples - 8 founders (1621, 16)
PBMCs - 8 founders (81, 7)
Samples - Bridge (416, 23)
Samples - F1s (2090, 18)
Samples - F1s_6mo (1190, 18)
Samples - CClines (6810, 18)
Total after filtering (12183, 29)
Dropping ['056_WSBJ_10F', '741_CC018_10M', '745_CC008_10M', '748_B6J_10F', '749_B6J_10M', '750_B6J_10F', '751_B6J_10M', '752_B6J_10F', '753_B6J_10M', '754_B6J_10F', '755_B6J_10M', '756_B6J_10F', '757_B6J_10M']
Total after filtering for mice (11976, 32)

,igvf sample box,mouse_tissue id,unnamed: 2,tissue,sex,genotype,tube label,tube weight (g),tube+tissue weight (g),tissue weight (mg) or blood volume (ul),...,pbmc rsb after rbc lysis,total # pbmcs,cryopreserved pbmc location,dissection end,body weight (g),collector,photographer,mouse name,tissue_name,tissue_id
0,IGVF_Sample_5,016_B6J_10F_01,NaN,Hypothalamus/Pituitary,F,B6J,016-01,1.046,1.118,72.0,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,016_B6J_10F,"[hypothalamus, pituitary gland]","[UBERON:0001898, UBERON:0000007]"
1,IGVF_Sample_5,016_B6J_10F_02,NaN,Cerebellum,F,B6J,016-02,1.046,NaN,-1046.0,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,016_B6J_10F,[cerebellum],[UBERON:0002037]
2,IGVF_Sample_5,016_B6J_10F_03,NaN,Cortex/Hippocampus left,F,B6J,016-03,1.040,1.181,141.0,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,016_B6J_10F,"[left cerebral cortex, Hippocampal formation l...","[NTR:0000646, NTR:0000750]"
3,IGVF_Sample_5,016_B6J_10F_04,NaN,Cortex/Hippocampus right,F,B6J,016-04,1.048,NaN,-1048.0,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,016_B6J_10F,"[right cerebral cortex, Hippocampal formation ...","[NTR:0000647, NTR:0000751]"
4,IGVF_Sample_5,016_B6J_10F_05,NaN,Liver,F,B6J,016-05,1.133,2.099,966.0,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,016_B6J_10F,[liver],[UBERON:0002107]

In [27]:
%debug

ERROR:root:No traceback has been produced, nothing to debug.

In [28]:
parse_mouse_tissue("128_B6AF1J_10M_33")

mouse_tissue_tuple(mouse_id='128', mouse_strain='B6AF1J', mouse_age='10', mouse_sex='M', tissue_id='33')

In [29]:
tissue_sheets[tissue_sheets["mouse_tissue id"].apply(lambda x: x.startswith("128_"))]

,igvf sample box,mouse_tissue id,unnamed: 2,tissue,sex,genotype,tube label,tube weight (g),tube+tissue weight (g),tissue weight (mg) or blood volume (ul),...,pbmc rsb after rbc lysis,total # pbmcs,cryopreserved pbmc location,dissection end,body weight (g),collector,photographer,mouse name,tissue_name,tissue_id
16,NaN,128_B6AF1J_10F_01,NaN,Hypothalamus/Pituitary,F,B6AF1J,128_01,1.038,1.119,81.0,...,NaN,NaN,NaN,2023-09-07 10:05:00,NaN,ET,ET,128_B6AF1J_10F,"[hypothalamus, pituitary gland]","[UBERON:0001898, UBERON:0000007]"
17,NaN,128_B6AF1J_10F_03,NaN,Cortex/Hippocampus left,F,B6AF1J,128_03,1.039,1.163,124.0,...,NaN,NaN,NaN,2023-09-07 10:05:00,NaN,ET,ET,128_B6AF1J_10F,"[left cerebral cortex, Hippocampal formation l...","[NTR:0000646, NTR:0000750]"
18,NaN,128_B6AF1J_10F_04,NaN,Cortex/Hippocampus right,F,B6AF1J,128_04,1.035,NaN,-1035.0,...,NaN,NaN,NaN,2023-09-07 10:05:00,NaN,ET,ET,128_B6AF1J_10F,"[right cerebral cortex, Hippocampal formation ...","[NTR:0000647, NTR:0000751]"
19,NaN,128_B6AF1J_10F_05,NaN,Liver,F,B6AF1J,128_05,1.138,2.011,873.0,...,NaN,NaN,NaN,2023-09-07 10:05:00,NaN,NM,NM,128_B6AF1J_10F,[liver],[UBERON:0002107]
20,NaN,128_B6AF1J_10F_06,NaN,Heart,F,B6AF1J,128_06,1.039,1.306,267.0,...,NaN,NaN,NaN,2023-09-07 10:05:00,NaN,NM,NM,128_B6AF1J_10F,[heart],[UBERON:0000948]
21,NaN,128_B6AF1J_10F_08,NaN,Adrenal,F,B6AF1J,128_08,1.035,1.058,23.0,...,NaN,NaN,NaN,2023-09-07 10:05:00,NaN,NM,NM,128_B6AF1J_10F,[adrenal gland],[UBERON:0002369]
22,NaN,128_B6AF1J_10F_10,NaN,Gonads -1 (Ovary),F,B6AF1J,128_10,1.039,1.055,16.0,...,NaN,NaN,NaN,2023-09-07 10:05:00,NaN,NM,NM,128_B6AF1J_10F,[ovary],[UBERON:0000992]
23,NaN,128_B6AF1J_10F_11,NaN,Gonads - 2 (Oviduct),F,B6AF1J,128_11,1.038,1.054,16.0,...,NaN,NaN,NaN,2023-09-07 10:05:00,NaN,NM,NM,128_B6AF1J_10F,[oviduct],[UBERON:0000993]
24,NaN,128_B6AF1J_10F_19,NaN,Tail,F,B6AF1J,128_19,1.038,NaN,-1038.0,...,NaN,NaN,NaN,2023-09-07 10:05:00,NaN,NM,NM,128_B6AF1J_10F,[tail],[UBERON:0002415]
25,NaN,128_B6AF1J_10F_20,NaN,PBMC - WBC,F,B6AF1J,128_20,6.008,NaN,-6008.0,...,NaN,NaN,NaN,2023-09-07 10:05:00,NaN,NM,NM,128_B6AF1J_10F,[peripheral blood mononuclear cell],[CL:2000001]
26,NaN,128_B6AF1J_10F_31,NaN,Kidney left,F,B6AF1J,128_31,1.040,1.178,138.0,...,NaN,NaN,NaN,2023-09-07 10:05:00,NaN,NM,NM,128_B6AF1J_10F,[kidney],[UBERON:0002113]
27,NaN,128_B6AF1J_10F_32,NaN,Kidney right,F,B6AF1J,128_32,1.036,NaN,-1036.0,...,NaN,NaN,NaN,2023-09-07 10:05:00,NaN,NM,NM,128_B6AF1J_10F,[kidney],[UBERON:0002113]
28,NaN,128_B6AF1J_10F_33,NaN,Gastrocnemius left,F,B6AF1J,128_33,1.033,1.154,121.0,...,NaN,NaN,NaN,2023-09-07 10:05:00,NaN,ET,ET,128_B6AF1J_10F,[gastrocnemius],[UBERON:0001388]
29,NaN,128_B6AF1J_10F_34,NaN,Gastrocnemius right,F,B6AF1J,128_34,1.043,NaN,-1043.0,...,NaN,NaN,NaN,2023-09-07 10:05:00,NaN,ET,ET,128_B6AF1J_10F,[gastrocnemius],[UBERON:0001388]

In [30]:
tissue_sheets[tissue_sheets["mouse_tissue id"] == "016_B6J_10F_16"]  #[["mouse_tissue id", "dissection start", "dissection end"]]

,igvf sample box,mouse_tissue id,unnamed: 2,tissue,sex,genotype,tube label,tube weight (g),tube+tissue weight (g),tissue weight (mg) or blood volume (ul),...,pbmc rsb after rbc lysis,total # pbmcs,cryopreserved pbmc location,dissection end,body weight (g),collector,photographer,mouse name,tissue_name,tissue_id
15,IGVF_Sample_5,016_B6J_10F_16,NaN,Gastrocnemius,F,B6J,016-16,1.047,1.273,226.0,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,016_B6J_10F,[gastrocnemius],[UBERON:0001388]

In [31]:
tissue_sheets["parsed_mouse_tissue"] = tissue_sheets["mouse_tissue id"].apply(parse_mouse_tissue)

tissue_map = {}
for i, row in tissue_sheets.iterrows():
    tissue_map.setdefault(row.parsed_mouse_tissue.tissue_id, set()).add(",".join(row.tissue_name))

In [32]:
tissue_map

{'01': {'hypothalamus,pituitary gland'},
 '02': {'cerebellum', 'left cerebral cortex,Hippocampal formation left'},
 '03': {'left cerebral cortex,Hippocampal formation left',
  'right cerebral cortex,Hippocampal formation right'},
 '04': {'cerebellum', 'right cerebral cortex,Hippocampal formation right'},
 '05': {'liver'},
 '06': {'heart'},
 '07': {'Lung', 'lung'},
 '08': {'adrenal gland'},
 '09': {'kidney'},
 '10': {'ovary', 'testis'},
 '11': {'epididymis', 'oviduct'},
 '12': {'gonadal fat pad'},
 '13': {'brown adipose tissue'},
 '14': {'soleus muscle'},
 '15': {'plantaris'},
 '16': {'gastrocnemius'},
 '17': {'tibialis anterior'},
 '18': {'extensor digitorum longus'},
 '19': {'tail'},
 '20': {'peripheral blood mononuclear cell'},
 '020': {'peripheral blood mononuclear cell'},
 '21': {'left cerebral cortex'},
 '22': {'Hippocampal formation left', 'right cerebral cortex'},
 '23': {'Hippocampal formation left', 'right cerebral cortex'},
 '24': {'Hippocampal formation right'},
 '27': {'Testis'},
 '28': {'Testis'},
 '29': {'Epididymis'},
 '30': {'Epididymis'},
 '31': {'Epididymis', 'kidney'},
 '32': {'kidney'},
 '33': {'gastrocnemius'},
 '34': {'Pancreas', 'gastrocnemius'},
 '35': {'Pancreas', 'tibialis anterior'},
 '36': {'tibialis anterior'}}

these two in Samples - Bridge were tissue swapped
- 100_CASTJ_10F_22
- 100_CASTJ_10F_23

In [33]:
tissue_sheets[tissue_sheets["mouse_tissue id"].str.endswith("23")][["mouse_tissue id", "tissue"]]

      mouse_tissue id            tissue
4    097_CASTJ_10M_23  Left hippocampus
10   098_CASTJ_10F_23  Left hippocampus
16   099_CASTJ_10M_23  Left hippocampus
22   100_CASTJ_10F_23      Right cortex
28   101_CASTJ_10M_23  Left hippocampus
34   102_CASTJ_10F_23  Left hippocampus
40   103_CASTJ_10M_23  Left hippocampus
46   104_CASTJ_10F_23  Left hippocampus
52   105_CASTJ_10M_23  Left hippocampus
58   106_CASTJ_10F_23  Left hippocampus
64   107_CASTJ_10M_23  Left hippocampus
70   108_CASTJ_10F_23  Left hippocampus
76     109_B6J_10M_23  Left hippocampus
82     110_B6J_10F_23  Left hippocampus
88     111_B6J_10M_23  Left hippocampus
94     112_B6J_10F_23  Left hippocampus
100    113_B6J_10M_23  Left hippocampus
106    114_B6J_10F_23  Left hippocampus
112    115_B6J_10M_23  Left hippocampus
118    116_B6J_10F_23  Left hippocampus
124    117_B6J_10M_23  Left hippocampus
130    118_B6J_10F_23  Left hippocampus
136    119_B6J_10M_23  Left hippocampus
142    120_B6J_10F_23  Left hippocampus
220    255_B6J_10M_23  Hippocampus left
240    256_B6J_10F_23  Hippocampus left
254    257_B6J_10M_23  Hippocampus left
274    258_B6J_10F_23  Hippocampus left
288  259_CASTJ_10M_23  Hippocampus left
308  260_CASTJ_10F_23  Hippocampus left
322  261_CASTJ_10M_23  Hippocampus left
342  262_CASTJ_10F_23  Hippocampus left
356  263_CASTJ_10M_23  Hippocampus left
376  264_CASTJ_10F_23  Hippocampus left
390  265_CASTJ_10M_23  Hippocampus left
410  266_CASTJ_10F_23  Hippocampus left

In [34]:
tissue_sheets[tissue_sheets["mouse_tissue id"].str.endswith("35") & (tissue_sheets["tissue"].str.endswith("TA left") == True)][["mouse_tissue id", "tissue"]]

    mouse_tissue id   tissue
160  123_B6J_10M_35  TA left
176  124_B6J_10F_35  TA left
194  125_B6J_10M_35  TA left
210  126_B6J_10F_35  TA left

In [35]:
def load_submitted_tissues():
    submitted_tissues = {}

    for accession_prefix in submitted_sheets:
        for i, row in submitted_sheets[accession_prefix]["tissue"].iterrows():
            if not pandas.isnull(row["accession"]):
                if accession_prefix == "igvftst":
                    see_also_template = "https://api.sandbox.igvf.org/tissues/{}/"
                elif accession_prefix == "igvf":
                    see_also_template = "https://api.data.igvf.org/tissues/{}/"

                aliases = row["aliases:array"].split(",")
                assert len(aliases) == 1
                alias_fields = aliases[0][len("ali-mortazavi:"):].split("_")
                tissue_id = "_".join(alias_fields[0:4])
                if pandas.notnull(row["accession"]):
                    submitted_tissues.setdefault(tissue_id, []).append({
                        "accession_prefix": accession_prefix,
                        "name": row["accession"],
                        "uuid": row["uuid"],
                        "see_also": see_also_template.format(row["accession"]),
                    })

    print("Submitted tissues count", len(submitted_tissues))
    return submitted_tissues

In [36]:
print("Loaded", import_tissues(tissue_sheets, submitted_tissues=load_submitted_tissues()), "tissues")

Submitted tissues count 692
Loaded 11976 tissues

In [37]:
protocol_by_ontology = {
    "UBERON:0001898": "hypo_pit_nuclei_prep", #Hypothalamus/Pituitary
    "UBERON:0000007": "hypo_pit_nuclei_prep", #Hypothalamus/Pituitary
    "UBERON:0002037": None, #Cerebellum
    "NTR:0000646": "left_cortex_nuclei_prep", #Cortex left
    "NTR:0000750": "cortex_hipp_nuclei_prep", #Hippocampus left
    "NTR:0000647": "cortex_hipp_nuclei_prep", #Cortex right
    "NTR:0000751": "cortex_hipp_nuclei_prep", #Hippocampus right
    "UBERON:0002107": "liver_nuclei_prep", #Liver
    "UBERON:0000948": "heart_nuclei_prep", #Heart
    "UBERON:0002048": None, #Lungs
    "UBERON:0002369": "adrenal_nuclei_prep", #Adrenal
    "UBERON:0002113": "kidney_nuclei_prep", #Kidney right
    "UBERON:0000992": "female_gonads_nuclei_prep", #Gonads -1 (Ovary)
    "UBERON:0000993": "female_gonads_nuclei_prep", #Gonads - 2 (Oviduct)
    "UBERON:0003428": None, #Perigonadal fat
    "UBERON:0001348": None, #Brown fat
    "UBERON:0001389": None, #Soleus
    "UBERON:0011905": None, #Plantaris
    "UBERON:0001388": "gastroc_nuclei_prep", #Gastrocnemius right
    "UBERON:0001385": "ta_nuclei_prep_misssing", #TA right
    "UBERON:0001386": None, #EDL
    "UBERON:0002415": None, #Tail
    "CL:2000001": "pbmc_cell_prep", #PBMC - WBC
    "UBERON:0000473": "male_gonads_nuclei_prep", #Testis right
    "UBERON:0001301": "male_gonads_nuclei_prep", #Epididymis right
    "UBERON:0001264": None, #Pancreas    
}


cellular_component_by_protocol = {
    "pbmc_cell_prep": models.CellularComponentEnum.cellular,
    "cortex_hipp_nuclei_prep": models.CellularComponentEnum.nuclei,
    "left_cortex_nuclei_prep": models.CellularComponentEnum.nuclei,
    "hypo_pit_nuclei_prep": models.CellularComponentEnum.nuclei,
    "gastroc_nuclei_prep": models.CellularComponentEnum.nuclei,
    "heart_nuclei_prep": models.CellularComponentEnum.nuclei,
    "liver_nuclei_prep": models.CellularComponentEnum.nuclei,
    "kidney_nuclei_prep": models.CellularComponentEnum.nuclei,
    "adrenal_nuclei_prep": models.CellularComponentEnum.nuclei,
    "male_gonads_nuclei_prep": models.CellularComponentEnum.nuclei,
    "female_gonads_nuclei_prep": models.CellularComponentEnum.nuclei,
    "ta_nuclei_prep_misssing": models.CellularComponentEnum.nuclei,
}

In [38]:
protocol_by_ontology["NTR:0000646"]

'left_cortex_nuclei_prep'

In [39]:
# Make sure our hard coded mappings are up to date.
for term in models.OntologyTerm.objects.all():
    assert term.curie in protocol_by_ontology, f"Need to update protocl mapping with {term.curie}"
    protocol = protocol_by_ontology.get(term.curie)
    if protocol is not None:
        assert protocol in cellular_component_by_protocol, f"No cellular component defined for {protocol}"

# Information from Samples into experiment

- Total barcoded nuclei (Samples into experiment)

Is this FixedTissue, ParseFixedSample, FixedBiosample?

In [40]:
# known sheets containing fixed sample data
fixed_sheets = [
    # (book name, sheet name, header start line)
    (founder_sheet_name, "Founder Samples into experiment", 1),
    (bridge_sheet_name, "Bridge samples into experiment", 0),
    (f1_sheet_name, "F1 Samples into experiment", 1),
    # According to Liz this sheet isn't ready yet.
    # lizs_sheet_name, "CC Samples into experiment", 1),
]


# According to liz: 10 and 11 were originally defined for gonads of both females and males. 
# 10 was originally ovaries or testes, and 11 was oviducts or epididymides, since we 
# collected gonads in separate tubes. However, when we do the experiment, the gonads 
# from an individual samples are pooled, which led to using 26 to indicate 
# pooled ovaries/oviducts from 1 female mouse and 25 to indicate pooled testes/epididymides from
# 1 male mouse. We are still collecting gonads in separate tubes, so females are still 10 and 11
# ovaries/oviducts and pooled to make 26. However, the males changed slightly — for the F1s and 
# CCs, we are collecting left and right testis and left and right epididymis separately, so
# no more 10/11 for males, but 27, 28, 29, 30 (left testis, right testis, left epididymis, right 
# epididymis). We are pooling the left testis and left epididymis rather than both sides for the 
# final plate, so 27 & 29 are now pooled to make 25.        

def validate_sex_specific_tissue(tissue_id, sex=None):    
    tissue = parse_mouse_tissue(tissue_id)
    
    if sex is None:
        sex = models.SexEnum(tissue.mouse_sex)
    elif isinstance(sex, str):
        sex = models.SexEnum(sex)

    sex_specific_tissues = {
        # left/right testis, left/right epididymis
        models.SexEnum.MALE: ["10", "11", "27", "28", "29", "30"],
        # ovary, ovaduct
        models.SexEnum.FEMALE: ["10", "11", "26"],
    }

    if tissue.tissue_id not in sex_specific_tissues[sex]:
        print(
            "Invalid tissue ID for {} mouse {}. allowed tissues {}".format(
                sex.name.lower(),
                tissue_id,
                sex_specific_tissues[sex]))


def validate_pooled_from(tissue_id, pooled_from):
    """Testis and ovaries have different tissue ids"""
    tissue = parse_mouse_tissue(tissue_id)
    
    allowed_child_tissues = {
        "25": ["10", "11","27", "29",],
        "26": ["10", "11",],
        #"29": [],
    }
    for pooled_id in pooled_from:
        pooled_tissue = parse_mouse_tissue(pooled_id)
        
        # equality always passes
        if tissue == pooled_tissue:
            continue
        
        if tissue.mouse_id != pooled_tissue.mouse_id:
            raise ValueError("Mouse dissection id does not match in {} {}".format(tissue_id, pooled_id))
        
        if tissue.mouse_strain != pooled_tissue.mouse_strain:
            raise ValueError("Mouse strain does not match in {} {}".format(tissue_id, pooled_id))
            
        if tissue.mouse_age != pooled_tissue.mouse_age:
            raise ValueError("Mouse age value does not match in {} {}".format(tissue_id, pooled_id))

        if tissue.mouse_sex != pooled_tissue.mouse_sex:
            raise ValueError("Mouse sex value does not match in {} {}".format(tissue_id, pooled_id))

        elif pooled_tissue.tissue_id not in allowed_child_tissues[tissue.tissue_id]:
            print("Mouse tissue_id {} includes an unexpeced pooled tissue {}".format(
                tissue_id, pooled_id))

def get_box_id(row):
    for label_name in ["IGVF Fixation BOX", "IGVF Sample BOX", "Box ID"]:
        if label_name in row.index:
            return row[label_name]


def get_nuclei_per_ul_before_fixation(row):
    if pandas.notnull(row.get("Count 1")):
        return None
    
    for name in ["Nuclei/mL (x10^6)"]:
        if name in row.index:
            return float(row[name]) * 1000

    print("Warning unable to find nuclei/ml in {}".format(row))

def get_nuclei_per_ul_after_fixation(row):
    if pandas.notnull(row.get("Count 1.1")):
        return None
    
    for name in ["Nuclei/mL (x10^6).1"]:
        if name in row.index:
            return float(row[name]) * 1000

    print("Warning unable to find nuclei/ml in {}".format(row))

def get_nuclei_into_fixation(row):
    for name in ["Nuclei into fixation (x10^6)", "Nuclei into PARSE (x10^6)"]:
        if name in row.index:
            return row[name]

def get_input_to_share(row):
    share_input = row.get("uL Input to SHARE")
    if share_input is None:
        return None
    else:
        return float(share_input)

def load_samples_into_experiment():
    book_cache = {}
    
    one_based = 1
    header_lines = 2
    fixed_samples = []

    for book_name, sheet_name, header in fixed_sheets:
        book = book_cache.get(book_name, pandas.ExcelFile(book_name))

        samples = book.parse(sheet_name=sheet_name, header=header, index_col=None).dropna(how="all")
        samples.rename({
            "Technician / Layering technician": "Fixation Tech.",
            "Technician": "Fixation Tech.",
            "Fixed sample counting technician": "Fixed Count Tech.",
        }, axis=1, inplace=True)
        #print(samples.columns)
        print("Loading sheet {}".format(sheet_name))
        #print(samples.head())
    
        failed = False
        for i, row in samples.iterrows():
            line_no = i + one_based + header_lines

            box_name = get_box_id(row)
            if isinstance(box_name, str):
                box_name = box_name.strip()

            if box_name in ["IGVF_FIX_001", "IGVF_FIX_002"]:
                continue

            if pandas.isnull(row["Mouse_Tissue ID"]):
                continue

            if pandas.isnull(row["Tissue"]):
                continue

            tissue_fields = parse_mouse_tissue(row["Mouse_Tissue ID"])
            tissue_id = join_mouse_tissue(tissue_fields)
            pooled_from = row.get("pooled_from")

            if pandas.isnull(tissue_id):
                continue

            #validate_sex_specific_tissue(tissue_id)

            if pandas.isnull(pooled_from):
                pooled_from = [tissue_id]
            else:
                normalized_pool = []
                for pooled_id in pooled_from.split(","):
                    normalized_pool.append(join_mouse_tissue(parse_mouse_tissue(pooled_id.strip())))
                pooled_from = normalized_pool

            validate_pooled_from(tissue_id, pooled_from)

            try:
                tissue = models.Tissue.objects.get(pk=pooled_from[0])
            except models.Tissue.DoesNotExist as e:
                print("Unable to find tissue id {} in tissue databsae".format(pooled_from[0]))
                raise e
            
            tissue_term = tissue.ontology_term.first()
            protocol = protocol_by_ontology[tissue_term.curie]
            assert protocol is not None, "We need another protocol added for {}".format(tissue_term)
            cellular_component = cellular_component_by_protocol[protocol]

            weight = positive_int_or_none(row["weight (mg)"])
            
            fixation_date = row["Fixation date"]
            notes = row["Notes"]

            sample_id = normalize_strain(row["Sample ID"]) if not pandas.isnull(row["Sample ID"]) else None
            if not (pandas.isnull(sample_id) or pandas.isnull(tissue_id)):
                if tissue_id != sample_id:
                    print(f"If defined, {tissue_id} should equal {sample_id} line {line_no}")
                    failed = True

            cap_label = row["Cap label"]
            if not validate_splitseq_cap_label(cap_label, sample_id):
                failed = True

            well_id = row["wells in Barcoding plate"]
            
            fixed_samples.append({
                "tissue_id": tissue_id,
                "tube_label": cap_label,
                "fixation_name": box_name,
                "fixation_date": row["Fixation date"],
                "pooled_from": pooled_from,
                "weight": weight,
                "isolation_technician": row.get("Isolation Tech.", None),
                "fixation_technician": row["Fixation Tech."],
                "fixed_count_technician": row["Fixed Count Tech."],
                "volume_ul": row["Volume RSB (mL)"] * 1000,
                "before_count1": row.get("Count 1"),
                "before_count2": row.get("Count 2"),
                "before_df1": row.get("DF1"),
                "before_df2": row.get("DF2"),
                "nuclei_per_ul_before_fixation": get_nuclei_per_ul_before_fixation(row),
                "starting_nuclei": row["Total nuclei (x10^6)"],
                "nuclei_into_fixation": get_nuclei_into_fixation(row),
                "fixed_nuclei": row["Total fixed nuclei (x10^6)"],
                "parse_input_ul": float(row.get("Input to Parse (mL)")) * 1000,
                "share_input_ul": get_input_to_share(row),
                
                "after_count1": row.get("Count 1.1"),
                "after_count2": row.get("Count 2.1"),
                "after_df1": row.get("DF", row.get("DF1.1")),
                "after_df2": row.get("DF2.1"),
                "nuclei_per_ul_after_fixation": get_nuclei_per_ul_after_fixation(row),
                
                "aliquots_made": row["# aliquots"],
                "aliquot_volume_ul": row["uL per aliquot"],
                "comments": row["Notes"],
                "sheet_name": sheet_name,
                "line_no": line_no,
                
                "cellular_component": cellular_component,
                "protocol": [protocol],
            })

    df = pandas.DataFrame(fixed_samples)
    duplicated = df.tissue_id.duplicated()
    print("Current {} duplicated entries".format(duplicated.sum()))
    df = df.drop_duplicates(subset=["tissue_id"])
    return df

fixed_samples = load_samples_into_experiment()
fixed_samples

Loading sheet Founder Samples into experiment
If defined, 194_B6CASTF1J_10F_20 should equal 194_B6CASTF1/J_10F_20 line 1078
If defined, 193_B6CASTF1J_10M_20 should equal 193_B6CASTF1/J_10M_20 line 1079
If defined, 196_B6CASTF1J_10F_20 should equal 196_B6CASTF1/J_10F_20 line 1080
If defined, 199_B6CASTF1J_10M_20 should equal 199_B6CASTF1/J_10M_20 line 1081
If defined, 202_B6CASTF1J_10F_20 should equal 202_B6CASTF1/J_10F_20 line 1082
If defined, 201_B6CASTF1J_10M_20 should equal 201_B6CASTF1/J_10M_20 line 1083
If defined, 204_B6CASTF1J_10F_20 should equal 204_B6CASTF1/J_10F_20 line 1084
If defined, 203_B6CASTF1J_10M_20 should equal 203_B6CASTF1/J_10M_20 line 1085
If defined, 216_B6PWKF1J_10F_20 should equal 216_B6PWKF1/J_10F_20 line 1086
If defined, 207_B6PWKF1J_10M_20 should equal 207_B6PWKF1/J_10M_20 line 1087
If defined, 218_B6PWKF1J_10F_20 should equal 218_B6PWKF1/J_10F_20 line 1088
If defined, 209_B6PWKF1J_10M_20 should equal 209_B6PWKF1/J_10M_20 line 1089
If defined, 220_B6PWKF1J_10F_20 should equal 220_B6PWKF1/J_10F_20 line 1090
If defined, 211_B6PWKF1J_10M_20 should equal 211_B6PWKF1/J_10M_20 line 1091
If defined, 222_B6PWKF1J_10F_20 should equal 222_B6PWKF1/J_10F_20 line 1092
If defined, 213_B6PWKF1J_10M_20 should equal 213_B6PWKF1/J_10M_20 line 1093
If defined, 224_B6WSBF1J_10F_20 should equal 224_B6WSBF1/J_10F_20 line 1094
If defined, 223_B6WSBF1J_10M_20 should equal 223_B6WSBF1/J_10M_20 line 1095
If defined, 232_B6WSBF1J_10F_20 should equal 232_B6WSBF1/J_10F_20 line 1096
If defined, 225_B6WSBF1J_10M_20 should equal 225_B6WSBF1/J_10M_20 line 1097
If defined, 234_B6WSBF1J_10F_20 should equal 234_B6WSBF1/J_10F_20 line 1098
If defined, 227_B6WSBF1J_10M_20 should equal 227_B6WSBF1/J_10M_20 line 1099
If defined, 236_B6WSBF1J_10F_20 should equal 236_B6WSBF1/J_10F_20 line 1100
If defined, 229_B6WSBF1J_10M_20 should equal 229_B6WSBF1/J_10M_20 line 1101
If defined, 160_B6NODF1J_10F_20 should equal 160_B6NODF1/J_10F_20 line 1102
If defined, 159_B6NODF1J_10M_20 should equal 159_B6NODF1/J_10M_20 line 1103
If defined, 164_B6NODF1J_10F_20 should equal 164_B6NODF1/J_10F_20 line 1104
If defined, 163_B6NODF1J_10M_20 should equal 163_B6NODF1/J_10M_20 line 1105
If defined, 166_B6NODF1J_10F_20 should equal 166_B6NODF1/J_10F_20 line 1106
If defined, 165_B6NODF1J_10M_20 should equal 165_B6NODF1/J_10M_20 line 1107
If defined, 168_B6NODF1J_10F_20 should equal 168_B6NODF1/J_10F_20 line 1108
If defined, 167_B6NODF1J_10M_20 should equal 167_B6NODF1/J_10M_20 line 1109
If defined, 198_B6CASTF1J_10F_20 should equal 198_B6CASTF1/J_10F_20 line 1115
If defined, 206_B6CASTF1J_10F_20 should equal 206_B6CASTF1/J_10F_20 line 1116
If defined, 208_B6PWKF1J_10F_20 should equal 208_B6PWKF1/J_10F_20 line 1117
If defined, 228_B6WSBF1J_10F_20 should equal 228_B6WSBF1/J_10F_20 line 1118
If defined, 170_B6NODF1J_10F_20 should equal 170_B6NODF1/J_10F_20 line 1119
Loading sheet Bridge samples into experiment
Loading sheet F1 Samples into experiment
Current 71 duplicated entries

,tissue_id,tube_label,fixation_name,fixation_date,pooled_from,weight,isolation_technician,fixation_technician,fixed_count_technician,volume_ul,...,after_df1,after_df2,nuclei_per_ul_after_fixation,aliquots_made,aliquot_volume_ul,comments,sheet_name,line_no,cellular_component,protocol
0,016_B6J_10F_03,016_03,IGVF_FIX_003,2022-11-02,[016_B6J_10F_03],141.0,None,HL,NaN,3000.0,...,NaN,None,14800.0,2.0,75.0,NaN,Founder Samples into experiment,101,N,[left_cortex_nuclei_prep]
1,017_B6J_10M_03,017_03,IGVF_FIX_003,2022-11-03,[017_B6J_10M_03],141.0,None,HL,NaN,3000.0,...,NaN,None,12150.0,2.0,150.0,ER isolated nuclei.,Founder Samples into experiment,102,N,[left_cortex_nuclei_prep]
2,018_B6J_10F_03,018_03,IGVF_FIX_003,2022-11-07,[018_B6J_10F_03],143.0,None,HL,NaN,3000.0,...,NaN,None,10010.0,2.0,150.0,ER started spinning SHARE samples without incu...,Founder Samples into experiment,103,N,[left_cortex_nuclei_prep]
3,019_B6J_10M_03,019_03,IGVF_FIX_003,2022-11-08,[019_B6J_10M_03],141.0,None,GF,NaN,3000.0,...,NaN,None,NaN,2.0,150.0,NaN,Founder Samples into experiment,104,N,[left_cortex_nuclei_prep]
4,020_B6J_10F_03,020_03,IGVF_FIX_003,2022-11-09,[020_B6J_10F_03],149.0,None,HL,NaN,3000.0,...,NaN,None,NaN,2.0,150.0,NaN,Founder Samples into experiment,105,N,[left_cortex_nuclei_prep]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1386,242_TREM2_10F_20,242_20,NaN,2023-11-21,[242_TREM2_10F_20],NaN,GF,GF,GF,500.0,...,4.0,None,NaN,1.0,100.0,NaN,F1 Samples into experiment,972,C,[pbmc_cell_prep]
1387,243_TREM2_10M_20,243_20,NaN,2023-11-21,[243_TREM2_10M_20],NaN,GF,GF,GF,500.0,...,4.0,None,NaN,1.0,100.0,NaN,F1 Samples into experiment,973,C,[pbmc_cell_prep]
1388,248_TREM2_10F_20,248_20,NaN,2023-11-21,[248_TREM2_10F_20],NaN,GF,GF,GF,500.0,...,4.0,None,NaN,1.0,75.0,NaN,F1 Samples into experiment,974,C,[pbmc_cell_prep]
1389,247_TREM2_10M_20,247_20,NaN,2023-11-21,[247_TREM2_10M_20],NaN,GF,GF,GF,500.0,...,4.0,None,NaN,1.0,100.0,NaN,F1 Samples into experiment,975,C,[pbmc_cell_prep]
1390,250_TREM2_10F_20,250_20,NaN,2023-11-21,[250_TREM2_10F_20],NaN,GF,GF,GF,500.0,...,4.0,None,NaN,1.0,100.0,NaN,F1 Samples into experiment,976,C,[pbmc_cell_prep]

In [41]:
%debug

ERROR:root:No traceback has been produced, nothing to debug.

In [42]:
# Extract some sample data for tests

#fixed_samples[fixed_samples["tissue_id"].isin(["016_B6J_10F_01", "016_B6J_10F_02", "017_B6J_10F_01", "017_B6J_10F_02", "144_B6129S1F1J_10F_01", "144_B6129S1F1J_10F_03"])].to_dict()

In [43]:
print("Added", import_splitseq_samples(fixed_samples))

Sum of tissue weights from 084_PWKJ_10F_03 0 doesn't match nan. Founder Samples into experiment:131
Sum of tissue weights from 085_PWKJ_10M_03 0 doesn't match nan. Founder Samples into experiment:132
Sum of tissue weights from 046_NZOJ_10F_03 150 doesn't match nan. Founder Samples into experiment:165
Sum of tissue weights from 046_NZOJ_10F_01 76 doesn't match nan. Founder Samples into experiment:465
Sum of tissue weights from 046_NZOJ_10F_17 116 doesn't match 190.0. Founder Samples into experiment:558
Sum of tissue weights from 095_CASTJ_10M_08 11 doesn't match 15.0. Founder Samples into experiment:749
Sum of tissue weights from 074_NODJ_10F_16 0 doesn't match nan. Founder Samples into experiment:913
Sum of tissue weights from 034_AJ_10F_16 0 doesn't match nan. Founder Samples into experiment:925
Sum of tissue weights from 035_AJ_10M_16 270 doesn't match nan. Founder Samples into experiment:926
Sum of tissue weights from 042_129S1J_10F_16 0 doesn't match nan. Founder Samples into experiment:935
Sum of tissue weights from 092_CASTJ_10F_16 0 doesn't match nan. Founder Samples into experiment:945
Sum of tissue weights from 064_WSBJ_10F_16 0 doesn't match nan. Founder Samples into experiment:953
Sum of tissue weights from 022_B6J_10F_16 0 doesn't match nan. Founder Samples into experiment:967
Sum of tissue weights from 122_B6J_10F_16 0 doesn't match nan. Founder Samples into experiment:968
Sum of tissue weights from 068_NODJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1003
Sum of tissue weights from 071_NODJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1004
Sum of tissue weights from 030_AJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1005
Sum of tissue weights from 081_PWKJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1006
Sum of tissue weights from 084_PWKJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1007
Sum of tissue weights from 088_CASTJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1008
Sum of tissue weights from 089_CASTJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1009
Sum of tissue weights from 064_WSBJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1010
Sum of tissue weights from 260_CASTJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1011
Sum of tissue weights from 022_B6J_10F_20 0 doesn't match nan. Founder Samples into experiment:1012
Sum of tissue weights from 016_B6J_10F_20 0 doesn't match nan. Founder Samples into experiment:1014
Sum of tissue weights from 017_B6J_10M_20 0 doesn't match nan. Founder Samples into experiment:1015
Sum of tissue weights from 018_B6J_10F_20 0 doesn't match nan. Founder Samples into experiment:1016
Sum of tissue weights from 019_B6J_10M_20 0 doesn't match nan. Founder Samples into experiment:1017
Sum of tissue weights from 020_B6J_10F_20 0 doesn't match nan. Founder Samples into experiment:1018
Sum of tissue weights from 021_B6J_10M_20 0 doesn't match nan. Founder Samples into experiment:1019
Sum of tissue weights from 024_B6J_10F_20 0 doesn't match nan. Founder Samples into experiment:1020
Sum of tissue weights from 025_B6J_10M_20 0 doesn't match nan. Founder Samples into experiment:1021
Sum of tissue weights from 066_NODJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1022
Sum of tissue weights from 067_NODJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1023
Sum of tissue weights from 070_NODJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1024
Sum of tissue weights from 069_NODJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1025
Sum of tissue weights from 072_NODJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1026
Sum of tissue weights from 073_NODJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1027
Sum of tissue weights from 074_NODJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1028
Sum of tissue weights from 075_NODJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1029
Sum of tissue weights from 026_AJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1030
Sum of tissue weights from 029_AJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1031
Sum of tissue weights from 028_AJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1032
Sum of tissue weights from 031_AJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1033
Sum of tissue weights from 032_AJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1034
Sum of tissue weights from 033_AJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1035
Sum of tissue weights from 034_AJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1036
Sum of tissue weights from 035_AJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1037
Sum of tissue weights from 076_PWKJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1038
Sum of tissue weights from 077_PWKJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1039
Sum of tissue weights from 078_PWKJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1040
Sum of tissue weights from 079_PWKJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1041
Sum of tissue weights from 080_PWKJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1042
Sum of tissue weights from 083_PWKJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1043
Sum of tissue weights from 082_PWKJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1044
Sum of tissue weights from 085_PWKJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1045
Sum of tissue weights from 036_129S1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1046
Sum of tissue weights from 037_129S1J_10M_20 0 doesn't match nan. Founder Samples into experiment:1047
Sum of tissue weights from 038_129S1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1048
Sum of tissue weights from 041_129S1J_10M_20 0 doesn't match nan. Founder Samples into experiment:1049
Sum of tissue weights from 040_129S1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1050
Sum of tissue weights from 043_129S1J_10M_20 0 doesn't match nan. Founder Samples into experiment:1051
Sum of tissue weights from 044_129S1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1052
Sum of tissue weights from 045_129S1J_10M_20 0 doesn't match nan. Founder Samples into experiment:1053
Sum of tissue weights from 086_CASTJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1054
Sum of tissue weights from 087_CASTJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1055
Sum of tissue weights from 090_CASTJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1056
Sum of tissue weights from 091_CASTJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1057
Sum of tissue weights from 092_CASTJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1058
Sum of tissue weights from 093_CASTJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1059
Sum of tissue weights from 094_CASTJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1060
Sum of tissue weights from 095_CASTJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1061
Sum of tissue weights from 058_WSBJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1062
Sum of tissue weights from 057_WSBJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1063
Sum of tissue weights from 060_WSBJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1064
Sum of tissue weights from 059_WSBJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1065
Sum of tissue weights from 062_WSBJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1066
Sum of tissue weights from 061_WSBJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1067
Sum of tissue weights from 096_WSBJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1068
Sum of tissue weights from 063_WSBJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1069
Sum of tissue weights from 046_NZOJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1070

Sum of tissue weights from 047_NZOJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1071
Sum of tissue weights from 048_NZOJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1072
Sum of tissue weights from 049_NZOJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1073
Sum of tissue weights from 050_NZOJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1074
Sum of tissue weights from 051_NZOJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1075
Sum of tissue weights from 052_NZOJ_10F_20 0 doesn't match nan. Founder Samples into experiment:1076
Sum of tissue weights from 053_NZOJ_10M_20 0 doesn't match nan. Founder Samples into experiment:1077
Sum of tissue weights from 194_B6CASTF1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1078
Sum of tissue weights from 193_B6CASTF1J_10M_20 0 doesn't match nan. Founder Samples into experiment:1079
Sum of tissue weights from 196_B6CASTF1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1080
Sum of tissue weights from 199_B6CASTF1J_10M_20 0 doesn't match nan. Founder Samples into experiment:1081
Sum of tissue weights from 202_B6CASTF1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1082
Sum of tissue weights from 201_B6CASTF1J_10M_20 0 doesn't match nan. Founder Samples into experiment:1083
Sum of tissue weights from 204_B6CASTF1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1084
Sum of tissue weights from 203_B6CASTF1J_10M_20 0 doesn't match nan. Founder Samples into experiment:1085
Sum of tissue weights from 216_B6PWKF1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1086
Sum of tissue weights from 207_B6PWKF1J_10M_20 0 doesn't match nan. Founder Samples into experiment:1087
Sum of tissue weights from 218_B6PWKF1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1088
Sum of tissue weights from 209_B6PWKF1J_10M_20 0 doesn't match nan. Founder Samples into experiment:1089
Sum of tissue weights from 220_B6PWKF1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1090
Sum of tissue weights from 211_B6PWKF1J_10M_20 0 doesn't match nan. Founder Samples into experiment:1091
Sum of tissue weights from 222_B6PWKF1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1092
Sum of tissue weights from 213_B6PWKF1J_10M_20 0 doesn't match nan. Founder Samples into experiment:1093
Sum of tissue weights from 224_B6WSBF1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1094
Sum of tissue weights from 223_B6WSBF1J_10M_20 0 doesn't match nan. Founder Samples into experiment:1095
Sum of tissue weights from 232_B6WSBF1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1096
Sum of tissue weights from 225_B6WSBF1J_10M_20 0 doesn't match nan. Founder Samples into experiment:1097
Sum of tissue weights from 234_B6WSBF1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1098
Sum of tissue weights from 227_B6WSBF1J_10M_20 0 doesn't match nan. Founder Samples into experiment:1099
Sum of tissue weights from 236_B6WSBF1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1100
Sum of tissue weights from 229_B6WSBF1J_10M_20 0 doesn't match nan. Founder Samples into experiment:1101
Sum of tissue weights from 160_B6NODF1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1102
Sum of tissue weights from 159_B6NODF1J_10M_20 0 doesn't match nan. Founder Samples into experiment:1103
Sum of tissue weights from 164_B6NODF1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1104
Sum of tissue weights from 163_B6NODF1J_10M_20 0 doesn't match nan. Founder Samples into experiment:1105
Sum of tissue weights from 166_B6NODF1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1106
Sum of tissue weights from 165_B6NODF1J_10M_20 0 doesn't match nan. Founder Samples into experiment:1107
Sum of tissue weights from 168_B6NODF1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1108
Sum of tissue weights from 167_B6NODF1J_10M_20 0 doesn't match nan. Founder Samples into experiment:1109
Sum of tissue weights from 255_B6J_10M_20 0 doesn't match nan. Founder Samples into experiment:1112
Sum of tissue weights from 256_B6J_10F_20 0 doesn't match nan. Founder Samples into experiment:1113
Sum of tissue weights from 257_B6J_10M_20 0 doesn't match nan. Founder Samples into experiment:1114
Sum of tissue weights from 198_B6CASTF1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1115
Sum of tissue weights from 206_B6CASTF1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1116
Sum of tissue weights from 208_B6PWKF1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1117
Sum of tissue weights from 228_B6WSBF1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1118
Sum of tissue weights from 170_B6NODF1J_10F_20 0 doesn't match nan. Founder Samples into experiment:1119
Sum of tissue weights from 208_B6PWKF1J_10F_03 0 doesn't match nan. F1 Samples into experiment:13
Sum of tissue weights from 138_B6AF1J_10F_04 0 doesn't match nan. F1 Samples into experiment:36
Sum of tissue weights from 133_B6AF1J_10M_04 0 doesn't match nan. F1 Samples into experiment:37
Sum of tissue weights from 210_B6PWKF1J_10F_03 0 doesn't match nan. F1 Samples into experiment:38
Sum of tissue weights from 207_B6PWKF1J_10M_03 0 doesn't match nan. F1 Samples into experiment:39
Sum of tissue weights from 204_B6CASTF1J_10F_04 0 doesn't match nan. F1 Samples into experiment:60
Sum of tissue weights from 130_B6AF1J_10F_08 0 doesn't match nan. F1 Samples into experiment:532
Sum of tissue weights from 193_B6CASTF1J_10M_31 196 doesn't match 203.0. F1 Samples into experiment:657
Sum of tissue weights from 193_B6CASTF1J_10M_33 207 doesn't match 220.0. F1 Samples into experiment:757
Sum of tissue weights from 191_B6CASTF1J_10M_20 0 doesn't match nan. F1 Samples into experiment:814
Sum of tissue weights from 192_B6CASTF1J_10F_20 0 doesn't match nan. F1 Samples into experiment:815
Sum of tissue weights from 195_B6CASTF1J_10M_20 0 doesn't match nan. F1 Samples into experiment:816
Sum of tissue weights from 197_B6CASTF1J_10M_20 0 doesn't match nan. F1 Samples into experiment:818
Sum of tissue weights from 200_B6CASTF1J_10F_20 0 doesn't match nan. F1 Samples into experiment:819
Sum of tissue weights from 210_B6PWKF1J_10F_20 0 doesn't match nan. F1 Samples into experiment:821
Sum of tissue weights from 215_B6PWKF1J_10M_20 0 doesn't match nan. F1 Samples into experiment:822
Sum of tissue weights from 212_B6PWKF1J_10F_20 0 doesn't match nan. F1 Samples into experiment:823
Sum of tissue weights from 217_B6PWKF1J_10M_20 0 doesn't match nan. F1 Samples into experiment:824
Sum of tissue weights from 214_B6PWKF1J_10F_20 0 doesn't match nan. F1 Samples into experiment:825
Sum of tissue weights from 231_B6WSBF1J_10M_20 0 doesn't match nan. F1 Samples into experiment:827
Sum of tissue weights from 226_B6WSBF1J_10F_20 0 doesn't match nan. F1 Samples into experiment:828
Sum of tissue weights from 127_B6AF1J_10M_20 0 doesn't match nan. F1 Samples into experiment:829
Sum of tissue weights from 128_B6AF1J_10F_20 0 doesn't match nan. F1 Samples into experiment:830
Sum of tissue weights from 129_B6AF1J_10M_20 0 doesn't match nan. F1 Samples into experiment:831
Sum of tissue weights from 130_B6AF1J_10F_20 0 doesn't match nan. F1 Samples into experiment:832
Sum of tissue weights from 131_B6AF1J_10M_20 0 doesn't match nan. F1 Samples into experiment:833
Sum of tissue weights from 132_B6AF1J_10F_20 0 doesn't match nan. F1 Samples into experiment:834
Sum of tissue weights from 133_B6AF1J_10M_20 0 doesn't match nan. F1 Samples into experiment:835
Sum of tissue weights from 134_B6AF1J_10F_20 0 doesn't match nan. F1 Samples into experiment:836
Sum of tissue weights from 143_B6129S1F1J_10M_20 0 doesn't match nan. F1 Samples into experiment:837
Sum of tissue weights from 144_B6129S1F1J_10F_20 0 doesn't match nan. F1 Samples into experiment:838
Sum of tissue weights from 145_B6129S1F1J_10M_20 0 doesn't match nan. F1 Samples into experiment:839
Sum of tissue weights from 146_B6129S1F1J_10F_20 0 doesn't match nan. F1 Samples into experiment:840

Sum of tissue weights from 147_B6129S1F1J_10M_20 0 doesn't match nan. F1 Samples into experiment:841
Sum of tissue weights from 148_B6129S1F1J_10F_20 0 doesn't match nan. F1 Samples into experiment:842
Sum of tissue weights from 149_B6129S1F1J_10M_20 0 doesn't match nan. F1 Samples into experiment:843
Sum of tissue weights from 150_B6129S1F1J_10F_20 0 doesn't match nan. F1 Samples into experiment:844
Sum of tissue weights from 175_B6NZOF1J_10M_20 0 doesn't match nan. F1 Samples into experiment:853
Sum of tissue weights from 176_B6NZOF1J_10F_20 0 doesn't match nan. F1 Samples into experiment:854
Sum of tissue weights from 177_B6NZOF1J_10M_20 0 doesn't match nan. F1 Samples into experiment:855
Sum of tissue weights from 178_B6NZOF1J_10F_20 0 doesn't match nan. F1 Samples into experiment:856
Sum of tissue weights from 179_B6NZOF1J_10M_20 0 doesn't match nan. F1 Samples into experiment:857
Sum of tissue weights from 180_B6NZOF1J_10F_20 0 doesn't match nan. F1 Samples into experiment:858
Sum of tissue weights from 181_B6NZOF1J_10M_20 0 doesn't match nan. F1 Samples into experiment:859
Sum of tissue weights from 182_B6NZOF1J_10F_20 0 doesn't match nan. F1 Samples into experiment:860
Sum of tissue weights from 699_B6J_10M_20 0 doesn't match nan. F1 Samples into experiment:885
Sum of tissue weights from 698_B6J_10F_20 0 doesn't match nan. F1 Samples into experiment:886
Sum of tissue weights from 701_B6J_10M_20 0 doesn't match nan. F1 Samples into experiment:887
Sum of tissue weights from 700_B6J_10F_20 0 doesn't match nan. F1 Samples into experiment:888
Sum of tissue weights from 703_B6J_10M_20 0 doesn't match nan. F1 Samples into experiment:889
Sum of tissue weights from 702_B6J_10F_20 0 doesn't match nan. F1 Samples into experiment:890
Sum of tissue weights from 705_B6J_10M_20 0 doesn't match nan. F1 Samples into experiment:891
Sum of tissue weights from 704_B6J_10F_20 0 doesn't match nan. F1 Samples into experiment:892
Sum of tissue weights from 244_TREM2_10F_20 0 doesn't match nan. F1 Samples into experiment:903
Sum of tissue weights from 245_TREM2_10M_20 0 doesn't match nan. F1 Samples into experiment:904
Sum of tissue weights from 239_TREM2_10M_20 0 doesn't match nan. F1 Samples into experiment:969
Sum of tissue weights from 240_TREM2_10F_20 0 doesn't match nan. F1 Samples into experiment:970
Sum of tissue weights from 241_TREM2_10M_20 0 doesn't match nan. F1 Samples into experiment:971
Sum of tissue weights from 242_TREM2_10F_20 0 doesn't match nan. F1 Samples into experiment:972
Sum of tissue weights from 243_TREM2_10M_20 0 doesn't match nan. F1 Samples into experiment:973
Sum of tissue weights from 248_TREM2_10F_20 0 doesn't match nan. F1 Samples into experiment:974
Sum of tissue weights from 247_TREM2_10M_20 0 doesn't match nan. F1 Samples into experiment:975
Sum of tissue weights from 250_TREM2_10F_20 0 doesn't match nan. F1 Samples into experiment:976
Added 1344

In [44]:
# According to Liz this sheet isn't ready yet.
# load_samples_into_experiment(lizs_sheet_name, "CC Samples into experiment", header=1)

# Plate layout

(the hard thing)

In [45]:
plate_layout = pandas.read_excel(
    lizs_sheet_name, 
    sheet_name="Plate setups",
    header=None,
)
print(plate_layout)

#for plate_name, plate_contents in parse_plate(plate_layout):
#    print(plate_name, len(plate_contents))

plate_parser = PlateLayoutParser()
plate_parser.import_plates(plate_layout)

      0         1    2                    3                    4   \
0    NaN  IGVF_003  NaN                  NaN                  NaN
1    NaN       NaN  NaN       Tissue1_F_rep1       Tissue1_M_rep1
2    NaN       NaN  NaN                    1                    2
3    NaN       B6J    A       016_B6J_10F_03       017_B6J_10M_03
4    NaN      NODJ    B      066_NODJ_10F_03      067_NODJ_10M_03
..   ...       ...  ...                  ...                  ...
775  NaN       NaN  NaN                  NaN                  NaN
776  NaN       NaN    G  228_B6WSBF1J_10F_26  223_B6WSBF1J_10M_25
777  NaN       NaN    H  178_B6NZOF1J_10F_26  175_B6NZOF1J_10M_25
778  NaN       NaN  NaN             GH_F1_26             GH_M1_25
779  NaN       NaN  NaN                   G9                  G10

                      5                    6                    7   \
0                    NaN                  NaN                  NaN
1         Tissue1_F_rep2       Tissue1_M_rep2       Tissue1_F_rep3
2                      3                    4                    5
3         018_B6J_10F_03       019_B6J_10M_03       020_B6J_10F_03
4        068_NODJ_10F_03      069_NODJ_10M_03      070_NODJ_10F_03
..                   ...                  ...                  ...
775                  NaN                  NaN                  NaN
776  232_B6WSBF1J_10F_26  225_B6WSBF1J_10M_25  234_B6WSBF1J_10F_26
777  180_B6NZOF1J_10F_26  177_B6NZOF1J_10M_25  188_B6NZOF1J_10F_26
778             GH_F2_26             GH_M2_25             GH_F3_26
779                  G11                  G12                   H9

                      8                    9                    10  \
0                    NaN                  NaN                  NaN
1         Tissue1_M_rep3       Tissue1_F_rep4       Tissue1_M_rep4
2                      6                    7                    8
3         021_B6J_10M_03       024_B6J_10F_03       025_B6J_10M_03
4        071_NODJ_10M_03      072_NODJ_10F_03      073_NODJ_10M_03
..                   ...                  ...                  ...
775                  NaN                  NaN                  NaN
776  227_B6WSBF1J_10M_25  238_B6WSBF1J_10F_26  229_B6WSBF1J_10M_25
777  181_B6NZOF1J_10M_25  190_B6NZOF1J_10F_26  185_B6NZOF1J_10M_25
778             GH_M3_25             GH_F4_26             GH_M4_25
779                  H10                  H11                  H12

                11             12             13             14
0              NaN            NaN            NaN            NaN
1    Tissue2_F_1/3  Tissue2_M_1/3  Tissue2_F_2/4  Tissue2_M_2/4
2                9             10             11             12
3         AB_F1_06       AB_M1_06       AB_F2_06       AB_M2_06
4         AB_F3_06       AB_M3_06       AB_F4_06       AB_M4_06
..             ...            ...            ...            ...
775            NaN            NaN            NaN            NaN
776            NaN            NaN            NaN            NaN
777            NaN            NaN            NaN            NaN
778            NaN            NaN            NaN            NaN
779            NaN            NaN            NaN            NaN

[780 rows x 15 columns]

In [46]:
%debug

ERROR:root:No traceback has been produced, nothing to debug.

In [47]:
plate_layout

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,NaN,IGVF_003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Tissue1_F_rep1,Tissue1_M_rep1,Tissue1_F_rep2,Tissue1_M_rep2,Tissue1_F_rep3,Tissue1_M_rep3,Tissue1_F_rep4,Tissue1_M_rep4,Tissue2_F_1/3,Tissue2_M_1/3,Tissue2_F_2/4,Tissue2_M_2/4
2,NaN,NaN,NaN,1,2,3,4,5,6,7,8,9,10,11,12
3,NaN,B6J,A,016_B6J_10F_03,017_B6J_10M_03,018_B6J_10F_03,019_B6J_10M_03,020_B6J_10F_03,021_B6J_10M_03,024_B6J_10F_03,025_B6J_10M_03,AB_F1_06,AB_M1_06,AB_F2_06,AB_M2_06
4,NaN,NODJ,B,066_NODJ_10F_03,067_NODJ_10M_03,068_NODJ_10F_03,069_NODJ_10M_03,070_NODJ_10F_03,071_NODJ_10M_03,072_NODJ_10F_03,073_NODJ_10M_03,AB_F3_06,AB_M3_06,AB_F4_06,AB_M4_06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
776,NaN,NaN,G,228_B6WSBF1J_10F_26,223_B6WSBF1J_10M_25,232_B6WSBF1J_10F_26,225_B6WSBF1J_10M_25,234_B6WSBF1J_10F_26,227_B6WSBF1J_10M_25,238_B6WSBF1J_10F_26,229_B6WSBF1J_10M_25,NaN,NaN,NaN,NaN
777,NaN,NaN,H,178_B6NZOF1J_10F_26,175_B6NZOF1J_10M_25,180_B6NZOF1J_10F_26,177_B6NZOF1J_10M_25,188_B6NZOF1J_10F_26,181_B6NZOF1J_10M_25,190_B6NZOF1J_10F_26,185_B6NZOF1J_10M_25,NaN,NaN,NaN,NaN
778,NaN,NaN,NaN,GH_F1_26,GH_M1_25,GH_F2_26,GH_M2_25,GH_F3_26,GH_M3_25,GH_F4_26,GH_M4_25,NaN,NaN,NaN,NaN
779,NaN,NaN,NaN,G9,G10,G11,G12,H9,H10,H11,H12,NaN,NaN,NaN,NaN

In [48]:
%debug

ERROR:root:No traceback has been produced, nothing to debug.

# Submitted measurement sets

In [49]:
def load_submitted_measurement_sets():
    measurement_sets = {}

    for accession_prefix in submitted_sheets:
        for i, row in submitted_sheets[accession_prefix]["measurement_set"].iterrows():
            if not pandas.isnull(row["accession"]):
                aliases = row["aliases:array"].split(',')
                name = aliases[0].replace("ali-mortazavi:", "")

                try:
                    record = models.MeasurementSet.objects.get(name=name)
                except models.MeasurementSet.DoesNotExist:
                    record = models.MeasurementSet(
                        name=name,
                    )
                    record.save()

                if accession_prefix == "igvftst":
                    see_also_template = "https://api.sandbox.igvf.org/measurment-sets/{}/"
                elif accession_prefix == "igvf":
                    see_also_template = "https://api.data.igvf.org/measurement-sets/{}/"

                try:
                    accession = models.Accession.objects.get(
                        accession_prefix=accession_prefix, 
                        name=row["accession"])
                except models.Accession.DoesNotExist:
                    accession = models.Accession(
                        accession_prefix=accession_prefix,
                        name=row["accession"],
                        uuid=row["uuid"],
                        see_also=see_also_template.format(row["accession"]),
                    )
                    accession.save()
                    
                if accession not in record.accession.all():
                    record.accession.add(accession)
                    record.save()
                measurement_sets[name] = record
    print("loaded", len(measurement_sets), "measurement_sets")
    return measurement_sets

load_submitted_measurement_sets()

loaded 175 measurement_sets

{'003_67A_illumina': <MeasurementSet: 003_67A_illumina>,
 '003_67B_illumina': <MeasurementSet: 003_67B_illumina>,
 '003_67C_illumina': <MeasurementSet: 003_67C_illumina>,
 '003_67D_illumina': <MeasurementSet: 003_67D_illumina>,
 '003_67E_illumina': <MeasurementSet: 003_67E_illumina>,
 '003_67F_illumina': <MeasurementSet: 003_67F_illumina>,
 '003_67G_illumina': <MeasurementSet: 003_67G_illumina>,
 '003_67H_illumina': <MeasurementSet: 003_67H_illumina>,
 '003_67I_illumina': <MeasurementSet: 003_67I_illumina>,
 '003_67J_illumina': <MeasurementSet: 003_67J_illumina>,
 '003_67K_illumina': <MeasurementSet: 003_67K_illumina>,
 '003_67L_illumina': <MeasurementSet: 003_67L_illumina>,
 '003_67M_illumina': <MeasurementSet: 003_67M_illumina>,
 '003_67N_illumina': <MeasurementSet: 003_67N_illumina>,
 '003_67O_illumina': <MeasurementSet: 003_67O_illumina>,
 '003_8A_illumina': <MeasurementSet: 003_8A_illumina>,
 '003_8A_nanopore': <MeasurementSet: 003_8A_nanopore>,
 'B01_13A_illumina': <MeasurementSet: B01_13A_illumina>,
 'B01_13B_illumina': <MeasurementSet: B01_13B_illumina>,
 'B01_13C_illumina': <MeasurementSet: B01_13C_illumina>,
 'B01_13D_illumina': <MeasurementSet: B01_13D_illumina>,
 'B01_13E_illumina': <MeasurementSet: B01_13E_illumina>,
 'B01_13F_illumina': <MeasurementSet: B01_13F_illumina>,
 'B01_13G_illumina': <MeasurementSet: B01_13G_illumina>,
 'B01_13H_illumina': <MeasurementSet: B01_13H_illumina>,
 'B01_13G_nanopore': <MeasurementSet: B01_13G_nanopore>,
 'B01_13H_nanopore': <MeasurementSet: B01_13H_nanopore>,
 '003_13A_illumina': <MeasurementSet: 003_13A_illumina>,
 '004_13A_illumina': <MeasurementSet: 004_13A_illumina>,
 '004_67A_illumina': <MeasurementSet: 004_67A_illumina>,
 '004_67B_illumina': <MeasurementSet: 004_67B_illumina>,
 '004_67C_illumina': <MeasurementSet: 004_67C_illumina>,
 '004_67D_illumina': <MeasurementSet: 004_67D_illumina>,
 '004_67E_illumina': <MeasurementSet: 004_67E_illumina>,
 '004_67F_illumina': <MeasurementSet: 004_67F_illumina>,
 '004_67G_illumina': <MeasurementSet: 004_67G_illumina>,
 '004_67H_illumina': <MeasurementSet: 004_67H_illumina>,
 '004_67I_illumina': <MeasurementSet: 004_67I_illumina>,
 '004_67J_illumina': <MeasurementSet: 004_67J_illumina>,
 '004_67K_illumina': <MeasurementSet: 004_67K_illumina>,
 '004_67L_illumina': <MeasurementSet: 004_67L_illumina>,
 '004_67M_illumina': <MeasurementSet: 004_67M_illumina>,
 '004_67N_illumina': <MeasurementSet: 004_67N_illumina>,
 '004_67O_illumina': <MeasurementSet: 004_67O_illumina>,
 '005_13A_illumina': <MeasurementSet: 005_13A_illumina>,
 '005_67I_illumina': <MeasurementSet: 005_67I_illumina>,
 '005_67J_illumina': <MeasurementSet: 005_67J_illumina>,
 '005_67K_illumina': <MeasurementSet: 005_67K_illumina>,
 '005_67L_illumina': <MeasurementSet: 005_67L_illumina>,
 '005_67M_illumina': <MeasurementSet: 005_67M_illumina>,
 '005_67N_illumina': <MeasurementSet: 005_67N_illumina>,
 '005_67O_illumina': <MeasurementSet: 005_67O_illumina>,
 '005_67A_illumina': <MeasurementSet: 005_67A_illumina>,
 '005_67B_illumina': <MeasurementSet: 005_67B_illumina>,
 '005_67C_illumina': <MeasurementSet: 005_67C_illumina>,
 '005_67D_illumina': <MeasurementSet: 005_67D_illumina>,
 '005_67E_illumina': <MeasurementSet: 005_67E_illumina>,
 '005_67F_illumina': <MeasurementSet: 005_67F_illumina>,
 '005_67G_illumina': <MeasurementSet: 005_67G_illumina>,
 '005_67H_illumina': <MeasurementSet: 005_67H_illumina>,
 '007_13A_illumina': <MeasurementSet: 007_13A_illumina>,
 '007_67I_illumina': <MeasurementSet: 007_67I_illumina>,
 '007_67J_illumina': <MeasurementSet: 007_67J_illumina>,
 '007_67K_illumina': <MeasurementSet: 007_67K_illumina>,
 '007_67L_illumina': <MeasurementSet: 007_67L_illumina>,
 '007_67M_illumina': <MeasurementSet: 007_67M_illumina>,
 '007_67N_illumina': <MeasurementSet: 007_67N_illumina>,
 '007_67O_illumina': <MeasurementSet: 007_67O_illumina>,
 '007_67A_illumina': <MeasurementSet: 007_67A_illumina>,
 '007_67B_illumina': <MeasurementSet: 007_67B_illumina>,
 '007_67C_illumina': <MeasurementSet: 007_67C_illumina>,
 '007_67D_illumina': <MeasurementSet: 007_67D_illumina>,
 '007_67E_illumina': <MeasurementSet: 007_67E_illumina>,
 '007_67F_illumina': <MeasurementSet: 007_67F_illumina>,
 '007_67G_illumina': <MeasurementSet: 007_67G_illumina>,
 '007_67H_illumina': <MeasurementSet: 007_67H_illumina>,
 '008_67C_illumina': <MeasurementSet: 008_67C_illumina>,
 '008_67G_illumina': <MeasurementSet: 008_67G_illumina>,
 '008_67I_illumina': <MeasurementSet: 008_67I_illumina>,
 '008_67A_illumina': <MeasurementSet: 008_67A_illumina>,
 '008_67B_illumina': <MeasurementSet: 008_67B_illumina>,
 '008_67D_illumina': <MeasurementSet: 008_67D_illumina>,
 '008_67E_illumina': <MeasurementSet: 008_67E_illumina>,
 '008_67F_illumina': <MeasurementSet: 008_67F_illumina>,
 '008_67H_illumina': <MeasurementSet: 008_67H_illumina>,
 '008B_13A_illumina': <MeasurementSet: 008B_13A_illumina>,
 '008B_67G_illumina': <MeasurementSet: 008B_67G_illumina>,
 '008B_67I_illumina': <MeasurementSet: 008B_67I_illumina>,
 '008B_67J_illumina': <MeasurementSet: 008B_67J_illumina>,
 '008B_67A_illumina': <MeasurementSet: 008B_67A_illumina>,
 '008B_67B_illumina': <MeasurementSet: 008B_67B_illumina>,
 '008B_67C_illumina': <MeasurementSet: 008B_67C_illumina>,
 '008B_67D_illumina': <MeasurementSet: 008B_67D_illumina>,
 '008B_67E_illumina': <MeasurementSet: 008B_67E_illumina>,
 '008B_67F_illumina': <MeasurementSet: 008B_67F_illumina>,
 '008B_67H_illumina': <MeasurementSet: 008B_67H_illumina>,
 '009_13A_illumina': <MeasurementSet: 009_13A_illumina>,
 '009_67A_illumina': <MeasurementSet: 009_67A_illumina>,
 '009_67O_illumina': <MeasurementSet: 009_67O_illumina>,
 '009_67I_illumina': <MeasurementSet: 009_67I_illumina>,
 '009_67J_illumina': <MeasurementSet: 009_67J_illumina>,
 '009_67K_illumina': <MeasurementSet: 009_67K_illumina>,
 '009_67L_illumina': <MeasurementSet: 009_67L_illumina>,
 '009_67M_illumina': <MeasurementSet: 009_67M_illumina>,
 '009_67N_illumina': <MeasurementSet: 009_67N_illumina>,
 '009_67B_illumina': <MeasurementSet: 009_67B_illumina>,
 '009_67C_illumina': <MeasurementSet: 009_67C_illumina>,
 '009_67D_illumina': <MeasurementSet: 009_67D_illumina>,
 '009_67E_illumina': <MeasurementSet: 009_67E_illumina>,
 '009_67F_illumina': <MeasurementSet: 009_67F_illumina>,
 '009_67G_illumina': <MeasurementSet: 009_67G_illumina>,
 '009_67H_illumina': <MeasurementSet: 009_67H_illumina>,
 '010_13A_illumina': <MeasurementSet: 010_13A_illumina>,
 '010_67D_illumina': <MeasurementSet: 010_67D_illumina>,
 '010_67O_illumina': <MeasurementSet: 010_67O_illumina>,
 '010_67I_illumina': <MeasurementSet: 010_67I_illumina>,
 '010_67J_illumina': <MeasurementSet: 010_67J_illumina>,
 '010_67K_illumina': <MeasurementSet: 010_67K_illumina>,
 '010_67L_illumina': <MeasurementSet: 010_67L_illumina>,
 '010_67M_illumina': <MeasurementSet: 010_67M_illumina>,
 '010_67N_illumina': <MeasurementSet: 010_67N_illumina>,
 '010_67A_illumina': <MeasurementSet: 010_67A_illumina>,
 '010_67B_illumina': <MeasurementSet: 010_67B_illumina>,
 '010_67C_illumina': <MeasurementSet: 010_67C_illumina>,
 '010_67E_illumina': <MeasurementSet: 010_67E_illumina>,
 '010_67F_illumina': <MeasurementSet: 010_67F_illumina>,
 '010_67G_illumina': <MeasurementSet: 010_67G_illumina>,
 '010_67H_illumina': <MeasurementSet: 010_67H_illumina>,
 '011_13A_illumina': <MeasurementSet: 011_13A_illumina>,
 '011_67M_illumina': <MeasurementSet: 011_67M_illumina>,
 '011_67O_illumina': <MeasurementSet: 011_67O_illumina>,
 '011_67I_illumina': <MeasurementSet: 011_67I_illumina>,
 '011_67J_illumina': <MeasurementSet: 011_67J_illumina>,
 '011_67K_illumina': <MeasurementSet: 011_67K_illumina>,
 '011_67L_illumina': <MeasurementSet: 011_67L_illumina>,
 '011_67N_illumina': <MeasurementSet: 011_67N_illumina>,
 '011_67A_illumina': <MeasurementSet: 011_67A_illumina>,
 '011_67B_illumina': <MeasurementSet: 011_67B_illumina>,
 '011_67C_illumina': <MeasurementSet: 011_67C_illumina>,
 '011_67D_illumina': <MeasurementSet: 011_67D_illumina>,
 '011_67E_illumina': <MeasurementSet: 011_67E_illumina>,
 '011_67F_illumina': <MeasurementSet: 011_67F_illumina>,
 '011_67G_illumina': <MeasurementSet: 011_67G_illumina>,
 '011_67H_illumina': <MeasurementSet: 011_67H_illumina>,
 '012_13A_illumina': <MeasurementSet: 012_13A_illumina>,
 '012_13B_illumina': <MeasurementSet: 012_13B_illumina>,
 '012_13C_illumina': <MeasurementSet: 012_13C_illumina>,
 '012_13D_illumina': <MeasurementSet: 012_13D_illumina>,
 '012_13E_illumina': <MeasurementSet: 012_13E_illumina>,
 '012_13F_illumina': <MeasurementSet: 012_13F_illumina>,
 '012_13G_illumina': <MeasurementSet: 012_13G_illumina>,
 '012_13H_illumina': <MeasurementSet: 012_13H_illumina>,
 '013_13A_illumina': <MeasurementSet: 013_13A_illumina>,
 '013_67H_illumina': <MeasurementSet: 013_67H_illumina>,
 '013_67J_illumina': <MeasurementSet: 013_67J_illumina>,
 '013_67A_illumina': <MeasurementSet: 013_67A_illumina>,
 '013_67B_illumina': <MeasurementSet: 013_67B_illumina>,
 '013_67C_illumina': <MeasurementSet: 013_67C_illumina>,
 '013_67D_illumina': <MeasurementSet: 013_67D_illumina>,
 '013_67E_illumina': <MeasurementSet: 013_67E_illumina>,
 '013_67F_illumina': <MeasurementSet: 013_67F_illumina>,
 '013_67G_illumina': <MeasurementSet: 013_67G_illumina>,
 '013_67I_illumina': <MeasurementSet: 013_67I_illumina>,
 '013_67K_illumina': <MeasurementSet: 013_67K_illumina>,
 '013_67L_illumina': <MeasurementSet: 013_67L_illumina>,
 '013_67M_illumina': <MeasurementSet: 013_67M_illumina>,
 '013_67N_illumina': <MeasurementSet: 013_67N_illumina>,
 '014_13A_illumina': <MeasurementSet: 014_13A_illumina>,
 '014_13B_illumina': <MeasurementSet: 014_13B_illumina>,
 '014_13C_illumina': <MeasurementSet: 014_13C_illumina>,
 '014_13D_illumina': <MeasurementSet: 014_13D_illumina>,
 '014_13E_illumina': <MeasurementSet: 014_13E_illumina>,
 '014_13F_illumina': <MeasurementSet: 014_13F_illumina>,
 '014_13G_illumina': <MeasurementSet: 014_13G_illumina>,
 '014_13H_illumina': <MeasurementSet: 014_13H_illumina>}

# Subpool

## Extract meaning from the Experiments tab

- number of nuclei per subpool (Experiment) 
- cDNA amp # PCR cycles (Experiment)
- cDNA ng/ul in 25ul (experiment)
- total cDNA ng (experiment)
- Bioanalyzer cDNA ave bp length (expierment)
- Sub library Index PCR # (experiment)
- Sublibrary Index (experiment)
- Sequence for SampleSheet (experiment)
- library ng/ul (experiment)
- Bioanalyzer library ave bp length (experiment)
- Nextseq run number (experiment)

- number of 67k aliquots  (experiment)
- number of 8k aliquots (experiment)

- QC # raw reads (1 mismatch) (experiment)

In [50]:
experiment = pandas.read_excel(
    lizs_sheet_name, 
    sheet_name="Experiment",
    header=0,
    index_col=None,
    #usecols=range(0, 49)
)
experiment

,Experiment,mice,Fixation Box,Split-seq prep start date,Sublibrary,Protocol,Metadata ready,Submit,[Barcoded Nuclei] (nuclei/uL),Barcoded Nuclei Vol. (uL),...,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71
0,IGVF_Splitseq_002,B6 (2F+2M),IGVF_FIX_001,2022-08-24 00:00:00,002_4A,NaN,Yes,No,4540,240,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Kit Used,CAST (2F+2M),IGVF_FIX_002,NaN,002_4B,NaN,Yes,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fixation V1,NaN,NaN,Technician,002_64A,NaN,Yes,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1M V1,NaN,NaN,ER,002_64B,NaN,Yes,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,002_64C,NaN,Yes,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
406,Gastroc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
407,Adrenal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
408,Hypothalamus + Pituitary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
409,Kidney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
410,Gonads,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
experiment = pandas.read_excel(
    lizs_sheet_name, 
    sheet_name="Experiment",
    header=0,
    index_col=None,
    #usecols=range(0, 49)
).rename(columns={
    # Unnamed: 42 seems like an index or reference to the sample sheet?
    "Unnamed: 43": "Novaseq raw reads",
    "Unnamed: 44": "Novaseq1 L001",
    "Unnamed: 45": "Novaseq1 L002",
    "Unnamed: 46": "Novaseq1 L003",
    "Unnamed: 47": "Novaseq1 L004",
    "Unnamed: 48": "Novaseq2 L001",
    "Unnamed: 49": "Novaseq2 L002",
    "Unnamed: 50": "Novaseq2 L003",
    "Unnamed: 51": "Novaseq2 L004",
})

experiment

,Experiment,mice,Fixation Box,Split-seq prep start date,Sublibrary,Protocol,Metadata ready,Submit,[Barcoded Nuclei] (nuclei/uL),Barcoded Nuclei Vol. (uL),...,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71
0,IGVF_Splitseq_002,B6 (2F+2M),IGVF_FIX_001,2022-08-24 00:00:00,002_4A,NaN,Yes,No,4540,240,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Kit Used,CAST (2F+2M),IGVF_FIX_002,NaN,002_4B,NaN,Yes,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fixation V1,NaN,NaN,Technician,002_64A,NaN,Yes,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1M V1,NaN,NaN,ER,002_64B,NaN,Yes,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,002_64C,NaN,Yes,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
406,Gastroc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
407,Adrenal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
408,Hypothalamus + Pituitary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
409,Kidney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
410,Gonads,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
def is_experiment_name(name):
    not_submittable = ["IGVF_Splitseq_EX"]
    return not pandas.isnull(name) and name.startswith("IGVF_Splitseq")

experiment[experiment["Experiment"].apply(is_experiment_name) & (pandas.notnull(experiment["mice"]))]

,Experiment,mice,Fixation Box,Split-seq prep start date,Sublibrary,Protocol,Metadata ready,Submit,[Barcoded Nuclei] (nuclei/uL),Barcoded Nuclei Vol. (uL),...,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71
0,IGVF_Splitseq_002,B6 (2F+2M),IGVF_FIX_001,2022-08-24 00:00:00,002_4A,NaN,Yes,No,4540,240,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,IGVF_Splitseq_003,8 founders (4M+4F),IGVF_FIX_003,2022-12-01 00:00:00,003_8A,NaN,Yes,No,6860,250,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
34,IGVF_Splitseq_004,8 founders (4M+4F),IGVF_FIX_005,2022-12-15 00:00:00,004_8A,NaN,Yes,No,2460,640,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
51,IGVF_Splitseq_005,8 founders (4M+4F),IGVF_FIX_010,2023-01-23 00:00:00,005_8A,NaN,Yes,No,4675,390,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
68,IGVF_Splitseq_006,8 founders (4M+4F),IGVF_FIX_006,2023-02-10 00:00:00,006_8A,NaN,Yes,No,3160,780,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
87,IGVF_Splitseq_007,8 founders (4M+4F),IGVF_FIX_006,2023-03-07 00:00:00,007_8A,NaN,No,No,2810,580,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
105,IGVF_Splitseq_008,8 founders (4M+4F),IGVF_FIX_008,2023-03-24 00:00:00,008_8A,NaN,No,No,2600,250,...,NaN,Total,L001,L002,L003,L004,NaN,NaN,NaN,NaN
117,IGVF_Splitseq_B01,CASTJ + B6J (2M+2F),NaN,2023-04-03 00:00:00,B01_13A,"splitseq_100k_v2, left_cortex_nuclei_prep",Yes,Yes,4920,83.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,IGVF_Splitseq_008B,8 founders (4M+4F),IGVF_FIX_008,2023-04-19 00:00:00,008B_67A,"splitseq_1M_v2, male_gonads_nuclei_prep, femal...",Yes,Yes,3330,250,...,2,1417529714,355914199,355917666,358863075,346834774,NaN,NaN,NaN,NaN
137,IGVF_Splitseq_009,8 founders (4M+4F),IGVF_FIX_004,2023-05-02 00:00:00,009_67A,"splitseq_1M_v2, adrenal_nuclei_prep, kidney_nu...",Yes,Yes,3370,285,...,2,1474101220,177858630,182128617,178436907,177628982,189105418,193500915,191649075,183792676
153,IGVF_Splitseq_010,8 founders (4M+4F),IGVF_FIX_011,2023-05-08 00:00:00,010_67A,"splitseq_1M_v2, kidney_nuclei_prep, gastroc_nu...",Yes,Yes,5440,250,...,2,1276835447,173224540,171233145,172829595,168517796,145490904,150435757,148667669,146436041
169,IGVF_Splitseq_011,8 founders (4M+4F),IGVF_FIX_012,2023-05-08 00:00:00,011_67A,"splitseq_1M_v2, gastroc_nuclei_prep, cortex_hi...",Yes,Yes,6620,250,...,2,1316269124,173623468,170663719,172876343,165573211,158569678,162211611,156551618,156199476
185,IGVF_Splitseq_EX,8 founders (4M+4F),NaN,2023-05-15 00:00:00,003_13A,"splitseq_1M_v2, cortex_hipp_nuclei_prep, heart...",Yes,Yes,6860,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,IGVF_Splitseq_012,B6J,IGVF_Repeats,2023-06-09 00:00:00,012_13A,"splitseq_100k_v2, gastroc_nuclei_prep, cortex_...",Yes,Yes,3220,81,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,IGVF_Splitseq_013,8 founders + 4 F1s (4M+4F),IGVF_FIX_021,2023-09-08 00:00:00,013_13A,"splitseq_1M_v2, pbmc_cell_prep, cdna_exome_cap...",Yes,Yes,4160,225,...,NaN,Total,L001,L002,L003,L004,NaN,NaN,NaN,NaN
225,IGVF_Splitseq_014,B6J,IGVF_FIX_021,2023-09-25 00:00:00,014_13A,"splitseq_100k_v2, pbmc_cell_prep",Yes,Yes,1040,97.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235,IGVF_Splitseq_015,TREM2R47HNSS,IGVF015_TREM2,2023-11-28 00:00:00,015_13A,"splitseq_1M_v2, gastroc_nuclei_prep, cortex_hi...",Yes,NaN,6620,225,...,Total,L001,L002,L003,L004,L001,L002,L003,L004,L004
253,IGVF_Splitseq_016,8 F1s (4M+4F),IGVF_FIX_013,2023-12-10 00:00:00,016_13A,"splitseq_1M_v2, cortex_hipp_nuclei_prep",Yes,NaN,7010,240,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
271,IGVF_Splitseq_017,8 F1s (4M+4F),IGVF_FIX_015,2024-01-30 00:00:00,017_13A,"splitseq_1M_v2, heart_nuclei_prep",Yes,NaN,2710,242,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
289,IGVF_Splitseq_018,8 F1s (4M+4F),IGVF_FIX_014,2024-02-22 00:00:00,018_13A,"splitseq_1M_v2, liver_nuclei_prep",Yes,NaN,5090,228,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
307,IGVF_Splitseq_019,8 F1s (4M+4F),IGVF_FIX_020,2024-03-19 00:00:00,019_13A,"splitseq_1M_v2, gastroc_nuclei_prep",Yes,NaN,6110,243,...,NaN,Total,L001,L002,L003,L004,L005,L006,L007,L008
325,IGVF_Splitseq_020,8 F1s (4M+4F),IGVF_FIX_016,2024-04-02 00:00:00,020_13A,"splitseq_1M_v2, adrenal_nuclei_prep",Yes,NaN,7540,235,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
343,IGVF_Splitseq_021,8 F1s (4M+4F),IGVF_FIX_012,2024-04-09 00:00:00,021_13A,"splitseq_1M_v2, hypo_pit_nuclei_prep",Yes,NaN,7370,240,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
361,IGVF_Splitseq_022,8 F1s (4M+4F),IGVF_FIX_019,2024-04-30 00:00:00,022_13A,"splitseq_1M_v2, kidney_nuclei_prep",Yes,NaN,6440,240,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
379,IGVF_Splitseq_023,8 F1s (4M+4F),IGVF_FIX_018,2024-05-24 00:00:00,023_13A,"splitseq_1M_v2, mgonads_fgonads_nuclei_prep",Yes,NaN,7400,215,...,NaN,Total,L001,L002,L003,L004,L001,L002,L003,L004
397,IGVF_Splitseq_024,8 F1s (4M+4F),NaN,2024-06-12 00:00:00,016_13A,"splitseq_1M_v2, cortex_hipp_nuclei_prep",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
def find_fixation_start(sheet):
    def is_experiment_name(name):
        #not_submittable = ["IGVF_Splitseq_EX"]
        return not pandas.isnull(name) and name.startswith("IGVF_Splitseq") # and not name in not_submittable

    has_experiment_name = sheet["Experiment"].apply(is_experiment_name)
    has_mice = pandas.notnull(sheet["mice"])
    has_counts = pandas.notnull(sheet["[Barcoded Nuclei] (nuclei/uL)"])
    for fixation_id_row in sheet[has_experiment_name & has_mice & has_counts].index:
        name = sheet.loc[fixation_id_row, "Experiment"]

        start = fixation_id_row

        stop = sheet.shape[0]
        for i, value in sheet.iloc[start:]["Sublibrary"].items():
            if pandas.isnull(value):
                stop = i - 1
                break

        yield (name, start, stop)

for name, start, stop in find_fixation_start(experiment):
    print(name, start, stop)

IGVF_Splitseq_002 0 15
IGVF_Splitseq_003 17 32
IGVF_Splitseq_004 34 49
IGVF_Splitseq_005 51 66
IGVF_Splitseq_006 68 85
IGVF_Splitseq_007 87 102
IGVF_Splitseq_008 105 114
IGVF_Splitseq_B01 117 124
IGVF_Splitseq_008B 126 135
IGVF_Splitseq_009 137 151
IGVF_Splitseq_010 153 167
IGVF_Splitseq_011 169 183
IGVF_Splitseq_EX 185 192
IGVF_Splitseq_012 196 203
IGVF_Splitseq_013 208 222
IGVF_Splitseq_014 225 232
IGVF_Splitseq_015 235 250
IGVF_Splitseq_016 253 268
IGVF_Splitseq_017 271 286
IGVF_Splitseq_018 289 304
IGVF_Splitseq_019 307 322
IGVF_Splitseq_020 325 340
IGVF_Splitseq_021 343 358
IGVF_Splitseq_022 361 376
IGVF_Splitseq_023 379 394

In [54]:
def parse_selection_type(value):
    if value is None:
        return None
    elif value.lower() in ("normal", "no"):
        return models.LibrarySelectionTypeEnum.no_selection
    elif value in ("capture", "EX"):
        return models.LibrarySelectionTypeEnum.exome_capture
    else:
        raise ValueError(f"Unrecognized capture type {value}")
        
def parse_sample_type(value):
    if value is None:
        return None
    elif value.lower() in ("nuclei",):
        return models.CellularComponentEnum.nuclei
    elif value.lower() in ("cells",):
        return models.CellularComponentEnum.cellular
    else:
        raise ValueError(f"Unrecognized sample type {value}")


def parse_fixation(sheet, experiment_name, start, stop):
    block = sheet.loc[start:stop]

    experiment_name_fields = experiment_name.split("_")
    plate_name = f"{experiment_name_fields[0]}_{experiment_name_fields[-1]}"
    
    version = None
    kit = None
    aliquots = {}
    for i, row in block.iterrows():
        count = row["# of backup aliquots"]
        size = row["Backup Aliquot Size"]
        if not (pandas.isnull(count) or pandas.isnull(size)):
            if isinstance(size, str) and size.endswith("k"):
                size = size[:-1]
            size = int(size) * 1000
            aliquots[size] = int(count)
            
        if row["Experiment"] == "Kit Used":
            version = block.loc[i+1, "Experiment"]
            kit = block.loc[i+2, "Experiment"]
    
    experiment = {
        "experiment_name": experiment_name,
        "plate_name": plate_name,
        "prep_date": block.loc[start, "Split-seq prep start date"],
        "unused_aliquots": aliquots,
        "protocol_vendor": version,
        "protocol_kit": kit,
        "subpool": [],
    }

    for i, row in block.iterrows():
        if not pandas.isnull(row["Sublibrary"]):
            if pandas.isnull(row["NovaSeq Sequencing date"]):
                novaseq_run_id = None
            else:
                novaseq_run_id = row["NovaSeq Sequencing date"].isoformat().split("T")[0]

            if pandas.isnull(row.get("Novaseq raw reads")):
                novaseq_raw_reads = None
                novaseq1_raw_reads = None
                novaseq2_raw_reads = None
            elif row["Novaseq raw reads"] == "Total":
                novaseq_raw_reads = None
                novaseq1_raw_reads = None
                novaseq2_raw_reads = None
            else:
                novaseq_raw_reads = int_or_none(row.get("Novaseq raw reads"))
                novaseq1_raw_reads = sum([int_or_none(row.get(x)) for x in["Novaseq1 L001", "Novaseq1 L002", "Novaseq1 L003", "Novaseq1 L004"]])
                novaseq2_raw_reads = sum([int_or_none(row.get(x)) for x in["Novaseq2 L001", "Novaseq2 L002", "Novaseq2 L003", "Novaseq2 L004"]])

            if pandas.isnull(row['Protocol']):
                experiment_protocols = None
            else:
                experiment_protocols = []
                for name in row["Protocol"].split(","):
                    name = name.strip()
                    if name in protocols:
                         experiment_protocols.append(protocols[name.strip()])
                    else:
                        print(f"Unable to find protocol for key {name} on {i+1} {row['Sublibrary']}")
                        
            if pandas.isnull(row["Nextseq run #"]):
                nextseq_run_id = None
            elif isinstance(row["Nextseq run #"], str):
                nextseq_run_id = [int(x) for x in row["Nextseq run #"].split(",")]
            else:
                nextseq_run_id = [int_or_none(row["Nextseq run #"])]

            plate_name, subname = row["Sublibrary"].split("_")
            print(row["Sublibrary Type"], row["Sublibrary"])
            subpool = {
                "name": row["Sublibrary"],
                "plate_name": "IGVF_{}".format(plate_name),
                "subpool_subname": subname,
                "submit": row["Submit"],
                "protocols": experiment_protocols,
                "nuclei": int_or_none(row["Nuclei / Sublibrary"]),
                "selection_type": parse_selection_type(row["Sublibrary Type"]),
                "cdna_pcr_rounds": row["cDNA Amp # PCR Cycles"],
                "cdna_ng_per_ul": row["[cDNA] (ng/uL)"],
                "cdna_volume": row["cDNA Vol. (uL)"],
                #total_cdna = cdna_ng_per_ul_in_25ul * 25
                "bioanalyzer_date": row["BA date"],
                "cdna_average_bp_length": int_or_none(row["cDNA Ave. Length (bp)"]),
                "gene_capture_ng_per_ul": row["[Gene Capture cDNA] (ng/uL)"],
                "index_pcr_no": int_or_none(row["Sub library Index PCR #"]),
                "index": str_or_none(row["Sublibrary Index"]),
                "i7_barcode": row["i7 Forward Sequence"],
                "i5_barcode": row["i5 Forward Sequence"],
                "library_ng_per_ul": float_or_none(row["[Library] (ng/ul)"]),
                "library_average_bp_length": float_or_none(row["Library Ave. Length (bp)"]),
                "nextseq_run_date": date_or_none(row["QC Sequencing date"]),
                "nextseq_run_id": nextseq_run_id,
                "nextseq_run_raw_reads": int_or_none(row["QC # raw reads  (1 mismatch)"]),
                "novaseq_run_date": date_or_none(row["NovaSeq Sequencing date"]),
                "novaseq_run_id": novaseq_run_id,
                "novaseq_run_raw_reads": novaseq_raw_reads,
                "novaseq1_raw_reads": novaseq1_raw_reads,
                "novaseq2_raw_reads": novaseq2_raw_reads,
            }
            experiment["subpool"].append(subpool)
            #if not pandas.isnull(subpool["nuclei"]):
            #    nuclei = subpool["nuclei"]
            #    aliquots[nuclei] = aliquots.get(nuclei) + 1

    return experiment

#parse_fixation(experiment, "IGVF_Splitseq_003", 17, 32)
#parse_fixation(experiment, "IGVF_Splitseq_008", 108, 117)
#parse_fixation(experiment, "IGVF_Splitseq_B01", 124, 131)
#parse_fixation(experiment, "IGVF_Splitseq_008B", 133, 143)
parse_fixation(experiment, "IGVF_Splitseq_EX", 186, 197)
#parse_fixation(experiment, 'IGVF_Splitseq_015', 235, 250)

EX 004_13A
EX 005_13A
EX 007_13A
EX 008B_13A
EX 009_13A
EX 010_13A
EX 011_13A
NO 012_13A
NO 012_13B

{'experiment_name': 'IGVF_Splitseq_EX',
 'plate_name': 'IGVF_EX',
 'prep_date': nan,
 'unused_aliquots': {13000: 12},
 'protocol_vendor': 'Parse Fixation V2',
 'protocol_kit': '1M V2',
 'subpool': [{'name': '004_13A',
   'plate_name': 'IGVF_004',
   'subpool_subname': '13A',
   'submit': 'Yes',
   'protocols': [<ProtocolLink: ProtocolLink object (splitseq_1M_v2)>,
    <ProtocolLink: ProtocolLink object (heart_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (liver_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (cdna_exome_capture)>,
    <ProtocolLink: ProtocolLink object (ont_library_prep)>],
   'nuclei': 13000,
   'selection_type': <LibrarySelectionTypeEnum.exome_capture: 'EX'>,
   'cdna_pcr_rounds': '5 + 8',
   'cdna_ng_per_ul': 23.8,
   'cdna_volume': 25.0,
   'bioanalyzer_date': NaT,
   'cdna_average_bp_length': None,
   'gene_capture_ng_per_ul': 51.5,
   'index_pcr_no': 12,
   'index': 2,
   'i7_barcode': 'ACTTGA',
   'i5_barcode': nan,
   'library_ng_per_ul': 24.4,
   'library_average_bp_length': None,
   'nextseq_run_date': datetime.date(2023, 5, 30),
   'nextseq_run_id': [1070],
   'nextseq_run_raw_reads': None,
   'novaseq_run_date': None,
   'novaseq_run_id': None,
   'novaseq_run_raw_reads': None,
   'novaseq1_raw_reads': None,
   'novaseq2_raw_reads': None},
  {'name': '005_13A',
   'plate_name': 'IGVF_005',
   'subpool_subname': '13A',
   'submit': 'Yes',
   'protocols': [<ProtocolLink: ProtocolLink object (splitseq_1M_v2)>,
    <ProtocolLink: ProtocolLink object (liver_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (hypo_pit_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (cdna_exome_capture)>,
    <ProtocolLink: ProtocolLink object (ont_library_prep)>],
   'nuclei': 13000,
   'selection_type': <LibrarySelectionTypeEnum.exome_capture: 'EX'>,
   'cdna_pcr_rounds': '5 + 8',
   'cdna_ng_per_ul': 52.0,
   'cdna_volume': 25.0,
   'bioanalyzer_date': NaT,
   'cdna_average_bp_length': None,
   'gene_capture_ng_per_ul': 45.4,
   'index_pcr_no': 12,
   'index': 3,
   'i7_barcode': 'GATCAG',
   'i5_barcode': nan,
   'library_ng_per_ul': 19.8,
   'library_average_bp_length': None,
   'nextseq_run_date': datetime.date(2023, 5, 30),
   'nextseq_run_id': [1070],
   'nextseq_run_raw_reads': None,
   'novaseq_run_date': None,
   'novaseq_run_id': None,
   'novaseq_run_raw_reads': None,
   'novaseq1_raw_reads': None,
   'novaseq2_raw_reads': None},
  {'name': '007_13A',
   'plate_name': 'IGVF_007',
   'subpool_subname': '13A',
   'submit': 'Yes',
   'protocols': [<ProtocolLink: ProtocolLink object (splitseq_1M_v2)>,
    <ProtocolLink: ProtocolLink object (hypo_pit_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (male_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (female_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (cdna_exome_capture)>,
    <ProtocolLink: ProtocolLink object (ont_library_prep)>],
   'nuclei': 13000,
   'selection_type': <LibrarySelectionTypeEnum.exome_capture: 'EX'>,
   'cdna_pcr_rounds': '5 + 8',
   'cdna_ng_per_ul': 62.4,
   'cdna_volume': 25.0,
   'bioanalyzer_date': NaT,
   'cdna_average_bp_length': None,
   'gene_capture_ng_per_ul': 35.5,
   'index_pcr_no': 12,
   'index': 4,
   'i7_barcode': 'TAGCTT',
   'i5_barcode': nan,
   'library_ng_per_ul': 17.5,
   'library_average_bp_length': None,
   'nextseq_run_date': datetime.date(2023, 5, 30),
   'nextseq_run_id': [1070],
   'nextseq_run_raw_reads': None,
   'novaseq_run_date': None,
   'novaseq_run_id': None,
   'novaseq_run_raw_reads': None,
   'novaseq1_raw_reads': None,
   'novaseq2_raw_reads': None},
  {'name': '008B_13A',
   'plate_name': 'IGVF_008B',
   'subpool_subname': '13A',
   'submit': 'Yes',
   'protocols': [<ProtocolLink: ProtocolLink object (splitseq_1M_v2)>,
    <ProtocolLink: ProtocolLink object (male_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (female_gonads_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (adrenal_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (cdna_exome_capture)>,
    <ProtocolLink: ProtocolLink object (ont_library_prep)>],
   'nuclei': 13000,
   'selection_type': <LibrarySelectionTypeEnum.exome_capture: 'EX'>,
   'cdna_pcr_rounds': '5 + 8',
   'cdna_ng_per_ul': 57.6,
   'cdna_volume': 25.0,
   'bioanalyzer_date': NaT,
   'cdna_average_bp_length': None,
   'gene_capture_ng_per_ul': 51.0,
   'index_pcr_no': 12,
   'index': 5,
   'i7_barcode': 'ATGTCA',
   'i5_barcode': nan,
   'library_ng_per_ul': 16.8,
   'library_average_bp_length': None,
   'nextseq_run_date': datetime.date(2023, 6, 2),
   'nextseq_run_id': [1071],
   'nextseq_run_raw_reads': None,
   'novaseq_run_date': None,
   'novaseq_run_id': None,
   'novaseq_run_raw_reads': None,
   'novaseq1_raw_reads': None,
   'novaseq2_raw_reads': None},
  {'name': '009_13A',
   'plate_name': 'IGVF_009',
   'subpool_subname': '13A',
   'submit': 'Yes',
   'protocols': [<ProtocolLink: ProtocolLink object (splitseq_1M_v2)>,
    <ProtocolLink: ProtocolLink object (adrenal_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (kidney_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (cdna_exome_capture)>,
    <ProtocolLink: ProtocolLink object (ont_library_prep)>],
   'nuclei': 13000,
   'selection_type': <LibrarySelectionTypeEnum.exome_capture: 'EX'>,
   'cdna_pcr_rounds': '5 + 8',
   'cdna_ng_per_ul': 84.5,
   'cdna_volume': 25.0,
   'bioanalyzer_date': NaT,
   'cdna_average_bp_length': None,
   'gene_capture_ng_per_ul': 39.5,
   'index_pcr_no': 12,
   'index': 6,
   'i7_barcode': 'CTTGTA',
   'i5_barcode': nan,
   'library_ng_per_ul': 20.8,
   'library_average_bp_length': None,
   'nextseq_run_date': datetime.date(2023, 6, 2),
   'nextseq_run_id': [1071],
   'nextseq_run_raw_reads': None,
   'novaseq_run_date': None,
   'novaseq_run_id': None,
   'novaseq_run_raw_reads': None,
   'novaseq1_raw_reads': None,
   'novaseq2_raw_reads': None},
  {'name': '010_13A',
   'plate_name': 'IGVF_010',
   'subpool_subname': '13A',
   'submit': 'Yes',
   'protocols': [<ProtocolLink: ProtocolLink object (splitseq_1M_v2)>,
    <ProtocolLink: ProtocolLink object (kidney_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (gastroc_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (cdna_exome_capture)>,
    <ProtocolLink: ProtocolLink object (ont_library_prep)>],
   'nuclei': 13000,
   'selection_type': <LibrarySelectionTypeEnum.exome_capture: 'EX'>,
   'cdna_pcr_rounds': '5 + 8',
   'cdna_ng_per_ul': 25.8,
   'cdna_volume': 25.0,
   'bioanalyzer_date': NaT,
   'cdna_average_bp_length': None,
   'gene_capture_ng_per_ul': 71.5,
   'index_pcr_no': 12,
   'index': 7,
   'i7_barcode': 'AGTCAA',
   'i5_barcode': nan,
   'library_ng_per_ul': 27.6,
   'library_average_bp_length': None,
   'nextseq_run_date': datetime.date(2023, 6, 2),
   'nextseq_run_id': [1071],
   'nextseq_run_raw_reads': None,
   'novaseq_run_date': None,
   'novaseq_run_id': None,
   'novaseq_run_raw_reads': None,
   'novaseq1_raw_reads': None,
   'novaseq2_raw_reads': None},
  {'name': '011_13A',
   'plate_name': 'IGVF_011',
   'subpool_subname': '13A',
   'submit': 'Yes',
   'protocols': [<ProtocolLink: ProtocolLink object (splitseq_1M_v2)>,
    <ProtocolLink: ProtocolLink object (kidney_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (gastroc_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (cdna_exome_capture)>,
    <ProtocolLink: ProtocolLink object (ont_library_prep)>],
   'nuclei': 13000,
   'selection_type': <LibrarySelectionTypeEnum.exome_capture: 'EX'>,
   'cdna_pcr_rounds': '5 + 8',
   'cdna_ng_per_ul': 98.0,
   'cdna_volume': 25.0,
   'bioanalyzer_date': NaT,
   'cdna_average_bp_length': None,
   'gene_capture_ng_per_ul': 32.2,
   'index_pcr_no': 12,
   'index': 8,
   'i7_barcode': 'AGTTCC',
   'i5_barcode': nan,
   'library_ng_per_ul': 17.9,
   'library_average_bp_length': None,
   'nextseq_run_date': datetime.date(2023, 6, 2),
   'nextseq_run_id': [1071],
   'nextseq_run_raw_reads': None,
   'novaseq_run_date': None,
   'novaseq_run_id': None,
   'novaseq_run_raw_reads': None,
   'novaseq1_raw_reads': None,
   'novaseq2_raw_reads': None},
  {'name': '012_13A',
   'plate_name': 'IGVF_012',
   'subpool_subname': '13A',
   'submit': 'Yes',
   'protocols': [<ProtocolLink: ProtocolLink object (splitseq_100k_v2)>,
    <ProtocolLink: ProtocolLink object (gastroc_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (cortex_hipp_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (heart_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (adrenal_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (hypo_pit_nuclei_prep)>],
   'nuclei': 13000,
   'selection_type': <LibrarySelectionTypeEnum.no_selection: 'NO'>,
   'cdna_pcr_rounds': '5 + 8',
   'cdna_ng_per_ul': 72.1,
   'cdna_volume': 20.0,
   'bioanalyzer_date': Timestamp('2023-06-13 00:00:00'),
   'cdna_average_bp_length': 1368,
   'gene_capture_ng_per_ul': nan,
   'index_pcr_no': 11,
   'index': 1,
   'i7_barcode': 'CAGATC',
   'i5_barcode': nan,
   'library_ng_per_ul': 19.2,
   'library_average_bp_length': 446.0,
   'nextseq_run_date': datetime.date(2023, 6, 16),
   'nextseq_run_id': [1072],
   'nextseq_run_raw_reads': None,
   'novaseq_run_date': None,
   'novaseq_run_id': None,
   'novaseq_run_raw_reads': None,
   'novaseq1_raw_reads': None,
   'novaseq2_raw_reads': None},
  {'name': '012_13B',
   'plate_name': 'IGVF_012',
   'subpool_subname': '13B',
   'submit': 'Yes',
   'protocols': [<ProtocolLink: ProtocolLink object (splitseq_100k_v2)>,
    <ProtocolLink: ProtocolLink object (gastroc_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (cortex_hipp_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (heart_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (adrenal_nuclei_prep)>,
    <ProtocolLink: ProtocolLink object (hypo_pit_nuclei_prep)>],
   'nuclei': 13000,
   'selection_type': <LibrarySelectionTypeEnum.no_selection: 'NO'>,
   'cdna_pcr_rounds': '5 + 8',
   'cdna_ng_per_ul': 95.2,
   'cdna_volume': 20.0,
   'bioanalyzer_date': Timestamp('2023-06-13 00:00:00'),
   'cdna_average_bp_length': 1458,
   'gene_capture_ng_per_ul': nan,
   'index_pcr_no': 11,
   'index': 2,
   'i7_barcode': 'ACTTGA',
   'i5_barcode': nan,
   'library_ng_per_ul': 14.8,
   'library_average_bp_length': 451.0,
   'nextseq_run_date': datetime.date(2023, 6, 16),
   'nextseq_run_id': [1072],
   'nextseq_run_raw_reads': None,
   'novaseq_run_date': None,
   'novaseq_run_id': None,
   'novaseq_run_raw_reads': None,
   'novaseq1_raw_reads': None,
   'novaseq2_raw_reads': None}]}

In [55]:
platforms = {x.name: x for x in models.Platform.objects.all()}
platforms

{'minion': <Platform: Oxford Nanopore MinION>,
 'nextseq2000': <Platform: Nextseq 2000>,
 'novaseq6000': <Platform: Novaseq 6000>,
 'pacbio': <Platform: Pac Bio>,
 'promethion': <Platform: ONT PromethION>,
 'gridion': <Platform: ONT GridION>,
 'p2solo': <Platform: ONT P2 Solo>}

In [56]:
experiment

,Experiment,mice,Fixation Box,Split-seq prep start date,Sublibrary,Protocol,Metadata ready,Submit,[Barcoded Nuclei] (nuclei/uL),Barcoded Nuclei Vol. (uL),...,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71
0,IGVF_Splitseq_002,B6 (2F+2M),IGVF_FIX_001,2022-08-24 00:00:00,002_4A,NaN,Yes,No,4540,240,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Kit Used,CAST (2F+2M),IGVF_FIX_002,NaN,002_4B,NaN,Yes,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fixation V1,NaN,NaN,Technician,002_64A,NaN,Yes,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1M V1,NaN,NaN,ER,002_64B,NaN,Yes,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,002_64C,NaN,Yes,No,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
406,Gastroc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
407,Adrenal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
408,Hypothalamus + Pituitary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
409,Kidney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
410,Gonads,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# load subpools, sequencing runs and subpools in sequencing run

In [57]:
def load_submitted_multiplexed_samples():
    multiplexed_samples = {}

    for accession_prefix in submitted_sheets:
        for i, row in submitted_sheets[accession_prefix]["multiplexed_sample"].iterrows():
            if not pandas.isnull(row["accession"]):
                aliases = row["aliases:array"].split(',')
                name = aliases[0].replace("ali-mortazavi:", "")
                if accession_prefix == "igvftst":
                    see_also_template = "https://api.sandbox.igvf.org/multiplexed-samples/{}/"
                elif accession_prefix == "igvf":
                    see_also_template = "https://api.data.igvf.org/multiplexed-samples/{}/"

                multiplexed_samples.setdefault(name, []).append({
                    "accession_prefix": accession_prefix,
                    "name": row["accession"],
                    "uuid": row["uuid"],
                    "see_also": see_also_template.format(row["accession"]),
                })
    print(len(multiplexed_samples))
    
    return multiplexed_samples

In [58]:
def load_split_seq_plates_as_dict():
    plates = {}
    for current_plate in models.SplitSeqPlate.objects.all():
        plates[current_plate.name] = current_plate
    return plates

In [59]:
load_split_seq_plates_as_dict()

{'IGVF_003': <SplitSeqPlate: IGVF_003>,
 'IGVF_004': <SplitSeqPlate: IGVF_004>,
 'IGVF_005': <SplitSeqPlate: IGVF_005>,
 'IGVF_006': <SplitSeqPlate: IGVF_006>,
 'IGVF_007': <SplitSeqPlate: IGVF_007>,
 'IGVF_008': <SplitSeqPlate: IGVF_008>,
 'IGVF_008B': <SplitSeqPlate: IGVF_008B>,
 'IGVF_B01': <SplitSeqPlate: IGVF_B01>,
 'IGVF_009': <SplitSeqPlate: IGVF_009>,
 'IGVF_010': <SplitSeqPlate: IGVF_010>,
 'IGVF_011': <SplitSeqPlate: IGVF_011>,
 'IGVF_012': <SplitSeqPlate: IGVF_012>,
 'IGVF_013': <SplitSeqPlate: IGVF_013>,
 'IGVF_014': <SplitSeqPlate: IGVF_014>,
 'IGVF_015': <SplitSeqPlate: IGVF_015>,
 'IGVF_016': <SplitSeqPlate: IGVF_016>,
 'IGVF_017': <SplitSeqPlate: IGVF_017>,
 'IGVF_018': <SplitSeqPlate: IGVF_018>,
 'IGVF_019': <SplitSeqPlate: IGVF_019>,
 'IGVF_020': <SplitSeqPlate: IGVF_020>,
 'IGVF_021': <SplitSeqPlate: IGVF_021>,
 'IGVF_022': <SplitSeqPlate: IGVF_022>}

In [60]:
models.LibraryConstructionReagent.objects.get(name="wt-mega-v1")

In [61]:
def load_experiments_return_submittable_subpools(experiment):
    compression=r"(?<compression>gz|bz2|xz|zstd)"
    nanopore_library_name_re_template = r"igvf(?P<run>[\d]+)_(?P<library_id>{library_name})_.*_(?P<fragment>[\d]+)\.fastq\.{compression}"
    nextseq_library_name_re_template = r"(?P<run>[\d]+)_(?P<library_id>{library_name})_(?P<read_id>[RI][\d])\.fastq\.{compression}"
    nextseq_library_index_re_template = r"Sublibrary_(?P<library_id>{library_index})_S(?P<sample_id>[\d]+)_(?P<lane_id>L[\d]+)_(?P<read_id>[RI][\d])_(?P<fragment>[\d]+)\.fastq\.{compression}"
    novaseq_library_index_re_template = r"Sublibrary_(?P<library_id>{library_index})_S(?P<sample_id>[\d]+)_(?P<lane_id>L[\d]+)_(?P<read_id>[RI][\d])_(?P<fragment>[\d]+)\.fastq\.{compression}"

    multiplexed_samples = load_submitted_multiplexed_samples()
    split_seq_plates = load_split_seq_plates_as_dict()

    failed_plates = {"IGVF_006",}
    failed = False
    submittable_subpools = {}
    kit_mapping = {
        "1M V1": models.LibraryConstructionReagent.objects.get(name="wt-mega-v1"),
        "1M V2": models.LibraryConstructionReagent.objects.get(name="wt-mega-v2"),
        "100K V2": models.LibraryConstructionReagent.objects.get(name="wt-v2"),
    }
    
    for experiment_name, experiment_start, experiment_stop in find_fixation_start(experiment):
        fixation = parse_fixation(experiment, experiment_name, experiment_start, experiment_stop)
        plate_name = fixation["plate_name"]

        if plate_name in failed_plates:
            print(f"Skipping failed plate {plate_name}")
            continue

        last_subpools = {}

        reagent = kit_mapping[fixation["protocol_kit"].upper()]

        for line_offset, subpool in enumerate(fixation["subpool"]):
            if subpool["plate_name"] not in split_seq_plates:
                print("Unable to find plate for {}".format(subpool["plate_name"]))
                continue

            subpool_index = normalize_barcode_index(subpool["index"])
            try:
                barcodes = models.LibraryBarcode.objects.filter(
                    reagent=reagent, 
                    barcode_type=None, 
                    code=subpool_index)
            except models.LibraryBarcode.DoesNotExist:
                print(f"Unable to find barcode {subpool_index}")
                
            if len(barcodes) == 0:
                print(f"Unable to find barcodes with {reagent} None {subpool_index}")

            # validate i7 barcodes
            library_i7_barcodes_sequence = {b.i7_sequence for b in barcodes if pandas.notnull(b.i7_sequence)}
            if not pandas.isnull(subpool["i7_barcode"]):
                i7_expected_sequence = set(subpool["i7_barcode"].split(","))
            else:
                i7_expected_sequence = set()
            if library_i7_barcodes_sequence != i7_expected_sequence:
                print(f"{subpool['name']} Database lookup of {subpool['index']} i7_barcodes {library_i7_barcodes_sequence} doesn't match human entry {i7_expected_sequence}")
                print(reagent, subpool_index, barcodes)
                failed = True
                continue

            # validate i5 barcodes
            library_i5_barcodes_sequence = {b.i5_sequence for b in barcodes if pandas.notnull(b.i5_sequence)}
            if len(library_i5_barcodes_sequence) > 0:
                if not pandas.isnull(subpool["i5_barcode"]):
                    i5_expected_sequence = set(subpool["i5_barcode"].split(","))
                else:
                    i5_expected_sequence = set()
                if library_i5_barcodes_sequence != i5_expected_sequence:
                    print(f"{subpool['name']} Database lookup of i5_barcodes {library_i5_barcodes_sequence} doesn't match human entry {i5_expected_sequence}")
                    failed = True
                    continue

            plate = split_seq_plates[subpool["plate_name"]]
            subpool_prefix = subpool["name"].split("_")[0]
            last_subpools[subpool["nuclei"]] = max(
                last_subpools.get(subpool["nuclei"]), 
                SubpoolName(subpool["subpool_subname"]))

            record = models.Subpool(
                name=subpool["name"],
                plate=plate,
                nuclei=subpool["nuclei"],
                selection_type=subpool["selection_type"],
                cdna_pcr_rounds=subpool["cdna_pcr_rounds"],
                cdna_ng_per_ul=float_or_none(subpool["cdna_ng_per_ul"]),
                cdna_volume=float_or_none(subpool["cdna_volume"]),
                bioanalyzer_date=date_or_none(subpool["bioanalyzer_date"]),
                cdna_average_bp_length=int_or_none(subpool["cdna_average_bp_length"]),
                gene_capture_ng_per_ul=float_or_none(subpool["gene_capture_ng_per_ul"]),
                index_pcr_number=int_or_none(subpool["index_pcr_no"]),
                index=str_or_none(normalize_barcode_index(subpool["index"])),
                library_ng_per_ul=float_or_none(subpool["library_ng_per_ul"]),
                library_average_bp_length=int_or_none(subpool["library_average_bp_length"]),
            )
            record.save()
            if subpool["protocols"] is not None and len(subpool["protocols"]) > 0:
                record.protocols.set(subpool["protocols"])
            record.barcode.set(barcodes)
            record.save()

            if pandas.notnull(subpool["submit"]):
                submittable_subpools[subpool["name"]] = subpool["submit"]

            name = "subpool_{}".format(subpool["name"].lower())
            if name in multiplexed_samples:
                for accession_row in multiplexed_samples[name]:
                    if pandas.notnull(accession_row["name"]):
                        print(name, record.name, multiplexed_samples[name])
                        accession = models.Accession(**accession_row)
                        accession.save()
                        record.accession.add(accession)
                        record.save()            

        for nuclei in fixation["unused_aliquots"]:
            if nuclei in last_subpools:
                subpool_name = last_subpools[nuclei]
                for i in range(fixation["unused_aliquots"][nuclei]):
                    subpool_name = subpool_name.next_code()

                    record = models.Subpool(
                        name="{}_{}".format(subpool_prefix, subpool_name),
                        plate=plate,
                        nuclei=nuclei,
                    )
                    print(record.name)
                    record.save()
            else:
                print("No unused aliquots {} {}".format(nuclei, last_subpools))

    #assert not failed
    return submittable_subpools
    
submittable_subpools = load_experiments_return_submittable_subpools(experiment)

171
NO 002_4A
NO 002_4B
NO 002_64A
NO 002_64B
NO 002_64C
NO 002_64D
NO 002_64E
NO 002_64F
NO 002_64G
NO 002_64H
NO 002_64I
NO 002_64J
NO 002_64K
NO 002_64L
NO 002_64M
NO 002_64N
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
Unable to find plate for IGVF_002
No unused aliquots 67000 {}
NO 003_8A
NO 003_67A
NO 003_67B
NO 003_67C
NO 003_67D
NO 003_67E
NO 003_67F
NO 003_67G
NO 003_67H
NO 003_67I
NO 003_67J
NO 003_67K
NO 003_67L
NO 003_67M
NO 003_67N
NO 003_67O
003_67P
003_67Q
003_67R
003_67S
003_67T
003_67U
003_67V
003_8B
003_8C
NO 004_8A
NO 004_67A
NO 004_67B
NO 004_67C
NO 004_67D
NO 004_67E
NO 004_67F
NO 004_67G
NO 004_67H
NO 004_67I
NO 004_67J
NO 004_67K
NO 004_67L
NO 004_67M
NO 004_67N
NO 004_67O
004_67P
004_67Q
004_67R
004_67S
004_67T
004_8B
004_8C
NO 005_8A
NO 005_67A
NO 005_67B
NO 005_67C
NO 005_67D
NO 005_67E
NO 005_67F
NO 005_67G
NO 005_67H
NO 005_67I
NO 005_67J
NO 005_67K
NO 005_67L
NO 005_67M
NO 005_67N
NO 005_67O
005_67P
005_67Q
005_67R
005_67S
005_67T
005_67U
005_8B
005_8C
005_8D
005_8E
005_8F
005_8G
005_8H
NO 006_8A
NO 006_67A
NO 006_67B
NO 006_67C
NO 006_67D
NO 006_67E
NO 006_67F
NO 006_67G
NO 006_67H
NO 006_67I
NO 006_67J
NO 006_67K
NO 006_67L
NO 006_67M
NO 006_67N
NO 006_67O
NO 006_67P
NO 006_67Q
Skipping failed plate IGVF_006
NO 007_8A
NO 007_67A
NO 007_67B
NO 007_67C
NO 007_67D
NO 007_67E
NO 007_67F
NO 007_67G
NO 007_67H
NO 007_67I
NO 007_67J
NO 007_67K
NO 007_67L
NO 007_67M
NO 007_67N
NO 007_67O
007_67P
007_67Q
007_67R
007_67S
007_67T
007_67U
007_67V
007_67W
007_8B
007_8C
007_8D
007_8E
007_8F
007_8G
007_8H
007_8I
NO 008_8A
NO 008_67A
NO 008_67B
NO 008_67C
NO 008_67D
NO 008_67E
NO 008_67F
NO 008_67G
NO 008_67H
NO 008_67I
NO B01_13A
NO B01_13B
NO B01_13C
NO B01_13D
NO B01_13E
NO B01_13F
EX B01_13G
NO B01_13H
subpool_b01_13a B01_13A [{'accession_prefix': 'igvftst', 'name': 'TSTSM35366348', 'uuid': '77a93b75-f44a-4aa5-937b-a6788051bc18', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM35366348/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM1676SYRC', 'uuid': 'efad3fdd-f466-4c59-94e0-8791e2bfaa93', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM1676SYRC/'}]
subpool_b01_13a B01_13A [{'accession_prefix': 'igvftst', 'name': 'TSTSM35366348', 'uuid': '77a93b75-f44a-4aa5-937b-a6788051bc18', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM35366348/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM1676SYRC', 'uuid': 'efad3fdd-f466-4c59-94e0-8791e2bfaa93', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM1676SYRC/'}]
subpool_b01_13b B01_13B [{'accession_prefix': 'igvftst', 'name': 'TSTSM99018100', 'uuid': '6cac6a8b-7750-4df6-92cf-fae41082813d', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM99018100/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM1955RVUC', 'uuid': 'f45edb75-5e28-4578-a2d5-395546f64b2a', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM1955RVUC/'}]
subpool_b01_13b B01_13B [{'accession_prefix': 'igvftst', 'name': 'TSTSM99018100', 'uuid': '6cac6a8b-7750-4df6-92cf-fae41082813d', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM99018100/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM1955RVUC', 'uuid': 'f45edb75-5e28-4578-a2d5-395546f64b2a', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM1955RVUC/'}]
subpool_b01_13c B01_13C [{'accession_prefix': 'igvftst', 'name': 'TSTSM36900951', 'uuid': '01858fa2-3c3d-476a-8d81-e82a0612c0e8', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM36900951/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM8093RPKR', 'uuid': '33b1fa8c-53ac-4db9-81e2-df137881c434', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM8093RPKR/'}]
subpool_b01_13c B01_13C [{'accession_prefix': 'igvftst', 'name': 'TSTSM36900951', 'uuid': '01858fa2-3c3d-476a-8d81-e82a0612c0e8', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM36900951/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM8093RPKR', 'uuid': '33b1fa8c-53ac-4db9-81e2-df137881c434', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM8093RPKR/'}]
subpool_b01_13d B01_13D [{'accession_prefix': 'igvftst', 'name': 'TSTSM27245068', 'uuid': 'b69b021b-aa90-41cf-8d1f-cfc59c726b20', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM27245068/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM9603DIDI', 'uuid': 'abb7e2a6-c08b-4a15-88fe-94c5c38a3400', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM9603DIDI/'}]
subpool_b01_13d B01_13D [{'accession_prefix': 'igvftst', 'name': 'TSTSM27245068', 'uuid': 'b69b021b-aa90-41cf-8d1f-cfc59c726b20', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM27245068/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM9603DIDI', 'uuid': 'abb7e2a6-c08b-4a15-88fe-94c5c38a3400', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM9603DIDI/'}]
subpool_b01_13e B01_13E [{'accession_prefix': 'igvftst', 'name': 'TSTSM90710268', 'uuid': '8d44590d-bcb5-46f9-8c87-ea375db12ea9', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM90710268/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM6958ESMJ', 'uuid': '92fcc1a8-9170-4a7c-90f8-5ec339a987d1', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM6958ESMJ/'}]
subpool_b01_13e B01_13E [{'accession_prefix': 'igvftst', 'name': 'TSTSM90710268', 'uuid': '8d44590d-bcb5-46f9-8c87-ea375db12ea9', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM90710268/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM6958ESMJ', 'uuid': '92fcc1a8-9170-4a7c-90f8-5ec339a987d1', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM6958ESMJ/'}]
subpool_b01_13f B01_13F [{'accession_prefix': 'igvftst', 'name': 'TSTSM57985101', 'uuid': '2f34272a-6603-41e0-9820-cf2dd432244b', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM57985101/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM6546CQJB', 'uuid': 'b2e62292-5163-4a73-9861-23a535a97dac', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM6546CQJB/'}]
subpool_b01_13f B01_13F [{'accession_prefix': 'igvftst', 'name': 'TSTSM57985101', 'uuid': '2f34272a-6603-41e0-9820-cf2dd432244b', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM57985101/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM6546CQJB', 'uuid': 'b2e62292-5163-4a73-9861-23a535a97dac', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM6546CQJB/'}]
subpool_b01_13g B01_13G [{'accession_prefix': 'igvftst', 'name': 'TSTSM10953505', 'uuid': 'b0e63479-2caf-4aac-9c98-2ff823f92c74', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM10953505/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM8722YQAW', 'uuid': '00179685-55cf-4dc1-a00a-3f5fb9133288', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM8722YQAW/'}]
subpool_b01_13g B01_13G [{'accession_prefix': 'igvftst', 'name': 'TSTSM10953505', 'uuid': 'b0e63479-2caf-4aac-9c98-2ff823f92c74', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM10953505/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM8722YQAW', 'uuid': '00179685-55cf-4dc1-a00a-3f5fb9133288', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM8722YQAW/'}]
subpool_b01_13h B01_13H [{'accession_prefix': 'igvftst', 'name': 'TSTSM89995437', 'uuid': '5484bec6-4b0e-4488-b3b1-fd4def0022df', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM89995437/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM2294BOOU', 'uuid': 'f25eb07b-ed33-496f-a8d7-83814b4b642f', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM2294BOOU/'}]

subpool_b01_13h B01_13H [{'accession_prefix': 'igvftst', 'name': 'TSTSM89995437', 'uuid': '5484bec6-4b0e-4488-b3b1-fd4def0022df', 'see_also': 'https://api.sandbox.igvf.org/multiplexed-samples/TSTSM89995437/'}, {'accession_prefix': 'igvf', 'name': 'IGVFSM2294BOOU', 'uuid': 'f25eb07b-ed33-496f-a8d7-83814b4b642f', 'see_also': 'https://api.data.igvf.org/multiplexed-samples/IGVFSM2294BOOU/'}]
B01_13I
B01_13J
B01_13K
B01_13L
B01_13M
B01_13N
B01_13O
B01_13P
B01_13Q
B01_13R
NO 008B_67A
NO 008B_67B
NO 008B_67C
NO 008B_67D
NO 008B_67E
NO 008B_67F
NO 008B_67G
NO 008B_67H
NO 008B_67I
NO 008B_67J
No unused aliquots 13000 {67000: SubpoolName('67J')}
NO 009_67A
NO 009_67B
NO 009_67C
NO 009_67D
NO 009_67E
NO 009_67F
NO 009_67G
NO 009_67H
NO 009_67I
NO 009_67J
NO 009_67K
NO 009_67L
NO 009_67M
NO 009_67N
NO 009_67O
No unused aliquots 13000 {67000: SubpoolName('67O')}
NO 010_67A
NO 010_67B
NO 010_67C
NO 010_67D
NO 010_67E
NO 010_67F
NO 010_67G
NO 010_67H
NO 010_67I
NO 010_67J
NO 010_67K
NO 010_67L
NO 010_67M
NO 010_67N
NO 010_67O
010_67P
010_67Q
010_67R
No unused aliquots 13000 {67000: SubpoolName('67O')}
NO 011_67A
NO 011_67B
NO 011_67C
NO 011_67D
NO 011_67E
NO 011_67F
NO 011_67G
NO 011_67H
NO 011_67I
NO 011_67J
NO 011_67K
NO 011_67L
NO 011_67M
NO 011_67N
NO 011_67O
011_67P
011_67Q
011_67R
011_67S
011_67T
011_67U
011_67V
No unused aliquots 13000 {67000: SubpoolName('67O')}
EX 003_13A
EX 004_13A
EX 005_13A
EX 007_13A
EX 008B_13A
EX 009_13A
EX 010_13A
EX 011_13A
011_13B
011_13C
NO 012_13A
NO 012_13B
NO 012_13C
NO 012_13D
NO 012_13E
NO 012_13F
NO 012_13G
NO 012_13H
012_13I
012_13J
012_13K
012_13L
012_13M
012_13N
012_13O
012_13P
012_13Q
012_13R
012_13S
012_13T
EX 013_13A
NO 013_67A
NO 013_67B
NO 013_67C
NO 013_67D
NO 013_67E
NO 013_67F
NO 013_67G
NO 013_67H
NO 013_67I
NO 013_67J
NO 013_67K
NO 013_67L
NO 013_67M
NO 013_67N
NO 014_13A
NO 014_13B
NO 014_13C
NO 014_13D
NO 014_13E
NO 014_13F
NO 014_13G
NO 014_13H
NO 015_13A
NO 015_67A
NO 015_67B
NO 015_67C
NO 015_67D
NO 015_67E
NO 015_67F
NO 015_67G
NO 015_67H
NO 015_67I
NO 015_67J
NO 015_67K
NO 015_67L
NO 015_67M
NO 015_67N
NO 015_67O
Unable to find barcodes with Parse WT Mega v2 None None
Unable to find barcodes with Parse WT Mega v2 None None
Unable to find barcodes with Parse WT Mega v2 None None
Unable to find barcodes with Parse WT Mega v2 None None
Unable to find barcodes with Parse WT Mega v2 None None
Unable to find barcodes with Parse WT Mega v2 None None
Unable to find barcodes with Parse WT Mega v2 None None
Unable to find barcodes with Parse WT Mega v2 None None
Unable to find barcodes with Parse WT Mega v2 None None
Unable to find barcodes with Parse WT Mega v2 None None
Unable to find barcodes with Parse WT Mega v2 None None
Unable to find barcodes with Parse WT Mega v2 None None
015_67P
015_67Q
015_67R
015_67S
015_67T
015_67U
015_67V
EX 016_13A
NO 016_67A
NO 016_67B
NO 016_67C
NO 016_67D
NO 016_67E
NO 016_67F
NO 016_67G
NO 016_67H
NO 016_67I
NO 016_67J
NO 016_67K
NO 016_67L
NO 016_67M
NO 016_67N
NO 016_67O
016_67P
016_67Q
016_67R
016_67S
016_67T
016_67U
016_67V
016_67W
016_67X
016_13B
016_13C
016_13D
016_13E
EX 017_13A
NO 017_44A
NO 017_44B
NO 017_44C
NO 017_44D
NO 017_44E
NO 017_44F
NO 017_44G
NO 017_44H
NO 017_44I
NO 017_44J
NO 017_44K
NO 017_44L
NO 017_44M
NO 017_44N
NO 017_28O
Unable to find barcodes with Parse WT Mega v2 None None
EX 018_13A
NO 018_67A
NO 018_67B
NO 018_67C
NO 018_67D
NO 018_67E
NO 018_67F
NO 018_67G
NO 018_67H
NO 018_67I
NO 018_67J
NO 018_67K
NO 018_67L
NO 018_67M
NO 018_67N
NO 018_67O
Unable to find barcodes with Parse WT Mega v2 None None
018_67P
018_67Q
018_67R
EX 019_13A
NO 019_67A
NO 019_67B
NO 019_67C
NO 019_67D
NO 019_67E
NO 019_67F
NO 019_67G
NO 019_67H
NO 019_67I
NO 019_67J
NO 019_67K
NO 019_67L
NO 019_67M
NO 019_67N
NO 019_67O
Unable to find barcodes with Parse WT Mega v2 None None
019_67P
019_67Q
019_67R
019_67S
019_67T
019_67U
EX 020_13A
NO 020_67A
NO 020_67B
NO 020_67C
NO 020_67D
NO 020_67E
NO 020_67F
NO 020_67G
NO 020_67H
NO 020_67I
NO 020_67J
NO 020_67K
NO 020_67L
NO 020_67M
NO 020_67N
NO 020_67O
Unable to find barcodes with Parse WT Mega v2 None None
020_67P
020_67Q
020_67R
020_67S
020_67T
020_67U
020_67V
020_67W
020_67X
020_67Y
020_67Z
EX 021_13A
NO 021_67A
NO 021_67B
NO 021_67C
NO 021_67D
NO 021_67E
NO 021_67F
NO 021_67G
NO 021_67H
NO 021_67I
NO 021_67J
NO 021_67K
NO 021_67L
NO 021_67M
NO 021_67N
NO 021_67O
Unable to find barcodes with Parse WT Mega v2 None None
021_67P
021_67Q
021_67R
021_67S
021_67T
021_67U
021_67V
021_67W
021_67X
021_67Y
021_67Z
EX 022_13A
NO 022_67A
NO 022_67B
NO 022_67C
NO 022_67D
NO 022_67E
NO 022_67F
NO 022_67G
NO 022_67H
NO 022_67I
NO 022_67J
NO 022_67K
NO 022_67L
NO 022_67M
NO 022_67N
NO 022_67O
Unable to find barcodes with Parse WT Mega v2 None None
022_67P
022_67Q
022_67R
022_67S
022_67T
022_67U
022_67V
022_13B
022_13C
022_13D
022_13E
Unable to find protocol for key mgonads_fgonads_nuclei_prep on 380 023_13A
EX 023_13A
Unable to find protocol for key mgonads_fgonads_nuclei_prep on 381 023_67A
NO 023_67A
Unable to find protocol for key mgonads_fgonads_nuclei_prep on 382 023_67B
NO 023_67B
Unable to find protocol for key mgonads_fgonads_nuclei_prep on 383 023_67C
NO 023_67C
Unable to find protocol for key mgonads_fgonads_nuclei_prep on 384 023_67D
NO 023_67D
Unable to find protocol for key mgonads_fgonads_nuclei_prep on 385 023_67E
NO 023_67E
Unable to find protocol for key mgonads_fgonads_nuclei_prep on 386 023_67F
NO 023_67F
Unable to find protocol for key mgonads_fgonads_nuclei_prep on 387 023_67G
NO 023_67G
Unable to find protocol for key mgonads_fgonads_nuclei_prep on 388 023_67H
NO 023_67H
Unable to find protocol for key mgonads_fgonads_nuclei_prep on 389 023_67I
NO 023_67I
Unable to find protocol for key mgonads_fgonads_nuclei_prep on 390 023_67J
NO 023_67J
Unable to find protocol for key mgonads_fgonads_nuclei_prep on 391 023_67K
NO 023_67K
Unable to find protocol for key mgonads_fgonads_nuclei_prep on 392 023_67L
NO 023_67L
Unable to find protocol for key mgonads_fgonads_nuclei_prep on 393 023_67M
NO 023_67M
Unable to find protocol for key mgonads_fgonads_nuclei_prep on 394 023_67N
NO 023_67N
Unable to find protocol for key mgonads_fgonads_nuclei_prep on 395 023_67O
NO 023_67O
Unable to find plate for IGVF_023
Unable to find plate for IGVF_023
Unable to find plate for IGVF_023
Unable to find plate for IGVF_023
Unable to find plate for IGVF_023
Unable to find plate for IGVF_023
Unable to find plate for IGVF_023
Unable to find plate for IGVF_023
Unable to find plate for IGVF_023
Unable to find plate for IGVF_023
Unable to find plate for IGVF_023
Unable to find plate for IGVF_023
Unable to find plate for IGVF_023
Unable to find plate for IGVF_023
Unable to find plate for IGVF_023
Unable to find plate for IGVF_023
No unused aliquots 67000 {}
No unused aliquots 13000 {}

# Parse ONT Sequencing

In [62]:
class PlateBoundary(IntEnum):
    START = 0
    PLATE_NAME = 1
    TECHNICIAN = 2

OntSplitseqPlate = namedtuple("OntSplitseqPlate", ["name", "category", "technicians", "start", "end"])
def find_ont_splitseq_plate_boundaries(sheet):
    state = PlateBoundary.START
    plate_name = None
    category = None
    technicians = []
    start_line = None
    end_line = None
    
    for i, row in sheet.iterrows():
        # Don't import incomplete records
        if pandas.notnull(row["Experiment"]) and row["Experiment"] == "F1s" and pandas.isnull(row["cDNA Build Date"]):
            break
        # Every valid record seems to have a Sample ID
        elif pandas.isnull(row["Sample ID"]):
            state = PlateBoundary.START
            end_line = i
            if start_line is not None:
                yield OntSplitseqPlate(plate_name, category, technicians, start_line, end_line)
                plate_name = None
                category = None
                technicians = []
                start_line = None
        elif isinstance(row["Experiment"], str) and row["Experiment"].startswith("IGVF"):
            plate_name = row["Experiment"]
            start_line = i
            state = PlateBoundary.PLATE_NAME
        elif state == PlateBoundary.PLATE_NAME and pandas.notnull(row["Experiment"]) and row["Experiment"] != "Technician":
            category = row["Experiment"]
        
        if pandas.notnull(row["Tech."]):
            technicians.append(row["Tech."])

    if start_line is not None:
        yield OntSplitseqPlate(plate_name, category, technicians, start_line, end_line)
            
def get_ont_splitseq_subpool_name(row):
    subpool_re = re.compile("igvf(?P<subpool>[\dB]+_[\d]+[A-Z])")
    sample_id = row["Sample ID"]
    if pandas.isnull(sample_id):
        return
    
    match = subpool_re.match(sample_id)
    if match:
        return match.group("subpool")

def normalize_ont_splitseq_plate_name(name):
    if name.startswith("IGVF_"):
        return name
    elif name.startswith("IGVFB"):
        return name.replace("IGVFB", "IGVF_B")
    elif name.startswith("IGVF0"):
        return name.replace("IGVF0", "IGVF_0")
    else:
        raise ValueError("Unrecognized plate name format")

In [63]:
def load_ont_splitseq_sequencing():
    nanopore_samples = {}
    sheet = pandas.read_excel(lizs_sheet_name, sheet_name="ONT Sequencing", skiprows=1)
    sheet["ONT Instrument"] = sheet["ONT Instrument"].apply(instrument_name_to_platform_id)
    sheet["subpool"] = sheet.apply(get_ont_splitseq_subpool_name, axis=1)

    for ont_plate in find_ont_splitseq_plate_boundaries(sheet):
        for i, row in sheet[ont_plate.start:ont_plate.end].iterrows():        
            tube_id = row["ONT Library Replicate ID"]
            if pandas.isnull(tube_id):
                continue
            elif tube_id in nanopore_samples:
                assert nanopore_samples[tube_id]["cdna_build_date"] == row["cDNA Build Date"]
                assert nanopore_samples[tube_id]["cdna_ng_per_ul"] == row["[cDNA] (ng/uL)"]
                assert nanopore_samples[tube_id]["subpool"] == row["subpool"]
            else:
                nanopore_samples[tube_id] = {
                    "plate": normalize_ont_splitseq_plate_name(ont_plate.name),
                    "subpool": row["subpool"],
                    "name": tube_id,
                    "sample_id": row["Sample ID"],
                    # nucleic acid extraction attributes
                    "cdna_build_date": row["cDNA Build Date"],
                    "cdna_volume_ul": row["cDNA Volume (uL)"],
                    "cdna_ng_per_ul": row["[cDNA] (ng/uL)"],
                    "average_length": row["Average Length (bp)"],
                    "technician": ",".join(ont_plate.technicians),
                    "passed_qc": True, # Otherwise it wouldn't be in this sheet.
                    # nanopore library attribtes
                    "library_build_date": row["Library Build Date"],
                    "library_volume_ul": row["Lib. Vol. (uL)"],
                    "library_input_ng_per_ul": row["[Library] (ng/uL)"],
                    # sequencing run attributes
                    "sequencing_run_date": row["Sequencing Date"],
                    "sequencing_run_platform": row["ONT Instrument"],
                    "flowcell_kit": row["Kit"],
                    "flowcell_type": row["Flow Cell Type"],
                    "flowcell_id": row["Flow Cell ID"],
                    "sequencing_software": row["Basecaller"],
                    "comments": row["Notes"],
                }

                try:
                    subpool = models.Subpool.objects.get(pk=row["subpool"])
                except models.Subpool.DoesNotExist as e:
                    print("Unable to find subpool {}".format(row["subpool"]))
                    raise e

    return pandas.DataFrame(nanopore_samples.values())

ont_sequencing = load_ont_splitseq_sequencing()
ont_sequencing

,plate,subpool,name,sample_id,cdna_build_date,cdna_volume_ul,cdna_ng_per_ul,average_length,technician,passed_qc,library_build_date,library_volume_ul,library_input_ng_per_ul,sequencing_run_date,sequencing_run_platform,flowcell_kit,flowcell_type,flowcell_id,sequencing_software,comments
0,IGVF_003,003_8A,ONT001,igvf003_8A_lig-ss_1,2022-12-02,1.153846,130.0,1150.0,"GF,JS",True,2022-12-06,15.0,2.34,2022-12-06,gridion,SQK-LSK114,FLO-MIN114,FAU11962,Guppy,NaN
1,IGVF_003,003_8A,ONT002,igvf003_8A_lig-ss_5,2022-12-02,1.153846,130.0,1150.0,"GF,JS",True,2022-12-08,15.0,3.82,2022-12-08,gridion,SQK-LSK114,FLO-MIN114,FAU05901,Guppy,NaN
2,IGVF_003,003_8A,ONT003,igvf003_8A_lig-ss_10,2022-12-02,1.153846,130.0,1150.0,"GF,JS",True,2022-12-13,15.0,6.10,2022-12-13,gridion,SQK-LSK114,FLO-MIN114,FAV21462,Guppy,NaN
3,IGVF_003,003_13A,ONT018,igvf003_13A-gc_lig-ss_qc_1,2023-05-18,3.091286,48.2,1144.0,"GF,JS",True,2023-05-22,15.0,2.90,2023-06-06,minion,SQK-LSK114-XL,FLO-MIN114,FAW82381,Guppy,NaN
4,IGVF_004,004_8A,ONT004,igvf004_8A_lig-ss_1,2022-12-15,1.870968,77.5,1113.0,GF,True,2023-01-03,15.0,5.90,2023-01-03,gridion,SQK-LSK114,FLO-MIN114,FAV32642,Guppy,NaN
5,IGVF_004,004_8A,ONT005,igvf004_8A_lig-ss_6,2022-12-15,1.870968,77.5,1113.0,GF,True,2023-01-03,15.0,6.02,2023-01-04,gridion,SQK-LSK114,FLO-MIN114,FAV22222,Guppy,NaN
6,IGVF_004,004_8A,ONT006,igvf004_8A_lig-ss_7,2022-12-15,1.870968,77.5,1113.0,GF,True,2023-01-03,15.0,6.74,2023-01-04,gridion,SQK-LSK114,FLO-MIN114,FAV32695,Guppy,NaN
7,IGVF_004,004_8A,ONT007,igvf004_8A_lig-ss_8,2022-12-15,1.587097,77.5,1113.0,GF,True,2023-01-13,15.0,6.66,2023-01-13,gridion,SQK-LSK114,FLO-MIN114,FAV32912,Guppy,NaN
8,IGVF_004,004_8A,ONT008,igvf004_8A_lig-ss_11,2022-12-15,1.677419,77.5,1113.0,GF,True,2023-01-18,15.0,6.24,2023-01-18,gridion,SQK-LSK114,FLO-MIN114,FAW03011,Guppy,NaN
9,IGVF_004,004_13A,ONT019,igvf004_13A-gc_lig-ss_qc_1,2023-05-18,2.660194,51.5,1053.0,GF,True,2023-05-22,15.0,2.78,2023-06-09,minion,SQK-LSK114-XL,FLO-MIN114,FAW87892,Guppy,NaN
10,IGVF_005,005_8A,ONT009,igvf005_8A_lig-ss_1,2023-01-24,3.792208,38.5,1125.0,,True,2023-01-25,15.0,4.16,2023-01-25,gridion,SQK-LSK114,FLO-MIN114,FAW03335,Guppy,NaN
11,IGVF_005,005_8A,ONT010,igvf005_8A_lig-ss_7,2023-01-24,3.792208,38.5,1125.0,,True,2023-02-01,15.0,4.44,2023-02-01,gridion,SQK-LSK114,FLO-MIN114,FAV24206,Guppy,NaN
12,IGVF_005,005_8A,ONT011,igvf005_8A_lig-ss_13,2023-01-24,3.792208,38.5,1125.0,,True,2023-02-24,15.0,2.02,2023-02-24,gridion,SQK-LSK114,FLO-MIN114,FAW26054,Guppy,NaN
13,IGVF_005,005_13A,ONT020&026,igvf005_13A-gc_lig-ss_qc_lid_1,2023-05-18,2.995595,45.4,1043.0,,True,2023-07-07,15.0,4.08,2023-07-07,gridion,SQK-LSK114-XL,FLO-MIN114,FAX29626,Guppy,Used Normal cDNA + GC cDNA to build library
14,IGVF_005,005_13A,ONT029,igvf005_13A-gc_lig-ss_qc_1,2023-05-18,2.995595,45.4,1043.0,,True,2023-07-28,15.0,3.54,2023-07-28,gridion,SQK-LSK114-XL,FLO-MIN114,FAX09019,Guppy,NaN
15,IGVF_B01,B01_13G,ONT012,igvfB01_13G-gc_lig-ss_1,2023-04-04,4.444444,43.2,1473.0,"GF,PM",True,2023-04-07,15.0,3.82,2023-04-07,gridion,SQK-LSK114,FLO-MIN114,FAW43925,Guppy,NaN
16,IGVF_B01,B01_13G,ONT014,igvfB01_13G-gc_lig-ss_4,2023-04-04,4.444444,43.2,1473.0,"GF,PM",True,2023-04-17,15.0,3.06,2023-04-17,gridion,SQK-LSK114,FLO-MIN114,FAW41308,Guppy,NaN
17,IGVF_B01,B01_13G,ONT016,igvfB01_13G-gc_lig-ss_7,2023-04-04,4.444444,43.2,1473.0,"GF,PM",True,2023-04-19,15.0,4.48,2023-04-19,gridion,SQK-LSK114,FLO-MIN114,FAW39182,Guppy,NaN
18,IGVF_B01,B01_13G,ONT021,igvfB01_13G-gc_lig-ss_11,2023-04-04,4.000000,35.5,1091.0,"GF,PM",True,2023-05-22,15.0,3.38,2023-05-19,p2solo,SQK-LSK114,FLO-PRO114M,PAO05399,dorado,NaN
19,IGVF_B01,B01_13H,ONT013,igvfB01_13H_lig-ss_1,2023-04-04,4.552058,41.3,1447.0,"GF,PM",True,2023-04-07,15.0,4.48,2023-04-07,gridion,SQK-LSK114,FLO-MIN114,FAW41173,dorado,NaN
20,IGVF_B01,B01_13H,ONT015,igvfB01_13H_lig-ss_5,2023-04-04,4.552058,41.3,1447.0,"GF,PM",True,2023-04-17,15.0,4.86,2023-04-17,gridion,SQK-LSK114,FLO-MIN114,FAW39354,dorado,NaN
21,IGVF_B01,B01_13H,ONT017,igvfB01_13H_lig-ss_10,2023-04-04,4.552058,41.3,1447.0,"GF,PM",True,2023-04-19,15.0,5.80,2023-04-24,gridion,SQK-LSK114,FLO-MIN114,FAW39859,dorado,NaN
22,IGVF_007,007_13A,ONT021&027,igvf007_13A-gc_lig-ss_qc_1,2023-05-18,4.000000,35.5,1091.0,"GF,PM",True,2023-07-21,15.0,2.58,2023-07-21,minion,SQK-LSK114-XL,FLO-MIN114,FAX05489,Guppy,Both priming and sample ports were left open f...
23,IGVF_007,007_13A,ONT030,igvf007_13A-gc_lig-ss_qc_2,2023-05-18,4.000000,35.5,1091.0,"GF,PM",True,2023-07-28,15.0,2.80,2023-08-03,minion,SQK-LSK114-XL,FLO-MIN114,FAW12158,Guppy,NaN
24,IGVF_008B,008B_13A,ONT031,igvf008B_13A-gc_lig-ss_qc_1,2023-05-18,2.774510,51.0,1089.0,GF,True,2023-07-28,15.0,2.40,2023-08-07,gridion,SQK-LSK114-XL,FLO-MIN114,FAW06562,Guppy,NaN
25,IGVF_009,009_13A,ONT032,igvf009_13A-gc_lig-ss_qc_1,2023-05-18,3.506329,39.5,1064.0,GF,True,2023-07-28,15.0,1.68,2023-08-07,gridion,SQK-LSK114-XL,FLO-MIN114,FAW06495,Guppy,NaN
26,IGVF_010,010_13A,ONT033,igvf010_13A-gc_lig-ss_qc_1,2023-05-18,1.916084,71.5,1054.0,GF,True,2023-07-28,15.0,1.56,2023-08-07,gridion,SQK-LSK114-XL,FLO-MIN114,FAW10031,Guppy,NaN
27,IGVF_011,011_13A,ONT034,igvf011_13A-gc_lig-ss_qc_1,2023-05-18,4.323077,32.5,1080.0,GF,True,2023-07-28,15.0,2.10,2023-08-07,gridion,SQK-LSK114-XL,FLO-MIN114,FAW11055,Guppy,NaN
28,IGVF_013,013_13A,ONT035,igvf013_13A-gc_lig-ss_qc_1,2023-09-12,5.707763,21.9,862.0,GF,True,2023-09-14,15.0,5.96,2023-09-14,gridion,SQK-LSK114-XL,FLO-MIN114,FAW12082,NaN,NaN
29,IGVF_013,013_13A,ONT036,igvf013_13A-gc_lig-ss_p2_2,2023-09-12,5.707763,21.9,862.0,GF,True,2023-09-14,15.0,5.96,2023-09-18,p2solo,SQK-LSK114-XL,FLO-PRO114M,PAS39875,NaN,Stopped: Device disconnected
30,IGVF_013,013_13A,ONT037,igvf013_13A-gc_lig-ss_p2_2_2,2023-09-12,5.707763,21.9,862.0,GF,True,2023-09-14,15.0,5.96,2023-09-18,p2solo,SQK-LSK114-XL,FLO-PRO114M,PAS39875,NaN,Stopped: Device disconnected
31,IGVF_013,013_13A,ONT038,igvf013_13A-gc_lig-ss_p2_2_3,2023-09-12,5.707763,21.9,862.0,GF,True,2023-09-14,15.0,5.96,2023-09-18,p2solo,SQK-LSK114-XL,FLO-PRO114M,PAS39875,NaN,NaN

In [64]:
import_splitseq_ont_samples(ont_sequencing)

In [65]:
%debug

ERROR:root:No traceback has been produced, nothing to debug.

# Load file information

In [66]:
def load_fastq_csv():
    fastqs = pandas.read_csv(
        "fastq_metadata.tsv", sep="\t",
        dtype={
            "sample_id": str,
            "read_id": str,
            "fragment": str,
            "sequencer_run": str,
            "lane": str,
        }).sort_values(["experiment", "subpool_name", "index_id", "lane", "read"])
    return fastqs

fastqs = load_fastq_csv()
fastqs.head()

,experiment,family,filename,md5sum,size,ctime,plate_id,subpool_name,fragment,compression,sequencer,sequencer_run,flowcell_id,nuclei,read,barcode,index_id,sample_id,lane,exome_capture
378,igvf_003,illumina,igvf_003/nextseq2/003_13A_R1.fastq.gz,57e977fdfe32850db83ee5f7addb7165,17707636592,2023-10-02,003,13A,NaN,gz,VH00582,6,AAC3V7HHV,13,R1,CAGATC,1,NaN,NaN,EX
377,igvf_003,illumina,igvf_003/nextseq2/003_13A_R2.fastq.gz,148c181e7d81e4aa15611fb2086d5971,10322410034,2023-10-02,003,13A,NaN,gz,VH00582,6,AAC3V7HHV,13,R2,CAGATC,1,NaN,NaN,EX
13,igvf_003,illumina,igvf_003/nextseq/003_67A_R1.fastq.gz,35350d53cf858267d294bce69e475c83,48483277280,2023-09-08,003,67A,NaN,gz,VH00582,1,AAATMGFHV,67,R1,ACTTGA,2,NaN,NaN,NaN
12,igvf_003,illumina,igvf_003/nextseq/003_67A_R2.fastq.gz,00c68ff0f9e0217d422c57e8948d4bb4,32327542019,2023-09-08,003,67A,NaN,gz,VH00582,1,AAATMGFHV,67,R2,ACTTGA,2,NaN,NaN,NaN
14,igvf_003,illumina,igvf_003/nextseq/003_67B_R1.fastq.gz,79db765143bb23e14c613c9e1339e9f7,44182320136,2023-09-08,003,67B,NaN,gz,VH00582,1,AAATMGFHV,67,R1,GATCAG,3,NaN,NaN,NaN

In [67]:
def fastq_metadata_row_to_subpool_name(row):
    if pandas.isnull(row.subpool_name):
        return None
    else:
        return "{}_{}".format(row.plate_id, row.subpool_name)

def get_subpool_from_fastq_row(row):
    plate_name = normalize_plate_name(row.experiment)
    subpool_name = fastq_metadata_row_to_subpool_name(row)

    query = {
        "plate__name": plate_name,
    }
    
    if pandas.notnull(subpool_name):
        query["name"] = subpool_name
    if pandas.notnull(row.index_id):
        query["index"] = str_or_none(row.index_id)
    
    # these are labeled as having X nuclei but actually have fewer nuclei. 
    # Not that you can tell that from the filename
    nuclei_dont_match = {"013_67N", "014_13H"}
    if pandas.notnull(row.nuclei) and subpool_name not in nuclei_dont_match:
        query["nuclei"] = int(row.nuclei)*1000
    if pandas.notnull(row.exome_capture):
        query["selection_type"] = row.exome_capture

    subpools = models.Subpool.objects.filter(**query)
    
    if len(subpools) == 0:
        print("Nothing found for {} {}".format(query, row.filename))
    elif len(subpools) > 1:
        print("Multiple hits for {}: {} {}".format(query, subpools, row.filename))
    else:
        return subpools[0]

from Bio.Seq import Seq
def check_fastq_barcode_is_equal(i7_sequence, i5_sequence, barcode):
    if pandas.isnull(i5_sequence):
        return i7_sequence == barcode
    
    sequences = barcode.split("+")
    if len(sequences) != 2:
        print("Warning: database says dual index, file says single index: {} {} {}".format(i7_sequence, i5_sequence, barcode))
        return False

    i7, i5 = sequences
    # barcodes in the fastq file are reverse complimented.
    i5 = Seq(i5).reverse_complement()
    return i7_sequence == i7 and i5_sequence == i5
    
assert check_fastq_barcode_is_equal("ACTTGA", None, "ACTTGA")
assert not check_fastq_barcode_is_equal("ACTTGA", None, "CTTGTA")
assert check_fastq_barcode_is_equal("GTGAAACT", "AGTCTGTA", "GTGAAACT+TACAGACT")
assert not check_fastq_barcode_is_equal("GTGAAACT", "AGTCTGTA", "ACTTGATC+TTTGGGTG")
assert not check_fastq_barcode_is_equal("GTGAAACT", "AGTCTGTA", "CTTGTA")
print("Finish check_fastq_barcode_is_equal test assertions")

def test_subpool_lookup(fastqs):
    for i, row in fastqs.iterrows():
        subpool = get_subpool_from_fastq_row(row)
        if subpool is None:
            continue
        barcodes = subpool.barcode.filter(barcode_type=None)
        if barcodes.count() != 1:
            print("Barcode count wrong {}".format(barcode))

        barcode = barcodes[0]
        if not check_fastq_barcode_is_equal(barcode.i7_sequence, barcode.i5_sequence, row["barcode"]):
            print(f"Barcode mismatch {subpool.plate_name()} {subpool.index} {barcode.i7_sequence} {barcode.i5_sequence} {row.barcode} {row.filename}")

test_subpool_lookup(fastqs)

Warning: database says dual index, file says single index: GTGAAACT AGTCTGTA CTTGTA
Finish check_fastq_barcode_is_equal test assertions
Barcode mismatch IGVF_003 1 CAGATC None nan igvf_003/nanopore/igvf003_8A_lig-ss_11.fastq.gz
Barcode mismatch IGVF_003 1 CAGATC None nan igvf_003/nanopore/igvf003_8A_lig-ss_4.fastq.gz
Barcode mismatch IGVF_003 1 CAGATC None nan igvf_003/nanopore/igvf003_8A_lig-ss_7.fastq.gz
Barcode mismatch IGVF_003 1 CAGATC None nan igvf_003/nanopore/igvf003_8A_lig-ss_6.fastq.gz
Barcode mismatch IGVF_003 1 CAGATC None nan igvf_003/nanopore/igvf003_8A_lig-ss_8.fastq.gz
Barcode mismatch IGVF_003 1 CAGATC None nan igvf_003/nanopore/igvf003_8A_lig-ss_5.fastq.gz
Barcode mismatch IGVF_003 1 CAGATC None nan igvf_003/nanopore/igvf003_8A_lig-ss_1.fastq.gz
Barcode mismatch IGVF_003 1 CAGATC None nan igvf_003/nanopore/igvf003_8A_lig-ss_2.fastq.gz
Barcode mismatch IGVF_003 1 CAGATC None nan igvf_003/nanopore/igvf003_8A_lig-ss_10.fastq.gz
Barcode mismatch IGVF_003 1 CAGATC None nan igvf_003/nanopore/igvf003_8A_lig-ss_9.fastq.gz
Barcode mismatch IGVF_003 1 CAGATC None nan igvf_003/nanopore/igvf003_8A_lig-ss_3.fastq.gz

In [68]:
[(x.index, x.nuclei, x.selection_type) for x in models.Subpool.objects.filter(plate__name="IGVF_013")]

[('UDI01', 13000, 'EX'),
 ('UDI02', 67000, 'NO'),
 ('UDI03', 67000, 'NO'),
 ('UDI04', 67000, 'NO'),
 ('UDI05', 67000, 'NO'),
 ('UDI06', 67000, 'NO'),
 ('UDI07', 67000, 'NO'),
 ('UDI08', 67000, 'NO'),
 ('UDI09', 67000, 'NO'),
 ('UDI10', 67000, 'NO'),
 ('UDI11', 67000, 'NO'),
 ('UDI12', 67000, 'NO'),
 ('UDI13', 67000, 'NO'),
 ('UDI14', 67000, 'NO'),
 ('UDI15', 48256, 'NO')]

Load information about previously submitted records

In [69]:
submitted_sequence_file = {}

for accession_prefix in submitted_sheets:
    for i, row in submitted_sheets[accession_prefix]["sequence_file"].iterrows():
        if not pandas.isnull(row["accession"]):
            if accession_prefix == "igvftst":
                see_also_template = "https://api.sandbox.igvf.org/sequence-files/{}/"
            elif accession_prefix == "igvf":
                see_also_template = "https://api.data.igvf.org/sequence-files/{}/"
            
            if pandas.notnull(row["accession"]):
                submitted_sequence_file.setdefault(row["submitted_file_name"], []).append({
                    "accession_prefix": accession_prefix,
                    "name": row["accession"],
                    "uuid": row["uuid"],
                    "see_also": see_also_template.format(row["accession"]),
                })
        
print("loaded {} submitted sequence_file records".format(len(submitted_sequence_file)))

loaded 2154 submitted sequence_file records

In [70]:
submitted_sheets.keys()

dict_keys(['igvftst', 'igvf'])

In [71]:
def built_in_cache(a, b, cache={}):
    cache.setdefault(a, b)
    print(cache)
    
built_in_cache('a', 1)
built_in_cache('b', 3)
built_in_cache('c', 4)
built_in_cache('a', 2)

{'a': 1}
{'a': 1, 'b': 3}
{'a': 1, 'b': 3, 'c': 4}
{'a': 1, 'b': 3, 'c': 4}

In [72]:
sequencing_experiments = {}
sequencing_subpools = {}

In [73]:
def get_or_create_sequencing_run(name, run_date, platform, plate, flowcell_id, accessions=None):
    if name in sequencing_experiments:
        return sequencing_experiments[name]
    
    try:
        sequencing_run = models.SequencingRun.objects.get(name=name)
    except models.SequencingRun.DoesNotExist:
        sequencing_run = models.SequencingRun(
            name=name,
            run_date=run_date,
            platform=platform,
            plate=plate,
            flowcell_id=flowcell_id,
            stranded=models.StrandedEnum.REVERSE,
        )
        sequencing_run.save()
        if accessions is not None:
            sequencing_run.accession.set(accessions)
            sequencing_run.save
        
    sequencing_experiments[name] = sequencing_run
    return sequencing_run

def get_or_create_library_in_run(subpool, sequencing_run, status, raw_reads=None, measurement_set=None):
    try:
        library_in_run = models.LibraryInRun.objects.get(subpool=subpool, sequencing_run=sequencing_run)
    except models.LibraryInRun.DoesNotExist:
        library_in_run = models.LibraryInRun(
            subpool=subpool, 
            sequencing_run=sequencing_run,
            raw_reads=None,
            status=status,
            measurement_set=measurement_set,
        )
        library_in_run.save()
        
    sequencing_subpools[name] = library_in_run
    return library_in_run


def lane_or_none(value):
    if pandas.isnull(value):
        return None
    elif isinstance(value, float):
        return int(value)
    elif value.startswith("L"):
        return int(value[1:])
    else:
        return int(value)

def load_fastqs(submittable_subpools):
    fastqs = load_fastq_csv()
    measurement_sets = load_submitted_measurement_sets()

    for i, row in fastqs.iterrows():
        #plate_name = normalize_plate_name(row.experiment)
        #subpool_name = "{}_{}".format(row.plate_id, row.subpool_name)
        #index_id = int(row.index_id)
        fastq_relative = Path(row.filename)
        sequencing_run_name = str(Path(fastq_relative.parts[0])/fastq_relative.parts[1])
        sequencer = row.get("sequencer")
        run_date = row["ctime"]
        md5sum = row["md5sum"]

        #if row["read_id"] in ('I1',):
        #    continue

        subpool = get_subpool_from_fastq_row(row)

        if subpool is None:
            print("Unable to import {row.filename}")
            continue

        current_plate = subpool.plate

        platform = {
            "A00850": models.Platform.objects.get(display_name="Novaseq 6000"),
            "VH00582": models.Platform.objects.get(display_name="Nextseq 2000"),
            "minion": models.Platform.objects.get(name="minion"),
            "promethion": models.Platform.objects.get(name="promethion"),
        }[sequencer]

        subpool_status = normalize_subpool_submission_status(submittable_subpools.get(subpool.name))

        sequencing_run = get_or_create_sequencing_run(sequencing_run_name, run_date, platform, current_plate, row["flowcell_id"], accessions=None)
        library_in_run = get_or_create_library_in_run(subpool=subpool, sequencing_run=sequencing_run, status=subpool_status)

        for accession_prefix in ["igvftst", "igvf"]:
            file_set_name = None
            submitted_md5s = submitted_sheets[accession_prefix]["sequence_file"].set_index("md5sum")
            if row.md5sum in submitted_md5s.index:
                file_set_alias = submitted_md5s.loc[row.md5sum]["file_set"]
                file_set_name = file_set_alias.split(":")[1]

        if file_set_name is None:
            pass
        elif file_set_name not in measurement_sets:
            # skip if there hasn't been a submitted measurement_set
            pass
        elif library_in_run.measurement_set is None:
            library_in_run.measurement_set = measurement_sets[file_set_name]
            library_in_run.save()
            print(f"updating {library_in_run} measurement set to {measurement_sets[file_set_name]}")
        else:
            assert library_in_run.measurement_set.name == file_set_name, f"SubpoolInRun measurement_set mismatch {library_in_run.measurement_set.name} {file_set_name}"


        subpool_file = models.SequencingFile(
            sequencing_run=sequencing_run,
            library_in_run=library_in_run,
            md5sum=md5sum,
            filename=str(fastq_relative),
        )
        if not pandas.isnull(row["lane"]):
            subpool_file.lane = lane_or_none(row["lane"])
        if not pandas.isnull(row["read"]):
            subpool_file.read = row["read"]
        subpool_file.save()

        for accession_info in submitted_sequence_file.get(str(fastq_relative), []):
            if pandas.notnull(accession_info["name"]):
                accession = models.Accession(
                    accession_prefix=accession_info["accession_prefix"],
                    name=accession_info["name"],
                    uuid=accession_info["uuid"],
                    see_also=accession_info["see_also"],
                )
                accession.save()                
                subpool_file.accession.add(accession)
                subpool_file.save()

load_fastqs(submittable_subpools)

print("total plates", models.SplitSeqPlate.objects.count())
print("total sequencing runs", models.SequencingRun.objects.count())
print("total subpools", models.Subpool.objects.count())
print("total Libraries in run", models.LibraryInRun.objects.count())
print("total sequencing files", models.SequencingFile.objects.count())

loaded 175 measurement_sets
updating 003_13A igvf_003/nextseq2 measurement set to 003_13A_illumina
updating 003_67A igvf_003/nextseq measurement set to 003_67A_illumina
updating 003_67B igvf_003/nextseq measurement set to 003_67B_illumina
updating 003_67I igvf_003/nova1 measurement set to 003_67I_illumina
updating 003_67I igvf_003/nova2 measurement set to 003_67I_illumina
updating 003_67J igvf_003/nova1 measurement set to 003_67J_illumina
updating 003_67J igvf_003/nova2 measurement set to 003_67J_illumina
updating 003_67K igvf_003/nova1 measurement set to 003_67K_illumina
updating 003_67K igvf_003/nova2 measurement set to 003_67K_illumina
updating 003_67L igvf_003/nova1 measurement set to 003_67L_illumina
updating 003_67L igvf_003/nova2 measurement set to 003_67L_illumina
updating 003_67M igvf_003/nova1 measurement set to 003_67M_illumina
updating 003_67M igvf_003/nova2 measurement set to 003_67M_illumina
updating 003_67N igvf_003/nova1 measurement set to 003_67N_illumina
updating 003_67N igvf_003/nova2 measurement set to 003_67N_illumina
updating 003_67O igvf_003/nova1 measurement set to 003_67O_illumina
updating 003_67O igvf_003/nova2 measurement set to 003_67O_illumina
updating 003_67A igvf_003/nova1 measurement set to 003_67A_illumina
updating 003_67A igvf_003/nova2 measurement set to 003_67A_illumina
updating 003_67B igvf_003/nova1 measurement set to 003_67B_illumina
updating 003_67B igvf_003/nova2 measurement set to 003_67B_illumina
updating 003_67C igvf_003/nova1 measurement set to 003_67C_illumina
updating 003_67C igvf_003/nova2 measurement set to 003_67C_illumina
updating 003_67D igvf_003/nova1 measurement set to 003_67D_illumina
updating 003_67D igvf_003/nova2 measurement set to 003_67D_illumina
updating 003_67E igvf_003/nova1 measurement set to 003_67E_illumina
updating 003_67E igvf_003/nova2 measurement set to 003_67E_illumina
updating 003_67F igvf_003/nova1 measurement set to 003_67F_illumina
updating 003_67F igvf_003/nova2 measurement set to 003_67F_illumina
updating 003_67G igvf_003/nova1 measurement set to 003_67G_illumina
updating 003_67G igvf_003/nova2 measurement set to 003_67G_illumina
updating 003_67H igvf_003/nova1 measurement set to 003_67H_illumina
updating 003_67H igvf_003/nova2 measurement set to 003_67H_illumina
updating 004_13A igvf_004/nextseq2 measurement set to 004_13A_illumina
updating 004_67A igvf_004/nextseq measurement set to 004_67A_illumina
updating 004_67B igvf_004/nextseq measurement set to 004_67B_illumina
updating 004_67I igvf_004/nova1 measurement set to 004_67I_illumina
updating 004_67I igvf_004/nova2 measurement set to 004_67I_illumina
updating 004_67J igvf_004/nova1 measurement set to 004_67J_illumina
updating 004_67J igvf_004/nova2 measurement set to 004_67J_illumina
updating 004_67K igvf_004/nova1 measurement set to 004_67K_illumina
updating 004_67K igvf_004/nova2 measurement set to 004_67K_illumina
updating 004_67L igvf_004/nova1 measurement set to 004_67L_illumina
updating 004_67L igvf_004/nova2 measurement set to 004_67L_illumina
updating 004_67M igvf_004/nova1 measurement set to 004_67M_illumina
updating 004_67M igvf_004/nova2 measurement set to 004_67M_illumina
updating 004_67N igvf_004/nova1 measurement set to 004_67N_illumina
updating 004_67N igvf_004/nova2 measurement set to 004_67N_illumina
updating 004_67O igvf_004/nova1 measurement set to 004_67O_illumina
updating 004_67O igvf_004/nova2 measurement set to 004_67O_illumina
updating 004_67A igvf_004/nova1 measurement set to 004_67A_illumina
updating 004_67A igvf_004/nova2 measurement set to 004_67A_illumina
updating 004_67B igvf_004/nova1 measurement set to 004_67B_illumina
updating 004_67B igvf_004/nova2 measurement set to 004_67B_illumina
updating 004_67C igvf_004/nova1 measurement set to 004_67C_illumina
updating 004_67C igvf_004/nova2 measurement set to 004_67C_illumina
updating 004_67D igvf_004/nova1 measurement set to 004_67D_illumina
updating 004_67D igvf_004/nova2 measurement set to 004_67D_illumina
updating 004_67E igvf_004/nova1 measurement set to 004_67E_illumina
updating 004_67E igvf_004/nova2 measurement set to 004_67E_illumina
updating 004_67F igvf_004/nova1 measurement set to 004_67F_illumina
updating 004_67F igvf_004/nova2 measurement set to 004_67F_illumina
updating 004_67G igvf_004/nova1 measurement set to 004_67G_illumina
updating 004_67G igvf_004/nova2 measurement set to 004_67G_illumina
updating 004_67H igvf_004/nova1 measurement set to 004_67H_illumina
updating 004_67H igvf_004/nova2 measurement set to 004_67H_illumina
updating 005_13A igvf_005/nextseq2 measurement set to 005_13A_illumina
updating 005_67I igvf_005/nova1 measurement set to 005_67I_illumina
updating 005_67I igvf_005/nova2 measurement set to 005_67I_illumina
updating 005_67J igvf_005/nova1 measurement set to 005_67J_illumina
updating 005_67J igvf_005/nova2 measurement set to 005_67J_illumina
updating 005_67K igvf_005/nova1 measurement set to 005_67K_illumina
updating 005_67K igvf_005/nova2 measurement set to 005_67K_illumina
updating 005_67L igvf_005/nova1 measurement set to 005_67L_illumina
updating 005_67L igvf_005/nova2 measurement set to 005_67L_illumina
updating 005_67M igvf_005/nova1 measurement set to 005_67M_illumina
updating 005_67M igvf_005/nova2 measurement set to 005_67M_illumina
updating 005_67N igvf_005/nova1 measurement set to 005_67N_illumina
updating 005_67N igvf_005/nova2 measurement set to 005_67N_illumina
updating 005_67O igvf_005/nova1 measurement set to 005_67O_illumina
updating 005_67O igvf_005/nova2 measurement set to 005_67O_illumina
updating 005_67A igvf_005/nova1 measurement set to 005_67A_illumina
updating 005_67A igvf_005/nova2 measurement set to 005_67A_illumina
updating 005_67B igvf_005/nova1 measurement set to 005_67B_illumina
updating 005_67B igvf_005/nova2 measurement set to 005_67B_illumina
updating 005_67C igvf_005/nova1 measurement set to 005_67C_illumina
updating 005_67C igvf_005/nova2 measurement set to 005_67C_illumina
updating 005_67D igvf_005/nova1 measurement set to 005_67D_illumina
updating 005_67D igvf_005/nova2 measurement set to 005_67D_illumina
updating 005_67E igvf_005/nova1 measurement set to 005_67E_illumina
updating 005_67E igvf_005/nova2 measurement set to 005_67E_illumina
updating 005_67F igvf_005/nova1 measurement set to 005_67F_illumina
updating 005_67F igvf_005/nova2 measurement set to 005_67F_illumina
updating 005_67G igvf_005/nova1 measurement set to 005_67G_illumina
updating 005_67G igvf_005/nova2 measurement set to 005_67G_illumina
updating 005_67H igvf_005/nova1 measurement set to 005_67H_illumina
updating 005_67H igvf_005/nova2 measurement set to 005_67H_illumina
updating 007_13A igvf_007/nextseq2 measurement set to 007_13A_illumina
updating 007_67I igvf_007/nova1 measurement set to 007_67I_illumina
updating 007_67I igvf_007/nova2 measurement set to 007_67I_illumina
updating 007_67J igvf_007/nova1 measurement set to 007_67J_illumina
updating 007_67J igvf_007/nova2 measurement set to 007_67J_illumina
updating 007_67K igvf_007/nova1 measurement set to 007_67K_illumina
updating 007_67K igvf_007/nova2 measurement set to 007_67K_illumina
updating 007_67L igvf_007/nova1 measurement set to 007_67L_illumina
updating 007_67L igvf_007/nova2 measurement set to 007_67L_illumina
updating 007_67M igvf_007/nova1 measurement set to 007_67M_illumina
updating 007_67M igvf_007/nova2 measurement set to 007_67M_illumina
updating 007_67N igvf_007/nova1 measurement set to 007_67N_illumina
updating 007_67N igvf_007/nova2 measurement set to 007_67N_illumina
updating 007_67O igvf_007/nova1 measurement set to 007_67O_illumina
updating 007_67O igvf_007/nova2 measurement set to 007_67O_illumina
updating 007_67A igvf_007/nova1 measurement set to 007_67A_illumina
updating 007_67A igvf_007/nova2 measurement set to 007_67A_illumina
updating 007_67B igvf_007/nova1 measurement set to 007_67B_illumina
updating 007_67B igvf_007/nova2 measurement set to 007_67B_illumina
updating 007_67C igvf_007/nova1 measurement set to 007_67C_illumina
updating 007_67C igvf_007/nova2 measurement set to 007_67C_illumina
updating 007_67D igvf_007/nova1 measurement set to 007_67D_illumina

updating 007_67D igvf_007/nova2 measurement set to 007_67D_illumina
updating 007_67E igvf_007/nova1 measurement set to 007_67E_illumina
updating 007_67E igvf_007/nova2 measurement set to 007_67E_illumina
updating 007_67F igvf_007/nova1 measurement set to 007_67F_illumina
updating 007_67F igvf_007/nova2 measurement set to 007_67F_illumina
updating 007_67G igvf_007/nova1 measurement set to 007_67G_illumina
updating 007_67G igvf_007/nova2 measurement set to 007_67G_illumina
updating 007_67H igvf_007/nova1 measurement set to 007_67H_illumina
updating 007_67H igvf_007/nova2 measurement set to 007_67H_illumina
updating 008_67C igvf_008/nextseq measurement set to 008_67C_illumina
updating 008_67G igvf_008/nextseq measurement set to 008_67G_illumina
updating 008_67I igvf_008/nova1 measurement set to 008_67I_illumina
updating 008_67A igvf_008/nova1 measurement set to 008_67A_illumina
updating 008_67B igvf_008/nova1 measurement set to 008_67B_illumina
updating 008_67C igvf_008/nova1 measurement set to 008_67C_illumina
updating 008_67D igvf_008/nova1 measurement set to 008_67D_illumina
updating 008_67E igvf_008/nova1 measurement set to 008_67E_illumina
updating 008_67F igvf_008/nova1 measurement set to 008_67F_illumina
updating 008_67G igvf_008/nova1 measurement set to 008_67G_illumina
updating 008_67H igvf_008/nova1 measurement set to 008_67H_illumina
updating 008B_13A igvf_008b/nextseq2 measurement set to 008B_13A_illumina
updating 008B_67G igvf_008b/nextseq measurement set to 008B_67G_illumina
updating 008B_67I igvf_008b/nextseq measurement set to 008B_67I_illumina
updating 008B_67I igvf_008b/nova1 measurement set to 008B_67I_illumina
updating 008B_67J igvf_008b/nova1 measurement set to 008B_67J_illumina
updating 008B_67A igvf_008b/nova1 measurement set to 008B_67A_illumina
updating 008B_67B igvf_008b/nova1 measurement set to 008B_67B_illumina
updating 008B_67C igvf_008b/nova1 measurement set to 008B_67C_illumina
updating 008B_67D igvf_008b/nova1 measurement set to 008B_67D_illumina
updating 008B_67E igvf_008b/nova1 measurement set to 008B_67E_illumina
updating 008B_67F igvf_008b/nova1 measurement set to 008B_67F_illumina
updating 008B_67G igvf_008b/nova1 measurement set to 008B_67G_illumina
updating 008B_67H igvf_008b/nova1 measurement set to 008B_67H_illumina
updating 009_13A igvf_009/nextseq2 measurement set to 009_13A_illumina
updating 009_67A igvf_009/nextseq measurement set to 009_67A_illumina
updating 009_67O igvf_009/nextseq measurement set to 009_67O_illumina
updating 009_67I igvf_009/nova1 measurement set to 009_67I_illumina
updating 009_67I igvf_009/nova2 measurement set to 009_67I_illumina
updating 009_67J igvf_009/nova1 measurement set to 009_67J_illumina
updating 009_67J igvf_009/nova2 measurement set to 009_67J_illumina
updating 009_67K igvf_009/nova1 measurement set to 009_67K_illumina
updating 009_67K igvf_009/nova2 measurement set to 009_67K_illumina
updating 009_67L igvf_009/nova1 measurement set to 009_67L_illumina
updating 009_67L igvf_009/nova2 measurement set to 009_67L_illumina
updating 009_67M igvf_009/nova1 measurement set to 009_67M_illumina
updating 009_67M igvf_009/nova2 measurement set to 009_67M_illumina
updating 009_67N igvf_009/nova1 measurement set to 009_67N_illumina
updating 009_67N igvf_009/nova2 measurement set to 009_67N_illumina
updating 009_67O igvf_009/nova1 measurement set to 009_67O_illumina
updating 009_67O igvf_009/nova2 measurement set to 009_67O_illumina
updating 009_67A igvf_009/nova1 measurement set to 009_67A_illumina
updating 009_67A igvf_009/nova2 measurement set to 009_67A_illumina
updating 009_67B igvf_009/nova1 measurement set to 009_67B_illumina
updating 009_67B igvf_009/nova2 measurement set to 009_67B_illumina
updating 009_67C igvf_009/nova1 measurement set to 009_67C_illumina
updating 009_67C igvf_009/nova2 measurement set to 009_67C_illumina
updating 009_67D igvf_009/nova1 measurement set to 009_67D_illumina
updating 009_67D igvf_009/nova2 measurement set to 009_67D_illumina
updating 009_67E igvf_009/nova1 measurement set to 009_67E_illumina
updating 009_67E igvf_009/nova2 measurement set to 009_67E_illumina
updating 009_67F igvf_009/nova1 measurement set to 009_67F_illumina
updating 009_67F igvf_009/nova2 measurement set to 009_67F_illumina
updating 009_67G igvf_009/nova1 measurement set to 009_67G_illumina
updating 009_67G igvf_009/nova2 measurement set to 009_67G_illumina
updating 009_67H igvf_009/nova1 measurement set to 009_67H_illumina
updating 009_67H igvf_009/nova2 measurement set to 009_67H_illumina
updating 010_13A igvf_010/nextseq2 measurement set to 010_13A_illumina
updating 010_67D igvf_010/nextseq measurement set to 010_67D_illumina
updating 010_67O igvf_010/nextseq measurement set to 010_67O_illumina
updating 010_67I igvf_010/nova1 measurement set to 010_67I_illumina
updating 010_67I igvf_010/nova2 measurement set to 010_67I_illumina
updating 010_67J igvf_010/nova1 measurement set to 010_67J_illumina
updating 010_67J igvf_010/nova2 measurement set to 010_67J_illumina
updating 010_67K igvf_010/nova1 measurement set to 010_67K_illumina
updating 010_67K igvf_010/nova2 measurement set to 010_67K_illumina
updating 010_67L igvf_010/nova1 measurement set to 010_67L_illumina
updating 010_67L igvf_010/nova2 measurement set to 010_67L_illumina
updating 010_67M igvf_010/nova1 measurement set to 010_67M_illumina
updating 010_67M igvf_010/nova2 measurement set to 010_67M_illumina
updating 010_67N igvf_010/nova1 measurement set to 010_67N_illumina
updating 010_67N igvf_010/nova2 measurement set to 010_67N_illumina
updating 010_67O igvf_010/nova1 measurement set to 010_67O_illumina
updating 010_67O igvf_010/nova2 measurement set to 010_67O_illumina
updating 010_67A igvf_010/nova1 measurement set to 010_67A_illumina
updating 010_67A igvf_010/nova2 measurement set to 010_67A_illumina
updating 010_67B igvf_010/nova1 measurement set to 010_67B_illumina
updating 010_67B igvf_010/nova2 measurement set to 010_67B_illumina
updating 010_67C igvf_010/nova1 measurement set to 010_67C_illumina
updating 010_67C igvf_010/nova2 measurement set to 010_67C_illumina
updating 010_67D igvf_010/nova1 measurement set to 010_67D_illumina
updating 010_67D igvf_010/nova2 measurement set to 010_67D_illumina
updating 010_67E igvf_010/nova1 measurement set to 010_67E_illumina
updating 010_67E igvf_010/nova2 measurement set to 010_67E_illumina
updating 010_67F igvf_010/nova1 measurement set to 010_67F_illumina
updating 010_67F igvf_010/nova2 measurement set to 010_67F_illumina
updating 010_67G igvf_010/nova1 measurement set to 010_67G_illumina
updating 010_67G igvf_010/nova2 measurement set to 010_67G_illumina
updating 010_67H igvf_010/nova1 measurement set to 010_67H_illumina
updating 010_67H igvf_010/nova2 measurement set to 010_67H_illumina
updating 011_13A igvf_011/nextseq2 measurement set to 011_13A_illumina
updating 011_67M igvf_011/nextseq measurement set to 011_67M_illumina
updating 011_67O igvf_011/nextseq measurement set to 011_67O_illumina
updating 011_67I igvf_011/nova1 measurement set to 011_67I_illumina
updating 011_67I igvf_011/nova2 measurement set to 011_67I_illumina
updating 011_67J igvf_011/nova1 measurement set to 011_67J_illumina
updating 011_67J igvf_011/nova2 measurement set to 011_67J_illumina
updating 011_67K igvf_011/nova1 measurement set to 011_67K_illumina
updating 011_67K igvf_011/nova2 measurement set to 011_67K_illumina
updating 011_67L igvf_011/nova1 measurement set to 011_67L_illumina
updating 011_67L igvf_011/nova2 measurement set to 011_67L_illumina
updating 011_67M igvf_011/nova1 measurement set to 011_67M_illumina
updating 011_67M igvf_011/nova2 measurement set to 011_67M_illumina
updating 011_67N igvf_011/nova1 measurement set to 011_67N_illumina
updating 011_67N igvf_011/nova2 measurement set to 011_67N_illumina
updating 011_67O igvf_011/nova1 measurement set to 011_67O_illumina
updating 011_67O igvf_011/nova2 measurement set to 011_67O_illumina
updating 011_67A igvf_011/nova1 measurement set to 011_67A_illumina
updating 011_67A igvf_011/nova2 measurement set to 011_67A_illumina
updating 011_67B igvf_011/nova1 measurement set to 011_67B_illumina

updating 011_67B igvf_011/nova2 measurement set to 011_67B_illumina
updating 011_67C igvf_011/nova1 measurement set to 011_67C_illumina
updating 011_67C igvf_011/nova2 measurement set to 011_67C_illumina
updating 011_67D igvf_011/nova1 measurement set to 011_67D_illumina
updating 011_67D igvf_011/nova2 measurement set to 011_67D_illumina
updating 011_67E igvf_011/nova1 measurement set to 011_67E_illumina
updating 011_67E igvf_011/nova2 measurement set to 011_67E_illumina
updating 011_67F igvf_011/nova1 measurement set to 011_67F_illumina
updating 011_67F igvf_011/nova2 measurement set to 011_67F_illumina
updating 011_67G igvf_011/nova1 measurement set to 011_67G_illumina
updating 011_67G igvf_011/nova2 measurement set to 011_67G_illumina
updating 011_67H igvf_011/nova1 measurement set to 011_67H_illumina
updating 011_67H igvf_011/nova2 measurement set to 011_67H_illumina
updating 012_13A igvf_012/nextseq measurement set to 012_13A_illumina
updating 012_13B igvf_012/nextseq measurement set to 012_13B_illumina
updating 012_13C igvf_012/nextseq measurement set to 012_13C_illumina
updating 012_13D igvf_012/nextseq measurement set to 012_13D_illumina
updating 012_13E igvf_012/nextseq measurement set to 012_13E_illumina
updating 012_13F igvf_012/nextseq measurement set to 012_13F_illumina
updating 012_13G igvf_012/nextseq measurement set to 012_13G_illumina
updating 012_13H igvf_012/nextseq measurement set to 012_13H_illumina
updating 013_13A igvf_013/nextseq measurement set to 013_13A_illumina
updating 013_67A igvf_013/nova1 measurement set to 013_67A_illumina
updating 013_67B igvf_013/nova1 measurement set to 013_67B_illumina
updating 013_67C igvf_013/nova1 measurement set to 013_67C_illumina
updating 013_67D igvf_013/nova1 measurement set to 013_67D_illumina
updating 013_67E igvf_013/nova1 measurement set to 013_67E_illumina
updating 013_67F igvf_013/nova1 measurement set to 013_67F_illumina
updating 013_67G igvf_013/nova1 measurement set to 013_67G_illumina
updating 013_67H igvf_013/nova1 measurement set to 013_67H_illumina
updating 013_67H igvf_013/nextseq measurement set to 013_67H_illumina
updating 013_67I igvf_013/nova1 measurement set to 013_67I_illumina
updating 013_67J igvf_013/nova1 measurement set to 013_67J_illumina
updating 013_67J igvf_013/nextseq measurement set to 013_67J_illumina
updating 013_67K igvf_013/nova1 measurement set to 013_67K_illumina
updating 013_67L igvf_013/nova1 measurement set to 013_67L_illumina
updating 013_67M igvf_013/nova1 measurement set to 013_67M_illumina
updating 013_67N igvf_013/nova1 measurement set to 013_67N_illumina
updating 014_13A igvf_014/nextseq measurement set to 014_13A_illumina
updating 014_13B igvf_014/nextseq measurement set to 014_13B_illumina
updating 014_13C igvf_014/nextseq measurement set to 014_13C_illumina
updating 014_13D igvf_014/nextseq measurement set to 014_13D_illumina
updating 014_13E igvf_014/nextseq measurement set to 014_13E_illumina
updating 014_13F igvf_014/nextseq measurement set to 014_13F_illumina
updating 014_13G igvf_014/nextseq measurement set to 014_13G_illumina
updating 014_13H igvf_014/nextseq measurement set to 014_13H_illumina
updating B01_13A igvf_b01/next2 measurement set to B01_13A_illumina
updating B01_13A igvf_b01/next1 measurement set to B01_13A_illumina
updating B01_13B igvf_b01/next2 measurement set to B01_13B_illumina
updating B01_13B igvf_b01/next1 measurement set to B01_13B_illumina
updating B01_13C igvf_b01/next2 measurement set to B01_13C_illumina
updating B01_13C igvf_b01/next1 measurement set to B01_13C_illumina
updating B01_13D igvf_b01/next2 measurement set to B01_13D_illumina
updating B01_13D igvf_b01/next1 measurement set to B01_13D_illumina
updating B01_13E igvf_b01/next2 measurement set to B01_13E_illumina
updating B01_13E igvf_b01/next1 measurement set to B01_13E_illumina
updating B01_13F igvf_b01/next2 measurement set to B01_13F_illumina
updating B01_13F igvf_b01/next1 measurement set to B01_13F_illumina
updating B01_13G igvf_b01/next2 measurement set to B01_13G_illumina
updating B01_13G igvf_b01/next1 measurement set to B01_13G_illumina
updating B01_13H igvf_b01/next2 measurement set to B01_13H_illumina
updating B01_13H igvf_b01/next1 measurement set to B01_13H_illumina
total plates 22
total sequencing runs 70
total subpools 445
total Libraries in run 336
total sequencing files 3119

In [74]:
for q in models.Subpool.objects.filter(plate__name="IGVF_014", index="UDI24"):
    print(q.name, q.index, q.nuclei, q.selection_type)

014_13H UDI24 10400 NO

In [75]:
[(x.name, x.index, x.selection_type) for x in models.Subpool.objects.filter(plate__name="IGVF_013")]

[('013_13A', 'UDI01', 'EX'),
 ('013_67A', 'UDI02', 'NO'),
 ('013_67B', 'UDI03', 'NO'),
 ('013_67C', 'UDI04', 'NO'),
 ('013_67D', 'UDI05', 'NO'),
 ('013_67E', 'UDI06', 'NO'),
 ('013_67F', 'UDI07', 'NO'),
 ('013_67G', 'UDI08', 'NO'),
 ('013_67H', 'UDI09', 'NO'),
 ('013_67I', 'UDI10', 'NO'),
 ('013_67J', 'UDI11', 'NO'),
 ('013_67K', 'UDI12', 'NO'),
 ('013_67L', 'UDI13', 'NO'),
 ('013_67M', 'UDI14', 'NO'),
 ('013_67N', 'UDI15', 'NO')]

In [76]:
def print_subpool_submission_status(fastqs):
    for i, row in fastqs.iterrows():
        plate_name = normalize_plate_name(row.experiment)
        index_id = row.index_id
        fastq_relative = Path(row.filename)
        sequencing_run_name = str(Path(fastq_relative.parts[0])/fastq_relative.parts[1])
        sequencer = row.get("sequencer")
        run_date = row["ctime"]
        md5sum = row["md5sum"]

        #if row["read_id"] in ('I1',):
        #    continue

        subpool = get_subpool_from_fastq_row(row)
        current_plate = subpool.plate

        platform = {
            "A00850": models.Platform.objects.get(display_name="Novaseq 6000"),
            "VH00582": models.Platform.objects.get(display_name="Nextseq 2000"),
            "minion": models.Platform.objects.get(name="minion"),
            "promethion": models.Platform.objects.get(name="promethion"),
        }[sequencer]

        subpool_status = {
            "Yes": models.RunStatus.PASS,
            "No": models.RunStatus.FAILED,
            None: models.RunStatus.FAILED,
        }[submittable_subpools.get(subpool.name)]

        #sequencing_run = get_or_create_sequencing_run(sequencing_run_name, run_date, platform, current_plate, accessions=None)
        #subpool_run = get_or_create_subpool_in_run(subpool=subpool, sequencing_run=sequencing_run, status=subpool_status)
        print(row.filename, row.index_id, sequencing_run_name, run_date, subpool, subpool_status)

#print_subpool_submission_status(fastqs)

In [77]:
md5counts = Counter(fastqs["md5sum"])
dupmd5s = set()
for md5sum in md5counts:
    if md5counts[md5sum] > 1:
        dupmd5s.add(md5sum)
        
dupfiles = fastqs[fastqs["md5sum"].isin(dupmd5s)].sort_values(["experiment", "md5sum", "filename"])
print(dupfiles.shape)
dupfiles

(0, 20)

Empty DataFrame
Columns: [experiment, family, filename, md5sum, size, ctime, plate_id, subpool_name, fragment, compression, sequencer, sequencer_run, flowcell_id, nuclei, read, barcode, index_id, sample_id, lane, exome_capture]
Index: []

In [78]:
print(dupfiles.to_csv(index=False))

experiment,family,filename,md5sum,size,ctime,plate_id,subpool_name,fragment,compression,sequencer,sequencer_run,flowcell_id,nuclei,read,barcode,index_id,sample_id,lane,exome_capture

In [79]:
models.SexEnum.choices

[('M', 'male'), ('F', 'female'), ('U', 'unknown'), ('O', 'other')]

In [80]:
# In case of interrupted upload

if 0:
    EC = str(Path("~/proj/encoded_client").expanduser())
    if EC not in sys.path:
        sys.path.append(EC)

    from encoded_client.encoded import ENCODED

    server = ENCODED("api.data.igvf.org")

    submitted_tissues = load_submitted_tissues()
    for tissue_id in submitted_tissues:
        for record in submitted_tissues[tissue_id]:
            if pandas.isnull(record["uuid"] ):
                tissue = server.get_json(record["see_also"])
                print("{}\t{}".format(record["name"], tissue["uuid"]))

In [83]:
models.SequencingFile.objects.get(md5sum="2a5a07155767a2f541cfb20e7d0636e0")

remember to flip the assert back on?

In [84]:
s = models.Subpool.objects.first()
print(s.protocols.all())
print(s.plate_name())

<QuerySet [<ProtocolLink: ProtocolLink object (cdna_exome_capture)>, <ProtocolLink: ProtocolLink object (cortex_hipp_nuclei_prep)>, <ProtocolLink: ProtocolLink object (heart_nuclei_prep)>, <ProtocolLink: ProtocolLink object (ont_library_prep)>, <ProtocolLink: ProtocolLink object (splitseq_1M_v2)>]>
IGVF_003

In [85]:
plate_protocols = {}
for subpool in models.Subpool.objects.all():
    for protocol in subpool.protocols.all():
        if protocol.name.startswith("splitseq"):
            plate_protocols.setdefault(protocol.name, set()).add(subpool.plate_name())
            
plate_protocols

{'splitseq_1M_v2': {'IGVF_003',
  'IGVF_004',
  'IGVF_005',
  'IGVF_007',
  'IGVF_008',
  'IGVF_008B',
  'IGVF_009',
  'IGVF_010',
  'IGVF_011',
  'IGVF_013',
  'IGVF_015',
  'IGVF_016',
  'IGVF_017',
  'IGVF_018',
  'IGVF_019',
  'IGVF_020',
  'IGVF_021',
  'IGVF_022'},
 'splitseq_100k_v2': {'IGVF_012', 'IGVF_014', 'IGVF_B01'}}

In [86]:
models.SplitSeqPlate.objects.get(name="IGVF_B01")
models.SplitSeqPlate.objects.get(name="IGVF_014")
models.SplitSeqPlate.objects.get(name="IGVF_015")

In [100]:
for subpool in models.Subpool.objects.filter(plate="IGVF_B01"):
    for accession in subpool.accession.filter(accession_prefix="igvf"):
        print(subpool.name, accession.name.replace("igvf:", ""))

B01_13A IGVFSM1676SYRC
B01_13B IGVFSM1955RVUC
B01_13C IGVFSM8093RPKR
B01_13D IGVFSM9603DIDI
B01_13E IGVFSM6958ESMJ
B01_13F IGVFSM6546CQJB
B01_13G IGVFSM8722YQAW
B01_13H IGVFSM2294BOOU

In [110]:
t = models.Tissue.objects.get(pk="105_CASTJ_10M_21")
t.accession.filter(accession_prefix="igvf")
t.name, t.accession.filter(accession_prefix="igvf").first().name

('105_CASTJ_10M_21', 'IGVFSM6969SYOD')